/* Testing Fundamentals — Unit 3: What Makes a Test Good */
window.CODELAB.addUnit("test", {
  id: "test-u3",
  title: "What Makes a Test Good",
  icon: "🎯",
  blurb: "Arrange–Act–Assert, sentence-shaped names, edge cases — and the contract behind every check: a test that can't fail isn't a test.",
  cheat: [
    { h: "Arrange, Act, Assert", lang: "js", code: "it(\"multiplies price by qty\", function () {\n  const cart = [{ price: 2, qty: 3 }]; // arrange\n  const total = cartTotal(cart);       // act\n  expect(total).toBe(6);               // assert\n});", note: "Three beats, in order — a test a stranger can read." },
    { h: "Name tests like sentences", lang: "js", code: "// BAD: tells you nothing when it fails\nit(\"works\", function () { /* three asserts */ });\n\n// GOOD: a red line IS the bug report\nit(\"lowercases the title\", function () {\n  expect(slugify(\"Draft\")).toBe(\"draft\");\n});", note: "One behavior per test — a mega-test hides which claim died." },
    { h: "The edge-case checklist", lang: "js", code: "median([])              // empty?\nmedian([7])             // single item?\nmedian([-5, 10, 3])     // negatives?\nmedian([1, 2, 3, 4])    // even length — the boundary?", note: "Empty, zero, negative, missing, boundary: bugs live at the edges." },
    { h: "Pin a known answer", lang: "js", code: "expect(average([2, 4])).toBe(3);      // exact — a wrong 6 dies here\nexpect(average([2, 4])).toBeTruthy(); // 6 is truthy too — proves nothing", note: "Vague assertions wave plausible wrong values straight through." },
    { h: "The mutant test", lang: "js", code: "// what the checks do to your suite, all course long:\nconst good = average;\naverage = function () { return 0; }; // sabotage (a MUTANT)\nrun();                               // your suite must go RED\naverage = good;                      // restore — green again", note: "A mutant that survives marks the exact thing you never tested." }
  ],
  lessons: [

    {
      id: "test-u3-1",
      title: "Arrange, Act, Assert",
      kind: "js", chip: "TEST", xp: 15, mins: 12,
      brief: "Every clear test tells a three-beat story. **Arrange**: build the input world — a cart, a user, a list. **Act**: call the function, once. **Assert**: state exactly what must now be true. When a test reads in that order, a stranger (including you, in three weeks) sees what it proves at a glance.\n\nNew unit, new deal: from here on **the subject code is already written**. `cartTotal()` sits below your test kit, correct and ready — in this course you never write the feature, you prove the feature works. Your `it()`/`expect()`/`run()` from Unit 2 is collapsed at the top of the file; use it, don't edit it.\n\nOne more thing, so grading never feels arbitrary: the checks here do more than run your suite. They also **swap in broken versions** of `cartTotal()` and demand your tests object. If a check says a broken version passed all your tests, your suite has a blind spot — and the message names the exact case to add.",
      example: { lang: "js", code: "it(\"totals a one-item cart\", function () {\n  const cart = [{ price: 3, qty: 1 }];   // arrange\n  const total = cartTotal(cart);         // act\n  expect(total).toBe(3);                 // assert\n});" },
      steps: [
        { text: "Two AAA tests with `it()`: a one-item cart, and a cart where `qty > 1` — green against the real `cartTotal()`.",
          test: "T.expect(typeof it === 'function' && typeof run === 'function', 'Keep the Unit 2 test kit at the top of the file — the checks call your it() and run().');\nvar r = run();\nT.expect(r.total >= 2, 'Write two AAA tests with it(): a one-item cart, and a cart where qty > 1.');\nT.eq(r.failed, 0, 'Your tests must all pass against the REAL cartTotal() — the console report names the failing test.');" },
        { text: "A broken `cartTotal()` that ignores `qty` must make your suite go red.",
          test: "var r = T.mutate('cartTotal', function (items) {\n  var sum = 0;\n  for (var i = 0; i < items.length; i++) sum += items[i].price;\n  return Math.round(sum * 100) / 100;\n}, function () { return run(); });\nT.expect(r.failed > 0, 'A version of cartTotal() that ignores qty and just adds up prices passed ALL your tests — arrange a cart where quantity matters, e.g. cartTotal([{ price: 2, qty: 3 }]) is 6.');" },
        { text: "A broken `cartTotal()` that rounds to whole dollars must go red too — then the real one comes back and you finish green.",
          test: "var r = T.mutate('cartTotal', function (items) {\n  var sum = 0;\n  for (var i = 0; i < items.length; i++) sum += items[i].price * items[i].qty;\n  return Math.round(sum);\n}, function () { return run(); });\nT.expect(r.failed > 0, 'A version of cartTotal() that rounds the total to whole dollars passed all your tests — assert a decimal total, e.g. cartTotal([{ price: 1.5, qty: 3 }]) is 4.5.');\nvar r2 = run();\nT.eq(r2.failed, 0, 'And with the real cartTotal() restored, your suite is green again.');" }
      ],
      files: [
        { name: "script.js", content: "// ---- your test kit from Unit 2 (collapsed -- use it, don't edit it) ----\nlet tests = [];\nlet results = [];\nfunction it(name, fn) { tests.push({ name: name, fn: fn }); }\nfunction expect(actual) {\n  return {\n    toBe: function (want) {\n      if (actual !== want) throw new Error(\"expected \" + JSON.stringify(want) + \" but got \" + JSON.stringify(actual));\n    },\n    toEqual: function (want) {\n      if (JSON.stringify(actual) !== JSON.stringify(want)) throw new Error(\"expected \" + JSON.stringify(want) + \" but got \" + JSON.stringify(actual));\n    }\n  };\n}\nfunction run() {\n  results = [];\n  for (const t of tests) {\n    try { t.fn(); results.push({ name: t.name, pass: true }); }\n    catch (e) { results.push({ name: t.name, pass: false, error: e.message }); }\n  }\n  const failed = results.filter(r => !r.pass).length;\n  return { total: tests.length, passed: tests.length - failed, failed: failed, results: results };\n}\n// ------------------------------------------------------------------------\n\n// The subject -- already written, already correct. You test it.\nfunction cartTotal(items) {\n  let sum = 0;\n  for (const item of items) sum += item.price * item.qty;\n  return Math.round(sum * 100) / 100;\n}\n\n// 1) An AAA test: arrange a one-item cart, act, assert the exact total.\n// it(\"totals a one-item cart\", function () {\n//   const cart = [{ price: 3, qty: 1 }];   // arrange\n//   ...                                    // act, then assert\n// });\n\n// 2) A second test: a cart where qty > 1 (put a decimal price in there too).\n\n// ---- report ----\nconst report = run();\nreport.results.forEach(r => console.log((r.pass ? \"PASS \" : \"FAIL \") + r.name + (r.error ? \" -- \" + r.error : \"\")));\nconsole.log(report.passed + \"/\" + report.total + \" passing\");\n" }
      ],
      hints: [
        "AAA in code: `const cart = [{ price: 2, qty: 3 }];` then `const total = cartTotal(cart);` then `expect(total).toBe(6);`",
        "The qty saboteur dies on any cart where qty > 1; the rounding one dies on any decimal total — `[{ price: 1.5, qty: 3 }]` totals 4.5."
      ],
      solution: {
        "script.js": "// ---- your test kit from Unit 2 (collapsed -- use it, don't edit it) ----\nlet tests = [];\nlet results = [];\nfunction it(name, fn) { tests.push({ name: name, fn: fn }); }\nfunction expect(actual) {\n  return {\n    toBe: function (want) {\n      if (actual !== want) throw new Error(\"expected \" + JSON.stringify(want) + \" but got \" + JSON.stringify(actual));\n    },\n    toEqual: function (want) {\n      if (JSON.stringify(actual) !== JSON.stringify(want)) throw new Error(\"expected \" + JSON.stringify(want) + \" but got \" + JSON.stringify(actual));\n    }\n  };\n}\nfunction run() {\n  results = [];\n  for (const t of tests) {\n    try { t.fn(); results.push({ name: t.name, pass: true }); }\n    catch (e) { results.push({ name: t.name, pass: false, error: e.message }); }\n  }\n  const failed = results.filter(r => !r.pass).length;\n  return { total: tests.length, passed: tests.length - failed, failed: failed, results: results };\n}\n// ------------------------------------------------------------------------\n\n// The subject -- already written, already correct. You test it.\nfunction cartTotal(items) {\n  let sum = 0;\n  for (const item of items) sum += item.price * item.qty;\n  return Math.round(sum * 100) / 100;\n}\n\nit(\"totals a one-item cart\", function () {\n  const cart = [{ price: 3, qty: 1 }];   // arrange\n  const total = cartTotal(cart);         // act\n  expect(total).toBe(3);                 // assert\n});\n\nit(\"multiplies price by quantity\", function () {\n  const cart = [{ price: 2, qty: 3 }, { price: 1.5, qty: 3 }];  // arrange\n  const total = cartTotal(cart);                                // act\n  expect(total).toBe(10.5);                                     // assert\n});\n\n// ---- report ----\nconst report = run();\nreport.results.forEach(r => console.log((r.pass ? \"PASS \" : \"FAIL \") + r.name + (r.error ? \" -- \" + r.error : \"\")));\nconsole.log(report.passed + \"/\" + report.total + \" passing\");\n"
      }
    },

    {
      id: "test-u3-2",
      title: "One behavior per test, named like a sentence",
      kind: "js", chip: "TEST", xp: 15, mins: 13,
      brief: "`it(\"works\", …)` is a name you'll curse in three weeks: when it fails, it tells you nothing. Name every test as **a sentence stating one behavior** — `it(\"lowercases the title\", …)` — and a red line becomes a bug report: subject, behavior, done.\n\nThe discipline behind the name: **one behavior per test**. `slugify()` below does three jobs — trims outer spaces, lowercases, turns spaces into dashes. That's three tests, not one mega-test with three asserts, because when a mega-test fails you still have to dig out WHICH claim died.\n\nThe checks make you prove the split: three sabotaged versions of `slugify()` — one per behavior — and each must knock over a **different** test. If two saboteurs break the same tests, somewhere one test is doing two jobs.",
      steps: [
        { text: "Three green tests against the real `slugify()` — each named like a sentence stating one behavior.",
          test: "var r = run();\nT.expect(r.total >= 3, 'Three behaviors, three separate it() tests.');\nT.eq(r.failed, 0, 'All three must pass against the real slugify() — the console report names the failing test.');\nT.expect(r.results.every(function (x) { return /\\S+\\s+\\S+/.test(x.name); }), 'Name each test like a sentence that states the behavior — \"lowercases the title\", not \"test1\".');" },
        { text: "Each sabotaged `slugify()` — no trim, no lowercase, no dashes — makes your suite go red.",
          test: "var muts = [\n  { impl: function (t) { return t.toLowerCase().replace(/\\s+/g, '-'); },\n    msg: 'A slugify() that never trims (so \"  hello  \" becomes \"-hello-\") passed ALL your tests — add a case with spaces around the edges, e.g. slugify(\"  draft  \") is \"draft\".' },\n  { impl: function (t) { return t.trim().replace(/\\s+/g, '-'); },\n    msg: 'A slugify() that skips the lowercasing (so \"Draft\" stays \"Draft\") passed all your tests — add a case with capital letters, e.g. slugify(\"Draft\") is \"draft\".' },\n  { impl: function (t) { return t.trim().toLowerCase(); },\n    msg: 'A slugify() that keeps the spaces (so \"hello world\" never gets its dash) passed all your tests — add a multi-word case, e.g. slugify(\"hello world\") is \"hello-world\".' }\n];\nfor (var i = 0; i < muts.length; i++) {\n  var r = T.mutate('slugify', muts[i].impl, function () { return run(); });\n  T.expect(r.failed > 0, muts[i].msg);\n}" },
        { text: "Each saboteur breaks a **different** test — proof that every behavior owns its own `it()`.",
          test: "function failNames(r) { return r.results.filter(function (x) { return !x.pass; }).map(function (x) { return x.name; }).sort().join('|'); }\nvar impls = [\n  function (t) { return t.toLowerCase().replace(/\\s+/g, '-'); },\n  function (t) { return t.trim().replace(/\\s+/g, '-'); },\n  function (t) { return t.trim().toLowerCase(); }\n];\nvar sigs = [];\nfor (var i = 0; i < impls.length; i++) {\n  var r = T.mutate('slugify', impls[i], function () { return run(); });\n  sigs.push(failNames(r));\n}\nT.expect(sigs[0] !== sigs[1] && sigs[1] !== sigs[2] && sigs[0] !== sigs[2], 'Two different saboteurs knocked over exactly the same set of tests — somewhere one test is checking two behaviors. Give each behavior an input only IT can fail: the trim test an already-lowercase word (\"  draft  \"), the case test a single word (\"Draft\"), the dash test a lowercase phrase (\"hello world\").');" }
      ],
      files: [
        { name: "script.js", content: "// ---- your test kit from Unit 2 (collapsed -- use it, don't edit it) ----\nlet tests = [];\nlet results = [];\nfunction it(name, fn) { tests.push({ name: name, fn: fn }); }\nfunction expect(actual) {\n  return {\n    toBe: function (want) {\n      if (actual !== want) throw new Error(\"expected \" + JSON.stringify(want) + \" but got \" + JSON.stringify(actual));\n    },\n    toEqual: function (want) {\n      if (JSON.stringify(actual) !== JSON.stringify(want)) throw new Error(\"expected \" + JSON.stringify(want) + \" but got \" + JSON.stringify(actual));\n    }\n  };\n}\nfunction run() {\n  results = [];\n  for (const t of tests) {\n    try { t.fn(); results.push({ name: t.name, pass: true }); }\n    catch (e) { results.push({ name: t.name, pass: false, error: e.message }); }\n  }\n  const failed = results.filter(r => !r.pass).length;\n  return { total: tests.length, passed: tests.length - failed, failed: failed, results: results };\n}\n// ------------------------------------------------------------------------\n\n// The subject -- three jobs in one function. You test each job separately.\nfunction slugify(title) {\n  return title.trim().toLowerCase().replace(/\\s+/g, \"-\");\n}\n\n// Three tests, one behavior each, named like sentences:\n// 1) trims the spaces around the edges   -> use an already-lowercase word\n// 2) lowercases the title                -> use a single capitalized word\n// 3) turns spaces into dashes            -> use a lowercase phrase\n\n// ---- report ----\nconst report = run();\nreport.results.forEach(r => console.log((r.pass ? \"PASS \" : \"FAIL \") + r.name + (r.error ? \" -- \" + r.error : \"\")));\nconsole.log(report.passed + \"/\" + report.total + \" passing\");\n" }
      ],
      hints: [
        "Give each behavior a laser-focused input: the trim test wants an already-lowercase single word (`\"  draft  \"`), the case test a single capitalized word (`\"Draft\"`), the dash test a lowercase phrase (`\"hello world\"`). That way each saboteur can only break its own test.",
        "`it(\"turns spaces into dashes\", function () { expect(slugify(\"hello world\")).toBe(\"hello-world\"); });`"
      ],
      solution: {
        "script.js": "// ---- your test kit from Unit 2 (collapsed -- use it, don't edit it) ----\nlet tests = [];\nlet results = [];\nfunction it(name, fn) { tests.push({ name: name, fn: fn }); }\nfunction expect(actual) {\n  return {\n    toBe: function (want) {\n      if (actual !== want) throw new Error(\"expected \" + JSON.stringify(want) + \" but got \" + JSON.stringify(actual));\n    },\n    toEqual: function (want) {\n      if (JSON.stringify(actual) !== JSON.stringify(want)) throw new Error(\"expected \" + JSON.stringify(want) + \" but got \" + JSON.stringify(actual));\n    }\n  };\n}\nfunction run() {\n  results = [];\n  for (const t of tests) {\n    try { t.fn(); results.push({ name: t.name, pass: true }); }\n    catch (e) { results.push({ name: t.name, pass: false, error: e.message }); }\n  }\n  const failed = results.filter(r => !r.pass).length;\n  return { total: tests.length, passed: tests.length - failed, failed: failed, results: results };\n}\n// ------------------------------------------------------------------------\n\n// The subject -- three jobs in one function. You test each job separately.\nfunction slugify(title) {\n  return title.trim().toLowerCase().replace(/\\s+/g, \"-\");\n}\n\nit(\"trims the spaces around the edges\", function () {\n  expect(slugify(\"  draft  \")).toBe(\"draft\");\n});\n\nit(\"lowercases the title\", function () {\n  expect(slugify(\"Draft\")).toBe(\"draft\");\n});\n\nit(\"turns spaces into dashes\", function () {\n  expect(slugify(\"hello world\")).toBe(\"hello-world\");\n});\n\n// ---- report ----\nconst report = run();\nreport.results.forEach(r => console.log((r.pass ? \"PASS \" : \"FAIL \") + r.name + (r.error ? \" -- \" + r.error : \"\")));\nconsole.log(report.passed + \"/\" + report.total + \" passing\");\n"
      }
    },

    {
      id: "test-u3-3",
      title: "Edge cases: empty, zero, negative, missing",
      kind: "js", chip: "TEST", xp: 15, mins: 13,
      brief: "The happy path almost never hides the bug. Bugs live at the **edges**: the empty list, the zero, the negative number, the boundary where one branch hands over to another. A suite that only feeds a function friendly input passes right up until production doesn't.\n\nMeet `median()` — already written, already correct, with real edge decisions baked in: it answers `null` for an empty list, it sorts **numerically** (JavaScript's default `.sort()` orders numbers like words!), and even-length lists average the two middle values.\n\nYour job: a suite that pins down the middle AND the edges. The checks will push broken versions at your suite — each one wrong at exactly one edge.",
      example: { lang: "js", code: "median([9, 40, 2])    // 9    (sorted numerically: 2, 9, 40)\nmedian([1, 2, 3, 4])  // 2.5  (even length: (2 + 3) / 2)\nmedian([])            // null (the shipped code's decision)" },
      steps: [
        { text: "Two green tests to start: an odd-length list and an even-length one.",
          test: "var r = run();\nT.expect(r.total >= 2, 'Start with two tests: an odd-length list and an even-length one.');\nT.eq(r.failed, 0, 'Both must pass against the real median() — the console report names the failing test.');" },
        { text: "A `median()` that sorts numbers like words must go red — feed it two-digit or negative numbers.",
          test: "var r = T.mutate('median', function (n) {\n  if (n.length === 0) return null;\n  var s = n.slice().sort();\n  var mid = Math.floor(s.length / 2);\n  return s.length % 2 === 1 ? s[mid] : (s[mid - 1] + s[mid]) / 2;\n}, function () { return run(); });\nT.expect(r.failed > 0, 'A median() that sorts numbers like WORDS (so [9, 40, 2] lines up as [2, 40, 9]) passed ALL your tests — add a case with two-digit or negative numbers, e.g. median([9, 40, 2]) is 9.');" },
        { text: "A `median()` that fumbles even-length lists must go red — test the boundary.",
          test: "var r = T.mutate('median', function (n) {\n  if (n.length === 0) return null;\n  var s = n.slice().sort(function (a, b) { return a - b; });\n  return s[Math.floor(s.length / 2)];\n}, function () { return run(); });\nT.expect(r.failed > 0, 'A median() that grabs the upper-middle number of an even-length list (3 for [1, 2, 3, 4]) passed all your tests — even lengths are the boundary; add e.g. median([1, 2, 3, 4]) is 2.5.');" },
        { text: "A `median()` that answers `0` for `[]` must go red — pin the empty-list decision to `null`.",
          test: "var r = T.mutate('median', function (n) {\n  if (n.length === 0) return 0;\n  var s = n.slice().sort(function (a, b) { return a - b; });\n  var mid = Math.floor(s.length / 2);\n  return s.length % 2 === 1 ? s[mid] : (s[mid - 1] + s[mid]) / 2;\n}, function () { return run(); });\nT.expect(r.failed > 0, 'A median() that answers 0 for the empty list passed — the real one answers null, and 0 is a number a caller might trust. Assert it: expect(median([])).toBe(null).');\nvar r2 = run();\nT.eq(r2.failed, 0, 'Saboteurs gone, real median() back — your suite ends green.');" }
      ],
      files: [
        { name: "script.js", content: "// ---- your test kit from Unit 2 (collapsed -- use it, don't edit it) ----\nlet tests = [];\nlet results = [];\nfunction it(name, fn) { tests.push({ name: name, fn: fn }); }\nfunction expect(actual) {\n  return {\n    toBe: function (want) {\n      if (actual !== want) throw new Error(\"expected \" + JSON.stringify(want) + \" but got \" + JSON.stringify(actual));\n    },\n    toEqual: function (want) {\n      if (JSON.stringify(actual) !== JSON.stringify(want)) throw new Error(\"expected \" + JSON.stringify(want) + \" but got \" + JSON.stringify(actual));\n    }\n  };\n}\nfunction run() {\n  results = [];\n  for (const t of tests) {\n    try { t.fn(); results.push({ name: t.name, pass: true }); }\n    catch (e) { results.push({ name: t.name, pass: false, error: e.message }); }\n  }\n  const failed = results.filter(r => !r.pass).length;\n  return { total: tests.length, passed: tests.length - failed, failed: failed, results: results };\n}\n// ------------------------------------------------------------------------\n\n// The subject -- correct, with edge decisions baked in. You pin them down.\nfunction median(nums) {\n  if (nums.length === 0) return null;\n  const sorted = [...nums].sort((a, b) => a - b);\n  const mid = Math.floor(sorted.length / 2);\n  if (sorted.length % 2 === 1) return sorted[mid];\n  return (sorted[mid - 1] + sorted[mid]) / 2;\n}\n\n// Cover the middle AND the edges:\n// 1) odd-length, unsorted, with a two-digit number in it\n// 2) even-length -> the two middle values get averaged\n// 3) negatives in the mix\n// 4) the empty list -> null, not 0\n\n// ---- report ----\nconst report = run();\nreport.results.forEach(r => console.log((r.pass ? \"PASS \" : \"FAIL \") + r.name + (r.error ? \" -- \" + r.error : \"\")));\nconsole.log(report.passed + \"/\" + report.total + \" passing\");\n" }
      ],
      hints: [
        "Four solid cases: `median([9, 40, 2])` is 9, `median([1, 2, 3, 4])` is 2.5, `median([-5, 10, 3])` is 3, `median([])` is null.",
        "`expect(median([])).toBe(null)` — null, not 0: that's the decision the shipped code made, so that's the claim your test pins.",
        "Single-digit sorted lists like [1, 2, 3] can't catch a words-not-numbers sort — you need a two-digit or negative number in an unsorted list."
      ],
      solution: {
        "script.js": "// ---- your test kit from Unit 2 (collapsed -- use it, don't edit it) ----\nlet tests = [];\nlet results = [];\nfunction it(name, fn) { tests.push({ name: name, fn: fn }); }\nfunction expect(actual) {\n  return {\n    toBe: function (want) {\n      if (actual !== want) throw new Error(\"expected \" + JSON.stringify(want) + \" but got \" + JSON.stringify(actual));\n    },\n    toEqual: function (want) {\n      if (JSON.stringify(actual) !== JSON.stringify(want)) throw new Error(\"expected \" + JSON.stringify(want) + \" but got \" + JSON.stringify(actual));\n    }\n  };\n}\nfunction run() {\n  results = [];\n  for (const t of tests) {\n    try { t.fn(); results.push({ name: t.name, pass: true }); }\n    catch (e) { results.push({ name: t.name, pass: false, error: e.message }); }\n  }\n  const failed = results.filter(r => !r.pass).length;\n  return { total: tests.length, passed: tests.length - failed, failed: failed, results: results };\n}\n// ------------------------------------------------------------------------\n\n// The subject -- correct, with edge decisions baked in. You pin them down.\nfunction median(nums) {\n  if (nums.length === 0) return null;\n  const sorted = [...nums].sort((a, b) => a - b);\n  const mid = Math.floor(sorted.length / 2);\n  if (sorted.length % 2 === 1) return sorted[mid];\n  return (sorted[mid - 1] + sorted[mid]) / 2;\n}\n\nit(\"finds the middle of an odd-length unsorted list\", function () {\n  expect(median([9, 40, 2])).toBe(9);\n});\n\nit(\"averages the two middle values of an even-length list\", function () {\n  expect(median([1, 2, 3, 4])).toBe(2.5);\n});\n\nit(\"keeps negative numbers in numeric order\", function () {\n  expect(median([-5, 10, 3])).toBe(3);\n});\n\nit(\"answers null for an empty list\", function () {\n  expect(median([])).toBe(null);\n});\n\n// ---- report ----\nconst report = run();\nreport.results.forEach(r => console.log((r.pass ? \"PASS \" : \"FAIL \") + r.name + (r.error ? \" -- \" + r.error : \"\")));\nconsole.log(report.passed + \"/\" + report.total + \" passing\");\n"
      }
    },

    {
      id: "test-u3-4",
      title: "The mutant test: a test that can't fail isn't a test",
      kind: "js", chip: "TEST", xp: 15, mins: 14,
      brief: "Time to name the trick this whole unit has been playing on you: **mutation testing**. Take a working function, deliberately break it — a **mutant** — run the suite, and demand red. If a mutant survives your suite, whatever it broke is something your tests never checked. That's the grading contract for the rest of this course, out loud: **a test that can't fail isn't a test**.\n\nThe subject is `average()` — correct, and it answers `null` for the empty list. The checks will swap in three mutants, one at a time: one **divides by `length - 1`**, one **silently drops negative numbers**, one **returns `0` for `[]`**. Your file never changes; the swap happens during grading and the real function is restored right after. Each mutant must make at least one of your tests fail.\n\nNotice what the mutants have in common: each returns a *plausible, wrong* value of the right type. A lazy assertion — \"is the result truthy?\" — waves all three straight through. Only exact claims catch them: `expect(average([2, 4])).toBe(3)`.",
      example: { lang: "js", code: "// what the grader does, in spirit:\nconst good = average;\naverage = function (n) { return 0; }; // MUTANT swapped in\nrun();                                // your suite must go RED\naverage = good;                       // restored — green again" },
      steps: [
        { text: "Three tests, all green against the real `average()`: a known answer, a negative, the empty list.",
          test: "var r = run();\nT.expect(r.total >= 3, 'Three behaviors, three tests: a known answer, a case with a negative, and the empty list.');\nT.eq(r.failed, 0, 'All three must pass against the REAL average() first — the mutants come next.');" },
        { text: "Mutant 1 — divides by `length - 1` — must make your suite go red.",
          test: "var r = T.mutate('average', function (n) {\n  if (n.length === 0) return null;\n  return n.reduce(function (a, b) { return a + b; }, 0) / (n.length - 1);\n}, function () { return run(); });\nT.expect(r.failed > 0, 'MUTANT SURVIVED: a version of average() that divides by length - 1 passed ALL your tests. Add a case with a known answer, e.g. average([2, 4]) === 3.');" },
        { text: "Mutant 2 — silently drops negatives — must go red.",
          test: "var r = T.mutate('average', function (n) {\n  if (n.length === 0) return null;\n  return n.filter(function (x) { return x > 0; }).reduce(function (a, b) { return a + b; }, 0) / n.length;\n}, function () { return run(); });\nT.expect(r.failed > 0, 'MUTANT SURVIVED: a version that silently drops negative numbers passed all your tests — add a case with a negative, e.g. average([-4, 4]) === 0.');" },
        { text: "Mutant 3 — returns `0` for `[]` — must go red; then the real `average()` comes back and you finish green.",
          test: "var r = T.mutate('average', function (n) {\n  if (n.length === 0) return 0;\n  return n.reduce(function (a, b) { return a + b; }, 0) / n.length;\n}, function () { return run(); });\nT.expect(r.failed > 0, 'MUTANT SURVIVED: a version that returns 0 for [] passed — the shipped average() answers null for an empty list, and 0 is a real number a caller might bill someone with. Assert it: expect(average([])).toBe(null).');\nvar r2 = run();\nT.eq(r2.failed, 0, 'All three mutants caught, real average() restored, suite green. That is what a trustworthy suite looks like.');" }
      ],
      files: [
        { name: "script.js", content: "// ---- your test kit from Unit 2 (collapsed -- use it, don't edit it) ----\nlet tests = [];\nlet results = [];\nfunction it(name, fn) { tests.push({ name: name, fn: fn }); }\nfunction expect(actual) {\n  return {\n    toBe: function (want) {\n      if (actual !== want) throw new Error(\"expected \" + JSON.stringify(want) + \" but got \" + JSON.stringify(actual));\n    },\n    toEqual: function (want) {\n      if (JSON.stringify(actual) !== JSON.stringify(want)) throw new Error(\"expected \" + JSON.stringify(want) + \" but got \" + JSON.stringify(actual));\n    }\n  };\n}\nfunction run() {\n  results = [];\n  for (const t of tests) {\n    try { t.fn(); results.push({ name: t.name, pass: true }); }\n    catch (e) { results.push({ name: t.name, pass: false, error: e.message }); }\n  }\n  const failed = results.filter(r => !r.pass).length;\n  return { total: tests.length, passed: tests.length - failed, failed: failed, results: results };\n}\n// ------------------------------------------------------------------------\n\n// The subject -- correct. Three mutants are coming for it:\n//   1) divides by length - 1\n//   2) silently drops negative numbers\n//   3) returns 0 for [] (the real one answers null)\nfunction average(nums) {\n  if (nums.length === 0) return null;\n  return nums.reduce((a, b) => a + b, 0) / nums.length;\n}\n\n// Write the three tests that catch them: a known answer, a negative, [].\n\n// ---- report ----\nconst report = run();\nreport.results.forEach(r => console.log((r.pass ? \"PASS \" : \"FAIL \") + r.name + (r.error ? \" -- \" + r.error : \"\")));\nconsole.log(report.passed + \"/\" + report.total + \" passing\");\n" }
      ],
      hints: [
        "`it(\"averages a known answer\", function () { expect(average([2, 4])).toBe(3); });` — the length-1 divider turns 3 into 6, so this kills it.",
        "One test per mutant: a known answer kills the length-1 divider, `average([-4, 4])` is 0 kills the negative-dropper, `average([])` is null kills the zero-returner."
      ],
      solution: {
        "script.js": "// ---- your test kit from Unit 2 (collapsed -- use it, don't edit it) ----\nlet tests = [];\nlet results = [];\nfunction it(name, fn) { tests.push({ name: name, fn: fn }); }\nfunction expect(actual) {\n  return {\n    toBe: function (want) {\n      if (actual !== want) throw new Error(\"expected \" + JSON.stringify(want) + \" but got \" + JSON.stringify(actual));\n    },\n    toEqual: function (want) {\n      if (JSON.stringify(actual) !== JSON.stringify(want)) throw new Error(\"expected \" + JSON.stringify(want) + \" but got \" + JSON.stringify(actual));\n    }\n  };\n}\nfunction run() {\n  results = [];\n  for (const t of tests) {\n    try { t.fn(); results.push({ name: t.name, pass: true }); }\n    catch (e) { results.push({ name: t.name, pass: false, error: e.message }); }\n  }\n  const failed = results.filter(r => !r.pass).length;\n  return { total: tests.length, passed: tests.length - failed, failed: failed, results: results };\n}\n// ------------------------------------------------------------------------\n\n// The subject -- correct. Three mutants are coming for it:\n//   1) divides by length - 1\n//   2) silently drops negative numbers\n//   3) returns 0 for [] (the real one answers null)\nfunction average(nums) {\n  if (nums.length === 0) return null;\n  return nums.reduce((a, b) => a + b, 0) / nums.length;\n}\n\nit(\"averages to a known answer\", function () {\n  expect(average([2, 4])).toBe(3);\n});\n\nit(\"keeps negative numbers in the math\", function () {\n  expect(average([-4, 4])).toBe(0);\n});\n\nit(\"answers null for an empty list\", function () {\n  expect(average([])).toBe(null);\n});\n\n// ---- report ----\nconst report = run();\nreport.results.forEach(r => console.log((r.pass ? \"PASS \" : \"FAIL \") + r.name + (r.error ? \" -- \" + r.error : \"\")));\nconsole.log(report.passed + \"/\" + report.total + \" passing\");\n"
      }
    },

    {
      id: "test-quiz-3",
      title: "Unit 3 quiz: Good tests, bad tests",
      kind: "quiz", xp: 10,
      brief: "AAA, sentence names, edge cases and mutants. 80% to pass.",
      questions: [
        { q: "In Arrange–Act–Assert terms, which phase is the line `const total = cartTotal(cart);`?",
          code: "it(\"totals the cart\", function () {\n  const cart = [{ price: 2, qty: 3 }];\n  const total = cartTotal(cart);\n  expect(total).toBe(6);\n});",
          lang: "js",
          choices: ["Arrange", "Assert", "Act", "Assemble"],
          answer: 2, explain: "Arrange builds the world (the cart), Act pokes it exactly once (the call under test), Assert states what must now be true (`toBe(6)`). Keeping the three beats in that order is what lets a stranger read the test's story at a glance — and \"Assemble\" isn't one of the beats." },
        { q: "A test named `it(\"works\", …)` goes red in your suite. What's the real cost of that name?",
          choices: ["Nothing — names are cosmetic once the suite is green", "A failure can't tell you which behavior broke", "The runner needs unique names to count results", "Tests with vague names are run last"],
          answer: 1, explain: "A test's name is the bug report you get when it fails: \"lowercases the title\" in red tells you the broken behavior before you open a file, while \"works\" in red tells you nothing and you re-debug from scratch. Runners neither require unique names nor reorder tests by them — the cost is purely human, and it's paid at the worst possible time." },
        { q: "Both tests pass. Which input family is this suite most obviously missing?",
          code: "it(\"totals two items\", () =>\n  expect(cartTotal([{ price: 2, qty: 1 }, { price: 3, qty: 1 }])).toBe(5));\nit(\"totals three items\", () =>\n  expect(cartTotal([{ price: 1, qty: 1 }, { price: 2, qty: 1 }, { price: 3, qty: 1 }])).toBe(6));",
          lang: "js",
          choices: ["A list with four items", "The same list passed twice", "A list that is already totaled", "An empty cart"],
          answer: 3, explain: "Both tests live on the same happy path: friendly little carts, every qty equal to 1. The edges are where the bugs hide — the empty cart (and a qty above 1) exercise decisions this suite never touches. A fourth happy-path item proves nothing the third didn't already prove." },
        { q: "The checks swap in an `average()` that divides by `length - 1`, and your suite stays green. What did you just learn?",
          choices: ["Your suite never pins an exact expected value", "The two versions are mathematically equivalent", "The runner restored the real function too early", "Off-by-one bugs can't be caught by unit tests"],
          answer: 0, explain: "A surviving mutant means the thing it broke is something no test checks: divide [2, 4]'s sum by `length - 1` and you get 6 instead of 3, so any test asserting `toBe(3)` kills it instantly. If nothing dies, no test asserts a real known answer. That's mutation testing's whole job — measuring whether your suite CAN fail." },
        { q: "Which broken `average()` sails straight through this test?",
          code: "it(\"averages\", function () {\n  expect(average([2, 4])).toBeTruthy();\n});",
          lang: "js",
          choices: ["One that returns 0 for every list", "One that throws on every call", "One that returns 7 for every list", "One that returns undefined"],
          answer: 2, explain: "`toBeTruthy()` accepts EVERY truthy value, and a wrong 7 is exactly as truthy as the right answer 3 — a plausible wrong number walks straight through. The other three all fail (0 and undefined are falsy, a throw is recorded as a failure), which makes the assertion look useful while it only catches cartoonish bugs. Pin the known answer instead: `toBe(3)`." },
        { q: "Which matcher pins `average([2, 4])` to its exact known answer?",
          choices: ["toBeTruthy()", "toBe(3)", "toBeCloseTo(0, 5)", "toEqual([3])"],
          answer: 1, explain: "`toBe(3)` makes the one claim a mutant can't dodge: the result is exactly 3. `toBeTruthy()` accepts any non-falsy value, `toBeCloseTo(0, 5)` asserts closeness to the WRONG number, and `toEqual([3])` claims the result is an array, which it isn't. An exact known answer is the cheapest strong assertion there is." }
      ]
    }
  ]
});
