/* Testing Fundamentals — Unit 7: Testing the DOM */
window.CODELAB.addUnit("test", {
  id: "test-u7",
  title: "Testing the DOM",
  icon: "🖱️",
  blurb: "Render a real component into a detached container, query it the way a user sees it, fire a real click, and assert exactly what rendered.",
  cheat: [
    { h: "A DOM test in four moves", lang: "js", code: "it('shows the name', () => {\n  const box = document.createElement('div'); // detached container\n  renderProfile(box, { name: 'Ada', pro: true });\n  expect(box.querySelector('.who').textContent).toBe('Ada');\n});", note: "Create → render → query → assert, always inside a container the test itself made." },
    { h: "Query like a user: byText", lang: "js", code: "function byText(root, label) {\n  const want = label.replace(/\\s+/g, ' ').trim().toLowerCase();\n  let hit = null;\n  for (const el of root.querySelectorAll('*')) {\n    const t = el.textContent.replace(/\\s+/g, ' ').trim().toLowerCase();\n    if (t === want) hit = el; // last match = deepest\n  }\n  if (!hit) throw new Error('Could not find an element with text \"' + label + '\"');\n  return hit;\n}", note: "Labels survive redesigns; class names do not." },
    { h: "A real click", lang: "js", code: "byText(box, '+1').dispatchEvent(\n  new MouseEvent('click', { bubbles: true })\n);", note: "bubbles: true — real clicks bubble, and delegated listeners rely on it." },
    { h: "Fresh DOM for every test", lang: "js", code: "let box;\nbeforeEach(() => {\n  box = document.createElement('div');\n});", note: "Nothing touches document.body, nothing leaks into the next test." },
    { h: "Re-query after re-render", lang: "js", code: "byText(box, '+1').dispatchEvent(new MouseEvent('click', { bubbles: true }));\n// the click RE-RENDERED the card — the old button is a dead node now\nbyText(box, '+1').dispatchEvent(new MouseEvent('click', { bubbles: true }));" },
    { h: "The same ideas, industrial strength", lang: "js", code: "// Testing Library (not runnable here — same philosophy):\nrender(<Counter />);\nawait userEvent.click(\n  screen.getByRole('button', { name: /\\+1/ })\n);\nexpect(screen.getByText('1')).toBeInTheDocument();", note: "byText ≈ getByText/getByRole; dispatchEvent ≈ userEvent.click." }
  ],
  lessons: [

    {
      id: "test-u7-1",
      title: "Render, query, assert",
      kind: "web", chip: "TEST", xp: 15, mins: 13,
      spec: true,
      brief: "For six units your tests have called functions and checked return values. Time to point them at something a user can actually see: **the DOM**. The recipe never changes — **render** the component into a container, **query** what showed up, **assert** the exact text.\n\nThe container trick is the whole secret: `document.createElement(\"div\")` gives you a **detached** element — a private little page per test. You never touch the real page, so tests cannot trample each other or leave litter behind. Everything renders synchronously, so you assert on the very next line.\n\n`renderProfile(root, user)` is already written — in this course you test components, you do not build them. Write the suite: render a pro user and a free user into fresh containers and assert exactly what each one shows.",
      steps: [
        { text: "Three green tests against the working component: the name in `.who`, the **PRO** badge, and the **FREE** badge — each rendered into a fresh detached container.",
          test: "var probe = document.createElement('div');\nrenderProfile(probe, { name: 'Grace', role: 'Admiral', pro: false });\nT.eq((probe.querySelector('.badge') || {}).textContent, 'FREE', 'Leave renderProfile() exactly as shipped — the deliverable is the suite, not the component.');\nvar r = await run();\nT.expect(r.total >= 3, 'Write at least three tests: the name, the PRO badge, and the FREE badge.');\nT.eq(r.failed, 0, 'All tests must pass against the WORKING renderProfile() — the spec panel shows which one disagrees.');" },
        { text: "Mutant check: a version that stamps **every** user PRO must turn your suite red.",
          test: "var r = await T.mutate('renderProfile', function (root, user) {\n  root.innerHTML = '<div class=\"profile\"><h2 class=\"who\">' + user.name + '</h2><p class=\"role\">' + user.role + '</p><span class=\"badge\">PRO</span></div>';\n}, function () { return run(); });\nT.expect(r.failed > 0, 'A version of renderProfile() that stamps EVERY user PRO passed all your tests — render a user with pro: false and assert the badge text is exactly \"FREE\".');" },
        { text: "Mutant check: a version that SHOUTS the name (`ADA`) must fail too — assert **exact** text. Then the real component is restored and your suite ends green.",
          test: "var r = await T.mutate('renderProfile', function (root, user) {\n  root.innerHTML = '<div class=\"profile\"><h2 class=\"who\">' + String(user.name).toUpperCase() + '</h2><p class=\"role\">' + user.role + '</p><span class=\"badge\">' + (user.pro ? 'PRO' : 'FREE') + '</span></div>';\n}, function () { return run(); });\nT.expect(r.failed > 0, 'A version that renders the name in ALL CAPS passed all your tests — assert the exact rendered text: expect(box.querySelector(\".who\").textContent).toBe(\"Ada\").');\nvar r2 = await run();\nT.eq(r2.failed, 0, 'With the real component back in place, your suite is green again.');" }
      ],
      files: [
        { name: "index.html", content: "<!DOCTYPE html>\n<html>\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n  <h1>Profile cards 🪪</h1>\n  <p>The component under test, rendered live below. Your suite tests it in private containers.</p>\n  <div id=\"app\"></div>\n\n  <script src=\"script.js\"></script>\n</body>\n</html>\n" },
        { name: "styles.css", content: "body {\n  font-family: Arial, sans-serif;\n  padding: 20px;\n}\n.profile {\n  display: inline-block;\n  padding: 14px 18px;\n  border: 2px solid #cbd5e1;\n  border-radius: 12px;\n}\n.who {\n  margin: 0 0 4px;\n}\n.role {\n  margin: 0 0 8px;\n  color: #64748b;\n}\n.badge {\n  display: inline-block;\n  padding: 2px 10px;\n  border-radius: 999px;\n  background: #1e293b;\n  color: white;\n  font-size: 12px;\n  letter-spacing: 1px;\n}\n" },
        { name: "script.js", content: "/* The component under test — already written. Do not edit it; test it. */\nfunction renderProfile(root, user) {\n  root.innerHTML =\n    '<div class=\"profile\">' +\n    '<h2 class=\"who\">' + user.name + '</h2>' +\n    '<p class=\"role\">' + user.role + '</p>' +\n    '<span class=\"badge\">' + (user.pro ? 'PRO' : 'FREE') + '</span>' +\n    '</div>';\n}\n\n// A live demo so the preview shows something:\nrenderProfile(document.querySelector('#app'), { name: 'Ada', role: 'Engineer', pro: true });\n\n// Your suite. The recipe, every time:\n//   const box = document.createElement('div');   // detached container\n//   renderProfile(box, { ... });                 // render\n//   expect(box.querySelector('.who').textContent).toBe('...'); // query + assert\n//\n// 1) it: renders the name into .who\n// 2) it: a pro user gets a PRO badge\n// 3) it: a free user gets a FREE badge\n\nrun();\n" }
      ],
      hints: [
        "Each test builds its own stage: `const box = document.createElement('div'); renderProfile(box, { name: 'Ada', role: 'Engineer', pro: true });` — then query inside `box`, never inside `document`.",
        "Exact text beats vague truthiness: `expect(box.querySelector('.badge').textContent).toBe('PRO');` — and a second test with `pro: false` asserting `'FREE'`.",
        "The FREE test needs its own user object — e.g. `{ name: 'Sam', role: 'Support', pro: false }` — rendered into its own fresh container."
      ],
      solution: {
        "script.js": "/* The component under test — already written. Do not edit it; test it. */\nfunction renderProfile(root, user) {\n  root.innerHTML =\n    '<div class=\"profile\">' +\n    '<h2 class=\"who\">' + user.name + '</h2>' +\n    '<p class=\"role\">' + user.role + '</p>' +\n    '<span class=\"badge\">' + (user.pro ? 'PRO' : 'FREE') + '</span>' +\n    '</div>';\n}\n\n// A live demo so the preview shows something:\nrenderProfile(document.querySelector('#app'), { name: 'Ada', role: 'Engineer', pro: true });\n\ndescribe('renderProfile', () => {\n  it('renders the name into .who', () => {\n    const box = document.createElement('div');\n    renderProfile(box, { name: 'Ada', role: 'Engineer', pro: true });\n    expect(box.querySelector('.who').textContent).toBe('Ada');\n  });\n\n  it('gives pro users a PRO badge', () => {\n    const box = document.createElement('div');\n    renderProfile(box, { name: 'Ada', role: 'Engineer', pro: true });\n    expect(box.querySelector('.badge').textContent).toBe('PRO');\n  });\n\n  it('gives free users a FREE badge', () => {\n    const box = document.createElement('div');\n    renderProfile(box, { name: 'Sam', role: 'Support', pro: false });\n    expect(box.querySelector('.badge').textContent).toBe('FREE');\n  });\n});\n\nrun();\n"
      }
    },

    {
      id: "test-u7-2",
      title: "Query like a user: byText",
      kind: "web", chip: "TEST", xp: 15, mins: 14,
      spec: true,
      brief: "`box.querySelector(\".btn-primary\")` works — until a redesign renames the class, and your test fails while the button works perfectly. A test should break when the **user's experience** breaks, not when a class name changes.\n\nSo query the way a user looks: **by visible text**. The real tools call this querying by role and accessible name — `getByRole(\"button\", { name: /add to cart/i })`. You will hand-roll the essential version: `byText(root, label)`.\n\nThree requirements, all graded: find an element by what it **says** (case and stray whitespace forgiven — users do not notice either), return the deepest matching element itself, and **throw a loud, helpful error** when nothing matches. A helper that returns `undefined` fails two lines later with a useless `Cannot read properties of undefined`; a helper that throws `Could not find an element with text \"Refund\"` fails at the scene of the crime.",
      steps: [
        { text: "Write `byText(root, label)` — it returns the element whose visible text matches. `byText(box, \"Checkout\")` finds the Checkout **button**, not its parent.",
          test: "T.expect(typeof byText === 'function', 'Declare it with function byText(root, label) { ... } so the checks can call it.');\nvar box = document.createElement('div');\nrenderToolbar(box);\nvar el = byText(box, 'Checkout');\nT.expect(!!el && !!el.tagName, 'byText must RETURN the element it found.');\nT.eq(el.tagName, 'BUTTON', 'Return the DEEPEST element whose text matches — the <button> itself, not a wrapper. Walk root.querySelectorAll(\"*\") and keep the LAST match.');" },
        { text: "Users do not notice case or stray spaces — neither does `byText`: `\"add to cart\"` finds the `  Add to cart  ` button.",
          test: "var box = document.createElement('div');\nrenderToolbar(box);\nvar el = byText(box, 'add to cart');\nT.expect(!!el && el.classList && el.classList.contains('btn-primary'), 'byText(\"add to cart\") must find the button whose text is \"  Add to cart  \" — normalize BOTH sides: .replace(/\\\\s+/g, \" \").trim().toLowerCase().');" },
        { text: "When nothing matches, `byText` **throws** — and the message names the missing label.",
          test: "var box = document.createElement('div');\nrenderToolbar(box);\nvar threw = false, msg = '';\ntry { byText(box, 'Refund'); } catch (e) { threw = true; msg = String((e && e.message) || e); }\nT.expect(threw, 'No match must THROW. A helper that quietly returns undefined makes the test fail two lines later with a useless message — fail loudly at the source.');\nT.expect(/not find|no element/i.test(msg), 'Make the error explain itself, e.g. Could not find an element with text \"Refund\". Yours said: ' + (msg || '(nothing)'));\nT.expect(msg.indexOf('Refund') !== -1, 'Include the label you searched for in the message — future-you will thank you. Yours said: ' + msg);" },
        { text: "The payoff: write one test that finds Checkout **by its label**. A redesign that renames every class must leave it green; the label changing to `Pay now` must turn it red.",
          test: "var r = await run();\nT.expect(r.total >= 1, 'Write at least one it() that uses byText to find the Checkout button and asserts it is a BUTTON.');\nT.eq(r.failed, 0, 'Your suite should be green against the real toolbar.');\nvar r2 = await T.mutate('renderToolbar', function (root) {\n  root.innerHTML = '<button class=\"c-act c-act--hot\">  Add to cart  </button><button class=\"c-act\">Checkout</button><a class=\"nav-help\" href=\"#\">Help</a>';\n}, function () { return run(); });\nT.eq(r2.failed, 0, 'The redesign renamed every class but kept every label — a byText suite SURVIVES that. Yours went red, which means a test still queries by class name.');\nvar r3 = await T.mutate('renderToolbar', function (root) {\n  root.innerHTML = '<button class=\"btn btn-primary\">  Add to cart  </button><button class=\"btn\">Pay now</button><a class=\"link\" href=\"#\">Help</a>';\n}, function () { return run(); });\nT.expect(r3.failed > 0, 'The Checkout button quietly became \"Pay now\" — the change a USER would notice — and your suite stayed green. Find the button with byText(box, \"Checkout\") so label changes fail the build.');" }
      ],
      files: [
        { name: "index.html", content: "<!DOCTYPE html>\n<html>\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n  <h1>Shop toolbar 🛒</h1>\n  <p>Three controls a user reads by their labels — and so should your tests.</p>\n  <div id=\"app\"></div>\n\n  <script src=\"script.js\"></script>\n</body>\n</html>\n" },
        { name: "styles.css", content: "body {\n  font-family: Arial, sans-serif;\n  padding: 20px;\n}\n#app {\n  display: flex;\n  gap: 10px;\n  align-items: center;\n}\n.btn {\n  font-size: 15px;\n  padding: 8px 14px;\n  border-radius: 10px;\n  border: 2px solid #cbd5e1;\n  background: white;\n  cursor: pointer;\n}\n.btn-primary {\n  background: #1e293b;\n  color: white;\n}\n.link {\n  color: #6366f1;\n}\n" },
        { name: "script.js", content: "/* Shipped and working — the toolbar under test. */\nfunction renderToolbar(root) {\n  root.innerHTML =\n    '<button class=\"btn btn-primary\">  Add to cart  </button>' +\n    '<button class=\"btn\">Checkout</button>' +\n    '<a class=\"link\" href=\"#\">Help</a>';\n}\n\nrenderToolbar(document.querySelector('#app'));\n\n// 1) function byText(root, label) { ... }\n//    - normalize BOTH sides: .replace(/\\s+/g, ' ').trim().toLowerCase()\n//    - walk root.querySelectorAll('*'); keep the LAST match (deepest wins)\n//    - nothing found? throw new Error('Could not find an element with text \"' + label + '\"')\n\n// 2) one test that finds Checkout LIKE A USER would:\n//    it('finds the Checkout button by its label', () => { ... expect(...tagName).toBe('BUTTON'); });\n\nrun();\n" }
      ],
      hints: [
        "The skeleton: `function byText(root, label) { var want = String(label).replace(/\\s+/g, ' ').trim().toLowerCase(); var hit = null; /* loop all elements */ if (!hit) throw new Error('Could not find an element with text \"' + label + '\"'); return hit; }`",
        "The loop: `for (const el of root.querySelectorAll('*')) { const t = (el.textContent || '').replace(/\\s+/g, ' ').trim().toLowerCase(); if (t === want) hit = el; }` — ancestors come first in document order, so keeping the LAST match returns the deepest element.",
        "The test for step 4: render the toolbar into a fresh container, then `expect(byText(box, 'Checkout').tagName).toBe('BUTTON');` — no class names anywhere in the test."
      ],
      solution: {
        "script.js": "/* Shipped and working — the toolbar under test. */\nfunction renderToolbar(root) {\n  root.innerHTML =\n    '<button class=\"btn btn-primary\">  Add to cart  </button>' +\n    '<button class=\"btn\">Checkout</button>' +\n    '<a class=\"link\" href=\"#\">Help</a>';\n}\n\nrenderToolbar(document.querySelector('#app'));\n\nfunction byText(root, label) {\n  var want = String(label).replace(/\\s+/g, ' ').trim().toLowerCase();\n  var hit = null;\n  var all = root.querySelectorAll('*');\n  for (var i = 0; i < all.length; i++) {\n    var t = (all[i].textContent || '').replace(/\\s+/g, ' ').trim().toLowerCase();\n    if (t === want) hit = all[i]; // later match = deeper match\n  }\n  if (!hit) throw new Error('Could not find an element with text \"' + label + '\"');\n  return hit;\n}\n\ndescribe('byText', () => {\n  it('finds the Checkout button by its label', () => {\n    const box = document.createElement('div');\n    renderToolbar(box);\n    expect(byText(box, 'Checkout').tagName).toBe('BUTTON');\n  });\n});\n\nrun();\n"
      }
    },

    {
      id: "test-u7-3",
      title: "Fire a real event",
      kind: "web", chip: "TEST", xp: 15, mins: 14,
      spec: true,
      brief: "A rendered component is scenery until someone clicks it. Your tests so far checked the scenery — now play the **user**: dispatch a **real event** and assert what re-rendered.\n\n`el.dispatchEvent(new MouseEvent(\"click\", { bubbles: true }))` sends a genuine click through the same plumbing a mouse uses — the listener fires, state updates, the DOM re-renders. `bubbles: true` matters: real clicks bubble, and delegated listeners depend on it.\n\nDo **not** call the handler yourself. `toggleLike(state)` called directly skips the wiring — a broken `addEventListener` would sail through your suite. Click the button the way a user would and the whole path gets tested. The like button ships working, with your `byText` helper from last lesson ready to use; you write the suite.",
      steps: [
        { text: "Two green tests minimum: what renders **before** any click (`♡ Like`, `12 likes`), and what renders **after** one real click (`♥ Liked`, exactly `13 likes`).",
          test: "var r = await run();\nT.expect(r.total >= 2, 'Two tests minimum: the render BEFORE any click, and the re-render AFTER one dispatched click.');\nT.eq(r.failed, 0, 'Green against the real component first — the spec panel shows which test disagrees.');" },
        { text: "Mutant check: a like button whose click changes **nothing** must go red.",
          test: "var r = await T.mutate('toggleLike', function (s) { return { liked: s.liked, count: s.count }; }, function () { return run(); });\nT.expect(r.failed > 0, 'A like button whose click changes NOTHING passed all your tests — after the dispatch, assert the re-rendered result: the label flips to \"♥ Liked\" and the count reads \"13 likes\".');" },
        { text: "Mutant check: a version that jumps the count by **2** must go red — assert the exact text, not just a bigger number.",
          test: "var r = await T.mutate('toggleLike', function (s) {\n  if (s.liked) return { liked: false, count: s.count - 1 };\n  return { liked: true, count: s.count + 2 };\n}, function () { return run(); });\nT.expect(r.failed > 0, 'A version that jumps the count by 2 per click passed all your tests — assert the EXACT rendered text after one click: \"13 likes\", not just that the number changed.');" },
        { text: "Mutant check: a button **nobody wired up** must go red — only a real dispatched click can tell the difference.",
          test: "var real = renderLikeButton;\nvar r = await T.mutate('renderLikeButton', function (root, s) {\n  real(root, s);\n  var b = root.querySelector('button');\n  b.replaceWith(b.cloneNode(true));\n}, function () { return run(); });\nT.expect(r.failed > 0, 'A button that LOOKS identical but ignores every click passed all your tests — dispatch a REAL event in your test: el.dispatchEvent(new MouseEvent(\"click\", { bubbles: true })), and never call toggleLike() yourself.');\nvar r2 = await run();\nT.eq(r2.failed, 0, 'Real component back in place — your suite ends green.');" }
      ],
      files: [
        { name: "index.html", content: "<!DOCTYPE html>\n<html>\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n  <h1>Like button ❤️</h1>\n  <p>Click the live demo — then make your tests do the clicking.</p>\n  <div id=\"app\"></div>\n\n  <script src=\"script.js\"></script>\n</body>\n</html>\n" },
        { name: "styles.css", content: "body {\n  font-family: Arial, sans-serif;\n  padding: 20px;\n}\n#app {\n  display: flex;\n  gap: 10px;\n  align-items: center;\n}\n.like {\n  font-size: 15px;\n  padding: 8px 14px;\n  border-radius: 10px;\n  border: 2px solid #cbd5e1;\n  background: white;\n  cursor: pointer;\n}\n.like.on {\n  background: #fda4af;\n  border-color: #f43f5e;\n}\n.count {\n  color: #64748b;\n}\n" },
        { name: "script.js", content: "/* Shipped and working — the component under test. */\nfunction toggleLike(state) {\n  if (state.liked) return { liked: false, count: state.count - 1 };\n  return { liked: true, count: state.count + 1 };\n}\n\nfunction renderLikeButton(root, state) {\n  root.innerHTML =\n    '<button class=\"like' + (state.liked ? ' on' : '') + '\">' + (state.liked ? '♥ Liked' : '♡ Like') + '</button>' +\n    '<span class=\"count\">' + state.count + ' likes</span>';\n  root.querySelector('button').addEventListener('click', function () {\n    renderLikeButton(root, toggleLike(state));\n  });\n}\n\n/* Your helper from last lesson — free to use. */\nfunction byText(root, label) {\n  var want = String(label).replace(/\\s+/g, ' ').trim().toLowerCase();\n  var hit = null;\n  var all = root.querySelectorAll('*');\n  for (var i = 0; i < all.length; i++) {\n    var t = (all[i].textContent || '').replace(/\\s+/g, ' ').trim().toLowerCase();\n    if (t === want) hit = all[i];\n  }\n  if (!hit) throw new Error('Could not find an element with text \"' + label + '\"');\n  return hit;\n}\n\nrenderLikeButton(document.querySelector('#app'), { liked: false, count: 12 });\n\n// Your suite — start every test fresh from { liked: false, count: 12 }.\n// 1) it: before any click — the button says '♡ Like', the count says '12 likes'\n// 2) it: dispatch a REAL click on the button, then assert the re-render:\n//        '♥ Liked' and EXACTLY '13 likes'\n\nrun();\n" }
      ],
      hints: [
        "Each test renders its own copy: `const box = document.createElement('div'); renderLikeButton(box, { liked: false, count: 12 });` — then find things with `byText(box, ...)`.",
        "The click: `byText(box, '♡ Like').dispatchEvent(new MouseEvent('click', { bubbles: true }));` — dispatch on the element, never call toggleLike() directly.",
        "After the click, assert what the USER sees: `expect(byText(box, '13 likes').textContent.trim()).toBe('13 likes');` — byText throws if the re-render went wrong, which is exactly what you want."
      ],
      solution: {
        "script.js": "/* Shipped and working — the component under test. */\nfunction toggleLike(state) {\n  if (state.liked) return { liked: false, count: state.count - 1 };\n  return { liked: true, count: state.count + 1 };\n}\n\nfunction renderLikeButton(root, state) {\n  root.innerHTML =\n    '<button class=\"like' + (state.liked ? ' on' : '') + '\">' + (state.liked ? '♥ Liked' : '♡ Like') + '</button>' +\n    '<span class=\"count\">' + state.count + ' likes</span>';\n  root.querySelector('button').addEventListener('click', function () {\n    renderLikeButton(root, toggleLike(state));\n  });\n}\n\n/* Your helper from last lesson — free to use. */\nfunction byText(root, label) {\n  var want = String(label).replace(/\\s+/g, ' ').trim().toLowerCase();\n  var hit = null;\n  var all = root.querySelectorAll('*');\n  for (var i = 0; i < all.length; i++) {\n    var t = (all[i].textContent || '').replace(/\\s+/g, ' ').trim().toLowerCase();\n    if (t === want) hit = all[i];\n  }\n  if (!hit) throw new Error('Could not find an element with text \"' + label + '\"');\n  return hit;\n}\n\nrenderLikeButton(document.querySelector('#app'), { liked: false, count: 12 });\n\ndescribe('like button', () => {\n  it('shows the label and count before any click', () => {\n    const box = document.createElement('div');\n    renderLikeButton(box, { liked: false, count: 12 });\n    expect(byText(box, '♡ Like').tagName).toBe('BUTTON');\n    expect(byText(box, '12 likes').tagName).toBe('SPAN');\n  });\n\n  it('one real click flips the label and shows exactly 13 likes', () => {\n    const box = document.createElement('div');\n    renderLikeButton(box, { liked: false, count: 12 });\n    byText(box, '♡ Like').dispatchEvent(new MouseEvent('click', { bubbles: true }));\n    expect(byText(box, '♥ Liked').tagName).toBe('BUTTON');\n    expect(byText(box, '13 likes').textContent.trim()).toBe('13 likes');\n  });\n});\n\nrun();\n"
      }
    },

    {
      id: "test-u7-p",
      title: "Project: Test a live component — the counter card",
      kind: "web", chip: "TEST", xp: 50, mins: 40, project: true,
      spec: true,
      brief: "Everything this unit taught, against one **live component**: the counter card. `renderCounter(root, state)` and `increment(state)` ship written and working — your deliverable is the **suite** that would catch anyone who breaks them.\n\nThe discipline checklist: a **fresh container** built in `beforeEach` (nothing ever touches `document.body`), queries by what the user sees, **real dispatched clicks**, and assertions on the **exact rendered text**. One trap to respect: every click re-renders the card, so the button you just clicked is now a dead node — **re-query before clicking again**.\n\nThe checks play saboteur: a `+1` that does nothing, one that jumps by 2, a button nobody wired up — and then the whole suite runs **twice**, demanding identical results. A suite that leaks DOM between tests tells a different story on run 2.",
      steps: [
        { text: "Your suite is green against the working counter — at least **four tests**: the starting count, exactly one click, two clicks, and a non-zero starting state.",
          test: "var probe = document.createElement('div');\nrenderCounter(probe, { count: 5 });\nT.eq((probe.querySelector('[data-count]') || {}).textContent, '5', 'Leave renderCounter() and increment() exactly as shipped — the deliverable is the suite, not the component.');\nvar r = await run();\nT.expect(r.total >= 4, 'Four tests minimum: the start value, exactly one click, two clicks, and a non-zero starting state like { count: 41 }.');\nT.eq(r.failed, 0, 'Your suite must be green against the WORKING counter — the spec panel shows which test disagrees.');" },
        { text: "Saboteur 1: a `+1` button that does **nothing** must turn the suite red.",
          test: "var r = await T.mutate('increment', function (s) { return { count: s.count }; }, function () { return run(); });\nT.expect(r.failed > 0, 'A + button that does NOTHING passed all your tests — dispatch a real click in a test and assert the rendered count afterwards.');" },
        { text: "Saboteur 2: a counter that adds **2** per click must fail too.",
          test: "var r = await T.mutate('increment', function (s) { return { count: s.count + 2 }; }, function () { return run(); });\nT.expect(r.failed > 0, 'A counter that adds 2 per click passed all your tests — click once and assert the exact rendered text, not just that it changed.');" },
        { text: "Saboteur 3: a card whose button was **never wired up** must fail — only a real dispatched click can tell.",
          test: "var real = renderCounter;\nvar r = await T.mutate('renderCounter', function (root, s) {\n  real(root, s);\n  var b = root.querySelector('button');\n  b.replaceWith(b.cloneNode(true));\n}, function () { return run(); });\nT.expect(r.failed > 0, 'A card that LOOKS right but ignores every click passed all your tests — click through the DOM with dispatchEvent, never by calling increment() yourself.');" },
        { text: "The suite tells the same story **twice**: run it again — identical results, zero leftovers.",
          test: "var a = await run();\nvar b = await run();\nT.eq(a.failed, 0, 'Green on run 1 with the real component restored.');\nT.eq(b.failed, 0, 'Run 2 went red — a test is reading DOM a previous run left behind. Build a FRESH container in beforeEach and never append anything to document.body.');\nT.eq(\n  b.results.map(function (x) { return x.suite + ' > ' + x.name + ' > ' + x.pass; }),\n  a.results.map(function (x) { return x.suite + ' > ' + x.name + ' > ' + x.pass; }),\n  'Two runs, two different stories — that is state leaking between tests. Every test gets its own container in beforeEach; nothing outlives a test.'\n);" }
      ],
      files: [
        { name: "index.html", content: "<!DOCTYPE html>\n<html>\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n  <h1>Counter card 🔢</h1>\n  <p>The live component. Your suite gets its own private copies.</p>\n  <div id=\"app\"></div>\n\n  <script src=\"script.js\"></script>\n</body>\n</html>\n" },
        { name: "styles.css", content: "body {\n  font-family: Arial, sans-serif;\n  padding: 20px;\n}\n.card {\n  display: inline-block;\n  padding: 16px 22px;\n  border: 2px solid #cbd5e1;\n  border-radius: 14px;\n  text-align: center;\n}\n.card h2 {\n  margin: 0 0 6px;\n  font-size: 16px;\n  color: #64748b;\n}\n.value {\n  font-size: 42px;\n  font-weight: bold;\n  margin: 0 0 10px;\n}\n.bump {\n  font-size: 15px;\n  padding: 8px 16px;\n  border-radius: 10px;\n  border: 2px solid #cbd5e1;\n  background: white;\n  cursor: pointer;\n}\n" },
        { name: "script.js", content: "/* Shipped and working — test it, do not rebuild it. */\nfunction increment(state) {\n  return { count: state.count + 1 };\n}\n\nfunction renderCounter(root, state) {\n  root.innerHTML =\n    '<div class=\"card\">' +\n    '<h2>Visitor counter</h2>' +\n    '<p class=\"value\" data-count>' + state.count + '</p>' +\n    '<button class=\"bump\">+1</button>' +\n    '</div>';\n  root.querySelector('button').addEventListener('click', function () {\n    renderCounter(root, increment(state));\n  });\n}\n\n/* Your byText helper, ready to use. */\nfunction byText(root, label) {\n  var want = String(label).replace(/\\s+/g, ' ').trim().toLowerCase();\n  var hit = null;\n  var all = root.querySelectorAll('*');\n  for (var i = 0; i < all.length; i++) {\n    var t = (all[i].textContent || '').replace(/\\s+/g, ' ').trim().toLowerCase();\n    if (t === want) hit = all[i];\n  }\n  if (!hit) throw new Error('Could not find an element with text \"' + label + '\"');\n  return hit;\n}\n\nrenderCounter(document.querySelector('#app'), { count: 0 });\n\n// The suite. Discipline:\n//   let box;\n//   beforeEach(() => { box = document.createElement('div'); });  // fresh stage, every test\n//   - real clicks: byText(box, '+1').dispatchEvent(new MouseEvent('click', { bubbles: true }))\n//   - every click RE-RENDERS the card — re-query the button before clicking again\n//   - assert the EXACT text in [data-count]\n//\n// 1) it: renders the starting count ('0')\n// 2) it: one click shows exactly '1'\n// 3) it: two clicks show exactly '2' (re-query between clicks!)\n// 4) it: starts wherever the state says — { count: 41 } renders '41'\n\nrun();\n" }
      ],
      hints: [
        "The fixture: `let box; beforeEach(() => { box = document.createElement('div'); });` — every test then starts with `renderCounter(box, { count: 0 });` (or 41) on an untouched stage.",
        "One click, exact assertion: `byText(box, '+1').dispatchEvent(new MouseEvent('click', { bubbles: true })); expect(box.querySelector('[data-count]').textContent).toBe('1');` — the string '1', because textContent is always a string.",
        "The two-click test clicks, then RE-QUERIES: the first click re-rendered the card, so call `byText(box, '+1')` again for the second click — the old button is detached and its clicks go nowhere."
      ],
      solution: {
        "script.js": "/* Shipped and working — test it, do not rebuild it. */\nfunction increment(state) {\n  return { count: state.count + 1 };\n}\n\nfunction renderCounter(root, state) {\n  root.innerHTML =\n    '<div class=\"card\">' +\n    '<h2>Visitor counter</h2>' +\n    '<p class=\"value\" data-count>' + state.count + '</p>' +\n    '<button class=\"bump\">+1</button>' +\n    '</div>';\n  root.querySelector('button').addEventListener('click', function () {\n    renderCounter(root, increment(state));\n  });\n}\n\n/* Your byText helper, ready to use. */\nfunction byText(root, label) {\n  var want = String(label).replace(/\\s+/g, ' ').trim().toLowerCase();\n  var hit = null;\n  var all = root.querySelectorAll('*');\n  for (var i = 0; i < all.length; i++) {\n    var t = (all[i].textContent || '').replace(/\\s+/g, ' ').trim().toLowerCase();\n    if (t === want) hit = all[i];\n  }\n  if (!hit) throw new Error('Could not find an element with text \"' + label + '\"');\n  return hit;\n}\n\nrenderCounter(document.querySelector('#app'), { count: 0 });\n\nlet box;\nbeforeEach(() => {\n  box = document.createElement('div');\n});\n\nfunction clickPlusOne() {\n  byText(box, '+1').dispatchEvent(new MouseEvent('click', { bubbles: true }));\n}\n\ndescribe('counter card', () => {\n  it('renders the starting count', () => {\n    renderCounter(box, { count: 0 });\n    expect(box.querySelector('[data-count]').textContent).toBe('0');\n  });\n\n  it('one click shows exactly 1', () => {\n    renderCounter(box, { count: 0 });\n    clickPlusOne();\n    expect(box.querySelector('[data-count]').textContent).toBe('1');\n  });\n\n  it('two clicks show exactly 2', () => {\n    renderCounter(box, { count: 0 });\n    clickPlusOne();\n    clickPlusOne(); // re-queried — the first click re-rendered the card\n    expect(box.querySelector('[data-count]').textContent).toBe('2');\n  });\n\n  it('starts wherever the state says', () => {\n    renderCounter(box, { count: 41 });\n    expect(box.querySelector('[data-count]').textContent).toBe('41');\n  });\n});\n\nrun();\n"
      }
    },

    {
      id: "test-quiz-7",
      title: "Unit 7 quiz: DOM tests",
      kind: "quiz", xp: 10,
      brief: "Containers, text queries, real events, and suites that behave twice in a row. 80% to pass.",
      questions: [
        { q: "This test fails against a perfectly working counter. Why?",
          code: "const box = document.createElement(\"div\");\nrenderCounter(box, { count: 0 });\nexpect(box.querySelector(\"[data-count]\").textContent).toBe(0);",
          lang: "js",
          choices: ["The counter renders asynchronously, so the DOM is still empty when the test asserts", "textContent is always a string — the test must expect \"0\"", "querySelector cannot see elements inside a detached container", "toBe never works on numbers; only toEqual can compare them"],
          answer: 1, explain: "textContent always hands back a string, so the element holds \"0\" — and \"0\" is not 0 under toBe's strict comparison. Assert the exact rendered text: .toBe(\"0\"). Detached containers are fully queryable and the component renders synchronously, so the DOM really is there; the type is the whole problem." },
        { q: "A redesign renames every CSS class; the buttons look and behave exactly the same. Which test survives, and why is that the right outcome?",
          choices: ["The querySelector(\".btn-primary\") test — class selectors are the most precise way to target elements", "Neither — any change to the markup should turn a good suite red", "Both — run() re-queries the DOM automatically after markup changes", "The byText(box, \"Add to cart\") test — users read labels, not class names"],
          answer: 3, explain: "The visible label is the component's public contract: it is what a user reads, and what a refactor must preserve. Class names are implementation details that legitimately change all the time, so a class-based query fails for reasons no user would ever notice. Query by text and your suite goes red only when the user's experience actually changes." },
        { q: "The delegated listener on the list never runs. What is missing from the dispatched event?",
          code: "list.addEventListener(\"click\", onItemClick); // delegated to the parent\n// in the test:\nitem.dispatchEvent(new MouseEvent(\"click\"));",
          lang: "js",
          choices: ["`{ bubbles: true }`", "`{ cancelable: true }`", "a `setTimeout` before asserting, so the event can travel", "a `stopPropagation()` call on the item"],
          answer: 0, explain: "Synthetic events default to bubbles: false, so the click fires on the item and dies right there — it never travels up to the parent where the delegated listener waits. Real user clicks always bubble. new MouseEvent(\"click\", { bubbles: true }) makes the test click behave like a finger." },
        { q: "This is the suite's only assertion after the click. Why does a broken counter that adds 2 per click still pass?",
          code: "byText(box, \"+1\").dispatchEvent(new MouseEvent(\"click\", { bubbles: true }));\nexpect(box.querySelector(\"[data-count]\").textContent).toBeTruthy();",
          lang: "js",
          choices: ["dispatchEvent swallowed the click, so the counter never actually moved", "toBeTruthy only re-renders the component; it does not assert anything", "\"2\" is truthy too — assert the exact text: expect(...).toBe(\"1\")", "the mutant also changes byText, hiding the wrong count from the query entirely"],
          answer: 2, explain: "toBeTruthy passes for \"1\", \"2\", or any non-empty string — it can tell something from nothing, never right from wrong. Pin the exact value: starting at 0, one click must render exactly \"1\", and the add-2 mutant dies instantly. Assert values, not vibes — that is the entire lesson mutation testing teaches." },
        { q: "The suite is green — until you run it a second time, when two tests go red. What is the usual culprit in DOM suites?",
          choices: ["The spec runner randomizes test order on every run() to catch dependencies", "A test left its card in document.body — later queries find the stale one", "expect() caches its results, and the cache expires between runs", "beforeEach hooks only fire on the very first run of a suite"],
          answer: 1, explain: "Everything a test attaches to document.body survives the run, so the second run's document-wide queries can match last run's leftover card before the fresh one. Test order is stable and nothing is cached — the leaked state is in your page. Isolate: build a fresh detached container in beforeEach and query only inside it." },
        { q: "One test clicks the counter up to 3; the next test expects a pristine 0 and fails. Which hook exists precisely to prevent this?",
          choices: ["`beforeEach`", "`describe`", "`toBeCloseTo`", "`run`"],
          answer: 0, explain: "beforeEach runs before every single test — build a brand-new container there (box = document.createElement(\"div\")) and each test starts from untouched DOM, whatever the previous test clicked. describe only labels a group and run() executes the suite; neither one resets anything." }
      ]
    }
  ]
});
