/* Back-End Foundations — Unit 7: Project: Bookmarks API */
window.CODELAB.addUnit("srv", {
  id: "srv-u7",
  title: "Project: Bookmarks API",
  icon: "🔖",
  blurb: "The graduation build: a real Bookmarks REST API — validation, error envelopes, search and counts — from empty file to shipped v1.",
  cheat: [
    { h: "The Bookmarks API at a glance", lang: "js", code: "GET    /api/bookmarks       // list  (+ ?q= & ?limit=)\nPOST   /api/bookmarks       // create (validated!)\nGET    /api/bookmarks/7     // read one\nPATCH  /api/bookmarks/7     // merge changes\nDELETE /api/bookmarks/7     // remove", note: "One noun, five moves — the exact shape of this unit's project." },
    { h: "Error envelope — every failure, one shape", lang: "js", code: "// 400: the client sent junk\n{ status: 400, body: { error: { code: \"invalid\",   message: \"title is required\" } } }\n// 404: the thing isn't there\n{ status: 404, body: { error: { code: \"not_found\", message: \"bookmark not found\" } } }", note: "Unit 6's rule, applied everywhere: clients handle ALL errors with one code path." },
    { h: "List responses with counts", lang: "js", code: "// GET /api/bookmarks?q=docs&limit=1\n{ status: 200, body: { items: [ /* first match */ ], total: 2 } }", note: "items is the sliced page; total counts every match BEFORE the limit — that's how a UI says \"showing 1 of 2\"." },
    { h: "Validate, then act", lang: "js", code: "if (!req.body || typeof req.body.title !== \"string\" || req.body.title.trim() === \"\")\n  return { status: 400, body: { error: { code: \"invalid\", message: \"title is required\" } } };\nif (typeof req.body.url !== \"string\" || !req.body.url.startsWith(\"http\"))\n  return { status: 400, body: { error: { code: \"invalid\", message: \"url must start with http\" } } };\n// only NOW touch the store", note: "Title first, then url — a fixed order means a null body always fails the same way." },
    { h: "How this looks in Express (real Node.js)", lang: "js", code: "app.get(\"/api/bookmarks/:id\", (req, res) => {\n  const found = bookmarks.find(b => b.id === Number(req.params.id));\n  if (!found) return res.status(404)\n    .json({ error: { code: \"not_found\", message: \"bookmark not found\" } });\n  res.json(found);\n});", note: "Express parses :id for you (req.params.id) — you've been doing its job by hand with split(\"/\")." }
  ],
  lessons: [

    {
      id: "srv-u7-1",
      title: "Spec & skeleton",
      kind: "js", chip: "SERVER", xp: 15, mins: 14,
      brief: "Time to ship something real. This whole unit is **one build**: a Bookmarks API, spec'd like a real ticket. A bookmark is `{ id, title, url }` — ids from a counter, starting at 1.\n\nThis lesson lays the foundation:\n\n- `GET /api/bookmarks` → `{ status: 200, body: [...] }`\n- `POST /api/bookmarks` → validate **title first, then url**: missing/empty `title` → 400 `{ error: { code: \"invalid\", message: \"title is required\" } }`; a `url` that doesn't start with `\"http\"` → 400 with `\"url must start with http\"`. Valid → **201** with the created bookmark.\n- Anything else → the 404 envelope with `\"no such route\"`.\n\nError envelopes are the Unit 6 shape — one format for every failure.",
      steps: [
        { text: "`GET /api/bookmarks` → 200 with the (empty) store.",
          test: "T.expect(typeof handleRequest === 'function', 'Define handleRequest(req).');\nvar res = handleRequest({ method: 'GET', path: '/api/bookmarks', body: null });\nT.eq(res, { status: 200, body: [] }, 'GET /api/bookmarks should answer { status: 200, body: [] } while the store is empty');" },
        { text: "`POST /api/bookmarks` → **201** with the created bookmark; ids count up from 1.",
          test: "var res = handleRequest({ method: 'POST', path: '/api/bookmarks', body: { title: 'MDN', url: 'https://developer.mozilla.org' } });\nT.eq(res, { status: 201, body: { id: 1, title: 'MDN', url: 'https://developer.mozilla.org' } }, 'POST should answer 201 with { id: 1, title, url } — yours returned status ' + (res && res.status));\nvar res2 = handleRequest({ method: 'POST', path: '/api/bookmarks', body: { title: 'CSS Tricks', url: 'https://css-tricks.com' } });\nT.eq(res2.body.id, 2, 'Ids count up: the second bookmark gets id 2');\nT.eq(handleRequest({ method: 'GET', path: '/api/bookmarks', body: null }).body, [{ id: 1, title: 'MDN', url: 'https://developer.mozilla.org' }, { id: 2, title: 'CSS Tricks', url: 'https://css-tricks.com' }], 'Both bookmarks should be IN the list afterwards');" },
        { text: "Validation: bad creates → **400** envelopes (title checked first), and nothing gets stored.",
          test: "T.eq(handleRequest({ method: 'POST', path: '/api/bookmarks', body: { url: 'https://ok.com' } }), { status: 400, body: { error: { code: 'invalid', message: 'title is required' } } }, 'Missing title → 400 with the \"title is required\" envelope');\nT.eq(handleRequest({ method: 'POST', path: '/api/bookmarks', body: { title: 'Old FTP', url: 'ftp://files.example' } }), { status: 400, body: { error: { code: 'invalid', message: 'url must start with http' } } }, 'A url that does not start with \"http\" → 400 envelope');\nT.eq(handleRequest({ method: 'POST', path: '/api/bookmarks', body: null }), { status: 400, body: { error: { code: 'invalid', message: 'title is required' } } }, 'A null body fails the title check first — check req.body BEFORE reading .title');\nT.eq(handleRequest({ method: 'GET', path: '/api/bookmarks', body: null }).body.length, 2, 'Rejected requests must not create anything');" },
        { text: "Everything else → the 404 envelope `\"no such route\"`.",
          test: "T.eq(handleRequest({ method: 'GET', path: '/api/nope', body: null }), { status: 404, body: { error: { code: 'not_found', message: 'no such route' } } }, 'Unknown paths get the 404 envelope');\nT.eq(handleRequest({ method: 'PUT', path: '/api/bookmarks', body: null }), { status: 404, body: { error: { code: 'not_found', message: 'no such route' } } }, 'Unknown method on a known path → same 404 envelope (for now)');" }
      ],
      files: [
        { name: "script.js", content: "// Bookmarks API — the unit project starts here.\n//   request  = { method, path, body }      (query joins in the final build)\n//   response = { status, body }\n// Error envelope (Unit 6 style): { error: { code, message } }\n\nlet bookmarks = [];\nlet nextId = 1;\n\nfunction handleRequest(req) {\n  // 1) GET  /api/bookmarks → { status: 200, body: bookmarks }\n  // 2) POST /api/bookmarks → validate FIRST (title, then url):\n  //      no body / no title       → 400 { error: { code: \"invalid\", message: \"title is required\" } }\n  //      url not starting \"http\"  → 400 { error: { code: \"invalid\", message: \"url must start with http\" } }\n  //      valid → 201 with { id, title, url }   (ids from nextId++)\n  // 3) anything else → 404 { error: { code: \"not_found\", message: \"no such route\" } }\n}\n\nconsole.log(handleRequest({ method: \"GET\", path: \"/api/bookmarks\", body: null }));\n" }
      ],
      hints: [
        "Validation is just early returns at the top of the POST branch: `if (!req.body || typeof req.body.title !== \"string\" || req.body.title.trim() === \"\") return { status: 400, body: { error: { code: \"invalid\", message: \"title is required\" } } };`",
        "The url check comes second: `if (typeof req.body.url !== \"string\" || !req.body.url.startsWith(\"http\")) …` — same envelope shape, message \"url must start with http\".",
        "Create like Unit 2: `const bm = { id: nextId++, title: req.body.title, url: req.body.url }; bookmarks.push(bm); return { status: 201, body: bm };`"
      ],
      solution: {
        "script.js": "// Bookmarks API — the unit project starts here.\n//   request  = { method, path, body }\n//   response = { status, body }\n\nlet bookmarks = [];\nlet nextId = 1;\n\nfunction handleRequest(req) {\n  if (req.method === \"GET\" && req.path === \"/api/bookmarks\") {\n    return { status: 200, body: bookmarks };\n  }\n\n  if (req.method === \"POST\" && req.path === \"/api/bookmarks\") {\n    if (!req.body || typeof req.body.title !== \"string\" || req.body.title.trim() === \"\") {\n      return { status: 400, body: { error: { code: \"invalid\", message: \"title is required\" } } };\n    }\n    if (typeof req.body.url !== \"string\" || !req.body.url.startsWith(\"http\")) {\n      return { status: 400, body: { error: { code: \"invalid\", message: \"url must start with http\" } } };\n    }\n    const bm = { id: nextId++, title: req.body.title, url: req.body.url };\n    bookmarks.push(bm);\n    return { status: 201, body: bm };\n  }\n\n  return { status: 404, body: { error: { code: \"not_found\", message: \"no such route\" } } };\n}\n\nconsole.log(handleRequest({ method: \"GET\", path: \"/api/bookmarks\", body: null }));\n"
      }
    },

    {
      id: "srv-u7-2",
      title: "Complete the resource",
      kind: "js", chip: "SERVER", xp: 15, mins: 14,
      brief: "A list you can't open items from is a teaser, not an API. Add the three **detail routes** — the id rides in the path (`/api/bookmarks/7`), so split and `Number(...)` it like Unit 2:\n\n- `GET /api/bookmarks/:id` → 200 with the record\n- `PATCH /api/bookmarks/:id` → **merge** `req.body` into the record (only the fields sent change — the rest survive), 200 with the updated record\n- `DELETE /api/bookmarks/:id` → 200 `{ ok: true }`\n\nAll three answer a missing id with `{ status: 404, body: { error: { code: \"not_found\", message: \"bookmark not found\" } } }`. And ids are **never reused** — deleting #1 doesn't rewind the counter.",
      steps: [
        { text: "`GET /api/bookmarks/<id>` → 200 with that record; missing id → the `\"bookmark not found\"` envelope.",
          test: "handleRequest({ method: 'POST', path: '/api/bookmarks', body: { title: 'MDN', url: 'https://developer.mozilla.org' } });\nhandleRequest({ method: 'POST', path: '/api/bookmarks', body: { title: 'CSS Tricks', url: 'https://css-tricks.com' } });\nvar res = handleRequest({ method: 'GET', path: '/api/bookmarks/1', body: null });\nT.eq(res, { status: 200, body: { id: 1, title: 'MDN', url: 'https://developer.mozilla.org' } }, 'GET /api/bookmarks/1 should return bookmark #1 — yours returned status ' + (res && res.status));\nT.eq(handleRequest({ method: 'GET', path: '/api/bookmarks/99', body: null }), { status: 404, body: { error: { code: 'not_found', message: 'bookmark not found' } } }, 'GET on a missing id → the 404 \"bookmark not found\" envelope');" },
        { text: "`PATCH /api/bookmarks/<id>` **merges** — untouched fields survive; missing id → 404 envelope.",
          test: "var res = handleRequest({ method: 'PATCH', path: '/api/bookmarks/2', body: { title: 'CSS-Tricks (updated)' } });\nT.eq(res, { status: 200, body: { id: 2, title: 'CSS-Tricks (updated)', url: 'https://css-tricks.com' } }, 'PATCH merges: a title-only patch must keep the url');\nvar res2 = handleRequest({ method: 'PATCH', path: '/api/bookmarks/1', body: { url: 'https://developer.mozilla.org/en-US' } });\nT.eq(res2, { status: 200, body: { id: 1, title: 'MDN', url: 'https://developer.mozilla.org/en-US' } }, 'A url-only patch must keep the title');\nT.eq(handleRequest({ method: 'PATCH', path: '/api/bookmarks/42', body: { title: 'ghost' } }), { status: 404, body: { error: { code: 'not_found', message: 'bookmark not found' } } }, 'PATCH on a missing id → 404 envelope');" },
        { text: "`DELETE /api/bookmarks/<id>` → 200 `{ ok: true }`; deleting it twice → 404 envelope.",
          test: "T.eq(handleRequest({ method: 'DELETE', path: '/api/bookmarks/1', body: null }), { status: 200, body: { ok: true } }, 'DELETE /api/bookmarks/1');\nvar list = handleRequest({ method: 'GET', path: '/api/bookmarks', body: null });\nT.eq(list.body, [{ id: 2, title: 'CSS-Tricks (updated)', url: 'https://css-tricks.com' }], 'Only #2 (with its patched title) should remain in the list');\nT.eq(handleRequest({ method: 'DELETE', path: '/api/bookmarks/1', body: null }), { status: 404, body: { error: { code: 'not_found', message: 'bookmark not found' } } }, 'Deleting the same id twice → 404 envelope');" },
        { text: "Ids are never reused: after deleting #1, the next create is **#3**.",
          test: "var res = handleRequest({ method: 'POST', path: '/api/bookmarks', body: { title: 'Node docs', url: 'https://nodejs.org' } });\nT.eq(res, { status: 201, body: { id: 3, title: 'Node docs', url: 'https://nodejs.org' } }, 'The counter keeps counting — the next id is 3, not 1');\nT.eq(handleRequest({ method: 'GET', path: '/api/bookmarks/3', body: null }).status, 200, 'And #3 is fetchable');" }
      ],
      files: [
        { name: "script.js", content: "// The store + list + create are done (last lesson). Add the detail routes.\n\nlet bookmarks = [];\nlet nextId = 1;\n\nfunction handleRequest(req) {\n  if (req.method === \"GET\" && req.path === \"/api/bookmarks\") {\n    return { status: 200, body: bookmarks };\n  }\n  if (req.method === \"POST\" && req.path === \"/api/bookmarks\") {\n    if (!req.body || typeof req.body.title !== \"string\" || req.body.title.trim() === \"\") {\n      return { status: 400, body: { error: { code: \"invalid\", message: \"title is required\" } } };\n    }\n    if (typeof req.body.url !== \"string\" || !req.body.url.startsWith(\"http\")) {\n      return { status: 400, body: { error: { code: \"invalid\", message: \"url must start with http\" } } };\n    }\n    const bm = { id: nextId++, title: req.body.title, url: req.body.url };\n    bookmarks.push(bm);\n    return { status: 201, body: bm };\n  }\n\n  // TODO — /api/bookmarks/<id> routes (parse the id from the path):\n  //   GET    → 200 with the record | 404 { error: { code: \"not_found\", message: \"bookmark not found\" } }\n  //   PATCH  → merge req.body's title/url into the record, 200 | 404 envelope\n  //   DELETE → 200 { ok: true } | 404 envelope\n\n  return { status: 404, body: { error: { code: \"not_found\", message: \"no such route\" } } };\n}\n" }
      ],
      hints: [
        "All three routes start the same: `if (req.path.startsWith(\"/api/bookmarks/\")) { const id = Number(req.path.split(\"/\")[3]); const found = bookmarks.find(b => b.id === id); … }` — parse once, find once, then branch on `req.method`.",
        "Merge = overwrite only what was sent: `if (req.body && typeof req.body.title === \"string\") found.title = req.body.title;` (and the same for `url`).",
        "DELETE reuses the Unit 2 filter trick: `bookmarks = bookmarks.filter(b => b.id !== id);` — which is exactly why the store is declared with `let`."
      ],
      solution: {
        "script.js": "// The store + list + create are done (last lesson). Add the detail routes.\n\nlet bookmarks = [];\nlet nextId = 1;\n\nfunction handleRequest(req) {\n  if (req.method === \"GET\" && req.path === \"/api/bookmarks\") {\n    return { status: 200, body: bookmarks };\n  }\n  if (req.method === \"POST\" && req.path === \"/api/bookmarks\") {\n    if (!req.body || typeof req.body.title !== \"string\" || req.body.title.trim() === \"\") {\n      return { status: 400, body: { error: { code: \"invalid\", message: \"title is required\" } } };\n    }\n    if (typeof req.body.url !== \"string\" || !req.body.url.startsWith(\"http\")) {\n      return { status: 400, body: { error: { code: \"invalid\", message: \"url must start with http\" } } };\n    }\n    const bm = { id: nextId++, title: req.body.title, url: req.body.url };\n    bookmarks.push(bm);\n    return { status: 201, body: bm };\n  }\n\n  if (req.path.startsWith(\"/api/bookmarks/\")) {\n    const id = Number(req.path.split(\"/\")[3]);\n    const found = bookmarks.find(b => b.id === id);\n\n    if (req.method === \"GET\") {\n      if (!found) return { status: 404, body: { error: { code: \"not_found\", message: \"bookmark not found\" } } };\n      return { status: 200, body: found };\n    }\n    if (req.method === \"PATCH\") {\n      if (!found) return { status: 404, body: { error: { code: \"not_found\", message: \"bookmark not found\" } } };\n      if (req.body && typeof req.body.title === \"string\") found.title = req.body.title;\n      if (req.body && typeof req.body.url === \"string\") found.url = req.body.url;\n      return { status: 200, body: found };\n    }\n    if (req.method === \"DELETE\") {\n      if (!found) return { status: 404, body: { error: { code: \"not_found\", message: \"bookmark not found\" } } };\n      bookmarks = bookmarks.filter(b => b.id !== id);\n      return { status: 200, body: { ok: true } };\n    }\n  }\n\n  return { status: 404, body: { error: { code: \"not_found\", message: \"no such route\" } } };\n}\n"
      }
    },

    {
      id: "srv-u7-p",
      title: "Project: Bookmarks API v1",
      kind: "js", chip: "SERVER", xp: 50, mins: 40, project: true,
      brief: "The real thing, from an empty file: **Bookmarks API v1** — every convention from Units 1–6 in one handler.\n\nThe v1 upgrade: the list response grows **counts** — `GET /api/bookmarks` answers `{ status: 200, body: { items, total } }`. `?q=` filters by title (case-insensitive), `?limit=N` slices the page, and `total` counts every match **before** the limit. Query values arrive as strings (`limit: \"2\"`), and `req.query` can be missing entirely — default it to `{}`.\n\nEverything else you've already built once: validation-first POST (title, then url), detail `GET`/`PATCH`(merge)/`DELETE` with `\"bookmark not found\"` envelopes, catch-all `\"no such route\"`. The checkpoints run one realistic session — create 3, search, patch, delete — so keep your store straight.",
      steps: [
        { text: "`GET /api/bookmarks` → 200 `{ items: [], total: 0 }` — with `query: {}` AND with no query at all; unknown routes → the `\"no such route\"` envelope.",
          test: "T.expect(typeof handleRequest === 'function', 'Define handleRequest(req).');\nvar res = handleRequest({ method: 'GET', path: '/api/bookmarks', query: {}, body: null });\nT.eq(res, { status: 200, body: { items: [], total: 0 } }, 'Empty store → { items: [], total: 0 }');\nvar res2 = handleRequest({ method: 'GET', path: '/api/bookmarks', body: null });\nT.eq(res2, { status: 200, body: { items: [], total: 0 } }, 'A request with NO query object must not crash — default req.query to {}');\nT.eq(handleRequest({ method: 'GET', path: '/api/nope', query: {}, body: null }), { status: 404, body: { error: { code: 'not_found', message: 'no such route' } } }, 'Unknown routes → the 404 envelope');" },
        { text: "`POST /api/bookmarks` creates with counter ids — build the session's three bookmarks.",
          test: "var res = handleRequest({ method: 'POST', path: '/api/bookmarks', body: { title: 'MDN Web Docs', url: 'https://developer.mozilla.org' } });\nT.eq(res, { status: 201, body: { id: 1, title: 'MDN Web Docs', url: 'https://developer.mozilla.org' } }, 'First create → 201 with id 1 — yours returned status ' + (res && res.status));\nhandleRequest({ method: 'POST', path: '/api/bookmarks', body: { title: 'Node.js Docs', url: 'https://nodejs.org' } });\nvar res2 = handleRequest({ method: 'POST', path: '/api/bookmarks', body: { title: 'CSS Tricks', url: 'https://css-tricks.com' } });\nT.eq(res2.body.id, 3, 'Ids count up: the third create gets id 3');\nvar list = handleRequest({ method: 'GET', path: '/api/bookmarks', query: {}, body: null });\nT.eq(list.body.total, 3, 'All three should be in the store');" },
        { text: "Validation: bad creates → **400** envelopes, and nothing sneaks into the store.",
          test: "T.eq(handleRequest({ method: 'POST', path: '/api/bookmarks', body: { url: 'https://a.com' } }), { status: 400, body: { error: { code: 'invalid', message: 'title is required' } } }, 'Missing title → 400 envelope');\nT.eq(handleRequest({ method: 'POST', path: '/api/bookmarks', body: { title: 'FTP fan', url: 'ftp://old.school' } }), { status: 400, body: { error: { code: 'invalid', message: 'url must start with http' } } }, 'Non-http url → 400 envelope');\nT.eq(handleRequest({ method: 'POST', path: '/api/bookmarks', body: null }), { status: 400, body: { error: { code: 'invalid', message: 'title is required' } } }, 'A null body fails the title check first — check req.body BEFORE reading .title');\nT.eq(handleRequest({ method: 'GET', path: '/api/bookmarks', query: {}, body: null }).body.total, 3, 'Rejected requests must not create anything');" },
        { text: "`?q=` filters titles case-insensitively; `?limit=` slices items; `total` counts matches **before** the limit.",
          test: "var res = handleRequest({ method: 'GET', path: '/api/bookmarks', query: { q: 'DOCS' }, body: null });\nT.eq(res, { status: 200, body: { items: [{ id: 1, title: 'MDN Web Docs', url: 'https://developer.mozilla.org' }, { id: 2, title: 'Node.js Docs', url: 'https://nodejs.org' }], total: 2 } }, '?q=DOCS should match 2 titles case-insensitively');\nvar res2 = handleRequest({ method: 'GET', path: '/api/bookmarks', query: { limit: '2' }, body: null });\nT.eq(res2, { status: 200, body: { items: [{ id: 1, title: 'MDN Web Docs', url: 'https://developer.mozilla.org' }, { id: 2, title: 'Node.js Docs', url: 'https://nodejs.org' }], total: 3 } }, '?limit=2 slices items to 2 but total stays 3 (limit is a STRING — Number() it)');\nvar res3 = handleRequest({ method: 'GET', path: '/api/bookmarks', query: { q: 'docs', limit: '1' }, body: null });\nT.eq(res3, { status: 200, body: { items: [{ id: 1, title: 'MDN Web Docs', url: 'https://developer.mozilla.org' }], total: 2 } }, 'q + limit combine: 1 item shown, 2 matched');" },
        { text: "`PATCH /:id` merges; `GET /:id` shows the merged record; missing ids → the 404 envelope.",
          test: "var res = handleRequest({ method: 'PATCH', path: '/api/bookmarks/2', body: { title: 'Node.js Documentation' } });\nT.eq(res, { status: 200, body: { id: 2, title: 'Node.js Documentation', url: 'https://nodejs.org' } }, 'PATCH merges: the url must survive a title-only patch');\nvar res2 = handleRequest({ method: 'PATCH', path: '/api/bookmarks/3', body: { url: 'https://css-tricks.com/archives' } });\nT.eq(res2, { status: 200, body: { id: 3, title: 'CSS Tricks', url: 'https://css-tricks.com/archives' } }, 'A url-only patch keeps the title');\nT.eq(handleRequest({ method: 'GET', path: '/api/bookmarks/2', query: {}, body: null }), { status: 200, body: { id: 2, title: 'Node.js Documentation', url: 'https://nodejs.org' } }, 'GET /:id shows the merged record');\nT.eq(handleRequest({ method: 'PATCH', path: '/api/bookmarks/42', body: { title: 'ghost' } }), { status: 404, body: { error: { code: 'not_found', message: 'bookmark not found' } } }, 'PATCH on a missing id → 404 envelope');" },
        { text: "`DELETE /:id`, then the final list — and deleting twice → 404.",
          test: "T.eq(handleRequest({ method: 'DELETE', path: '/api/bookmarks/1', body: null }), { status: 200, body: { ok: true } }, 'DELETE /api/bookmarks/1');\nvar res = handleRequest({ method: 'GET', path: '/api/bookmarks', query: {}, body: null });\nT.eq(res, { status: 200, body: { items: [{ id: 2, title: 'Node.js Documentation', url: 'https://nodejs.org' }, { id: 3, title: 'CSS Tricks', url: 'https://css-tricks.com/archives' }], total: 2 } }, 'Final state: #2 and #3 (both patched), total 2');\nT.eq(handleRequest({ method: 'DELETE', path: '/api/bookmarks/1', body: null }), { status: 404, body: { error: { code: 'not_found', message: 'bookmark not found' } } }, 'Deleting the same id twice → 404 envelope');" }
      ],
      files: [
        { name: "script.js", content: "// ===== Bookmarks API v1 — the spec =====\n// request  = { method, path, query?, body? }   query is pre-parsed; it MAY be missing\n// response = { status, body }\n//\n// GET    /api/bookmarks        → 200 { items, total }\n//        ?q=      case-insensitive title filter\n//        ?limit=  slice items (a STRING — Number() it); total = matches BEFORE the limit\n// POST   /api/bookmarks        → validate title then url → 400 envelopes; valid → 201 created\n// GET    /api/bookmarks/<id>   → 200 record | 404 \"bookmark not found\" envelope\n// PATCH  /api/bookmarks/<id>   → merge title/url from body → 200 | 404 envelope\n// DELETE /api/bookmarks/<id>   → 200 { ok: true } | 404 envelope\n// else                         → 404 { error: { code: \"not_found\", message: \"no such route\" } }\n//\n// envelopes: 400 { error: { code: \"invalid\",   message: … } }\n//            404 { error: { code: \"not_found\", message: … } }\n\nlet bookmarks = [];\nlet nextId = 1;\n\nfunction handleRequest(req) {\n  // build it route by route — catch-all 404 last\n}\n" }
      ],
      hints: [
        "Skeleton order matters: list route, then POST (validation first!), then the /api/bookmarks/<id> block, then the catch-all 404 as the very last line.",
        "The list route: `const q = req.query || {};` — then `let matches = bookmarks;`, filter when `q.q` is set (`b.title.toLowerCase().includes(q.q.toLowerCase())`), and slice AFTER: `items = matches.slice(0, Number(q.limit))`. `total` is `matches.length`, captured before the slice.",
        "The detail block: parse the id once (`Number(req.path.split(\"/\")[3])`), `find` once, then branch on method — GET returns it, PATCH merges only the fields sent, DELETE filters the store. All three share the same \"bookmark not found\" 404 envelope."
      ],
      solution: {
        "script.js": "// Bookmarks API v1 — request in, response out. That's the whole backend.\n\nlet bookmarks = [];\nlet nextId = 1;\n\nfunction handleRequest(req) {\n  if (req.method === \"GET\" && req.path === \"/api/bookmarks\") {\n    const q = req.query || {};\n    let matches = bookmarks;\n    if (typeof q.q === \"string\" && q.q !== \"\") {\n      const needle = q.q.toLowerCase();\n      matches = bookmarks.filter(b => b.title.toLowerCase().includes(needle));\n    }\n    let items = matches;\n    if (q.limit !== undefined) {\n      items = matches.slice(0, Number(q.limit));\n    }\n    return { status: 200, body: { items: items, total: matches.length } };\n  }\n\n  if (req.method === \"POST\" && req.path === \"/api/bookmarks\") {\n    if (!req.body || typeof req.body.title !== \"string\" || req.body.title.trim() === \"\") {\n      return { status: 400, body: { error: { code: \"invalid\", message: \"title is required\" } } };\n    }\n    if (typeof req.body.url !== \"string\" || !req.body.url.startsWith(\"http\")) {\n      return { status: 400, body: { error: { code: \"invalid\", message: \"url must start with http\" } } };\n    }\n    const bm = { id: nextId++, title: req.body.title, url: req.body.url };\n    bookmarks.push(bm);\n    return { status: 201, body: bm };\n  }\n\n  if (req.path.startsWith(\"/api/bookmarks/\")) {\n    const id = Number(req.path.split(\"/\")[3]);\n    const found = bookmarks.find(b => b.id === id);\n\n    if (req.method === \"GET\") {\n      if (!found) return { status: 404, body: { error: { code: \"not_found\", message: \"bookmark not found\" } } };\n      return { status: 200, body: found };\n    }\n    if (req.method === \"PATCH\") {\n      if (!found) return { status: 404, body: { error: { code: \"not_found\", message: \"bookmark not found\" } } };\n      if (req.body && typeof req.body.title === \"string\") found.title = req.body.title;\n      if (req.body && typeof req.body.url === \"string\") found.url = req.body.url;\n      return { status: 200, body: found };\n    }\n    if (req.method === \"DELETE\") {\n      if (!found) return { status: 404, body: { error: { code: \"not_found\", message: \"bookmark not found\" } } };\n      bookmarks = bookmarks.filter(b => b.id !== id);\n      return { status: 200, body: { ok: true } };\n    }\n  }\n\n  return { status: 404, body: { error: { code: \"not_found\", message: \"no such route\" } } };\n}\n"
      }
    },

    {
      id: "srv-quiz-7",
      title: "Unit 7 quiz: REST in practice",
      kind: "quiz", xp: 10,
      brief: "Statuses, merges, envelopes and counts — the habits of a working REST API. 80% to pass.",
      questions: [
        { q: "A client POSTs a valid new bookmark. The textbook response?",
          choices: ["200 with the full list of bookmarks", "204 No Content, with an empty body", "201 with the created record", "302 redirect back to the list"],
          answer: 2, explain: "201 Created plus the created record — including its server-assigned `id` — is the REST handshake: the client instantly knows what was made and can link straight to it. 200 with the whole list makes the client hunt for the new row, 204 sends nothing back at all, and a redirect costs an extra round trip." },
        { q: "What should happen to this record's `url`?",
          code: "handleRequest({\n  method: \"PATCH\", path: \"/api/bookmarks/7\",\n  body: { title: \"New\" }\n});",
          lang: "js",
          choices: ["It's wiped — the body replaces the record", "It survives — PATCH merges the body in", "It becomes null, since url wasn't sent", "The server answers 400 — url is missing"],
          answer: 1, explain: "PATCH = merge: only the fields actually sent change, so `url` survives untouched and is never nulled out. A missing field isn't a validation error either — partial bodies are the whole point of PATCH. PUT is the verb that replaces wholesale (Unit 2)." },
        { q: "Why give every failure the same `{ error: { code, message } }` envelope?",
          choices: ["It compresses better over the network", "HTTP requires an error code field", "It lets the server skip logging failures", "One client handler covers every failure"],
          answer: 3, explain: "One predictable shape means the front-end writes a SINGLE error handler for every failure — check `code`, show `message`, done. It isn't about compression, and HTTP mandates no body shape at all. You still log the full failure — stack trace and all — server-side; the envelope only decides what the CLIENT gets to see." },
        { q: "Which belongs in the QUERY STRING rather than the path?",
          choices: ["Optional knobs like ?q=css&limit=2", "The resource noun, like bookmarks", "The id of one particular record", "The HTTP method the client picked"],
          answer: 0, explain: "Path = WHICH thing: the noun and the id both live there (`/api/bookmarks/7` names one record). Query = HOW to slice a listing — searches, filters and limits are optional, so they ride after the `?`. The method never appears in the URL at all; it's a separate part of the request." },
        { q: "Your store holds 5 bookmarks; `?q=docs` matches 2 of them; `?limit=1` rides along. With this unit's `{ items, total }` convention, the response holds…",
          choices: ["items: 5 records, total: 5", "items: 1 record, total: 5", "items: 1 record, total: 2", "items: 2 records, total: 1"],
          answer: 2, explain: "Filter first (2 matches), then slice (1 item). total reports matches BEFORE the limit — that's how a UI says \"showing 1 of 2\"." },
        { q: "`POST /api/bookmarks` arrives with `{ title: \"\", url: \"https://x.com\" }`. The right status?",
          choices: ["404 — nothing matched that title", "400 with the validation envelope", "500 — something broke server-side", "201 — be generous and create it"],
          answer: 1, explain: "4xx = the client's mistake: an empty title fails validation, so answer 400 and hand back the `{ error: { code, message } }` envelope so the client can say WHICH field was wrong. 404 is for missing resources, 500 is for YOUR bugs, and creating the junk record anyway just pushes the problem downstream." }
      ]
    }
  ]
});
