window.ACADEMY.addUnit("attachment", {
  id: "unit-15",
  title: "Measuring Adult Attachment",
  color: "#e0518a",
  icon: "📏",
  description: "This unit surveys the self-report tradition of adult attachment, tracing Bartholomew's four categories, the model of self and other, and the two-dimensional anxiety-avoidance model measured by the ECR and ECR-R.",
  lessons: [
    {
      id: "l113",
      title: "Bartholomew's Four Categories",
      intro: "Kim Bartholomew's 1991 model expanded adult attachment into four categories: secure, preoccupied, dismissing, and fearful.",
      questions: [
        {
          type: "mcq",
          q: "Who introduced the four-category model of adult attachment in 1991?",
          choices: ["Kim Bartholomew and Leonard Horowitz", "Cindy Hazan and Phillip Shaver", "John Bowlby and Mary Ainsworth", "George, Kaplan, and Main"],
          answer: 0,
          explain: "Bartholomew and Horowitz (1991) proposed the four-category model, expanding earlier three-category descriptions of adult attachment."
        },
        {
          type: "truefalse",
          q: "Bartholomew's model split the single avoidant style into two distinct types: dismissing and fearful.",
          answer: true,
          explain: "Where Hazan and Shaver had one avoidant type, Bartholomew distinguished dismissing (self-reliant) avoidance from fearful (anxious) avoidance."
        },
        {
          type: "match",
          q: "Match each of Bartholomew's four categories to its hallmark:",
          pairs: [
            ["Secure", "Comfortable with both closeness and independence"],
            ["Preoccupied", "Craves intimacy but fears the partner will leave"],
            ["Dismissing", "Values self-reliance and downplays needing others"],
            ["Fearful", "Wants closeness yet avoids it out of fear of being hurt"]
          ],
          explain: "Each category names a recognizable pattern; secure is the one comfortable style, and the other three are distinct forms of insecurity."
        },
        {
          type: "fill",
          q: "In Bartholomew's scheme, the ____ style pairs a desire for closeness with a fear of rejection that pushes the person to avoid intimacy.",
          answer: "fearful",
          accept: ["fearful", "fearful-avoidant", "fearful avoidant"],
          explain: "Fearful individuals both want and avoid closeness, wanting connection but expecting to be hurt by it."
        },
        {
          type: "mcq",
          q: "Which category describes someone who anxiously seeks approval and worries about being abandoned, while still valuing relationships?",
          choices: ["Secure", "Dismissing", "Preoccupied", "Fearful"],
          answer: 2,
          explain: "Preoccupied individuals are absorbed in relationships and anxious about their partner's availability and love."
        },
        {
          type: "order",
          q: "Put these attachment models in the historical order they were developed:",
          items: ["Bowlby's attachment theory", "Ainsworth's infant Strange Situation patterns", "Hazan and Shaver's three romantic attachment styles", "Bartholomew's four-category adult model"],
          explain: "The field moved from Bowlby's theory (1960s-80s) to Ainsworth's infant patterns, then Hazan and Shaver's 1987 romantic styles, and finally Bartholomew's 1991 four categories."
        },
        {
          type: "truefalse",
          q: "Bartholomew's dismissing and fearful types feel exactly the same way about depending on other people.",
          answer: false,
          explain: "They differ sharply: dismissing individuals prefer not to depend on others and feel fine about it, while fearful individuals long for closeness but avoid it out of fear."
        }
      ]
    },
    {
      id: "l114",
      title: "Model of Self and Other",
      intro: "Bartholomew's four categories are generated by crossing two underlying dimensions: a person's internal model of self and model of others.",
      questions: [
        {
          type: "mcq",
          q: "Bartholomew's four categories are generated by crossing which two underlying dimensions?",
          choices: ["Model of self and model of other", "Anxiety and depression", "Warmth and control", "Approach and avoidance of conflict"],
          answer: 0,
          explain: "Following Bowlby's internal working models, Bartholomew crossed the model of self (positive/negative) with the model of others (positive/negative)."
        },
        {
          type: "truefalse",
          q: "A positive model of self means a person's sense of worth does not depend heavily on others' approval.",
          answer: true,
          explain: "A positive self-model reflects internalized self-worth, so the person feels valuable without constant external validation."
        },
        {
          type: "match",
          q: "Match each category to its self and other combination:",
          pairs: [
            ["Secure", "Positive self, positive other"],
            ["Preoccupied", "Negative self, positive other"],
            ["Dismissing", "Positive self, negative other"],
            ["Fearful", "Negative self, negative other"]
          ],
          explain: "The four categories are the four cells created by crossing a positive or negative model of self with a positive or negative model of others."
        },
        {
          type: "fill",
          q: "A ____ model of others reflects the expectation that other people are available, trustworthy, and supportive.",
          answer: "positive",
          accept: ["positive"],
          explain: "A positive model of others leads a person to approach relationships expecting reliability and support."
        },
        {
          type: "mcq",
          q: "Which combination of models defines the preoccupied style?",
          choices: ["Positive self, negative other", "Negative self, positive other", "Positive self, positive other", "Negative self, negative other"],
          answer: 1,
          explain: "Preoccupied individuals hold a negative model of self (feeling unworthy) but a positive model of others, so they seek approval from partners they view positively."
        },
        {
          type: "truefalse",
          q: "The model of self dimension maps most closely onto attachment avoidance, while the model of other maps onto attachment anxiety.",
          answer: false,
          explain: "It is the reverse: a negative model of self underlies attachment anxiety, and a negative model of others underlies attachment avoidance."
        },
        {
          type: "mcq",
          q: "The dismissing style combines which pair of models?",
          choices: ["Negative self, negative other", "Positive self, positive other", "Positive self, negative other", "Negative self, positive other"],
          answer: 2,
          explain: "Dismissing individuals hold a positive model of self but a negative model of others, so they rely on themselves and devalue depending on others."
        }
      ]
    },
    {
      id: "l115",
      title: "The Two-Dimensional Model",
      intro: "Modern self-report research maps adult attachment onto two continuous axes: attachment anxiety and attachment avoidance.",
      questions: [
        {
          type: "mcq",
          q: "Modern self-report research describes adult attachment using how many continuous dimensions?",
          choices: ["Two", "Four", "Three", "One"],
          answer: 0,
          explain: "The dominant model uses two orthogonal continuous dimensions: attachment anxiety and attachment avoidance."
        },
        {
          type: "truefalse",
          q: "In the two-dimensional model, attachment security is defined as low scores on both anxiety and avoidance.",
          answer: true,
          explain: "Security sits in the low-anxiety, low-avoidance region of the two-dimensional space."
        },
        {
          type: "match",
          q: "Match each region of the two-dimensional space to the category it corresponds to:",
          pairs: [
            ["Low anxiety, low avoidance", "Secure"],
            ["High anxiety, low avoidance", "Preoccupied"],
            ["Low anxiety, high avoidance", "Dismissing"],
            ["High anxiety, high avoidance", "Fearful"]
          ],
          explain: "The four traditional categories are simply quadrants of the continuous anxiety-by-avoidance space."
        },
        {
          type: "fill",
          q: "The anxiety and avoidance dimensions are roughly ____, meaning a person's score on one does not strongly predict their score on the other.",
          answer: "orthogonal",
          accept: ["orthogonal", "independent", "uncorrelated"],
          explain: "Because the two axes are largely independent, they can vary freely, which is why all four quadrants exist."
        },
        {
          type: "mcq",
          q: "Someone scoring high on avoidance but low on anxiety best fits which category?",
          choices: ["Preoccupied", "Fearful", "Dismissing", "Secure"],
          answer: 2,
          explain: "High avoidance with low anxiety is the dismissing pattern: uncomfortable with closeness but not worried about abandonment."
        },
        {
          type: "truefalse",
          q: "The two-dimensional model treats attachment as a set of mutually exclusive boxes rather than as positions in a continuous space.",
          answer: false,
          explain: "The dimensional model treats attachment as continuous positions on two axes; the four categories are convenient labels, not rigid boxes."
        },
        {
          type: "fill",
          q: "The two axes of the two-dimensional model are attachment anxiety and attachment ____.",
          answer: "avoidance",
          accept: ["avoidance"],
          explain: "Anxiety captures fear of abandonment, and avoidance captures discomfort with closeness; together they span the model."
        }
      ]
    },
    {
      id: "l116",
      title: "Attachment Anxiety Dimension",
      intro: "The anxiety dimension captures fear of abandonment, rejection sensitivity, and a hyperactivated need for reassurance.",
      questions: [
        {
          type: "mcq",
          q: "Attachment anxiety is primarily characterized by:",
          choices: ["A fear of abandonment and heightened sensitivity to rejection", "A wish to avoid intimacy at all costs", "Complete indifference to relationships", "An absence of any emotional response to partners"],
          answer: 0,
          explain: "High anxiety centers on worry that a partner will leave or withhold love, along with strong reactions to any hint of rejection."
        },
        {
          type: "truefalse",
          q: "People high in attachment anxiety tend to seek frequent reassurance from their partners.",
          answer: true,
          explain: "Reassurance seeking is a hallmark of anxiety, as the person tries to relieve worry about the partner's commitment."
        },
        {
          type: "fill",
          q: "High attachment anxiety is linked to ____ of the attachment system, an intensification of proximity-seeking and distress when a partner seems unavailable.",
          answer: "hyperactivation",
          accept: ["hyperactivation", "hyperactivating"],
          explain: "Mikulincer and Shaver describe anxiety as hyperactivation: ramping up attachment behavior to force a response from the partner."
        },
        {
          type: "match",
          q: "Match each anxiety-related term to its description:",
          pairs: [
            ["Rejection sensitivity", "Readily perceiving and reacting to signs of rejection"],
            ["Fear of abandonment", "Worrying that a partner will leave or stop loving them"],
            ["Reassurance seeking", "Repeatedly asking for signs of love and commitment"],
            ["Hyperactivation", "Turning up attachment behaviors under threat"]
          ],
          explain: "These four features cluster together as the core of the attachment anxiety dimension."
        },
        {
          type: "mcq",
          q: "Which pattern is most typical of a person high in attachment anxiety?",
          choices: ["Suppressing emotions and avoiding closeness", "Worrying that a partner does not love them enough", "Feeling secure and rarely thinking about the relationship", "Preferring solitude to companionship"],
          answer: 1,
          explain: "Chronic worry about the partner's love and availability is central to attachment anxiety."
        },
        {
          type: "truefalse",
          q: "Attachment anxiety is generally associated with a very positive model of oneself.",
          answer: false,
          explain: "Anxiety is tied to a negative model of self; anxious individuals often doubt their own worth and fear they are not lovable enough."
        },
        {
          type: "order",
          q: "Order these steps in a typical anxious response to a partner's silence:",
          items: ["A partner is slow to reply to a message", "Anxious thoughts about being abandoned arise", "The person repeatedly tries to reach the partner", "Relief follows once the partner responds"],
          explain: "This sequence illustrates hyperactivation: a small cue triggers worry, escalating proximity-seeking until reassurance arrives."
        }
      ]
    },
    {
      id: "l117",
      title: "Attachment Avoidance Dimension",
      intro: "The avoidance dimension captures discomfort with closeness, a preference for self-reliance, and deactivation of the attachment system.",
      questions: [
        {
          type: "mcq",
          q: "Attachment avoidance is best described as:",
          choices: ["Discomfort with closeness and reluctance to depend on others", "An intense fear of being abandoned", "A constant craving for reassurance", "A balanced comfort with intimacy"],
          answer: 0,
          explain: "High avoidance centers on unease with intimacy and a strong preference for independence over depending on a partner."
        },
        {
          type: "truefalse",
          q: "People high in avoidance tend to value self-reliance and keep emotional distance in relationships.",
          answer: true,
          explain: "Avoidant individuals emphasize autonomy and self-sufficiency, maintaining distance to avoid depending on others."
        },
        {
          type: "fill",
          q: "Avoidance is associated with ____ of the attachment system, a suppression of proximity-seeking and of attachment-related emotion.",
          answer: "deactivation",
          accept: ["deactivation", "deactivating"],
          explain: "Mikulincer and Shaver describe avoidance as deactivation: turning down the attachment system to avoid the risks of dependence."
        },
        {
          type: "match",
          q: "Match each avoidance-related term to its description:",
          pairs: [
            ["Compulsive self-reliance", "Insisting on handling everything alone"],
            ["Discomfort with closeness", "Feeling uneasy when a partner wants deep intimacy"],
            ["Emotional suppression", "Downplaying or hiding attachment feelings"],
            ["Deactivation", "Turning down the attachment system to avoid dependence"]
          ],
          explain: "These features cluster together as the core of the attachment avoidance dimension."
        },
        {
          type: "mcq",
          q: "Which response is most characteristic of someone high in avoidance during relationship stress?",
          choices: ["Clinging and seeking constant contact", "Withdrawing and relying on themselves", "Demanding continual reassurance", "Feeling comforted by leaning on the partner"],
          answer: 1,
          explain: "Under stress, avoidant individuals tend to distance themselves and depend on their own resources rather than turn to a partner."
        },
        {
          type: "truefalse",
          q: "Attachment avoidance and attachment anxiety are simply the same dimension measured in opposite directions.",
          answer: false,
          explain: "They are two separate, roughly independent dimensions; a person can be high, low, or moderate on each, and fearful individuals are high on both."
        },
        {
          type: "order",
          q: "Order these steps in a typical avoidant response to a bid for closeness:",
          items: ["A partner asks for more emotional closeness", "Discomfort and a wish for distance arise", "The person withdraws and stresses self-reliance", "Distance restores their sense of control"],
          explain: "This sequence illustrates deactivation: a closeness cue triggers discomfort, leading to withdrawal that relieves the felt threat of dependence."
        }
      ]
    },
    {
      id: "l118",
      title: "Brennan, Clark, and Shaver",
      intro: "In 1998, Brennan, Clark, and Shaver factor-analyzed existing attachment items to build the Experiences in Close Relationships (ECR) inventory.",
      questions: [
        {
          type: "mcq",
          q: "The Experiences in Close Relationships (ECR) inventory was published in 1998 by:",
          choices: ["Brennan, Clark, and Shaver", "Bartholomew and Horowitz", "Hazan and Shaver", "Fraley and Waller"],
          answer: 0,
          explain: "Kelly Brennan, Catherine Clark, and Phillip Shaver constructed the ECR in 1998 as a self-report measure of two attachment dimensions."
        },
        {
          type: "truefalse",
          q: "Brennan, Clark, and Shaver built the ECR by factor-analyzing a large pool of existing self-report attachment items.",
          answer: true,
          explain: "They gathered many previously published items and used factor analysis to distill them into two coherent subscales."
        },
        {
          type: "fill",
          q: "The ECR measures two subscales: attachment ____ and attachment avoidance.",
          answer: "anxiety",
          accept: ["anxiety"],
          explain: "The factor analysis consistently produced two dimensions, anxiety and avoidance, which became the ECR's subscales."
        },
        {
          type: "mcq",
          q: "How many items does the original ECR contain?",
          choices: ["12 items", "36 items", "100 items", "4 items"],
          answer: 1,
          explain: "The ECR has 36 items, split evenly with 18 measuring anxiety and 18 measuring avoidance."
        },
        {
          type: "match",
          q: "Match each ECR-related term to its meaning:",
          pairs: [
            ["ECR", "1998 self-report inventory of two attachment dimensions"],
            ["Anxiety subscale", "18 items on fear of abandonment and reassurance needs"],
            ["Avoidance subscale", "18 items on discomfort with closeness and dependence"],
            ["Factor analysis", "Statistical method used to derive the two subscales"]
          ],
          explain: "The ECR pairs an anxiety subscale and an avoidance subscale, both distilled through factor analysis."
        },
        {
          type: "truefalse",
          q: "The ECR was designed to sort people into discrete attachment categories rather than to place them along continuous dimensions.",
          answer: false,
          explain: "The ECR yields continuous scores on two dimensions; any categories are derived afterward from where a person falls on the axes."
        },
        {
          type: "order",
          q: "Order the steps Brennan, Clark, and Shaver followed to build the ECR:",
          items: ["Assemble a large pool of existing attachment self-report items", "Administer the items to a large sample", "Factor-analyze the responses", "Retain items loading on the anxiety and avoidance factors"],
          explain: "This item-pooling and factor-analytic strategy produced a clean two-dimensional measure from a messy set of prior scales."
        }
      ]
    },
    {
      id: "l119",
      title: "ECR and ECR-R Measures",
      intro: "The ECR-R, developed by Fraley, Waller, and Brennan in 2000, refined the continuous scoring of the same two dimensions using item response theory.",
      questions: [
        {
          type: "mcq",
          q: "The ECR-R (Revised) was developed in 2000 by:",
          choices: ["Fraley, Waller, and Brennan", "Bartholomew and Horowitz", "Main and Goldwyn", "Ainsworth and Bell"],
          answer: 0,
          explain: "R. Chris Fraley, Niels Waller, and Kelly Brennan published the ECR-R in 2000 as a refined revision of the ECR."
        },
        {
          type: "truefalse",
          q: "The ECR-R used item response theory to select items and refine measurement of the two dimensions.",
          answer: true,
          explain: "Fraley and colleagues applied item response theory (IRT) to improve item precision, especially at the secure end of each dimension."
        },
        {
          type: "fill",
          q: "Both the ECR and ECR-R produce ____ scores on the anxiety and avoidance dimensions rather than assigning a single category.",
          answer: "continuous",
          accept: ["continuous"],
          explain: "Both instruments locate a person along two continuous axes, treating attachment as a matter of degree."
        },
        {
          type: "mcq",
          q: "The ECR-R retained which two dimensions from the original ECR?",
          choices: ["Warmth and dominance", "Approach and withdrawal", "Attachment anxiety and attachment avoidance", "Self-esteem and sociability"],
          answer: 2,
          explain: "The revision kept the same two constructs, anxiety and avoidance, and only improved how precisely they are measured."
        },
        {
          type: "match",
          q: "Match each measure or method to its description:",
          pairs: [
            ["ECR", "1998 original inventory by Brennan, Clark, and Shaver"],
            ["ECR-R", "2000 revision using item response theory"],
            ["Item response theory", "Method used to sharpen item precision in the ECR-R"],
            ["Continuous scoring", "Placing respondents along dimensions rather than in boxes"]
          ],
          explain: "The ECR and ECR-R share the same two dimensions; the ECR-R differs mainly in its IRT-based item selection."
        },
        {
          type: "truefalse",
          q: "The ECR-R measures entirely different constructs from the original ECR.",
          answer: false,
          explain: "The ECR-R measures the same two constructs, anxiety and avoidance, using refined items rather than new dimensions."
        },
        {
          type: "order",
          q: "Order these self-report attachment measures by year of publication:",
          items: ["Hazan and Shaver's romantic attachment measure (1987)", "Brennan, Clark, and Shaver's ECR (1998)", "Fraley, Waller, and Brennan's ECR-R (2000)"],
          explain: "The self-report tradition progressed from Hazan and Shaver's single-item forced choice to the ECR and then the IRT-refined ECR-R."
        }
      ]
    },
    {
      id: "l120",
      title: "Interview Versus Self-Report Debate",
      intro: "The Adult Attachment Interview and the self-report questionnaires belong to different research traditions and correlate only weakly.",
      questions: [
        {
          type: "mcq",
          q: "The Adult Attachment Interview (AAI) was developed by:",
          choices: ["George, Kaplan, and Main", "Brennan, Clark, and Shaver", "Hazan and Shaver", "Bartholomew and Horowitz"],
          answer: 0,
          explain: "Carol George, Nancy Kaplan, and Mary Main developed the AAI in the mid-1980s to assess adults' states of mind about attachment."
        },
        {
          type: "truefalse",
          q: "The AAI assesses an adult's state of mind regarding early attachment experiences with caregivers, whereas self-report scales assess conscious feelings about romantic relationships.",
          answer: true,
          explain: "The AAI probes how adults narrate their childhood attachment history, while the ECR asks about current feelings in close romantic relationships."
        },
        {
          type: "match",
          q: "Match each tool or tradition to its description:",
          pairs: [
            ["AAI", "Coded interview about childhood attachment experiences"],
            ["ECR / ECR-R", "Self-report questionnaire on romantic attachment"],
            ["Developmental tradition", "Research lineage that produced the AAI"],
            ["Social-personality tradition", "Research lineage that produced self-report scales"]
          ],
          explain: "The AAI grew out of developmental psychology, while the self-report measures grew out of social and personality psychology."
        },
        {
          type: "fill",
          q: "Studies such as Roisman and colleagues (2007) found that AAI and self-report measures are largely ____, showing only a weak overlap.",
          answer: "independent",
          accept: ["independent", "unrelated", "uncorrelated"],
          explain: "Research repeatedly finds the two traditions are nearly independent, suggesting they tap somewhat different aspects of attachment."
        },
        {
          type: "mcq",
          q: "What is the main reason the two traditions can diverge?",
          choices: ["They were invented in the same year", "They tap different targets and levels of awareness", "They both use identical interview coding", "They only apply to children"],
          answer: 1,
          explain: "The AAI captures largely unconscious discourse patterns about caregivers, while self-reports capture conscious feelings about romantic partners, so they measure different things."
        },
        {
          type: "truefalse",
          q: "The AAI is a brief self-scored questionnaire that respondents complete in a few minutes.",
          answer: false,
          explain: "The AAI is a lengthy structured interview that must be transcribed verbatim and coded by trained raters, not a quick self-report."
        },
        {
          type: "order",
          q: "Order the steps in administering and scoring an AAI:",
          items: ["Conduct the structured attachment interview", "Transcribe the interview verbatim", "A trained coder rates the transcript", "Assign a state-of-mind classification"],
          explain: "The AAI's coding depends on analyzing how the person talks about attachment, which requires a full transcript and expert rating."
        }
      ]
    }
  ]
});
