window.ACADEMY.addUnit("sysdesign", {
  id: "unit-3",
  title: "Relational Data Modeling",
  color: "#eab308",
  icon: "\u{1F5C4}\u{FE0F}",
  description: "The default datastore, and the one most engineers use without understanding.",
  lessons: [
    {
      id: "l17",
      title: "Tables, keys, and relationships",
      intro: "How rows are identified, how tables point at each other, and what the database will and will not enforce.",
      questions: [
        {
          type: "mcq",
          q: "What does a PRIMARY KEY constraint guarantee about a column or set of columns?",
          choices: [
            "Values are stored in sorted order on disk in every engine",
            "Values are automatically generated by the database",
            "Values are checked for referential integrity on insert",
            "Values are unique and not null, identifying each row"
          ],
          answer: 3,
          explain: "A primary key is a uniqueness constraint plus NOT NULL. Auto-generation, physical ordering, and referential checks are separate features that may or may not accompany it."
        },
        {
          type: "truefalse",
          q: "A foreign key constraint can reference a column that has no unique or primary key constraint on it.",
          answer: false,
          explain: "The referenced column must be unique (primary key or unique constraint), otherwise a single foreign key value could point at many parent rows and the constraint would be undefined."
        },
        {
          type: "fill",
          q: "Any minimal set of columns whose values are unique across every row, and which could therefore serve as the primary key, is called a ____ key.",
          answer: "candidate",
          accept: ["candidate", "candidate key", "Candidate", "candidate keys"],
          explain: "Every relation can have several candidate keys; the one you pick is the primary key and the rest usually get UNIQUE constraints."
        },
        {
          type: "match",
          q: "Match each relationship cardinality to how it is normally represented physically.",
          pairs: [
            ["One-to-many", "Foreign key column on the many side pointing at the one side"],
            ["Many-to-many", "A separate join table holding a foreign key to each side"],
            ["One-to-one", "Foreign key on one side with a unique constraint added to it"]
          ],
          explain: "Cardinality is a logical idea; physically it comes down to where the foreign key lives and whether a uniqueness constraint sits on top of it."
        },
        {
          type: "mcq",
          q: "What is the practical argument for a surrogate key (a generated id) over a natural key such as an email address?",
          choices: [
            "Surrogate keys make joins mathematically correct where natural keys do not",
            "Natural keys cannot be indexed by most relational engines",
            "Business values change, and a changing key must cascade to every referencing row",
            "Surrogate keys remove the need for a unique constraint on the natural value"
          ],
          answer: 2,
          explain: "Natural keys are perfectly valid relationally; the problem is mutability and reuse. You still add a unique constraint on the natural column to prevent duplicates."
        },
        {
          type: "truefalse",
          q: "ON DELETE CASCADE deletes the child rows automatically when the parent row is deleted.",
          answer: true,
          explain: "It is the referential action the database applies to dependent rows. It is convenient but dangerous, since a single parent delete can silently remove large subtrees."
        },
        {
          type: "mcq",
          q: "A nullable foreign key column typically encodes which of the following?",
          choices: [
            "That the relationship is optional for the child row",
            "That the parent table has no primary key",
            "That the constraint is deferred until commit",
            "That the relationship is many-to-many"
          ],
          answer: 0,
          explain: "NULL in a foreign key means no related parent, so the constraint is not checked for that row. Deferral and cardinality are controlled separately."
        }
      ]
    },
    {
      id: "l18",
      title: "Normalization - and when to deliberately denormalize",
      intro: "What the normal forms actually remove, and the conditions under which breaking them is the right call.",
      questions: [
        {
          type: "mcq",
          q: "Third normal form removes which specific problem?",
          choices: [
            "Repeating groups stored inside a single column value",
            "Partial dependence of a non-key column on part of a composite key",
            "Transitive dependence of a non-key column on another non-key column",
            "Overlapping candidate keys sharing a common attribute"
          ],
          answer: 2,
          explain: "1NF removes repeating groups, 2NF removes partial dependencies on part of a composite key, and 3NF removes transitive dependencies where a non-key column determines another non-key column."
        },
        {
          type: "fill",
          q: "Storing the same fact in more than one place creates the risk of update ____, where one copy is changed and the others are not.",
          answer: "anomalies",
          accept: ["anomalies", "anomaly", "Anomalies"],
          explain: "Update, insert, and delete anomalies are the concrete harms normalization prevents. Denormalizing means accepting them and managing them deliberately."
        },
        {
          type: "truefalse",
          q: "Normalization primarily optimizes read performance.",
          answer: false,
          explain: "Normalization optimizes for correctness and write integrity. It often costs reads extra joins, which is precisely why denormalization exists as a read optimization."
        },
        {
          type: "mcq",
          q: "Which situation is the most defensible reason to denormalize?",
          choices: [
            "A hot read path needs an aggregate that is expensive to recompute per request",
            "The schema has more than a handful of tables and feels complicated",
            "The ORM produces awkward class names for join tables",
            "Writes are slow and the team wants fewer constraints to check"
          ],
          answer: 0,
          explain: "Denormalization buys read speed at the cost of write complexity and duplication. It is justified by a measured read cost, not by schema aesthetics."
        },
        {
          type: "match",
          q: "Match each denormalization technique to what it duplicates.",
          pairs: [
            ["Counter column", "A count that could otherwise be derived by aggregating child rows"],
            ["Materialized view", "The stored result set of a query, refreshed on some schedule or trigger"],
            ["Column copy on the child", "A parent attribute repeated on each child row to avoid a join"]
          ],
          explain: "All three trade duplicate state for fewer joins or aggregates at read time; each needs an explicit story for how the copy stays correct."
        },
        {
          type: "mcq",
          q: "You add a denormalized like_count column to posts. What is the main new correctness obligation?",
          choices: [
            "The column must be indexed to be readable",
            "Every write that adds or removes a like must update the count in the same transaction",
            "The likes table must be dropped to avoid two sources of truth",
            "The count must be recomputed on every read to stay accurate"
          ],
          answer: 1,
          explain: "The duplicate must be maintained atomically with the source of truth, or it drifts. Recomputing on read would defeat the purpose of caching the value."
        },
        {
          type: "truefalse",
          q: "A column holding a comma-separated list of tag ids violates first normal form.",
          answer: true,
          explain: "1NF requires atomic values per column. A delimited list forces string parsing, blocks foreign key constraints, and cannot be indexed usefully for membership."
        }
      ]
    },
    {
      id: "l19",
      title: "Indexes and B-tree mechanics",
      intro: "Why a B-tree index makes lookups cheap, what a composite index can and cannot serve, and what indexes cost.",
      questions: [
        {
          type: "mcq",
          q: "You have an index on (tenant_id, created_at). Which query can use that index to seek efficiently?",
          choices: [
            "WHERE created_at > $1",
            "WHERE tenant_id = $1 AND created_at > $2",
            "WHERE created_at > $1 ORDER BY tenant_id",
            "WHERE lower(tenant_id) = $1"
          ],
          answer: 1,
          explain: "The leftmost-prefix rule: an index on (a,b) serves a query on a, or on a plus b, but not on b alone. Wrapping a column in a function also defeats the plain index."
        },
        {
          type: "truefalse",
          q: "Adding an index speeds up reads that match it and slows down writes to that table.",
          answer: true,
          explain: "Every insert, delete, and update of an indexed column must also maintain the index structure. Indexes are a read-versus-write trade, not free."
        },
        {
          type: "fill",
          q: "An index that contains every column a query needs, so the engine never reads the table itself, is called a ____ index.",
          answer: "covering",
          accept: ["covering", "covered", "Covering"],
          explain: "When the index covers the query, the engine can answer from the index alone. Postgres calls the resulting plan node an index-only scan."
        },
        {
          type: "mcq",
          q: "Why do relational engines use B-trees rather than in-memory-style binary search trees for on-disk indexes?",
          choices: [
            "B-trees guarantee unique keys while binary trees do not",
            "B-trees keep data sorted while binary trees do not",
            "B-trees avoid rebalancing entirely, so writes never restructure the tree",
            "High fan-out per node keeps the tree shallow, minimizing page reads per lookup"
          ],
          answer: 3,
          explain: "Disk and page cache access dominates cost. A node sized to a page holds hundreds of keys, so depth stays small and a lookup touches only a few pages. B-trees do rebalance on split and merge."
        },
        {
          type: "match",
          q: "Match each index concept to its meaning.",
          pairs: [
            ["Selectivity", "How small a fraction of rows a predicate keeps"],
            ["Clustered index", "An index whose leaf level physically stores the table rows"],
            ["Partial index", "An index built over only the subset of rows matching a WHERE clause"]
          ],
          explain: "Selectivity drives whether the planner bothers with the index; clustering and partiality describe how and over what the index is physically built."
        },
        {
          type: "mcq",
          q: "A query filters on a boolean column where about half the rows are true. Why might the planner skip an index on that column?",
          choices: [
            "Boolean columns cannot be stored in a B-tree",
            "The predicate is unselective, so random row lookups cost more than a sequential scan",
            "Indexes only support equality on integer and text types",
            "Half-and-half distributions make the index tree unbalanced"
          ],
          answer: 1,
          explain: "Fetching half the table through an index means many scattered page reads plus the index reads. A straight sequential scan reads pages in order and wins."
        },
        {
          type: "truefalse",
          q: "If a table already has an index on (a, b), a separate index on (a) alone is usually redundant.",
          answer: true,
          explain: "The composite index already serves queries on a because a is the leftmost column. The single-column index would mostly add write cost for little gain."
        }
      ]
    },
    {
      id: "l20",
      title: "Reading a query plan (EXPLAIN)",
      intro: "How to read the plan the optimizer chose, and how to tell a bad estimate from a bad query.",
      questions: [
        {
          type: "mcq",
          q: "What is the key difference between EXPLAIN and EXPLAIN ANALYZE in Postgres?",
          choices: [
            "EXPLAIN ANALYZE rewrites the query, EXPLAIN only inspects it",
            "EXPLAIN ANALYZE actually runs the query and reports actual rows and timings alongside the estimates",
            "EXPLAIN ANALYZE updates the table statistics used by the planner",
            "EXPLAIN ANALYZE shows only the cheapest node in the plan tree"
          ],
          answer: 1,
          explain: "Plain EXPLAIN shows the planner estimates. EXPLAIN ANALYZE executes the query so you can compare actual rows against estimated rows. Refreshing statistics is the job of ANALYZE on its own."
        },
        {
          type: "truefalse",
          q: "Because EXPLAIN ANALYZE executes the statement, running it on an UPDATE or DELETE will change data unless you wrap it in a transaction you roll back.",
          answer: true,
          explain: "It performs the real work. Wrap it in BEGIN and ROLLBACK when profiling write statements."
        },
        {
          type: "fill",
          q: "A plan node showing estimated rows of 12 but actual rows of 480,000 signals a bad row ____, usually from stale or missing statistics.",
          answer: "estimate",
          accept: ["estimate", "estimates", "estimation", "Estimate"],
          explain: "A large estimate-versus-actual gap is the single most useful diagnostic in a plan, because every choice above that node was made on the wrong assumption."
        },
        {
          type: "match",
          q: "Match each join strategy to the condition under which the planner tends to choose it.",
          pairs: [
            ["Nested loop", "One side yields few rows and the other side has an index on the join key"],
            ["Hash join", "Both sides are large, the join is on equality, and one side fits in memory as a hash table"],
            ["Merge join", "Both inputs are already sorted, or cheaply sortable, on the join key"]
          ],
          explain: "Join strategy is a cost decision driven by row counts, sortedness, and available indexes, not by how the SQL was written."
        },
        {
          type: "mcq",
          q: "A plan is read in which direction to follow execution order?",
          choices: [
            "Top to bottom, since the top node runs first",
            "Left to right across each line of output",
            "Innermost and deepest nodes first, with results flowing up to the root",
            "In the order the tables appear in the FROM clause"
          ],
          answer: 2,
          explain: "The plan is a tree. Leaf nodes such as scans produce rows that flow upward through joins and aggregates to the top node, which emits the final result."
        },
        {
          type: "order",
          q: "Put these steps in the order you would follow to diagnose a slow query.",
          items: [
            "Run EXPLAIN ANALYZE to get actual timings and row counts",
            "Find the node where actual rows diverge most from estimated rows",
            "Fix the underlying cause: refresh statistics, add an index, or rewrite the predicate",
            "Re-measure to confirm the plan and the wall-clock time actually improved"
          ],
          explain: "Measure, localize, fix the cause, then verify. Adding indexes before reading the plan is guessing."
        },
        {
          type: "truefalse",
          q: "The cost numbers in an EXPLAIN plan are measured in milliseconds.",
          answer: false,
          explain: "Costs are unitless planner estimates on an arbitrary scale, calibrated to a notional sequential page read. Only EXPLAIN ANALYZE reports real time."
        }
      ]
    },
    {
      id: "l21",
      title: "ACID and what a transaction promises",
      intro: "The four guarantees, what isolation levels actually prevent, and where the promise stops.",
      questions: [
        {
          type: "fill",
          q: "ACID stands for Atomicity, Consistency, Isolation, and ____.",
          answer: "Durability",
          accept: ["Durability", "durability", "durable"],
          explain: "Durability means that once a commit is acknowledged, the change survives a crash, normally because the write-ahead log record was flushed to stable storage first."
        },
        {
          type: "match",
          q: "Match each ACID property to the guarantee it makes.",
          pairs: [
            ["Atomicity", "All statements in the transaction take effect, or none of them do"],
            ["Isolation", "Concurrent transactions do not observe each other's partial work"],
            ["Durability", "A committed change survives a process or machine crash"]
          ],
          explain: "Consistency, the fourth property, is the promise that a transaction moves the database from one state satisfying its constraints to another such state."
        },
        {
          type: "mcq",
          q: "Which statement correctly describes the step from READ COMMITTED up to REPEATABLE READ?",
          choices: [
            "READ COMMITTED prevents dirty reads, and REPEATABLE READ also prevents non-repeatable reads",
            "READ COMMITTED prevents lost updates, and REPEATABLE READ also prevents dirty reads",
            "READ COMMITTED prevents phantom reads, and REPEATABLE READ also prevents write skew",
            "READ COMMITTED prevents non-repeatable reads, and REPEATABLE READ also prevents dirty reads"
          ],
          answer: 0,
          explain: "The classic ladder: READ UNCOMMITTED allows dirty reads, READ COMMITTED blocks them, REPEATABLE READ additionally blocks non-repeatable reads, and SERIALIZABLE blocks the rest including write skew."
        },
        {
          type: "truefalse",
          q: "Setting a transaction to SERIALIZABLE means transactions literally execute one at a time.",
          answer: false,
          explain: "It guarantees the result is equivalent to some serial order. Engines achieve this with concurrency plus conflict detection, aborting transactions that would break serializability."
        },
        {
          type: "mcq",
          q: "Two transactions each read a shared invariant and then write different rows in a way that jointly violates it. This anomaly is called:",
          choices: [
            "A dirty read",
            "A phantom read",
            "Write skew",
            "A lost update"
          ],
          answer: 2,
          explain: "Write skew is the classic reason snapshot isolation is weaker than serializable: neither transaction overwrites the other's row, so no conflict is detected, yet the invariant breaks."
        },
        {
          type: "mcq",
          q: "What mechanism most directly delivers durability in a typical relational engine?",
          choices: [
            "Flushing every modified data page to disk before the commit returns",
            "Flushing the write-ahead log record for the transaction before the commit returns",
            "Holding row locks until a background checkpoint completes",
            "Replicating the transaction to a standby before the commit returns"
          ],
          answer: 1,
          explain: "Write-ahead logging lets the engine make a small sequential log write durable at commit and defer the random data-page writes to a checkpoint. Synchronous replication is a stronger, separate option."
        },
        {
          type: "truefalse",
          q: "A long-running open transaction can prevent the database from reclaiming old row versions, causing table bloat.",
          answer: true,
          explain: "Multi-version engines must keep any row version that an open snapshot might still need, so an idle-in-transaction session blocks cleanup and grows the table."
        }
      ]
    },
    {
      id: "l22",
      title: "Joins, the N+1 problem, and the ORM trap",
      intro: "How join types differ, how lazy loading multiplies queries, and how to fix it without abandoning the ORM.",
      questions: [
        {
          type: "mcq",
          q: "The N+1 query problem is best described as:",
          choices: [
            "One query per row plus one final aggregate query at the end",
            "N joined tables producing N+1 intermediate result sets",
            "N connections opened plus one held open for the transaction",
            "One query to fetch a list, plus one additional query per row in that list"
          ],
          answer: 3,
          explain: "You issue one query for the parents and then, usually via lazy-loaded associations, one more query for each parent's children. The cost is dominated by round-trip latency, not by rows."
        },
        {
          type: "fill",
          q: "The standard ORM fix for N+1 is ____ loading, where related rows are fetched up front in one or two queries instead of one per row.",
          answer: "eager",
          accept: ["eager", "Eager", "eager-loading", "eager loading"],
          explain: "Named includes, joinedload, or with clauses depending on the ORM. Either the ORM joins the tables or it issues one extra query using an IN list of parent ids."
        },
        {
          type: "match",
          q: "Match each join type to what it returns.",
          pairs: [
            ["INNER JOIN", "Only rows where the join condition matches on both sides"],
            ["LEFT OUTER JOIN", "All rows from the left side, with nulls where the right side has no match"],
            ["CROSS JOIN", "Every combination of left rows with right rows, with no join condition"]
          ],
          explain: "Choosing INNER when you meant LEFT silently drops parents that have no children, one of the most common quiet data bugs in reporting queries."
        },
        {
          type: "truefalse",
          q: "Adding a WHERE clause on a right-hand table column to a LEFT JOIN generally turns it into an inner join in effect.",
          answer: true,
          explain: "The unmatched rows carry nulls in those columns, and a normal comparison against null is not true, so those rows are filtered out. Put the condition in the ON clause instead if you want to keep them."
        },
        {
          type: "mcq",
          q: "Fetching parents and their children with a single joined query has which drawback compared to two queries?",
          choices: [
            "It cannot use indexes on the child table",
            "It breaks referential integrity checks during the read",
            "Parent columns are duplicated once per child row, inflating the bytes transferred",
            "It requires a serializable transaction to be correct"
          ],
          answer: 2,
          explain: "This is the cartesian inflation problem. It gets much worse joining two child collections at once, which is why many ORMs default to a second query with an IN list."
        },
        {
          type: "mcq",
          q: "Why is N+1 often invisible in local development but severe in production?",
          choices: [
            "Local databases skip constraint checking to run faster",
            "Local round trips are sub-millisecond and seed data is small, so 200 extra queries barely register",
            "ORMs disable lazy loading outside of production mode",
            "Connection pools reuse prepared statements only in production"
          ],
          answer: 1,
          explain: "The pathology is per-query latency times row count. On a loopback socket with 10 seed rows it disappears; across a network with 500 rows it dominates the response."
        },
        {
          type: "truefalse",
          q: "An ORM removes the need to understand the SQL it generates.",
          answer: false,
          explain: "An ORM maps rows to objects; it does not choose good access patterns for you. Query logging in development is the standard defense against surprises."
        }
      ]
    },
    {
      id: "l23",
      title: "Connection pooling and why databases run out of connections",
      intro: "Why a database connection is expensive, how pools bound concurrency, and how pools get exhausted.",
      questions: [
        {
          type: "mcq",
          q: "Why is a Postgres connection comparatively expensive to hold open?",
          choices: [
            "Each connection is backed by a separate server process with its own memory allocation",
            "Each connection reserves a dedicated slice of the shared buffer cache",
            "Each connection holds an exclusive lock on the system catalogs",
            "Each connection maintains its own copy of the write-ahead log"
          ],
          answer: 0,
          explain: "The classic Postgres model forks a backend process per connection, so idle connections still consume memory and scheduling attention. That is why a pool in front of it matters so much."
        },
        {
          type: "truefalse",
          q: "Raising max_connections is generally the correct first response to connection exhaustion.",
          answer: false,
          explain: "More backends usually means more context switching and memory pressure, not more throughput. The right move is normally a pool with a sane bound, plus finding the queries or leaks holding connections."
        },
        {
          type: "fill",
          q: "When every pooled connection is checked out and a new request must wait, the request eventually fails with a pool ____ timeout.",
          answer: "acquisition",
          accept: ["acquisition", "acquire", "checkout", "wait", "acquisition timeout"],
          explain: "The symptom appears in the application as a timeout waiting for a connection, not as a slow database. The real cause is usually long-held connections upstream."
        },
        {
          type: "mcq",
          q: "You run 10 application instances, each with a pool max of 50, against one database. What is the effective peak demand on the server?",
          choices: [
            "50 connections, since the pool bound is global",
            "500 connections, since each instance holds its own independent pool",
            "10 connections, one per instance",
            "It depends only on the database max_connections setting"
          ],
          answer: 1,
          explain: "Pools are per process. Total demand is instances times pool size, which is how teams blow past the server limit after a routine scale-out."
        },
        {
          type: "match",
          q: "Match each pooling mode to what it does.",
          pairs: [
            ["Session pooling", "A client keeps the same server connection for its whole session"],
            ["Transaction pooling", "A server connection is assigned only for the duration of one transaction"],
            ["Statement pooling", "A server connection is released back after each individual statement"]
          ],
          explain: "Transaction pooling gives the best reuse but breaks session-scoped state such as some prepared statements, temporary tables, and session variables."
        },
        {
          type: "mcq",
          q: "Which application bug most reliably exhausts a connection pool?",
          choices: [
            "Opening a transaction, calling a slow external HTTP API inside it, then committing",
            "Using parameterized queries instead of string concatenation",
            "Reading more rows per query than the client needs",
            "Running the same query from several threads at once"
          ],
          answer: 0,
          explain: "Holding a connection across network I/O you do not control multiplies hold time by the third party's latency. Do the external call outside the transaction."
        },
        {
          type: "truefalse",
          q: "A serverless or per-request-process deployment model can exhaust database connections faster than a long-lived server, because each instance may open its own connections.",
          answer: true,
          explain: "Hundreds of short-lived instances each opening a connection overwhelms a server tuned for a few long-lived pools, which is why an external pooler is the usual answer there."
        }
      ]
    },
    {
      id: "l24",
      title: "Schema migrations that do not take the site down",
      intro: "The expand-and-contract pattern, which DDL statements lock, and how to deploy schema and code safely.",
      questions: [
        {
          type: "order",
          q: "Put the expand-and-contract steps for renaming a column in the correct order.",
          items: [
            "Add the new column and start writing to both old and new",
            "Backfill the new column for existing rows in batches",
            "Switch reads to the new column and deploy that code everywhere",
            "Stop writing the old column, then drop it in a later migration"
          ],
          explain: "Expand and contract keeps old and new schema valid simultaneously, so any mix of old and new application code running during a rolling deploy still works."
        },
        {
          type: "mcq",
          q: "Why is adding a NOT NULL column with no default to a large, busy table dangerous?",
          choices: [
            "On a table that already has rows the statement is rejected outright, and filling every row instead rewrites the table under an exclusive lock",
            "It invalidates every index on the table",
            "It forces the planner to discard all statistics for the table",
            "It cannot be rolled back once committed"
          ],
          answer: 0,
          explain: "Existing rows have no value to put in the new column, so the engine refuses the statement. Supplying a value for every row instead means a full rewrite while holding an exclusive lock. The safe sequence is add the column nullable, backfill in batches, then add the NOT NULL constraint."
        },
        {
          type: "truefalse",
          q: "A migration must be deployable before the application code that uses it, and the old code must keep working against the new schema.",
          answer: true,
          explain: "During a rolling deploy both code versions run at once. Backward-compatible schema changes are what make zero-downtime deploys possible at all."
        },
        {
          type: "fill",
          q: "Building an index without blocking writes to the table requires the ____ option in Postgres, at the cost of a slower build and a possible invalid index on failure.",
          answer: "CONCURRENTLY",
          accept: ["CONCURRENTLY", "concurrently", "concurrent"],
          explain: "CREATE INDEX CONCURRENTLY takes a weaker lock and makes two passes over the table. If it fails it can leave an invalid index that must be dropped and retried."
        },
        {
          type: "mcq",
          q: "A migration acquires a lock but a long-running read holds the table. What is the most common production failure that follows?",
          choices: [
            "The migration silently applies to a stale snapshot of the table",
            "The migration waits, and every subsequent query queues behind its pending lock request",
            "The database escalates to a serializable snapshot and aborts the reader",
            "The migration is rewritten by the planner into a non-locking form"
          ],
          answer: 1,
          explain: "In Postgres a pending strong lock request blocks later, weaker lock requests behind it, so one blocked ALTER can stall all traffic to that table. Short lock timeouts with retries are the standard defense."
        },
        {
          type: "match",
          q: "Match each schema change to its typical operational risk profile.",
          pairs: [
            ["Adding a nullable column with no default", "Usually a fast metadata-only change on modern engines"],
            ["Backfilling a column for every existing row", "Long running and best done in batches outside the migration transaction"],
            ["Dropping a column still referenced by running code", "Immediate application errors until the old code is fully rolled out"]
          ],
          explain: "Risk is about lock duration and about which code versions are live, not about how many lines the migration file has."
        },
        {
          type: "truefalse",
          q: "Every migration should be written so it can be reversed by an automatic down migration.",
          answer: false,
          explain: "Destructive changes such as a dropped column cannot restore the data, so a down migration is a false promise. The practical standard is forward-only fixes plus backups, with reversibility where it is genuinely possible."
        }
      ]
    }
  ]
});
