/* Deploying Your App — Unit 3: Build time vs. run time */
window.CODELAB.addUnit("ship", {
  id: "ship-u3",
  title: "Build time vs. run time",
  icon: "📦",
  blurb: "A build is a pure function: bake the env in, hash the filenames, rewrite the HTML, and pick the cache policy that decides whether anyone ever sees v2.",
  cheat: [
    { h: "The two clocks", lang: "js", code: "// BUILD time — runs once, before deploy:\nbuild(src, env)   // bake env in, hash names, rewrite HTML\n\n// RUN time — runs on every request/visit:\nworker.fetch(request, env)   // reads env LIVE, no rebuild", note: "The practical test: if changing it requires re-running build, it's build time." },
    { h: "What a real bundler adds", lang: "js", code: "// your build():  env inject + hash + HTML rewrite (~30 lines)\n// Vite / esbuild / webpack ALSO do:\n//   module resolution (import graphs)\n//   tree-shaking (drop dead code)\n//   transpilation, minification, source maps", note: "That machinery is the Node & npm course — this unit only makes the two clocks concrete." },
    { h: "Real build output (Vite)", lang: "js", code: "// $ npm run build\n// dist/index.html\n// dist/assets/index-B3xK9d2f.js    ← content-hashed\n// dist/assets/index-Dk29fjq1.css   ← content-hashed", note: "The exact shape you build by hand here: hashed assets plus a rewritten index.html that points at them." },
    { h: "The cache policy, verbatim", lang: "js", code: "// hashed files — the name changes when the content does:\n\"Cache-Control: public, max-age=31536000, immutable\"\n\n// index.html — same name forever:\n\"Cache-Control: no-cache\"   // revalidate each visit", note: "no-cache does NOT mean \"never store\" — the browser keeps a copy but checks with the server before using it." },
    { h: "Where you actually set headers", lang: "js", code: "// GitHub Pages: you can't — it serves max-age=600 (10 min)\n// Cloudflare Pages: a _headers file in your output folder\n// Workers: you write them yourself:\nnew Response(body, { headers: { \"cache-control\": \"no-cache\" } })", note: "Hashed names still pay off on Pages: after the 10 minutes, unchanged files revalidate cheaply." }
  ],
  lessons: [

    {
      id: "ship-u3-1",
      title: "Two clocks: build time and run time",
      kind: "js", chip: "SHIP", xp: 15, mins: 13,
      brief: "Deployment's most confused pair of words, made concrete. **Build time** is when `build(src, env)` runs — once, on your machine or in CI, producing the `dist` folder you upload. **Run time** is when a visitor's browser executes what you shipped. Between the two sits a hard wall: once built, files are frozen bytes.\n\nYour source `app.js` holds the placeholder `__API_URL__`. Write `build(src, env)` returning a **new** file map with every placeholder replaced by `env.API_URL`. Then prove the point this unit is named after: changing `env` *after* a build changes **nothing**, because the bytes were already written.\n\nHonesty note: this is the 30-line core of a build, nothing more. A real bundler adds module resolution, tree-shaking, transpilation, source maps and minification — that's the Node & npm course.",
      example: { lang: "js", code: "// BUILD time (once):\nconst dist = build(SRC, { API_URL: \"https://api.live\" });\n// dist[\"app.js\"] → 'const API = \"https://api.live\";…'\n\n// changing env NOW does nothing to dist —\n// it is already frozen bytes on a disk" },
      steps: [
        { text: "Write `build(src, env)` — return a **new** file map with `__API_URL__` replaced by `env.API_URL`.",
          test: "T.expect(typeof build === 'function', 'Define build(src, env).');\nvar src1 = { 'app.js': 'const API = \"__API_URL__\";' };\nvar dist = build(src1, { API_URL: 'https://api.live' });\nT.expect(!!dist && typeof dist === 'object', 'build must RETURN a new file-map object.');\nT.expect(typeof dist['app.js'] === 'string' && dist['app.js'].indexOf('https://api.live') !== -1, 'dist[\"app.js\"] must contain https://api.live — the env value gets baked in at build time');\nT.expect(dist['app.js'].indexOf('__API_URL__') === -1, 'the placeholder must be GONE — it was replaced at build time; the shipped file never contains it');" },
        { text: "A build is **pure**: `src` stays untouched, and files without a placeholder ride through unchanged.",
          test: "var src2 = { 'index.html': '<h1>NoteStream</h1>', 'app.js': 'const API = \"__API_URL__\";' };\nvar dist = build(src2, { API_URL: 'https://api.live' });\nT.eq(src2['app.js'], 'const API = \"__API_URL__\";', 'build must not MUTATE src — a build reads the repo and writes a NEW dist. Copy, never edit in place.');\nT.eq(dist['index.html'], '<h1>NoteStream</h1>', 'files without a placeholder must still appear in dist, unchanged — you upload dist, so it needs EVERY file');" },
        { text: "Prove the two clocks: build twice with different envs, then show a later env can't touch the earlier build.",
          test: "var srcT = { 'app.js': 'const API = \"__API_URL__\";' };\nvar d1 = build(srcT, { API_URL: 'https://one.example' });\nvar d2 = build(srcT, { API_URL: 'https://two.example' });\nT.expect(d1['app.js'] !== d2['app.js'], 'change the env, REBUILD, get different bytes — that is the build clock ticking');\nT.expect(d1['app.js'].indexOf('two.example') === -1, 'changing the env AFTER the build cannot touch an already-built file — d1 was finished before two.example existed. That is what \"build time\" means.');\nT.eq(d1['app.js'], 'const API = \"https://one.example\";', 'd1 keeps the value it was built with, forever');" }
      ],
      files: [
        { name: "script.js", content: "// Your repo, as a plain object — filename → file text.\nconst SRC = {\n  \"index.html\": \"<!doctype html>\\n<h1>NoteStream</h1>\\n<script src=\\\"app.js\\\"><\\/script>\",\n  \"app.js\": \"const API = \\\"__API_URL__\\\";\\nconsole.log(\\\"calling \\\" + API);\"\n};\n\n// build(src, env) → a NEW file map, ready to upload.\n// Replace every __API_URL__ with env.API_URL. Never edit src itself.\nfunction build(src, env) {\n  // walk src, copy each file into a new object, replacing the placeholder\n}\n\nconsole.log(build(SRC, { API_URL: \"https://api.live\" }));\n" }
      ],
      hints: [
        "Loop the filenames: `for (const key of Object.keys(src)) { … }` and fill a fresh `const dist = {};` — never assign back into `src`.",
        "Replace ALL occurrences without regex escapes: `src[key].split(\"__API_URL__\").join(env.API_URL)`.",
        "Files with no placeholder need zero special-casing — split/join on a string that isn't there just copies the text."
      ],
      solution: {
        "script.js": "// Your repo, as a plain object — filename → file text.\nconst SRC = {\n  \"index.html\": \"<!doctype html>\\n<h1>NoteStream</h1>\\n<script src=\\\"app.js\\\"><\\/script>\",\n  \"app.js\": \"const API = \\\"__API_URL__\\\";\\nconsole.log(\\\"calling \\\" + API);\"\n};\n\n// build(src, env) → a NEW file map, ready to upload.\nfunction build(src, env) {\n  const dist = {};\n  for (const key of Object.keys(src)) {\n    dist[key] = src[key].split(\"__API_URL__\").join(env.API_URL);\n  }\n  return dist;\n}\n\nconsole.log(build(SRC, { API_URL: \"https://api.live\" }));\n"
      }
    },

    {
      id: "ship-u3-2",
      title: "Content hashing: app.a3f9d2c.js",
      kind: "js", chip: "SHIP", xp: 15, mins: 13,
      brief: "Real builds don't ship `app.js` — they ship `app.a3f9d2c.js`, where `a3f9d2c` is a **hash of the file's content**. New content → new hash → new *name*. That name change is the entire trick behind safe caching (next two lessons cash it in).\n\nThe starter **gives you** `hash(str)` — six lines of deterministic djb2. The lesson is the *pipeline*, not the hashing: upgrade `build()` so the bundle ships as `\"app.\" + hash(builtContent) + \".js\"`. Hash the **output** you ship — after the placeholder is replaced — because that's what the browser will actually receive.\n\nSame honesty note as before: a real bundler does this plus module resolution, tree-shaking, transpilation, source maps and minification. That's the Node & npm course; here we're only making the mechanism visible.",
      example: { lang: "js", code: "hash('const API = \"https://api.live\";')  // → \"1cd9mcc\" (say)\n// same string in → same hash out, every time, every machine\n// one changed byte → a completely different hash" },
      steps: [
        { text: "Emit the bundle as `app.<hash>.js` — hashed from the **built** content, with plain `app.js` gone from dist.",
          test: "var src1 = { 'index.html': '<h1>NoteStream</h1>', 'app.js': 'const API = \"__API_URL__\";' };\nvar dist = build(src1, { API_URL: 'https://api.live' });\nvar keys = Object.keys(dist);\nT.expect(keys.some(function (k) { return /^app\\.[0-9a-z]+\\.js$/.test(k); }), 'emit app.<hash>.js — the bundle filename must carry its content hash, e.g. app.a3f9d2c.js. Build the name with \"app.\" + hash(content) + \".js\"');\nT.expect(!('app.js' in dist), 'plain app.js must NOT ship — the hashed file REPLACES it, it does not sit next to it');\nvar hashedKey = keys.filter(function (k) { return /^app\\.[0-9a-z]+\\.js$/.test(k); })[0];\nT.expect(dist[hashedKey].indexOf('https://api.live') !== -1, 'the hashed file must hold the BUILT content — replace the placeholder first, then hash');\nT.expect('index.html' in dist, 'index.html still ships too — only app.js gets renamed');" },
        { text: "Determinism: the same input must produce the **same filenames**, run after run.",
          test: "var src2 = { 'index.html': '<h1>NoteStream</h1>', 'app.js': 'const API = \"__API_URL__\";' };\nvar env2 = { API_URL: 'https://api.live' };\nT.eq(Object.keys(build(src2, env2)).sort(), Object.keys(build(src2, env2)).sort(), 'same input, same filenames — a build is a pure function. No timestamps, no randomness: hash the CONTENT and nothing else.');" },
        { text: "Sensitivity: one changed byte — in the source **or** in the env — must change the name.",
          test: "var base = { 'app.js': 'const API = \"__API_URL__\";' };\nvar oneByte = { 'app.js': 'const API = \"__API_URL__\";\\n' };\nvar envA = { API_URL: 'https://api.live' };\nfunction bundleOf(d) { return Object.keys(d).filter(function (k) { return /^app\\./.test(k); })[0]; }\nT.expect(bundleOf(build(oneByte, envA)) !== bundleOf(build(base, envA)), 'one changed byte must change the hash — that new NAME is what will let browsers cache the old file forever, safely');\nT.expect(bundleOf(build(base, { API_URL: 'https://one' })) !== bundleOf(build(base, { API_URL: 'https://two' })), 'different env → different built bytes → different hash. Hash the OUTPUT you ship, not the source you read.');" }
      ],
      files: [
        { name: "script.js", content: "const SRC = {\n  \"index.html\": \"<!doctype html>\\n<h1>NoteStream</h1>\\n<script src=\\\"app.js\\\"><\\/script>\",\n  \"app.js\": \"const API = \\\"__API_URL__\\\";\\nconsole.log(\\\"calling \\\" + API);\"\n};\n\n// ---- GIVEN: a tiny deterministic content hash (djb2). Do not edit. ----\nfunction hash(str) {\n  let h = 5381;\n  for (let i = 0; i < str.length; i++) {\n    h = ((h * 33) ^ str.charCodeAt(i)) >>> 0;\n  }\n  return h.toString(36);\n}\n\n// Upgrade build(): after replacing the placeholder, ship app.js under\n// the name \"app.\" + hash(builtContent) + \".js\". Hash the OUTPUT.\nfunction build(src, env) {\n  const dist = {};\n  for (const key of Object.keys(src)) {\n    dist[key] = src[key].split(\"__API_URL__\").join(env.API_URL);\n  }\n  return dist;\n}\n\nconsole.log(Object.keys(build(SRC, { API_URL: \"https://api.live\" })));\n" }
      ],
      hints: [
        "Compute the built text first (`const built = src[key].split(\"__API_URL__\").join(env.API_URL);`), THEN hash it — the hash must cover the bytes you actually ship.",
        "Only `app.js` changes name: `if (key === \"app.js\") dist[\"app.\" + hash(built) + \".js\"] = built; else dist[key] = built;`",
        "If your env-sensitivity check fails, you hashed `src[key]` (the source) instead of `built` (the output)."
      ],
      solution: {
        "script.js": "const SRC = {\n  \"index.html\": \"<!doctype html>\\n<h1>NoteStream</h1>\\n<script src=\\\"app.js\\\"><\\/script>\",\n  \"app.js\": \"const API = \\\"__API_URL__\\\";\\nconsole.log(\\\"calling \\\" + API);\"\n};\n\n// ---- GIVEN: a tiny deterministic content hash (djb2). Do not edit. ----\nfunction hash(str) {\n  let h = 5381;\n  for (let i = 0; i < str.length; i++) {\n    h = ((h * 33) ^ str.charCodeAt(i)) >>> 0;\n  }\n  return h.toString(36);\n}\n\nfunction build(src, env) {\n  const dist = {};\n  for (const key of Object.keys(src)) {\n    const built = src[key].split(\"__API_URL__\").join(env.API_URL);\n    if (key === \"app.js\") {\n      dist[\"app.\" + hash(built) + \".js\"] = built;\n    } else {\n      dist[key] = built;\n    }\n  }\n  return dist;\n}\n\nconsole.log(Object.keys(build(SRC, { API_URL: \"https://api.live\" })));\n"
      }
    },

    {
      id: "ship-u3-3",
      title: "Rewriting the HTML (or the site 404s)",
      kind: "js", chip: "SHIP", xp: 15, mins: 13,
      brief: "Last lesson left a bug live in production: `dist` ships `app.a3f9d2c.js`, but `index.html` still says `<script src=\"app.js\">` — a file that **no longer exists**. Every visitor 404s on the very first script tag. A hashed build is only half a build until the HTML is rewritten to match.\n\nUpgrade `build()` one more time: `dist`'s `index.html` must reference the hashed bundle name, and the old `src=\"app.js\"` must be **gone**. The reference can never dangle — whatever filename the HTML names must actually exist in `dist`, on this build and on every rebuild after it.\n\nStill the honest 30-line core: real bundlers do this same rewrite (plus module resolution, tree-shaking, transpilation, source maps, minification — the Node & npm course's territory).",
      example: { lang: "js", code: "// before (source):        after (dist):\n// <script src=\"app.js\">   <script src=\"app.1cd9mcc.js\">\n//        └── names a file that must EXIST in dist ──┘" },
      steps: [
        { text: "`dist['index.html']` must reference the hashed bundle filename.",
          test: "var src1 = { 'index.html': '<!doctype html>\\n<h1>NoteStream</h1>\\n<script src=\"app.js\"><\\/script>', 'app.js': 'const API = \"__API_URL__\";' };\nvar dist = build(src1, { API_URL: 'https://api.live' });\nvar bundle = Object.keys(dist).filter(function (k) { return /^app\\.[0-9a-z]+\\.js$/.test(k); })[0];\nT.expect(!!bundle, 'build must still emit app.<hash>.js (keep everything from the last lesson)');\nT.expect(typeof dist['index.html'] === 'string' && dist['index.html'].indexOf(bundle) !== -1, 'index.html must point at the hashed file — rewrite src=\"app.js\" to the new bundle name (' + bundle + ')');" },
        { text: "The old `src=\"app.js\"` must be **gone** from the shipped HTML.",
          test: "var src1 = { 'index.html': '<!doctype html>\\n<h1>NoteStream</h1>\\n<script src=\"app.js\"><\\/script>', 'app.js': 'const API = \"__API_URL__\";' };\nvar dist = build(src1, { API_URL: 'https://api.live' });\nT.expect(!/src=\"app\\.js\"/.test(dist['index.html']), 'the old src=\"app.js\" must be GONE — dist has no app.js, so every visitor would 404 on the very first script tag');" },
        { text: "The reference never dangles: on this build **and** on a rebuild with changed content, the HTML names a file that exists in that dist.",
          test: "var srcA = { 'index.html': '<!doctype html>\\n<script src=\"app.js\"><\\/script>', 'app.js': 'const API = \"__API_URL__\";' };\nvar envA = { API_URL: 'https://api.live' };\nvar dA = build(srcA, envA);\nvar mA = /src=\"([^\"]+)\"/.exec(dA['index.html']);\nT.expect(!!mA, 'index.html still needs its <script src=\"...\"> tag — rewrite the name, do not delete the tag');\nT.expect(mA[1] in dA, 'the file the HTML names must EXIST in dist — the reference can never dangle');\nvar srcB = { 'index.html': '<!doctype html>\\n<script src=\"app.js\"><\\/script>', 'app.js': 'const API = \"__API_URL__\"; // v2' };\nvar dB = build(srcB, envA);\nvar mB = /src=\"([^\"]+)\"/.exec(dB['index.html']);\nT.expect(!!mB && mB[1] !== mA[1], 'new content → new hash → the rewritten HTML must reference the NEW bundle name');\nT.expect(!!mB && (mB[1] in dB), 'and the new reference must resolve inside the new dist — HTML and bundle always ship as a matched pair');" }
      ],
      files: [
        { name: "script.js", content: "const SRC = {\n  \"index.html\": \"<!doctype html>\\n<h1>NoteStream</h1>\\n<script src=\\\"app.js\\\"><\\/script>\",\n  \"app.js\": \"const API = \\\"__API_URL__\\\";\\nconsole.log(\\\"calling \\\" + API);\"\n};\n\n// ---- GIVEN: deterministic content hash (djb2). Do not edit. ----\nfunction hash(str) {\n  let h = 5381;\n  for (let i = 0; i < str.length; i++) {\n    h = ((h * 33) ^ str.charCodeAt(i)) >>> 0;\n  }\n  return h.toString(36);\n}\n\n// Upgrade build() again: index.html in dist must reference the hashed\n// bundle name — and the old app.js reference must be gone.\nfunction build(src, env) {\n  const dist = {};\n  for (const key of Object.keys(src)) {\n    const built = src[key].split(\"__API_URL__\").join(env.API_URL);\n    if (key === \"app.js\") {\n      dist[\"app.\" + hash(built) + \".js\"] = built;\n    } else {\n      dist[key] = built;\n    }\n  }\n  return dist;\n}\n\nconsole.log(build(SRC, { API_URL: \"https://api.live\" })[\"index.html\"]);\n" }
      ],
      hints: [
        "Two passes keep it clean: first replace placeholders in EVERY file into a `built` map, then compute `const bundle = \"app.\" + hash(built[\"app.js\"]) + \".js\";`, then assemble dist.",
        "The rewrite is one line: `dist[\"index.html\"] = built[\"index.html\"].split(\"app.js\").join(bundle);`",
        "If step 3's rebuild check fails, you hard-coded a name somewhere — the bundle name must be recomputed from content on every build."
      ],
      solution: {
        "script.js": "const SRC = {\n  \"index.html\": \"<!doctype html>\\n<h1>NoteStream</h1>\\n<script src=\\\"app.js\\\"><\\/script>\",\n  \"app.js\": \"const API = \\\"__API_URL__\\\";\\nconsole.log(\\\"calling \\\" + API);\"\n};\n\n// ---- GIVEN: deterministic content hash (djb2). Do not edit. ----\nfunction hash(str) {\n  let h = 5381;\n  for (let i = 0; i < str.length; i++) {\n    h = ((h * 33) ^ str.charCodeAt(i)) >>> 0;\n  }\n  return h.toString(36);\n}\n\nfunction build(src, env) {\n  const built = {};\n  for (const key of Object.keys(src)) {\n    built[key] = src[key].split(\"__API_URL__\").join(env.API_URL);\n  }\n  const bundle = \"app.\" + hash(built[\"app.js\"]) + \".js\";\n  const dist = {};\n  for (const key of Object.keys(built)) {\n    if (key === \"app.js\") {\n      dist[bundle] = built[key];\n    } else if (key === \"index.html\") {\n      dist[key] = built[key].split(\"app.js\").join(bundle);\n    } else {\n      dist[key] = built[key];\n    }\n  }\n  return dist;\n}\n\nconsole.log(build(SRC, { API_URL: \"https://api.live\" })[\"index.html\"]);\n"
      }
    },

    {
      id: "ship-u3-4",
      title: "Cache-Control: the deploy nobody can see",
      kind: "js", chip: "SHIP", xp: 15, mins: 13,
      brief: "Your build is correct — now decide how long browsers may keep each file. The policy follows straight from the naming: a **hashed** file can never change behind its name, so cache it for a year: `public, max-age=31536000, immutable`. But `index.html` keeps the **same name** across deploys, so it must be revalidated every visit: `no-cache`. Get that backwards and you ship *the deploy nobody can see* — v2 is live, and every returning visitor is frozen on v1.\n\nWrite `headersFor(filename)` returning the right `{ \"cache-control\": … }` for each file. Then the **given** ~20-line simulated browser (a plain object we control — not `localStorage`, storage is a different lesson's business) replays two deploys against your policy and proves both the win and the failure mode.\n\nWhere real hosts let you set these headers lives in the cheat sheet; and as ever, a real bundler + CDN pipeline layers much more on top — Node & npm course territory.",
      example: { lang: "js", code: "headersFor(\"app.a3f9d2c.js\")\n// → { \"cache-control\": \"public, max-age=31536000, immutable\" }\nheadersFor(\"index.html\")\n// → { \"cache-control\": \"no-cache\" }   // revalidate, NOT \"never store\"" },
      steps: [
        { text: "Write `headersFor(filename)` — forever-cache for `app.<hash>.js`, `no-cache` for everything else.",
          test: "T.expect(typeof headersFor === 'function', 'Define headersFor(filename).');\nT.eq(headersFor('app.a3f9d2c.js')['cache-control'], 'public, max-age=31536000, immutable', 'a hashed file can never change behind its name — cache it forever: \"public, max-age=31536000, immutable\"');\nT.eq(headersFor('index.html')['cache-control'], 'no-cache', 'index.html keeps its name across deploys, so the browser must revalidate it on every visit: \"no-cache\"');\nT.eq(headersFor('app.js')['cache-control'], 'no-cache', 'no hash in the name means the bytes behind it can change — an UNhashed app.js must never get the forever policy. Match the app.<hash>.js shape, not the .js extension.');" },
        { text: "Replay two deploys through the given browser: with your policy, v2 is visible immediately — and the old hashed asset serves from cache, correctly.",
          test: "deploySite({ '/index.html': { version: 1, scriptSrc: 'app.aaa1111.js' }, '/app.aaa1111.js': { version: 1 } });\nvar b = makeBrowser();\nT.eq(b.get('/index.html').version, 1, 'first visit: the browser fetches v1');\nb.get('/app.aaa1111.js');\ndeploySite({ '/index.html': { version: 2, scriptSrc: 'app.bbb2222.js' }, '/app.bbb2222.js': { version: 2 } });\nvar second = b.get('/index.html');\nT.eq(second.version, 2, 'index.html on no-cache means the browser refetches it — the new deploy is visible immediately');\nT.eq(second.fromCache, false, 'no-cache means index.html is never served straight from this cache');\nT.eq(b.get('/app.aaa1111.js').fromCache, true, 'the OLD hashed asset serves from cache — and that is CORRECT, because a new build got a new NAME and the new HTML asks for that instead');\nT.eq(b.get('/app.bbb2222.js').version, 2, 'the browser follows the new HTML to the new bundle, fresh from the server');" },
        { text: "The wrong-policy variant: put `immutable` on **everything** and v2 becomes the deploy nobody can see.",
          test: "T.mutate('headersFor', function () { return { 'cache-control': 'public, max-age=31536000, immutable' }; }, function () {\n  deploySite({ '/index.html': { version: 1 } });\n  var trapped = makeBrowser();\n  trapped.get('/index.html');\n  deploySite({ '/index.html': { version: 2 } });\n  var seen = trapped.get('/index.html');\n  T.eq(seen.version, 1, 'with immutable on EVERYTHING, the browser never refetches index.html — v2 shipped and nobody saw it');\n  T.eq(seen.fromCache, true, 'this is \"the deploy nobody can see\": the HTML that names your new files is itself frozen in cache');\n});\ndeploySite({ '/index.html': { version: 1 } });\nvar fine = makeBrowser();\nfine.get('/index.html');\ndeploySite({ '/index.html': { version: 3 } });\nT.eq(fine.get('/index.html').version, 3, 'with YOUR headersFor restored, deploys are visible again — no-cache on index.html is the whole trick');" }
      ],
      files: [
        { name: "script.js", content: "// From the last lesson, dist ships index.html + app.<hash>.js.\n// Final decision: what Cache-Control does each file get?\n\n// headersFor(filename) → { \"cache-control\": \"...\" }\n//   app.<hash>.js  → \"public, max-age=31536000, immutable\"\n//   everything else (index.html!) → \"no-cache\"\nfunction headersFor(filename) {\n  // does the name carry a hash? (shape: app.<lowercase letters/digits>.js)\n}\n\n// ---- GIVEN: a tiny simulated browser + server. Plain objects — NOT\n// localStorage; this is a cache model, not a storage lesson. Do not edit. ----\nconst SERVER = { files: {} };\nfunction deploySite(dist) { SERVER.files = Object.assign({}, dist); }\n\nfunction makeBrowser() {\n  const cache = {}; // this browser's private cache\n  return {\n    get(path) {\n      if (cache[path]) return Object.assign({ fromCache: true }, cache[path]);\n      const file = SERVER.files[path];\n      if (!file) return { fromCache: false, missing: true };\n      const policy = (headersFor(path.slice(1)) || {})[\"cache-control\"] || \"\";\n      if (policy.indexOf(\"immutable\") !== -1) cache[path] = file; // keep forever\n      return Object.assign({ fromCache: false }, file);\n    }\n  };\n}\n\nconsole.log(headersFor(\"app.a3f9d2c.js\"), headersFor(\"index.html\"));\n" }
      ],
      hints: [
        "Test the SHAPE of the name, not the extension: `/^app\\.[0-9a-z]+\\.js$/.test(filename)` is true for app.a3f9d2c.js but false for app.js (no hash segment).",
        "Return real header objects: `{ \"cache-control\": \"public, max-age=31536000, immutable\" }` for hashed names, `{ \"cache-control\": \"no-cache\" }` for everything else.",
        "If step 2 says the old asset was not served from cache, your hashed branch never matched — check the regex anchors (`^` and `$`)."
      ],
      solution: {
        "script.js": "// From the last lesson, dist ships index.html + app.<hash>.js.\n// Final decision: what Cache-Control does each file get?\nfunction headersFor(filename) {\n  if (/^app\\.[0-9a-z]+\\.js$/.test(filename)) {\n    return { \"cache-control\": \"public, max-age=31536000, immutable\" };\n  }\n  return { \"cache-control\": \"no-cache\" };\n}\n\n// ---- GIVEN: a tiny simulated browser + server. Plain objects — NOT\n// localStorage; this is a cache model, not a storage lesson. Do not edit. ----\nconst SERVER = { files: {} };\nfunction deploySite(dist) { SERVER.files = Object.assign({}, dist); }\n\nfunction makeBrowser() {\n  const cache = {}; // this browser's private cache\n  return {\n    get(path) {\n      if (cache[path]) return Object.assign({ fromCache: true }, cache[path]);\n      const file = SERVER.files[path];\n      if (!file) return { fromCache: false, missing: true };\n      const policy = (headersFor(path.slice(1)) || {})[\"cache-control\"] || \"\";\n      if (policy.indexOf(\"immutable\") !== -1) cache[path] = file; // keep forever\n      return Object.assign({ fromCache: false }, file);\n    }\n  };\n}\n\nconsole.log(headersFor(\"app.a3f9d2c.js\"), headersFor(\"index.html\"));\n"
      }
    },

    {
      id: "ship-quiz-3",
      title: "Unit 3 quiz: Build vs. runtime",
      kind: "quiz", xp: 10,
      brief: "Two clocks, hashed names, rewritten HTML and the cache policy that decides who sees v2. 80% to pass.",
      questions: [
        { q: "Your deployed bundle still calls the OLD API URL after you changed `API_URL` in your host's dashboard. What actually fixes it?",
          choices: ["Wait an hour — host dashboard changes propagate to already-deployed files", "Rebuild and redeploy — the value was baked in at build time", "Hard-refresh the browser to clear the old value", "Point the DNS record at the new API server"],
          answer: 1, explain: "`build()` copied `env.API_URL` into the file when it ran; from that moment the bundle is frozen bytes, and no dashboard, refresh or DNS change can reach inside them. Runtime config only affects code that READS env while running — a Worker does, a static bundle does not. The fix is always the same: change the env, run the build again, deploy the new dist." },
        { q: "Which of these happens at RUN time?",
          choices: ["Replacing `__API_URL__` with a real URL", "Computing the `app.<hash>.js` filename", "Rewriting `<script src=\"app.js\">` to the hashed filename in index.html", "A Worker reading `env.GREETING` to answer a request"],
          answer: 3, explain: "The first three are `build()` steps — they run once, on your machine or in CI, before anything is deployed. A Worker's `env` is handed to `fetch(request, env, ctx)` on EVERY request, so changing a binding takes effect with no rebuild at all. That's the practical test: if changing it requires re-running build, it's build time." },
        { q: "You run `build(SRC, ENV)` twice with byte-identical inputs. What comes out?",
          choices: ["Identical filenames and content", "Identical content behind freshly randomized hash names", "Different filenames, because the hash includes a build timestamp", "It depends on which machine runs the build"],
          answer: 0, explain: "A build is a pure function: same input, same output — filenames included, because djb2 hashes only the content, with no timestamps or randomness mixed in. That determinism is what makes builds trustworthy: CI and your laptop produce the same dist, and an unchanged file keeps its exact name (and its year-long cache) across deploys. If two runs ever differ, something impure leaked into the pipeline." },
        { q: "Your whole `build()` is about 30 lines. Which job belongs to a real bundler, NOT to your build?",
          choices: ["Replacing placeholders with env values", "Hashing content into the output filenames", "Module resolution and tree-shaking", "Copying every source file into dist"],
          answer: 2, explain: "Your 30 lines really are the core: inject env, hash, rewrite the HTML. A real bundler (Vite, esbuild, webpack) additionally resolves `import` graphs, tree-shakes dead code, transpiles newer syntax, minifies, and emits source maps — machinery that belongs to the Node & npm course. Building the core by hand was about making build time vs. run time concrete, not about replacing your tooling." },
        { q: "Which `Cache-Control` belongs on index.html?",
          choices: ["`public, max-age=31536000, immutable`", "`no-cache`", "`max-age=86400`", "No header — browsers work out sensible caching on their own"],
          answer: 1, explain: "index.html keeps the SAME name across deploys, so the browser must check it against the server on every visit — `no-cache` means exactly that: revalidate before using, not \"never store\". It's the one file that names all your hashed assets, so it's the doorway every deploy walks through. Save the year-long `immutable` policy for files whose name changes whenever their content does." },
        { q: "index.html shipped with `max-age=31536000, immutable` by mistake. You deploy v2. What do returning visitors get?",
          choices: ["v2 immediately — deploying invalidates browser caches", "A 404, because v1's hashed bundle was deleted", "v2 after a few minutes of CDN propagation", "v1, until the cache expires or they hard-refresh"],
          answer: 3, explain: "Deploying reaches your server, not your users' browser caches: their cached index.html is trusted for a year and keeps naming v1's bundle, which is also cached. Everything works and nothing updates — the deploy nobody can see. That's why the policy split matters as much as the build itself: hashed files get forever, the un-hashed entry point gets `no-cache`." }
      ]
    }
  ]
});
