/* Deploying Your App — Unit 4: Your Worker at the edge */
window.CODELAB.addUnit("ship", {
  id: "ship-u4",
  title: "Your Worker at the edge",
  icon: "⚡",
  blurb: "Course 7's handleRequest goes live: real fetch(request, env, ctx), real Request and Response objects, and the CORS handshake between your Pages site and your API.",
  cheat: [
    { h: "The Worker file, whole", lang: "js", code: "export default {\n  async fetch(request, env, ctx) {\n    const url = new URL(request.url);\n    // route on request.method + url.pathname\n    return new Response(JSON.stringify(data), {\n      status: 200,\n      headers: { \"content-type\": \"application/json\" }\n    });\n  }\n};", note: "This exact shape deploys as src/index.js in a wrangler project. Request in, Response out — Course 7's model with real types." },
    { h: "The port from Course 7", lang: "js", code: "// Course 7                      // Cloudflare Worker\nhandleRequest(req)                fetch(request, env, ctx)\nreq.path                          new URL(request.url).pathname\nreq.query.q                       url.searchParams.get(\"q\")\nreq.body                          await request.json()\n{ status: 200, body }             new Response(JSON.stringify(body),\n                                    { status: 200, headers })", note: "Same brain, new types. Routing, status codes and the error envelope carry over unchanged." },
    { h: "wrangler, the four commands", lang: "js", code: "npm create cloudflare@latest      // scaffold a Worker project\nnpx wrangler dev                  // run it at http://localhost:8787\nnpx wrangler deploy               // ship it to your *.workers.dev URL\nnpx wrangler secret put API_KEY   // store a secret in env, never in code", note: "Command-line procedure lives here and in the Unit 7 field guide — the lessons grade the code, which doesn't expire." },
    { h: "wrangler.toml → env", lang: "js", code: "// wrangler.toml                  // your code\n// name = \"notes-api\"\n// [vars]\n// GREETING = \"hola\"              env.GREETING            // \"hola\"\n// ALLOWED_ORIGINS = \"https://me.github.io\"\n//                                env.ALLOWED_ORIGINS.split(\",\")", note: "[vars] for plain config, wrangler secret put for secrets — both arrive on the same env object, always as STRINGS (Unit 2's rule)." },
    { h: "CORS in three moves", lang: "js", code: "// 1) WHO may read — echo an allowlisted caller, silence for strangers\naccess-control-allow-origin: https://me.github.io\n// 2) WHICH verbs the preflight approves\naccess-control-allow-methods: GET, POST, DELETE, OPTIONS\n// 3) the preflight itself: the browser's OPTIONS request → answer 204", note: "The server grants, the browser enforces. Strangers get no header at all — an allowlist, not *." },
    { h: "204 means NO body", lang: "js", code: "return new Response(null, { status: 204, headers });  // ✓\nreturn new Response(\"\",  { status: 204 });             // ✗ throws\n// 204 and 304 forbid a body — pass null, not an empty string", note: "No Content means it. The Response constructor enforces the spec for you." }
  ],
  lessons: [

    {
      id: "ship-u4-1",
      title: "From handleRequest to fetch(request, env, ctx)",
      kind: "js", chip: "SHIP", xp: 15, mins: 13,
      brief: "This is the graduation Course 7 was building toward. Your `handleRequest(req)` becomes a **Cloudflare Worker**: `export default { async fetch(request, env, ctx) { … } }` — and this time the file is real. Paste it into a wrangler project and it deploys unmodified.\n\nSame job, real types: `request` is a Fetch-API `Request` whose `.url` is the *full* URL string — `new URL(request.url).pathname` gets you the path. And instead of a plain `{ status, body }` object you return a real `Response`: the body goes on the wire as a **string** (`JSON.stringify` it) and you declare the `content-type` yourself.\n\nRouting, status codes and the 404-last habit are Course 7's and don't change — today is purely the port. Build two routes: `GET /api/health` answering `200` JSON `{ ok: true }`, and the catch-all `404` speaking the same error envelope your Bookmarks API spoke.",
      example: { lang: "js", code: "// Course 7:                       // today:\nfunction handleRequest(req) {      export default {\n  return { status: 200, body };      async fetch(request, env, ctx) {\n}                                      return new Response(txt, { status: 200, headers });\n                                     }\n                                   };" },
      steps: [
        { text: "Keep the `export default { async fetch }` shape and make `GET /api/health` answer **200** with a real `Response`.",
          test: "T.expect(worker && typeof worker.fetch === 'function', 'Keep the export default { async fetch(request, env, ctx) { … } } shape — that object IS your server now');\nvar res = await worker.fetch(new Request('https://api.me.dev/api/health'), {});\nT.expect(res instanceof Response, 'fetch must RETURN a new Response(...) — the plain { status, body } object was Course 7');\nT.eq(res.status, 200, 'GET /api/health should answer 200 — yours answered ' + res.status);" },
        { text: "The health body is JSON on the wire: `{ ok: true }`, with the `content-type` header declared.",
          test: "var res = await worker.fetch(new Request('https://api.me.dev/api/health'), {});\nT.eq(res.headers.get('content-type'), 'application/json', 'say what you are sending: headers: { \"content-type\": \"application/json\" }');\nT.eq(await res.json(), { ok: true }, 'the body travels as a STRING — JSON.stringify({ ok: true }) it');" },
        { text: "Every other path → **404** with the `{ error: { code, message } }` envelope.",
          test: "var res = await worker.fetch(new Request('https://api.me.dev/nope'), {});\nT.eq(res.status, 404, 'unknown paths still get an answer — the catch-all 404 is the last line, exactly like Course 7');\nT.eq(await res.json(), { error: { code: 'not_found', message: 'no such route' } }, 'the 404 body is the envelope your Bookmarks API spoke: { error: { code: \"not_found\", message: \"no such route\" } }');\nvar res2 = await worker.fetch(new Request('https://api.me.dev/api/health/extra'), {});\nT.eq(res2.status, 404, '/api/health/extra is not /api/health — match url.pathname exactly');" }
      ],
      files: [
        { name: "script.js", content: "// Course 7 taught you:  function handleRequest(req) → { status, body }\n// The platform runs:    export default { async fetch(request, env, ctx) } → new Response(...)\n//\n// Routes:\n//   GET /api/health → 200 JSON { ok: true }\n//   anything else   → 404 JSON { error: { code: \"not_found\", message: \"no such route\" } }\n\nexport default {\n  async fetch(request, env, ctx) {\n    // request.url is the FULL url — new URL(request.url).pathname is the path\n  }\n};\n" }
      ],
      hints: [
        "`const url = new URL(request.url);` — then route on `url.pathname === \"/api/health\"` with the same early returns as Course 7.",
        "A JSON response, spelled out once: `return new Response(JSON.stringify({ ok: true }), { status: 200, headers: { \"content-type\": \"application/json\" } });`",
        "The catch-all is the last line of fetch — same envelope, status 404: `JSON.stringify({ error: { code: \"not_found\", message: \"no such route\" } })`."
      ],
      solution: {
        "script.js": "export default {\n  async fetch(request, env, ctx) {\n    const url = new URL(request.url);\n\n    if (url.pathname === \"/api/health\") {\n      return new Response(JSON.stringify({ ok: true }), {\n        status: 200,\n        headers: { \"content-type\": \"application/json\" }\n      });\n    }\n\n    return new Response(JSON.stringify({ error: { code: \"not_found\", message: \"no such route\" } }), {\n      status: 404,\n      headers: { \"content-type\": \"application/json\" }\n    });\n  }\n};\n"
      }
    },

    {
      id: "ship-u4-2",
      title: "URL, pathname and searchParams — the real API",
      kind: "js", chip: "SHIP", xp: 15, mins: 13,
      brief: "In Course 7 Unit 3 you split query strings by hand — `split(\"&\")`, `split(\"=\")` — to learn what's inside them. The platform hands you the finished tool: `new URL(request.url)` gives `.pathname` for routing and `.searchParams` for the query, already decoded, no parsing bugs. This lesson grades the API, not the parsing.\n\nTwo rules carry over from earlier units: `searchParams.get(\"limit\")` returns a **string** (`\"2\"`, not `2` — Unit 2's everything-is-a-string rule), and a param that isn't there comes back `null`, so check before you use it.\n\nAdd `GET /api/notes` to the Worker: no query → every note; `?q=` filters `text` case-insensitively; `?limit=` slices **after** the filter.",
      example: { lang: "js", code: "const url = new URL(\"https://api.me.dev/api/notes?q=ship&limit=2\");\nurl.pathname                    // \"/api/notes\"\nurl.searchParams.get(\"q\")       // \"ship\"\nurl.searchParams.get(\"limit\")   // \"2\"  ← a STRING\nurl.searchParams.get(\"nope\")    // null ← missing, not \"\"" },
      steps: [
        { text: "`GET /api/notes` with no query → **200** with every note.",
          test: "var res = await worker.fetch(new Request('https://api.me.dev/api/notes'), {});\nT.eq(res.status, 200, 'GET /api/notes should answer 200 — yours answered ' + res.status);\nT.eq(await res.json(), [{ id: 1, text: 'buy milk' }, { id: 2, text: 'water the plants' }, { id: 3, text: 'ship it' }], 'no query string → the whole NOTES list');" },
        { text: "`?q=` keeps only notes whose `text` contains it, case-insensitively.",
          test: "var res = await worker.fetch(new Request('https://api.me.dev/api/notes?q=ship'), {});\nT.eq(await res.json(), [{ id: 3, text: 'ship it' }], '?q=ship keeps only matching texts — url.searchParams.get(\"q\"), no split(\"&\") in sight');\nvar res2 = await worker.fetch(new Request('https://api.me.dev/api/notes?q=PLANTS'), {});\nT.eq(await res2.json(), [{ id: 2, text: 'water the plants' }], 'match case-insensitively — lowercase both sides before includes()');\nvar res3 = await worker.fetch(new Request('https://api.me.dev/api/notes?q=zzz'), {});\nT.eq(await res3.json(), [], 'no matches → an empty list, still 200 — an empty result is not an error');" },
        { text: "`?limit=` slices the list — remember it arrives as a **string**.",
          test: "var res = await worker.fetch(new Request('https://api.me.dev/api/notes?limit=2'), {});\nT.eq(await res.json(), [{ id: 1, text: 'buy milk' }, { id: 2, text: 'water the plants' }], '?limit=2 keeps the first two — searchParams.get(\"limit\") is the STRING \"2\": Number() it');\nvar res2 = await worker.fetch(new Request('https://api.me.dev/api/notes'), {});\nT.eq((await res2.json()).length, 3, 'no limit param → no slicing — a missing param is null, so check it before calling slice');" },
        { text: "`q` and `limit` combine: filter **first**, then slice.",
          test: "var res = await worker.fetch(new Request('https://api.me.dev/api/notes?q=ship&limit=2'), {});\nT.eq(await res.json(), [{ id: 3, text: 'ship it' }], 'filter first: one match, so limit=2 has nothing left to trim');\nvar res2 = await worker.fetch(new Request('https://api.me.dev/api/notes?q=t&limit=1'), {});\nT.eq(await res2.json(), [{ id: 2, text: 'water the plants' }], '?q=t matches two notes; limit=1 keeps the FIRST of the matches — filter, THEN slice');" }
      ],
      files: [
        { name: "script.js", content: "const NOTES = [\n  { id: 1, text: \"buy milk\" },\n  { id: 2, text: \"water the plants\" },\n  { id: 3, text: \"ship it\" }\n];\n\nexport default {\n  async fetch(request, env, ctx) {\n    const url = new URL(request.url);\n\n    if (url.pathname === \"/api/health\") {\n      return new Response(JSON.stringify({ ok: true }), {\n        status: 200,\n        headers: { \"content-type\": \"application/json\" }\n      });\n    }\n\n    // GET /api/notes → 200 JSON\n    //   ?q=      case-insensitive filter on note.text   (url.searchParams.get(\"q\"))\n    //   ?limit=  slice AFTER the filter — it arrives as a STRING (or null when absent)\n\n    return new Response(JSON.stringify({ error: { code: \"not_found\", message: \"no such route\" } }), {\n      status: 404,\n      headers: { \"content-type\": \"application/json\" }\n    });\n  }\n};\n" }
      ],
      hints: [
        "Start from the full list and narrow it: `let out = NOTES;` — filter when `q` is set, slice when `limit` is set, then respond with `out`.",
        "The filter: `const q = url.searchParams.get(\"q\"); if (q !== null && q !== \"\") { const needle = q.toLowerCase(); out = out.filter(n => n.text.toLowerCase().includes(needle)); }`",
        "The slice: `const lim = url.searchParams.get(\"limit\"); if (lim !== null) out = out.slice(0, Number(lim));` — Number(null) is 0, so slicing unconditionally would empty the list."
      ],
      solution: {
        "script.js": "const NOTES = [\n  { id: 1, text: \"buy milk\" },\n  { id: 2, text: \"water the plants\" },\n  { id: 3, text: \"ship it\" }\n];\n\nexport default {\n  async fetch(request, env, ctx) {\n    const url = new URL(request.url);\n\n    if (url.pathname === \"/api/health\") {\n      return new Response(JSON.stringify({ ok: true }), {\n        status: 200,\n        headers: { \"content-type\": \"application/json\" }\n      });\n    }\n\n    if (url.pathname === \"/api/notes\") {\n      const q = url.searchParams.get(\"q\");\n      const lim = url.searchParams.get(\"limit\");\n      let out = NOTES;\n      if (q !== null && q !== \"\") {\n        const needle = q.toLowerCase();\n        out = out.filter(n => n.text.toLowerCase().includes(needle));\n      }\n      if (lim !== null) {\n        out = out.slice(0, Number(lim));\n      }\n      return new Response(JSON.stringify(out), {\n        status: 200,\n        headers: { \"content-type\": \"application/json\" }\n      });\n    }\n\n    return new Response(JSON.stringify({ error: { code: \"not_found\", message: \"no such route\" } }), {\n      status: 404,\n      headers: { \"content-type\": \"application/json\" }\n    });\n  }\n};\n"
      }
    },

    {
      id: "ship-u4-3",
      title: "env is the second argument",
      kind: "js", chip: "SHIP", xp: 15, mins: 13,
      brief: "Unit 2's config object has a third spelling now: what `process.env` is to Node and the Variables panel is to a dashboard, the **`env` argument** is to a Worker — the second parameter of `fetch`, filled from `[vars]` in wrangler.toml and from `wrangler secret put`. Same object, same rules: values arrive as strings, and config changes without code changes.\n\nThis starter has both classic sins. The greeting is welded into the code, and someone pasted a live key into the handler while debugging — which means it ships to anyone who reads the source. Fix both: greet with `env.GREETING`, falling back to `\"hello\"` when the binding is missing (a missing binding must never crash the Worker), and delete the key outright — secrets ride in `env`, set by `wrangler secret put`, never in the file.\n\nOnly *where config lives* is today's topic — auth and tokens themselves stay Course 7's.",
      steps: [
        { text: "`GET /api/hello` greets from config: with `env.GREETING = \"hola\"` the message is `\"hola, world\"`.",
          test: "var res = await worker.fetch(new Request('https://api.me.dev/api/hello'), { GREETING: 'hola' });\nT.eq(res.status, 200, 'GET /api/hello should answer 200');\nT.eq((await res.json()).message, 'hola, world', 'env is the SECOND argument of fetch — read env.GREETING instead of hardcoding the word');" },
        { text: "A missing binding falls back to `\"hello\"` — it never crashes.",
          test: "var res = await worker.fetch(new Request('https://api.me.dev/api/hello'), {});\nT.eq((await res.json()).message, 'hello, world', 'a missing binding falls back to a default — env.GREETING || \"hello\" — it does not crash the Worker');\nvar res2 = await worker.fetch(new Request('https://api.me.dev/api/hello'), { GREETING: 'howdy' });\nT.eq((await res2.json()).message, 'howdy, world', 'new config, same code: the deploy decides the greeting, not the file');" },
        { text: "Delete the pasted key — no secret may appear in the handler's source.",
          test: "T.expect(worker.fetch.toString().indexOf('sk_live') === -1, 'never hardcode a secret — delete the pasted key and read secrets from env (wrangler secret put)');\nvar res = await worker.fetch(new Request('https://api.me.dev/api/hello'), { GREETING: 'hola' });\nT.eq((await res.json()).message, 'hola, world', 'still greeting from env after the cleanup');" }
      ],
      files: [
        { name: "script.js", content: "// This Worker greets — but the greeting is welded into the code, and a debug\n// key got pasted into the handler. Config belongs in env, the SECOND argument:\n//   wrangler.toml  [vars] GREETING = \"hola\"   →   env.GREETING\n//   wrangler secret put API_KEY               →   env.API_KEY   (never in source)\n\nexport default {\n  async fetch(request, env, ctx) {\n    const url = new URL(request.url);\n\n    if (url.pathname === \"/api/hello\") {\n      const DEBUG_KEY = \"sk_live_abc123\"; // ← delete me: this ships to every reader of the source\n      return new Response(JSON.stringify({ message: \"hello, world\" }), {\n        status: 200,\n        headers: { \"content-type\": \"application/json\" }\n      });\n    }\n\n    return new Response(JSON.stringify({ error: { code: \"not_found\", message: \"no such route\" } }), {\n      status: 404,\n      headers: { \"content-type\": \"application/json\" }\n    });\n  }\n};\n" }
      ],
      hints: [
        "Read the binding with a fallback, exactly like Unit 2's getConfig defaults: `const greeting = env.GREETING || \"hello\";`",
        "Then build the message from it: `JSON.stringify({ message: greeting + \", world\" })`.",
        "The DEBUG_KEY line isn't refactored — it's DELETED. A secret the Worker needs would arrive as `env.API_KEY`, set by `wrangler secret put API_KEY`, and never appear in the file."
      ],
      solution: {
        "script.js": "export default {\n  async fetch(request, env, ctx) {\n    const url = new URL(request.url);\n\n    if (url.pathname === \"/api/hello\") {\n      const greeting = env.GREETING || \"hello\";\n      return new Response(JSON.stringify({ message: greeting + \", world\" }), {\n        status: 200,\n        headers: { \"content-type\": \"application/json\" }\n      });\n    }\n\n    return new Response(JSON.stringify({ error: { code: \"not_found\", message: \"no such route\" } }), {\n      status: 404,\n      headers: { \"content-type\": \"application/json\" }\n    });\n  }\n};\n"
      }
    },

    {
      id: "ship-u4-4",
      title: "CORS, or why your Pages site can't call your Worker",
      kind: "js", chip: "SHIP", xp: 15, mins: 13,
      brief: "Day one after deploying, your Pages site at `https://me.github.io` calls your Worker and the console says: *blocked by CORS policy: No 'Access-Control-Allow-Origin' header*. Here's the handshake: the browser stamps every cross-origin request with an `Origin` header, the **server** answers with `access-control-allow-origin` naming who may read the response, and the browser enforces it. The request still reaches you — the browser just withholds the answer from the page.\n\nSo the fix is server-side, and it's an **allowlist, not `*`**: echo the caller's origin back when it's one of yours, send *no* CORS header to strangers. For verbs like `DELETE` the browser first sends an `OPTIONS` **preflight** — answer `204 No Content` (a 204 takes a `null` body) with the origin echo plus `access-control-allow-methods` listing what you accept.\n\nThis is the server half of the handshake only — the client's `fetch()` call and its options belong to Course 6, and nothing about them changes here.",
      example: { lang: "js", code: "// browser adds:            origin: https://me.github.io\n// allowlisted → you answer: access-control-allow-origin: https://me.github.io\n// stranger    → you answer: (no CORS header at all)\n// OPTIONS preflight → 204 + the echo + access-control-allow-methods" },
      steps: [
        { text: "Allowlisted callers get their **own** origin echoed in `access-control-allow-origin`.",
          test: "var res = await worker.fetch(new Request('https://api.me.dev/api/notes', { headers: { origin: 'https://me.github.io' } }), {});\nT.eq(res.status, 200, 'the data route still answers 200');\nT.eq(res.headers.get('access-control-allow-origin'), 'https://me.github.io', 'echo the caller\\'s origin when it is on the allowlist — this is the header the browser is looking for');\nvar res2 = await worker.fetch(new Request('https://api.me.dev/api/notes', { headers: { origin: 'http://localhost:5173' } }), {});\nT.eq(res2.headers.get('access-control-allow-origin'), 'http://localhost:5173', 'each allowlisted caller gets ITS OWN origin back — read request.headers.get(\"origin\") and check it against ALLOWED');" },
        { text: "Strangers get **no** CORS header — and no-origin requests (curl, same-origin) don't need one.",
          test: "var bad = await worker.fetch(new Request('https://api.me.dev/api/notes', { headers: { origin: 'https://evil.example' } }), {});\nT.eq(bad.headers.get('access-control-allow-origin'), null, 'a stranger gets no CORS header — an allowlist, not *');\nT.eq(bad.status, 200, 'CORS does not stop the SERVER from answering — the BROWSER withholds the response from the page; the header only grants permission to read it');\nvar plain = await worker.fetch(new Request('https://api.me.dev/api/notes'), {});\nT.eq(plain.headers.get('access-control-allow-origin'), null, 'no origin header on the request (curl, same-origin) → nothing to echo');" },
        { text: "`OPTIONS` preflight → **204** with the echo plus `access-control-allow-methods` including `DELETE`.",
          test: "var pre = await worker.fetch(new Request('https://api.me.dev/api/notes', { method: 'OPTIONS', headers: { origin: 'https://me.github.io' } }), {});\nT.eq(pre.status, 204, 'a preflight answers 204 No Content — permission headers only, and a 204 takes a null body: new Response(null, …)');\nT.eq(pre.headers.get('access-control-allow-origin'), 'https://me.github.io', 'the preflight carries the same origin echo');\nT.expect((pre.headers.get('access-control-allow-methods') || '').indexOf('DELETE') !== -1, 'advertise DELETE in access-control-allow-methods — the browser will not send a verb the preflight never approved');\nvar preBad = await worker.fetch(new Request('https://api.me.dev/api/notes', { method: 'OPTIONS', headers: { origin: 'https://evil.example' } }), {});\nT.eq(preBad.headers.get('access-control-allow-origin'), null, 'strangers get no permission on the preflight either');" }
      ],
      files: [
        { name: "script.js", content: "// The API works — but a browser on https://me.github.io calling it sees:\n//   \"blocked by CORS policy: No 'Access-Control-Allow-Origin' header\"\n// The SERVER decides who may read its answers. Fix the server.\n\nconst NOTES = [\n  { id: 1, text: \"buy milk\" },\n  { id: 2, text: \"water the plants\" },\n  { id: 3, text: \"ship it\" }\n];\n\nconst ALLOWED = [\"https://me.github.io\", \"http://localhost:5173\"];\n\nfunction json(data, code, extra) {\n  return new Response(JSON.stringify(data), {\n    status: code,\n    headers: Object.assign({ \"content-type\": \"application/json\" }, extra || {})\n  });\n}\n\nexport default {\n  async fetch(request, env, ctx) {\n    const url = new URL(request.url);\n\n    // 1) CORS headers for THIS request:\n    //      request.headers.get(\"origin\") in ALLOWED\n    //        → { \"access-control-allow-origin\": that exact origin }\n    //        otherwise → {} — strangers get no CORS header at all\n    //    …and attach them to EVERY response below (json's third argument).\n    // 2) OPTIONS preflight → 204, CORS headers plus\n    //      \"access-control-allow-methods\": \"GET, POST, DELETE, OPTIONS\"\n    //    (a 204 has NO body: new Response(null, { status: 204, headers }))\n\n    if (url.pathname === \"/api/notes\") {\n      return json(NOTES, 200);\n    }\n\n    return json({ error: { code: \"not_found\", message: \"no such route\" } }, 404);\n  }\n};\n" }
      ],
      hints: [
        "Compute the headers once, up top: `const caller = request.headers.get(\"origin\"); const cors = caller && ALLOWED.includes(caller) ? { \"access-control-allow-origin\": caller } : {};` — then pass `cors` as json's third argument on every return.",
        "The preflight branch goes before the routing: `if (request.method === \"OPTIONS\") return new Response(null, { status: 204, headers: Object.assign({ \"access-control-allow-methods\": \"GET, POST, DELETE, OPTIONS\" }, cors) });`",
        "Don't special-case the stranger — an empty `cors` object simply adds no header, which IS the correct answer for them."
      ],
      solution: {
        "script.js": "const NOTES = [\n  { id: 1, text: \"buy milk\" },\n  { id: 2, text: \"water the plants\" },\n  { id: 3, text: \"ship it\" }\n];\n\nconst ALLOWED = [\"https://me.github.io\", \"http://localhost:5173\"];\n\nfunction json(data, code, extra) {\n  return new Response(JSON.stringify(data), {\n    status: code,\n    headers: Object.assign({ \"content-type\": \"application/json\" }, extra || {})\n  });\n}\n\nexport default {\n  async fetch(request, env, ctx) {\n    const url = new URL(request.url);\n\n    const caller = request.headers.get(\"origin\");\n    const cors = caller && ALLOWED.includes(caller)\n      ? { \"access-control-allow-origin\": caller }\n      : {};\n\n    if (request.method === \"OPTIONS\") {\n      return new Response(null, {\n        status: 204,\n        headers: Object.assign({ \"access-control-allow-methods\": \"GET, POST, DELETE, OPTIONS\" }, cors)\n      });\n    }\n\n    if (url.pathname === \"/api/notes\") {\n      return json(NOTES, 200, cors);\n    }\n\n    return json({ error: { code: \"not_found\", message: \"no such route\" } }, 404, cors);\n  }\n};\n"
      }
    },

    {
      id: "ship-u4-p",
      title: "Project: your Worker API, live",
      kind: "js", chip: "SHIP", xp: 50, mins: 40, project: true,
      brief: "The whole unit in one production-shaped file: **notes-api**, a complete Cloudflare Worker you could paste into a wrangler project as `src/index.js` and deploy as-is.\n\nThe spec: `GET /api/health` for the deploy's boot check; `GET`/`POST`/`DELETE` on `/api/notes` with counter ids; a JSON body that isn't usable → **400** with the `invalid` envelope (and a body that isn't JSON at all must 400, not crash — `try/catch` around `await request.json()`); unknown anything → **404** with the `not_found` envelope. CORS on **every** response, driven by config: the allowlist comes from `env.ALLOWED_ORIGINS` (a comma-separated **string** — Unit 2's rule) with `\"https://me.github.io,http://localhost:5173\"` as the default, plus the `OPTIONS` preflight advertising `DELETE`.\n\nThe checkpoints replay one real cross-origin session — boot check, browsing, a create, a rejected create, the preflight-then-DELETE, a wrong turn — so keep your store straight from step to step. Wrangler's commands stay in the cheat sheet; this file is the part that's yours.",
      steps: [
        { text: "Boot check: `GET /api/health` → **200** JSON `{ ok: true }`.",
          test: "T.expect(worker && typeof worker.fetch === 'function', 'Keep the export default { async fetch(request, env, ctx) { … } } shape');\nvar res = await worker.fetch(new Request('https://api.me.dev/api/health'), {});\nT.expect(res instanceof Response, 'fetch must return a new Response(...)');\nT.eq(res.status, 200, '/api/health is the first thing a deploy checks — answer 200, yours answered ' + res.status);\nT.eq(res.headers.get('content-type'), 'application/json', 'health speaks JSON like every other route');\nT.eq(await res.json(), { ok: true }, 'body: { ok: true }');" },
        { text: "Cross-origin `GET /api/notes`: allowlisted origins echo, strangers get nothing — and the allowlist reads from `env.ALLOWED_ORIGINS`.",
          test: "var res = await worker.fetch(new Request('https://api.me.dev/api/notes', { headers: { origin: 'https://me.github.io' } }), {});\nT.eq(res.status, 200, 'GET /api/notes answers 200');\nT.eq(res.headers.get('access-control-allow-origin'), 'https://me.github.io', 'the Pages site is on the default allowlist — echo its origin');\nT.eq(await res.json(), [], 'the store starts empty');\nvar bad = await worker.fetch(new Request('https://api.me.dev/api/notes', { headers: { origin: 'https://evil.example' } }), {});\nT.eq(bad.headers.get('access-control-allow-origin'), null, 'a stranger gets no CORS header — an allowlist, not *');\nvar staged = await worker.fetch(new Request('https://api.me.dev/api/notes', { headers: { origin: 'https://staging.me.dev' } }), { ALLOWED_ORIGINS: 'https://staging.me.dev' });\nT.eq(staged.headers.get('access-control-allow-origin'), 'https://staging.me.dev', 'the allowlist comes from env.ALLOWED_ORIGINS — new config, same code');\nvar res2 = await worker.fetch(new Request('https://api.me.dev/api/notes', { headers: { origin: 'https://me.github.io' } }), { ALLOWED_ORIGINS: 'https://staging.me.dev' });\nT.eq(res2.headers.get('access-control-allow-origin'), null, 'when env.ALLOWED_ORIGINS is set it REPLACES the default list — on staging, me.github.io is the stranger');" },
        { text: "`POST /api/notes` with `{ text }` → **201**, and the note appears in a later `GET`.",
          test: "var res = await worker.fetch(new Request('https://api.me.dev/api/notes', { method: 'POST', headers: { 'content-type': 'application/json', origin: 'https://me.github.io' }, body: JSON.stringify({ text: 'ship the notes api' }) }), {});\nT.eq(res.status, 201, 'a successful create answers 201 — yours answered ' + res.status);\nT.eq(await res.json(), { id: 1, text: 'ship the notes api' }, 'echo the created note — { id, text }, ids from a counter starting at 1');\nT.eq(res.headers.get('access-control-allow-origin'), 'https://me.github.io', 'CORS headers ride on EVERY response, not just GETs');\nvar list = await worker.fetch(new Request('https://api.me.dev/api/notes'), {});\nT.eq(await list.json(), [{ id: 1, text: 'ship the notes api' }], 'the note appears in a later GET — a FRESH fetch call, because a Response body reads once');" },
        { text: "Bad creates → **400** envelopes, and nothing enters the store — including a body that isn't JSON.",
          test: "var res = await worker.fetch(new Request('https://api.me.dev/api/notes', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({}) }), {});\nT.eq(res.status, 400, 'a JSON body with no usable text → 400 — yours answered ' + res.status);\nT.eq(await res.json(), { error: { code: 'invalid', message: 'text is required' } }, 'speak the invalid envelope: { error: { code: \"invalid\", message: \"text is required\" } }');\nvar res2 = await worker.fetch(new Request('https://api.me.dev/api/notes', { method: 'POST', body: 'ship it' }), {});\nT.eq(res2.status, 400, 'a body that is not JSON must answer 400, not crash — wrap await request.json() in try/catch');\nT.eq(await res2.json(), { error: { code: 'invalid', message: 'body must be JSON' } }, 'name the actual problem: { error: { code: \"invalid\", message: \"body must be JSON\" } }');\nvar list = await worker.fetch(new Request('https://api.me.dev/api/notes'), {});\nT.eq((await list.json()).length, 1, 'rejected requests must not create anything — the store still holds exactly 1 note');" },
        { text: "The `OPTIONS` preflight approves `DELETE` — then honor the `DELETE` it approved.",
          test: "var pre = await worker.fetch(new Request('https://api.me.dev/api/notes', { method: 'OPTIONS', headers: { origin: 'https://me.github.io' } }), {});\nT.eq(pre.status, 204, 'the preflight answers 204 No Content (a 204 takes a null body)');\nT.eq(pre.headers.get('access-control-allow-origin'), 'https://me.github.io', 'the preflight echoes the allowlisted origin');\nT.expect((pre.headers.get('access-control-allow-methods') || '').indexOf('DELETE') !== -1, 'advertise DELETE in access-control-allow-methods — the browser will not send a verb the preflight never approved');\nvar res = await worker.fetch(new Request('https://api.me.dev/api/notes/1', { method: 'DELETE', headers: { origin: 'https://me.github.io' } }), {});\nT.eq(res.status, 200, 'DELETE /api/notes/1 → 200 — yours answered ' + res.status);\nT.eq(await res.json(), { ok: true }, 'confirm the delete with { ok: true }');\nvar gone = await worker.fetch(new Request('https://api.me.dev/api/notes/1', { method: 'DELETE' }), {});\nT.eq(gone.status, 404, 'deleting the same id twice → 404');\nT.eq(await gone.json(), { error: { code: 'not_found', message: 'note not found' } }, 'the missing-note envelope: { error: { code: \"not_found\", message: \"note not found\" } }');\nvar list = await worker.fetch(new Request('https://api.me.dev/api/notes'), {});\nT.eq(await list.json(), [], 'the store is empty again');" },
        { text: "Every wrong turn gets the **404** envelope — unknown paths and unbuilt verbs alike.",
          test: "var res = await worker.fetch(new Request('https://api.me.dev/api/unicorns'), {});\nT.eq(res.status, 404, 'unknown paths still get an answer');\nT.eq(res.headers.get('content-type'), 'application/json', 'even the 404 speaks JSON');\nT.eq(await res.json(), { error: { code: 'not_found', message: 'no such route' } }, 'one envelope for every failure: { error: { code: \"not_found\", message: \"no such route\" } }');\nvar res2 = await worker.fetch(new Request('https://api.me.dev/api/notes', { method: 'PATCH', body: '{}' }), {});\nT.eq(res2.status, 404, 'a verb you did not build falls through to the same catch-all — PATCH can join the API later');" }
      ],
      files: [
        { name: "script.js", content: "// ===== notes-api — a complete Cloudflare Worker =====\n// Production-shaped: paste this file into a wrangler project (src/index.js) and it deploys.\n//\n// Routes:\n//   GET    /api/health      → 200 { ok: true }\n//   GET    /api/notes       → 200 [ …notes ]\n//   POST   /api/notes       → JSON body { text } → 201 { id, text }   (ids from a counter)\n//                             no usable text     → 400 { error: { code: \"invalid\", message: \"text is required\" } }\n//                             body not JSON      → 400 { error: { code: \"invalid\", message: \"body must be JSON\" } }\n//   DELETE /api/notes/<id>  → 200 { ok: true } | 404 { error: { code: \"not_found\", message: \"note not found\" } }\n//   anything else           → 404 { error: { code: \"not_found\", message: \"no such route\" } }\n//\n// CORS, on EVERY response:\n//   allowlist = (env.ALLOWED_ORIGINS || \"https://me.github.io,http://localhost:5173\").split(\",\")\n//   allowlisted caller → echo its origin in access-control-allow-origin; stranger → no header\n//   OPTIONS preflight  → 204 (null body), CORS headers + access-control-allow-methods: \"GET, POST, DELETE, OPTIONS\"\n\nlet notes = [];\nlet nextId = 1;\n\nfunction json(data, code, extra) {\n  return new Response(JSON.stringify(data), {\n    status: code,\n    headers: Object.assign({ \"content-type\": \"application/json\" }, extra || {})\n  });\n}\n\nexport default {\n  async fetch(request, env, ctx) {\n    // build it route by route — CORS first, preflight early, catch-all 404 last\n  }\n};\n" }
      ],
      hints: [
        "Order of operations inside fetch: parse the URL, compute `cors` from `request.headers.get(\"origin\")` against `(env.ALLOWED_ORIGINS || \"https://me.github.io,http://localhost:5173\").split(\",\")`, answer OPTIONS with the 204 preflight, then route — catch-all 404 as the very last line. Pass `cors` as json's third argument on every return.",
        "The POST branch, validation first: `let body; try { body = await request.json(); } catch (e) { return json({ error: { code: \"invalid\", message: \"body must be JSON\" } }, 400, cors); }` — then the Course 7 text check (`!body || typeof body.text !== \"string\" || body.text.trim() === \"\"`) before touching the store.",
        "DELETE parses the id from the path exactly like the Bookmarks API: `const id = Number(url.pathname.split(\"/\")[3]);` — find it (missing → the note-not-found envelope), then `notes = notes.filter(n => n.id !== id);` and answer `{ ok: true }`."
      ],
      solution: {
        "script.js": "// notes-api — a complete Cloudflare Worker. Deployable as-is.\n\nlet notes = [];\nlet nextId = 1;\n\nfunction json(data, code, extra) {\n  return new Response(JSON.stringify(data), {\n    status: code,\n    headers: Object.assign({ \"content-type\": \"application/json\" }, extra || {})\n  });\n}\n\nexport default {\n  async fetch(request, env, ctx) {\n    const url = new URL(request.url);\n\n    const allowlist = (env.ALLOWED_ORIGINS || \"https://me.github.io,http://localhost:5173\").split(\",\");\n    const caller = request.headers.get(\"origin\");\n    const cors = caller && allowlist.includes(caller)\n      ? { \"access-control-allow-origin\": caller }\n      : {};\n\n    if (request.method === \"OPTIONS\") {\n      return new Response(null, {\n        status: 204,\n        headers: Object.assign({ \"access-control-allow-methods\": \"GET, POST, DELETE, OPTIONS\" }, cors)\n      });\n    }\n\n    if (request.method === \"GET\" && url.pathname === \"/api/health\") {\n      return json({ ok: true }, 200, cors);\n    }\n\n    if (request.method === \"GET\" && url.pathname === \"/api/notes\") {\n      return json(notes, 200, cors);\n    }\n\n    if (request.method === \"POST\" && url.pathname === \"/api/notes\") {\n      let body;\n      try {\n        body = await request.json();\n      } catch (e) {\n        return json({ error: { code: \"invalid\", message: \"body must be JSON\" } }, 400, cors);\n      }\n      if (!body || typeof body.text !== \"string\" || body.text.trim() === \"\") {\n        return json({ error: { code: \"invalid\", message: \"text is required\" } }, 400, cors);\n      }\n      const note = { id: nextId++, text: body.text };\n      notes.push(note);\n      return json(note, 201, cors);\n    }\n\n    if (request.method === \"DELETE\" && url.pathname.startsWith(\"/api/notes/\")) {\n      const id = Number(url.pathname.split(\"/\")[3]);\n      const found = notes.find(n => n.id === id);\n      if (!found) {\n        return json({ error: { code: \"not_found\", message: \"note not found\" } }, 404, cors);\n      }\n      notes = notes.filter(n => n.id !== id);\n      return json({ ok: true }, 200, cors);\n    }\n\n    return json({ error: { code: \"not_found\", message: \"no such route\" } }, 404, cors);\n  }\n};\n"
      }
    },

    {
      id: "ship-quiz-4",
      title: "Unit 4 quiz: Workers & CORS",
      kind: "quiz", xp: 10,
      brief: "The real Worker API — fetch, env, URL, and the CORS handshake. 80% to pass.",
      questions: [
        { q: "Your deployed Worker needs an API key. Where does it live?",
          choices: ["Hardcoded near the top of the file", "In `env`, the second fetch argument", "In a query string the client sends", "In the ctx argument's waitUntil store"],
          answer: 1, explain: "Secrets are stored with `wrangler secret put API_KEY` and arrive at runtime as `env.API_KEY` — the second argument of fetch, same object that carries `[vars]` config. Hardcoding ships the key to anyone who reads the source, and a client-sent query string would mean the client already holds your secret. `ctx` is for lifetime helpers like `waitUntil`, not configuration." },
        { q: "In Course 7, handleRequest returned a plain `{ status, body }` object. A Worker's fetch handler returns…",
          choices: ["The same plain object — the platform converts it", "A string of HTML", "A real Response object", "Nothing — it calls a send() callback instead"],
          answer: 2, explain: "The types are real now: fetch receives a Fetch-API `Request` and must return a `Response` — `new Response(body, { status, headers })`, with the body already a string (`JSON.stringify` it) and the `content-type` declared by you. Nothing converts a plain object for you; returning one breaks the Worker. That fidelity is exactly why this file deploys unmodified." },
        { q: "What does the last line evaluate to?",
          code: "const url = new URL(\"https://api.me.dev/api/notes?limit=2\");\nurl.searchParams.get(\"limit\");",
          lang: "js",
          choices: ["2 (the number)", "\"2\" (a string)", "undefined", "[\"2\"] (an array)"],
          answer: 1, explain: "Everything that rides in a URL is text, so `searchParams.get` always hands back a string — `\"2\" + 1` is `\"21\"`, so `Number()` it before doing math, exactly like Unit 2's env values. A param that isn't present comes back as `null` (not `undefined`), which is what makes the check-before-slice pattern work." },
        { q: "The console says: \"blocked by CORS policy: No 'Access-Control-Allow-Origin' header\". Where does the fix go?",
          choices: ["The server — send access-control-allow-origin for approved origins", "The client — add mode: 'cors' and the right headers to the fetch() call", "The browser — disable its CORS enforcement setting", "The URL — switch the API from http to https"],
          answer: 0, explain: "CORS is the server granting the browser permission to let a cross-origin page read the response — only the server can send `access-control-allow-origin`, so only the server can fix its absence. No `fetch()` option can grant a permission the server didn't give. The request even reaches the server and gets answered; the browser simply withholds the response from the page." },
        { q: "Your Pages site sends a cross-origin DELETE to your Worker. What does the browser do first?",
          choices: ["Sends the DELETE with a special flag attached", "Asks the user for permission", "Refuses immediately — DELETE is never allowed across origins", "Sends an OPTIONS preflight and waits for approval"],
          answer: 3, explain: "Non-simple requests — DELETE, or a POST with a JSON content-type — trigger a preflight: the browser sends `OPTIONS` first, and the server answers `204` with `access-control-allow-methods` naming the verbs it accepts. Only if DELETE is on that list does the real request go out. Cross-origin DELETE is perfectly legal once the preflight approves it; simple GETs skip the preflight entirely." },
        { q: "Why echo the caller's origin from an allowlist instead of answering `access-control-allow-origin: *`?",
          choices: ["An allowlist names who may read the API; * hands that right to any site", "* is invalid syntax in a Worker's Response headers", "Browsers silently ignore * unless the request's origin also happens to match it", "* only works for GET requests and never for POST"],
          answer: 0, explain: "`*` tells every site on the internet it may read your API's responses from its users' browsers — fine for truly public data, wrong the moment anything is user-specific or write-shaped. An allowlist keeps the read grant to the front ends you actually own, and echoing the matching origin is how one server serves several of them (production, localhost, staging). `*` is legal syntax and works for any method; being too permissive is precisely the problem." }
      ]
    }
  ]
});
