/* Deploying Your App — Unit 6: Ship, break, roll back */
window.CODELAB.addUnit("ship", {
  id: "ship-u6",
  title: "Ship, break, roll back",
  icon: "🧯",
  blurb: "Preflight as code, a three-second smoke gate, rollback as a pointer move, and log forensics — the night-of-the-deploy toolkit.",
  cheat: [
    { h: "Preflight, the executable kind", lang: "js", code: "preflight(repo)\n// → [\"absolute-asset-path\", \"missing-index\",\n//    \"secret-in-repo\", \"uppercase-index\"]\n// → []  means ship it", note: "<title>/viewport/description stay on Course 8's hand-walked checklist — these four are the ones a script catches better than eyes." },
    { h: "A /health route earns its keep", lang: "js", code: "if (url.pathname === \"/health\") {\n  return new Response(JSON.stringify({ ok: true }), {\n    status: 200,\n    headers: { \"content-type\": \"application/json\" }\n  });\n}", note: "Four lines. In return: every smoke test, uptime monitor and rollback script gets one URL that answers for the whole build." },
    { h: "Rollback on the real platforms", lang: "js", code: "# Cloudflare Workers\nwrangler deployments list      # find the previous version id\nwrangler rollback [version-id]\n\n# GitHub Pages\ngit revert HEAD    # a new commit that undoes the bad one\ngit push           # Pages redeploys the reverted site", note: "Both are pointer moves — nothing gets deleted. That is exactly why they are safe to run at 2am." },
    { h: "The log signature table", lang: "js", code: "\"only differ in casing\"             → case-mismatch\n\"ENOENT\" + \"index.html\"             → missing-index\n\"is incompatible with this module\"  → node-version\n\"sk_live\" in an artifact            → secret-in-bundle\nanything else                       → unknown (say so!)", note: "Every ops team keeps a table like this, usually in one veteran's head. Yours is now code." },
    { h: "Smoke test ≠ test suite", lang: "js", code: "// deploy gate: 3 checks, seconds, the LIVE build\nawait smokeTest(worker)\n// → { passed: 3, failed: 0, failures: [] }\n\n// deep coverage: hundreds of checks, pre-merge\n// → that is the Testing course", note: "If the gate's report is not readable at a glance during an incident, the gate has failed its own smoke test." }
  ],
  lessons: [

    {
      id: "ship-u6-1",
      title: "The pre-flight check (as code, not a list)",
      kind: "js", chip: "SHIP", xp: 15, mins: 13,
      brief: "Back in the capstone (cap-u6-1) you walked the deploy-ready checklist **by hand**: `<title>`, viewport, description, repo link — checked by eye, once. Eyes don't run on every deploy. Code does. You already wrote the `<head>` checklist by hand; now make the *rest* of it executable.\n\n`preflight(repo)` takes a repo file-map and returns a **sorted array of failure codes** — and the code list is a fixed contract, written before a single check is implemented:\n\n- `missing-index` — no `index.html` at the repo root (the blank-site classic from Unit 1)\n- `uppercase-index` — an `Index.html` posing as the index (Linux will not be fooled)\n- `absolute-asset-path` — `href=\"/…\"` or `src=\"/…\"` in an `.html` file (Unit 1's base-path trap)\n- `secret-in-repo` — `sk_live` or `AKIA` anywhere, in *any* file (Unit 2's cardinal sin)\n\n`[]` means ship it. What preflight deliberately does **not** check: `<title>`, viewport, description, the footer link — head metadata is cap-u6-1's territory and stays a human's job in Course 8.",
      example: { lang: "js", code: "preflight(BROKEN)\n// → [\"absolute-asset-path\", \"missing-index\",\n//    \"secret-in-repo\", \"uppercase-index\"]\npreflight(FIXED)\n// → []   ← the only output that ships" },
      steps: [
        { text: "Write `preflight(repo)` returning the **sorted** array of failure codes. `BROKEN` trips all four alarms.",
          test: "T.expect(typeof preflight === 'function', 'Define function preflight(repo) { … }');\nT.eq(preflight(BROKEN), ['absolute-asset-path', 'missing-index', 'secret-in-repo', 'uppercase-index'], 'BROKEN trips all four checks — return every code that applies, alphabetically sorted (an array plus .sort() gets you there)');" },
        { text: "Each check stands alone — prove it on four tiny repos.",
          test: "T.eq(preflight({ 'index.html': '<h1>hi</h1>' }), [], 'A clean one-file repo passes: empty array, ship it');\nT.eq(preflight({ 'Index.html': '<h1>hi</h1>' }), ['missing-index', 'uppercase-index'], 'Index.html is NOT index.html — GitHub Pages serves from case-sensitive Linux, so this repo has a wrong-case file AND no real index');\nT.eq(preflight({ 'index.html': '<link rel=\"stylesheet\" href=\"/styles.css\">' }), ['absolute-asset-path'], 'href=\"/styles.css\" asks the DOMAIN root — on username.github.io/repo/ that file does not exist (Unit 1, the base-path trap)');\nT.eq(preflight({ 'index.html': '<h1>hi</h1>', 'notes.md': 'the key is sk_live_abc' }), ['secret-in-repo'], 'A secret is a secret in ANY file — even a markdown note gets published with the repo');" },
        { text: "Now fix the patient: edit the `FIXED` object (data, not code) until every alarm clears.",
          test: "T.eq(preflight(FIXED), [], 'FIXED must come back clean: rename to index.html, make both asset paths relative, get the key out of the file');\nT.expect(typeof FIXED['index.html'] === 'string', 'The cure for Index.html is a RENAME to index.html — do not delete the page');\nT.expect(FIXED['index.html'].indexOf('styles.css') !== -1 && FIXED['index.html'].indexOf('app.js') !== -1, 'Keep both asset links — just relative (styles.css), not root-absolute (/styles.css)');\nT.expect(typeof FIXED['config.js'] === 'string' && FIXED['config.js'].indexOf('sk_live') === -1, 'Keep config.js but strip the secret — in the real repo that value moves to an env binding (Unit 2)');\nT.eq(preflight(BROKEN), ['absolute-asset-path', 'missing-index', 'secret-in-repo', 'uppercase-index'], 'Leave BROKEN untouched — it is the before picture');" }
      ],
      files: [
        { name: "script.js", content: "// A repo is a file map: { \"path\": \"file contents\", … }\n// This one is 30 seconds from being pushed. It should not be.\n\nconst BROKEN = {\n  \"Index.html\": \"<!DOCTYPE html>\\n<html>\\n<head>\\n  <title>NoteStream</title>\\n  <link rel=\\\"stylesheet\\\" href=\\\"/styles.css\\\">\\n</head>\\n<body>\\n  <h1>NoteStream</h1>\\n  <script src=\\\"/app.js\\\"></script>\\n</body>\\n</html>\\n\",\n  \"styles.css\": \"body { font-family: system-ui, sans-serif; }\\n\",\n  \"app.js\": \"console.log(\\\"NoteStream booting\\\");\\n\",\n  \"config.js\": \"const STRIPE_KEY = \\\"sk_live_51HneverEver\\\";\\n\"\n};\n\n// Step 3: edit THIS object until preflight(FIXED) returns [].\nconst FIXED = {\n  \"Index.html\": \"<!DOCTYPE html>\\n<html>\\n<head>\\n  <title>NoteStream</title>\\n  <link rel=\\\"stylesheet\\\" href=\\\"/styles.css\\\">\\n</head>\\n<body>\\n  <h1>NoteStream</h1>\\n  <script src=\\\"/app.js\\\"></script>\\n</body>\\n</html>\\n\",\n  \"styles.css\": \"body { font-family: system-ui, sans-serif; }\\n\",\n  \"app.js\": \"console.log(\\\"NoteStream booting\\\");\\n\",\n  \"config.js\": \"const STRIPE_KEY = \\\"sk_live_51HneverEver\\\";\\n\"\n};\n\n// preflight(repo) → SORTED array of failure codes:\n//   \"missing-index\"        no \"index.html\" key at the repo root\n//   \"uppercase-index\"      a key other than \"index.html\" whose .toLowerCase() IS \"index.html\"\n//   \"absolute-asset-path\"  any .html file matching  href=\"/…  or  src=\"/…\n//   \"secret-in-repo\"       any file containing \"sk_live\" or \"AKIA\"\nfunction preflight(repo) {\n  // your code\n}\n" }
      ],
      hints: [
        "Gather codes into an array, then `return problems.sort();` — alphabetical order comes free.",
        "The four checks over `const paths = Object.keys(repo)`: `paths.indexOf(\"index.html\") === -1` → missing-index; `paths.some((p) => p !== \"index.html\" && p.toLowerCase() === \"index.html\")` → uppercase-index; `paths.some((p) => p.endsWith(\".html\") && /(href|src)=\"\\//.test(repo[p]))` → absolute-asset-path; `paths.some((p) => repo[p].includes(\"sk_live\") || repo[p].includes(\"AKIA\"))` → secret-in-repo.",
        "Step 3 edits DATA, not code: in `FIXED`, rename the `\"Index.html\"` key to `\"index.html\"`, drop the leading `/` from both asset paths inside it, and replace the key literal in `config.js` with a read from env."
      ],
      solution: {
        "script.js": "// A repo is a file map: { \"path\": \"file contents\", … }\n// This one is 30 seconds from being pushed. It should not be.\n\nconst BROKEN = {\n  \"Index.html\": \"<!DOCTYPE html>\\n<html>\\n<head>\\n  <title>NoteStream</title>\\n  <link rel=\\\"stylesheet\\\" href=\\\"/styles.css\\\">\\n</head>\\n<body>\\n  <h1>NoteStream</h1>\\n  <script src=\\\"/app.js\\\"></script>\\n</body>\\n</html>\\n\",\n  \"styles.css\": \"body { font-family: system-ui, sans-serif; }\\n\",\n  \"app.js\": \"console.log(\\\"NoteStream booting\\\");\\n\",\n  \"config.js\": \"const STRIPE_KEY = \\\"sk_live_51HneverEver\\\";\\n\"\n};\n\n// Step 3: edit THIS object until preflight(FIXED) returns [].\nconst FIXED = {\n  \"index.html\": \"<!DOCTYPE html>\\n<html>\\n<head>\\n  <title>NoteStream</title>\\n  <link rel=\\\"stylesheet\\\" href=\\\"styles.css\\\">\\n</head>\\n<body>\\n  <h1>NoteStream</h1>\\n  <script src=\\\"app.js\\\"></script>\\n</body>\\n</html>\\n\",\n  \"styles.css\": \"body { font-family: system-ui, sans-serif; }\\n\",\n  \"app.js\": \"console.log(\\\"NoteStream booting\\\");\\n\",\n  \"config.js\": \"const STRIPE_KEY = env.STRIPE_KEY; // the value lives in the platform dashboard, not the repo\\n\"\n};\n\n// preflight(repo) → SORTED array of failure codes:\n//   \"missing-index\"        no \"index.html\" key at the repo root\n//   \"uppercase-index\"      a key other than \"index.html\" whose .toLowerCase() IS \"index.html\"\n//   \"absolute-asset-path\"  any .html file matching  href=\"/…  or  src=\"/…\n//   \"secret-in-repo\"       any file containing \"sk_live\" or \"AKIA\"\nfunction preflight(repo) {\n  const problems = [];\n  const paths = Object.keys(repo);\n  if (paths.indexOf(\"index.html\") === -1) {\n    problems.push(\"missing-index\");\n  }\n  if (paths.some((p) => p !== \"index.html\" && p.toLowerCase() === \"index.html\")) {\n    problems.push(\"uppercase-index\");\n  }\n  if (paths.some((p) => p.endsWith(\".html\") && /(href|src)=\"\\//.test(repo[p]))) {\n    problems.push(\"absolute-asset-path\");\n  }\n  if (paths.some((p) => repo[p].includes(\"sk_live\") || repo[p].includes(\"AKIA\"))) {\n    problems.push(\"secret-in-repo\");\n  }\n  return problems.sort();\n}\n"
      }
    },

    {
      id: "ship-u6-2",
      title: "Smoke tests and /health",
      kind: "js", chip: "SHIP", xp: 15, mins: 13,
      brief: "Your build is uploaded. Is it *alive*? A **smoke test** answers in seconds: hit `/health`, hit one real route, hit one URL that must 404 — and report `{ passed, failed, failures }` where every failure **names what broke**: `'GET /api/notes expected 200, got 500'`, never `'test 2 failed'`.\n\nThe worker up top is given, fully written — a real `export default { async fetch }` file, exactly the shape you ship to Cloudflare (the sandbox aliases it to `worker`). Below it sit two builds from the hall of shame: one whose notes store is down, and one where somebody \"fixed\" 404s with a catch-all 200. Your `async smokeTest(worker)` runs the same three `CHECKS` against whichever build it is handed — one fresh `Request` per check.\n\nSay it plainly: this is a **deploy gate, not a test framework**. No `describe`, no `it`, no assertion library — deep coverage runs before merge and belongs to the Testing course. A gate is three questions, three seconds, one unarguable answer.",
      example: { lang: "js", code: "// the night of the deploy:\nconst report = await smokeTest(worker);\nif (report.failed > 0) {\n  // do NOT flip traffic — read report.failures\n}" },
      steps: [
        { text: "Write `async smokeTest(worker)` and run the gate on the shipping build — three up, zero down.",
          test: "T.expect(typeof smokeTest === 'function', 'Define async function smokeTest(worker) { … }');\nvar report = await smokeTest(worker);\nT.eq(report, { passed: 3, failed: 0, failures: [] }, 'The shipping build clears the gate: { passed: 3, failed: 0, failures: [] } — run each CHECK with a fresh Request and compare res.status to check.expect');" },
        { text: "Gate the broken build — the report **names** the casualty.",
          test: "var report = await smokeTest(brokenNotes);\nT.eq(report.failures, ['GET /api/notes expected 200, got 500'], 'A smoke test names WHAT broke — method, path, expected, got — not just that something did');\nT.eq(report.passed, 2, '/health and the known-404 check still pass — passed counts them');\nT.eq(report.failed, 1, 'failed is the failure count (failures.length)');" },
        { text: "Gate the catch-all build — a 200 in the wrong place is also a failure.",
          test: "var report = await smokeTest(catchAll200);\nT.eq(report.failures, ['GET /definitely-not-a-route expected 404, got 200'], 'A catch-all 200 FAILS the gate: if nonsense gets 200, the router is gone and every client error will look like success');\nT.eq(report.passed, 2, 'The two real routes do answer 200 — only the negative-space check catches this build');\nT.eq(report.failed, 1, 'One casualty, precisely reported');" }
      ],
      files: [
        { name: "script.js", content: "/* THE BUILD YOU ARE SHIPPING — given, already written.\n   In the real repo, this file is byte-for-byte a Cloudflare Worker. */\nexport default {\n  async fetch(request, env, ctx) {\n    const url = new URL(request.url);\n    if (url.pathname === \"/health\") {\n      return new Response(JSON.stringify({ ok: true }), {\n        status: 200, headers: { \"content-type\": \"application/json\" }\n      });\n    }\n    if (url.pathname === \"/api/notes\") {\n      return new Response(JSON.stringify([{ id: 1, text: \"ship it\" }]), {\n        status: 200, headers: { \"content-type\": \"application/json\" }\n      });\n    }\n    return new Response(JSON.stringify({ error: { code: \"not_found\", message: \"no such route\" } }), {\n      status: 404, headers: { \"content-type\": \"application/json\" }\n    });\n  }\n};\n\n/* LAST WEEK'S INCIDENT, preserved in amber: the notes store is down. */\nconst brokenNotes = {\n  async fetch(request) {\n    const url = new URL(request.url);\n    if (url.pathname === \"/health\") {\n      return new Response(JSON.stringify({ ok: true }), {\n        status: 200, headers: { \"content-type\": \"application/json\" }\n      });\n    }\n    if (url.pathname === \"/api/notes\") {\n      return new Response(JSON.stringify({ error: { code: \"db_down\", message: \"notes store unreachable\" } }), {\n        status: 500, headers: { \"content-type\": \"application/json\" }\n      });\n    }\n    return new Response(JSON.stringify({ error: { code: \"not_found\", message: \"no such route\" } }), {\n      status: 404, headers: { \"content-type\": \"application/json\" }\n    });\n  }\n};\n\n/* AND THE ONE WHERE SOMEBODY \"FIXED\" THE 404s… with a catch-all 200. */\nconst catchAll200 = {\n  async fetch(request) {\n    return new Response(\"<h1>NoteStream</h1>\", {\n      status: 200, headers: { \"content-type\": \"text/html\" }\n    });\n  }\n};\n\n// The gate: three checks, in this order.\nconst CHECKS = [\n  { method: \"GET\", path: \"/health\", expect: 200 },\n  { method: \"GET\", path: \"/api/notes\", expect: 200 },\n  { method: \"GET\", path: \"/definitely-not-a-route\", expect: 404 }\n];\n\n// smokeTest(worker) → { passed, failed, failures }\n//   failures entries read:  \"GET /api/notes expected 200, got 500\"\nasync function smokeTest(worker) {\n  // run every CHECK against this worker — one fresh Request each\n}\n" }
      ],
      hints: [
        "Loop the table: `for (const check of CHECKS) { const res = await worker.fetch(new Request(\"https://api.me.dev\" + check.path, { method: check.method })); … }` — a fresh Request per check, never a reused one.",
        "Compare `res.status` to `check.expect`: a match counts as passed; a mismatch pushes `check.method + \" \" + check.path + \" expected \" + check.expect + \", got \" + res.status` onto the failures array.",
        "The report writes itself: `return { passed: passed, failed: failures.length, failures: failures };` — `failed` is just the length."
      ],
      solution: {
        "script.js": "/* THE BUILD YOU ARE SHIPPING — given, already written.\n   In the real repo, this file is byte-for-byte a Cloudflare Worker. */\nexport default {\n  async fetch(request, env, ctx) {\n    const url = new URL(request.url);\n    if (url.pathname === \"/health\") {\n      return new Response(JSON.stringify({ ok: true }), {\n        status: 200, headers: { \"content-type\": \"application/json\" }\n      });\n    }\n    if (url.pathname === \"/api/notes\") {\n      return new Response(JSON.stringify([{ id: 1, text: \"ship it\" }]), {\n        status: 200, headers: { \"content-type\": \"application/json\" }\n      });\n    }\n    return new Response(JSON.stringify({ error: { code: \"not_found\", message: \"no such route\" } }), {\n      status: 404, headers: { \"content-type\": \"application/json\" }\n    });\n  }\n};\n\n/* LAST WEEK'S INCIDENT, preserved in amber: the notes store is down. */\nconst brokenNotes = {\n  async fetch(request) {\n    const url = new URL(request.url);\n    if (url.pathname === \"/health\") {\n      return new Response(JSON.stringify({ ok: true }), {\n        status: 200, headers: { \"content-type\": \"application/json\" }\n      });\n    }\n    if (url.pathname === \"/api/notes\") {\n      return new Response(JSON.stringify({ error: { code: \"db_down\", message: \"notes store unreachable\" } }), {\n        status: 500, headers: { \"content-type\": \"application/json\" }\n      });\n    }\n    return new Response(JSON.stringify({ error: { code: \"not_found\", message: \"no such route\" } }), {\n      status: 404, headers: { \"content-type\": \"application/json\" }\n    });\n  }\n};\n\n/* AND THE ONE WHERE SOMEBODY \"FIXED\" THE 404s… with a catch-all 200. */\nconst catchAll200 = {\n  async fetch(request) {\n    return new Response(\"<h1>NoteStream</h1>\", {\n      status: 200, headers: { \"content-type\": \"text/html\" }\n    });\n  }\n};\n\n// The gate: three checks, in this order.\nconst CHECKS = [\n  { method: \"GET\", path: \"/health\", expect: 200 },\n  { method: \"GET\", path: \"/api/notes\", expect: 200 },\n  { method: \"GET\", path: \"/definitely-not-a-route\", expect: 404 }\n];\n\n// smokeTest(worker) → { passed, failed, failures }\n//   failures entries read:  \"GET /api/notes expected 200, got 500\"\nasync function smokeTest(worker) {\n  const failures = [];\n  let passed = 0;\n  for (const check of CHECKS) {\n    const res = await worker.fetch(new Request(\"https://api.me.dev\" + check.path, { method: check.method }));\n    if (res.status === check.expect) {\n      passed = passed + 1;\n    } else {\n      failures.push(check.method + \" \" + check.path + \" expected \" + check.expect + \", got \" + res.status);\n    }\n  }\n  return { passed: passed, failed: failures.length, failures: failures };\n}\n"
      }
    },

    {
      id: "ship-u6-3",
      title: "Rollback: the previous build is the safety net",
      kind: "js", chip: "SHIP", xp: 15, mins: 13,
      brief: "Deploys fail. The teams that survive them treat deployment as a tiny **state machine**: `{ current, history }`, two functions, two iron rules.\n\n`deploy(state, build)` returns a **new** state: every build enters `history` — even the failures, *especially* the failures — but only a `healthy` build (one that passed its smoke test) becomes `current`. A bad build gets recorded and ignored; users never see it.\n\n`rollback(state)` moves the `current` pointer back to the previous healthy build in history. It deletes nothing and rewrites nothing — which is exactly why it is safe to run at 2am with shaking hands. And because the old state *is* the record you roll back to, both functions return fresh objects instead of mutating their input.\n\nOn the real platforms this is `wrangler rollback` or a `git revert` + push (cheat sheet has both) — the git ritual itself belongs to the Git course.",
      example: { lang: "js", code: "let s = deploy(state, { v: 7, healthy: true });  // v7 live\ns = deploy(s, { v: 8, healthy: false });         // v8 recorded — v7 STILL live\ns = rollback(s);                                 // the pointer steps back" },
      steps: [
        { text: "Write `deploy(state, build)`: healthy builds take over, history records everything, and the input state is never mutated.",
          test: "T.expect(typeof deploy === 'function', 'Define function deploy(state, build) { … }');\nvar s = deploy({ current: null, history: [] }, { v: 1, healthy: true });\nT.eq(s.current, { v: 1, healthy: true }, 'A healthy build becomes current');\nT.eq(s.history, [{ v: 1, healthy: true }], 'And history records it');\ns = deploy(s, { v: 2, healthy: true });\nT.eq(s.current.v, 2, 'Each healthy deploy takes over from the last');\nT.eq(s.history.length, 2, 'History keeps every build, in order');\nvar before = { current: null, history: [] };\ndeploy(before, { v: 9, healthy: true });\nT.eq(before.history.length, 0, 'deploy must return a NEW state, not mutate the old one — the old state IS the record you roll back to (concat, not push)');" },
        { text: "A build that fails its smoke test is recorded — and refused.",
          test: "var s = deploy({ current: null, history: [] }, { v: 1, healthy: true });\ns = deploy(s, { v: 2, healthy: true });\ns = deploy(s, { v: 3, healthy: false });\nT.eq(s.current.v, 2, 'A build that fails its smoke test must NOT become current — users keep getting v2');\nT.eq(s.history.length, 3, 'But the failed build IS still recorded — the postmortem needs the audit trail');\nT.eq(s.history[2], { v: 3, healthy: false }, 'v3 sits in history, marked unhealthy, having never served a request');" },
        { text: "Write `rollback(state)`: the pointer steps back to the previous healthy build — and holds the floor when there is none.",
          test: "T.expect(typeof rollback === 'function', 'Define function rollback(state) { … }');\nvar s = deploy({ current: null, history: [] }, { v: 1, healthy: true });\ns = deploy(s, { v: 2, healthy: true });\ns = deploy(s, { v: 3, healthy: false });\ns = rollback(s);\nT.eq(s.current.v, 1, 'Rollback steps current BACK to the previous HEALTHY build: v3 never went live, so from v2 you land on v1');\nT.eq(s.history.length, 3, 'Rollback moves the current pointer — it never rewrites history');\ns = rollback(s);\nT.eq(s.current.v, 1, 'Nothing healthy exists before v1 — rollback holds the floor instead of crashing mid-incident');" }
      ],
      files: [
        { name: "script.js", content: "/* Deploy state — the whole thing:\n     { current: <build or null>, history: [ every build ever attempted, in order ] }\n   A build:\n     { v: 3, healthy: true }   // healthy = it passed its smoke test\n*/\n\n// deploy(state, build) → a NEW state (never mutate the one you were given!)\n//   • the build ALWAYS goes into history — even a failed one (audit trail)\n//   • it becomes current ONLY if build.healthy is true\nfunction deploy(state, build) {\n  // your code\n}\n\n// rollback(state) → a NEW state:\n//   • current steps BACK to the previous healthy build in history\n//     (the nearest one BEFORE the current one)\n//   • nothing older and healthy? current stays where it is\n//   • history is never rewritten\nfunction rollback(state) {\n  // your code\n}\n" }
      ],
      hints: [
        "deploy is two lines once you see it: `return { current: build.healthy ? build : state.current, history: state.history.concat([build]) };` — `concat` makes a new array, which is the whole no-mutation trick.",
        "rollback: find where current sits with `const at = state.history.indexOf(state.current);`, then walk `for (let i = at - 1; i >= 0; i--)` looking for `state.history[i].healthy` — first hit wins: `return { current: state.history[i], history: state.history };`",
        "No healthy build before it? Fall through to `return { current: state.current, history: state.history };` — holding the floor beats exploding mid-incident."
      ],
      solution: {
        "script.js": "/* Deploy state — the whole thing:\n     { current: <build or null>, history: [ every build ever attempted, in order ] }\n   A build:\n     { v: 3, healthy: true }   // healthy = it passed its smoke test\n*/\n\n// deploy(state, build) → a NEW state (never mutate the one you were given!)\n//   • the build ALWAYS goes into history — even a failed one (audit trail)\n//   • it becomes current ONLY if build.healthy is true\nfunction deploy(state, build) {\n  return {\n    current: build.healthy ? build : state.current,\n    history: state.history.concat([build])\n  };\n}\n\n// rollback(state) → a NEW state:\n//   • current steps BACK to the previous healthy build in history\n//     (the nearest one BEFORE the current one)\n//   • nothing older and healthy? current stays where it is\n//   • history is never rewritten\nfunction rollback(state) {\n  const at = state.history.indexOf(state.current);\n  for (let i = at - 1; i >= 0; i--) {\n    if (state.history[i].healthy) {\n      return { current: state.history[i], history: state.history };\n    }\n  }\n  return { current: state.current, history: state.history };\n}\n"
      }
    },

    {
      id: "ship-u6-4",
      title: "Reading a failed build log",
      kind: "js", chip: "SHIP", xp: 15, mins: 13,
      brief: "The deploy failed and the platform hands you forty lines of log. Reading it is not wizardry — it is **pattern matching against failures you have seen before**, which is exactly the job code does best.\n\n`diagnose(logLines)` scans a log (an array of lines) against the shop's signature table — **first match wins**:\n\n- a line containing `only differ in casing` → `case-mismatch`\n- a line containing both `ENOENT` *and* `index.html` → `missing-index`\n- a line containing `is incompatible with this module` → `node-version`\n- a line containing `sk_live` → `secret-in-bundle`\n- nothing matches → `unknown`\n\nEvery signature is a bug you have already lived: the casing trap was Unit 1, the missing index is preflight's top alarm, the leaked key was Unit 2. And the rule that separates pros from guessers: **when nothing matches, say `unknown` — do not guess.** A confident wrong diagnosis sends the fix to the wrong place; an honest `unknown` sends a human to actually read the log.",
      example: { lang: "js", code: "diagnose(LOG_A) // → \"case-mismatch\"\ndiagnose(LOG_E) // → \"unknown\"  ← an ANSWER,\n                //    not a failure to answer" },
      steps: [
        { text: "Write `diagnose(logLines)` and read the first two logs: a casing casualty and a Node mismatch.",
          test: "T.expect(typeof diagnose === 'function', 'Define function diagnose(logLines) { … }');\nT.eq(diagnose(LOG_A), 'case-mismatch', \"webpack's casing warning is the tell: the build passed on your case-insensitive laptop and died on case-sensitive Linux — scan every line with .some()\");\nT.eq(diagnose(LOG_C), 'node-version', 'The CI machine runs an older Node than the project demands — the signature is the incompatible-engine line');" },
        { text: "Two more: the entry file that never made it, and the key that did.",
          test: "T.eq(diagnose(LOG_B), 'missing-index', 'ENOENT + index.html on one line: the publish step reached for dist/index.html and grabbed air — this needle needs BOTH strings on the SAME line');\nT.eq(diagnose(LOG_D), 'secret-in-bundle', 'sk_live in a build artifact means the secret survived the build — push protection said no so you did not have to say sorry');" },
        { text: "The most important row of the table: when nothing matches, say so.",
          test: "T.eq(diagnose(LOG_E), 'unknown', 'When nothing matches, say unknown — do not guess. A wrong diagnosis sends the fix to the wrong place');\nT.eq(diagnose([]), 'unknown', 'An empty log matches nothing — unknown again, never a crash');\nT.eq(diagnose(['ENOENT: cannot open dist/index.html — an sk_live key was found nearby']), 'missing-index', 'First match WINS: this line carries two signatures, and the table is checked top to bottom');" }
      ],
      files: [
        { name: "script.js", content: "/* Five real-shaped build logs. CI does not write prose — it writes these. */\n\nconst LOG_A = [\n  \"12:03:41 Cloning repository...\",\n  \"12:03:44 Installing dependencies (node_modules restored from cache)\",\n  \"12:03:52 > notestream@1.0.0 build\",\n  \"12:03:52 > webpack --mode production\",\n  \"12:03:58 ERROR in ./src/app.js 3:0-42\",\n  \"12:03:58 Module not found: Error: Can't resolve './components/Header.js'\",\n  \"12:03:58 There are multiple modules with names that only differ in casing.\",\n  \"12:03:59 webpack compiled with 1 error\",\n  \"12:03:59 Build failed with exit code 1\"\n];\n\nconst LOG_B = [\n  \"12:10:02 Cloning repository...\",\n  \"12:10:09 Build completed in 6.4s\",\n  \"12:10:10 Deploying to pages...\",\n  \"12:10:11 Error: ENOENT: no such file or directory, open '/opt/build/dist/index.html'\",\n  \"12:10:11 Deploy failed: the publish directory has no entry file\",\n  \"12:10:11 Build failed with exit code 1\"\n];\n\nconst LOG_C = [\n  \"12:14:30 Cloning repository...\",\n  \"12:14:33 Installing dependencies...\",\n  \"12:14:41 error notestream@1.0.0: The engine node is incompatible with this module.\",\n  \"12:14:41 Expected version >=20.0.0. Got 16.20.2\",\n  \"12:14:41 error Found incompatible module.\",\n  \"12:14:41 Build failed with exit code 1\"\n];\n\nconst LOG_D = [\n  \"12:20:15 Cloning repository...\",\n  \"12:20:22 Build completed in 7.1s\",\n  \"12:20:23 Scanning artifact for secrets...\",\n  \"12:20:24 BLOCKED: dist/app.4f2a91c.js contains a value matching sk_live_*\",\n  \"12:20:24 Push protection: remove the secret, rotate the key, rebuild\",\n  \"12:20:24 Build failed with exit code 1\"\n];\n\nconst LOG_E = [\n  \"12:31:07 Cloning repository...\",\n  \"12:31:15 > webpack --mode production\",\n  \"12:31:58 FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory\",\n  \"12:31:58 Build failed with exit code 1\"\n];\n\n// diagnose(logLines) → one cause code. First match wins, top to bottom:\n//   \"only differ in casing\"                       → \"case-mismatch\"\n//   \"ENOENT\" AND \"index.html\" on the SAME line    → \"missing-index\"\n//   \"is incompatible with this module\"            → \"node-version\"\n//   \"sk_live\"                                     → \"secret-in-bundle\"\n//   nothing matches                               → \"unknown\"  (do NOT guess)\nfunction diagnose(logLines) {\n  // your code\n}\n" }
      ],
      hints: [
        "One `.some()` per row of the table, in table order, each returning its code: `if (logLines.some((line) => line.includes(\"only differ in casing\"))) return \"case-mismatch\";`",
        "The two-needle row wants both strings on ONE line: `logLines.some((line) => line.includes(\"ENOENT\") && line.includes(\"index.html\"))`.",
        "The last line of diagnose is literally `return \"unknown\";` — the most important row in the table."
      ],
      solution: {
        "script.js": "/* Five real-shaped build logs. CI does not write prose — it writes these. */\n\nconst LOG_A = [\n  \"12:03:41 Cloning repository...\",\n  \"12:03:44 Installing dependencies (node_modules restored from cache)\",\n  \"12:03:52 > notestream@1.0.0 build\",\n  \"12:03:52 > webpack --mode production\",\n  \"12:03:58 ERROR in ./src/app.js 3:0-42\",\n  \"12:03:58 Module not found: Error: Can't resolve './components/Header.js'\",\n  \"12:03:58 There are multiple modules with names that only differ in casing.\",\n  \"12:03:59 webpack compiled with 1 error\",\n  \"12:03:59 Build failed with exit code 1\"\n];\n\nconst LOG_B = [\n  \"12:10:02 Cloning repository...\",\n  \"12:10:09 Build completed in 6.4s\",\n  \"12:10:10 Deploying to pages...\",\n  \"12:10:11 Error: ENOENT: no such file or directory, open '/opt/build/dist/index.html'\",\n  \"12:10:11 Deploy failed: the publish directory has no entry file\",\n  \"12:10:11 Build failed with exit code 1\"\n];\n\nconst LOG_C = [\n  \"12:14:30 Cloning repository...\",\n  \"12:14:33 Installing dependencies...\",\n  \"12:14:41 error notestream@1.0.0: The engine node is incompatible with this module.\",\n  \"12:14:41 Expected version >=20.0.0. Got 16.20.2\",\n  \"12:14:41 error Found incompatible module.\",\n  \"12:14:41 Build failed with exit code 1\"\n];\n\nconst LOG_D = [\n  \"12:20:15 Cloning repository...\",\n  \"12:20:22 Build completed in 7.1s\",\n  \"12:20:23 Scanning artifact for secrets...\",\n  \"12:20:24 BLOCKED: dist/app.4f2a91c.js contains a value matching sk_live_*\",\n  \"12:20:24 Push protection: remove the secret, rotate the key, rebuild\",\n  \"12:20:24 Build failed with exit code 1\"\n];\n\nconst LOG_E = [\n  \"12:31:07 Cloning repository...\",\n  \"12:31:15 > webpack --mode production\",\n  \"12:31:58 FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory\",\n  \"12:31:58 Build failed with exit code 1\"\n];\n\n// diagnose(logLines) → one cause code. First match wins, top to bottom:\n//   \"only differ in casing\"                       → \"case-mismatch\"\n//   \"ENOENT\" AND \"index.html\" on the SAME line    → \"missing-index\"\n//   \"is incompatible with this module\"            → \"node-version\"\n//   \"sk_live\"                                     → \"secret-in-bundle\"\n//   nothing matches                               → \"unknown\"  (do NOT guess)\nfunction diagnose(logLines) {\n  if (logLines.some((line) => line.includes(\"only differ in casing\"))) {\n    return \"case-mismatch\";\n  }\n  if (logLines.some((line) => line.includes(\"ENOENT\") && line.includes(\"index.html\"))) {\n    return \"missing-index\";\n  }\n  if (logLines.some((line) => line.includes(\"is incompatible with this module\"))) {\n    return \"node-version\";\n  }\n  if (logLines.some((line) => line.includes(\"sk_live\"))) {\n    return \"secret-in-bundle\";\n  }\n  return \"unknown\";\n}\n"
      }
    },

    {
      id: "ship-quiz-6",
      title: "Unit 6 quiz: Shipping and un-shipping",
      kind: "quiz", xp: 10,
      brief: "Preflight gates, smoke tests, rollback and log forensics. 80% to pass.",
      questions: [
        { q: "preflight() runs on your machine and flags `secret-in-repo` — so the push never happens. Why was that the cheapest possible catch?",
          choices: [
            "Secrets bloat the bundle, so the build would have been noticeably slower",
            "Once pushed, the key is public history — it must be rotated, not just deleted",
            "Nothing serious was at stake — hosting platforms strip secrets out of published files automatically",
            "The API would have rejected any deploy containing a live key with a CORS error"
          ],
          answer: 1, explain: "A pushed secret lives on in history even if a later commit deletes the file, and scrapers watch public pushes in near-real time — so the only real fix is rotating the key, which costs far more than a preflight failure. Catching it before anything leaves your machine turns an incident into a ten-second edit. That is the economics of every gate in this unit: the earlier the failure, the cheaper it is." },
        { q: "Your smoke test hits `/health`, `/api/notes` — and one URL you KNOW does not exist, expecting a 404. What is that third check for?",
          choices: [
            "It warms the platform's cache so real visitors never see a cold 404 page",
            "It measures worst-case latency, because unknown routes exercise the slowest code path",
            "It proves the router still says no — a catch-all 200 would hide every missing route",
            "It confirms the custom 404 page renders with the correct styling"
          ],
          answer: 2, explain: "If nonsense comes back 200, your router or an over-eager fallback is swallowing everything, and clients will happily parse an HTML shell as 'success'. Expecting a 404 verifies the negative space of your API: a healthy build must also know what it does NOT serve. That failure mode is invisible to a gate that only checks real routes — which is exactly why yours checks a fake one." },
        { q: "Read the state, then the call. What is `state.current.v` afterwards?",
          code: "state.history  // [ {v:1, healthy:true}, {v:2, healthy:true}, {v:3, healthy:false} ]\nstate.current  // {v:2, healthy:true}\nstate = rollback(state);",
          lang: "js",
          choices: ["1", "2", "3", "null"],
          answer: 0, explain: "v3 failed its smoke test, so it never became current — traffic stayed on v2 the whole time. Rollback steps the pointer back to the previous HEALTHY build before the current one in history, which is v1. History keeps all three entries untouched; only the pointer moves." },
        { q: "deploy() records the failed v3 in history even though v3 never served a single request. Why keep it?",
          choices: [
            "So the rollback command can restore v3 automatically once the bug that broke it has been fixed",
            "Because history and current must always agree on the latest version number",
            "Deleting entries from a JavaScript array is slow, so appending is the only safe operation",
            "It is the audit trail — a postmortem needs what was attempted, when, and that it failed"
          ],
          answer: 3, explain: "When someone asks 'what happened Tuesday night?', the answer lives in history: v3 was attempted, failed its gate, never went live. Deploy and rollback only ever move the current pointer — rewriting history would erase exactly the evidence you need most on the worst day. Real platforms work the same way: failed deployments stay listed." },
        { q: "The site builds fine on your Windows laptop and dies in CI with this log. What should your `diagnose()` return?",
          code: "ERROR in ./src/app.js\nModule not found: Error: Can't resolve './components/Header.js'\nThere are multiple modules with names that only differ in casing.",
          lang: "js",
          choices: ["`node-version`", "`missing-index`", "`case-mismatch`", "`unknown`"],
          answer: 2, explain: "Windows and macOS file systems match names case-insensitively, so importing `./Header.js` happily finds `header.js` on your laptop — Linux CI matches exactly and refuses. It is the same failure class as Unit 1's `Index.html`: the file exists, the NAME is wrong. The casing warning is the needle your signature table keys on." },
        { q: "A teammate wants to grow the three-check smoke test into the full unit-test suite, 'since it already runs on every deploy'. The best counter?",
          choices: [
            "Unit tests cannot run against a live build, only against source files on disk",
            "Smoke tests have to be written in a different programming language than the app",
            "Adding more checks would make deploys flaky, so the gate must never gain another check no matter what breaks in production",
            "A gate must stay fast and unarguable — deep coverage runs before merge, in the test suite"
          ],
          answer: 3, explain: "The smoke test's one job is a go/no-go answer in seconds, against the live build, at the worst possible hour — every added check makes that answer slower and muddier. Thorough coverage absolutely should exist, but it runs before code merges, in a real test framework with describe/it and assertions: that is the Testing course's territory. Different tools, different moments, both necessary." }
      ]
    }
  ]
});
