/* ============================================================
   Political Academy — glossary
   ------------------------------------------------------------
   Terms that briefings link with [[term]] or [[term-id|label]].
   The id is the slug of the term ("Electoral College" →
   "electoral-college"). Definitions stay short (the validator caps
   them at 60 words), general enough to reuse across countries, and
   neutral: describe what a thing is, not whether it is good.
   ============================================================ */
window.POLITICS.addTerms([
  { id: "1992-consensus", term: "1992 Consensus",
    def: "A formula said to come from 1992 talks between Beijing and Taipei, under which both sides accept there is 'one China' but differ on what it means. Taiwan's KMT accepts it; the DPP rejects it, and Beijing treats acceptance as a condition for dialogue." },
  { id: "abraham-accords", term: "Abraham Accords",
    def: "Agreements brokered by the United States in 2020 under which the UAE, Bahrain, Morocco and later Sudan normalised relations with Israel. Saudi Arabia has said it could join if there is a credible path to a Palestinian state." },
  { id: "article-49-3", term: "Article 49.3",
    def: "A clause of France's constitution that lets the government declare a bill adopted without a vote. Deputies can stop it only by passing a motion of no confidence within 48 hours, which brings the government down." },
  { id: "aukus", term: "AUKUS",
    def: "A 2021 security pact between Australia, the UK and the US. Its main project gives Australia nuclear-powered (not nuclear-armed) submarines: at least three US Virginia-class boats from the 2030s, then a new class built with Britain. It also covers advanced technologies." },
  { id: "blockade", term: "Blockade",
    def: "Using naval or military force to stop ships or goods from entering or leaving a country's ports. Under international law a blockade is generally treated as an act of war." },
  { id: "brics", term: "BRICS",
    def: "A club of large emerging economies named after its first members, Brazil, Russia, India, China and South Africa, since expanded to include Egypt, Ethiopia, Iran, the UAE, Indonesia and others. It presents itself as a voice for the developing world." },
  { id: "bundesrat", term: "Bundesrat",
    def: "Germany's second chamber, made up of members of the 16 state governments. It must approve laws that affect the states' powers or finances, so state elections can change what the federal government can pass." },
  { id: "bundestag", term: "Bundestag",
    def: "Germany's federal parliament, capped at 630 seats since a 2023 reform. It passes laws and the budget and elects the chancellor. Parties need 5% of the national vote to win list seats." },
  { id: "by-election", term: "By-election",
    def: "A special election held to fill a single seat in parliament between general elections, for example after an MP resigns or dies. In the UK, by-elections are often read as tests of the national mood." },
  { id: "central-military-commission", term: "Central Military Commission",
    def: "The body that commands China's armed forces, the People's Liberation Army. It is formally both a Party and a state body, and it is chaired by the Party's leader, currently Xi Jinping, so the army answers to the Party." },
  { id: "checks-and-balances", term: "Checks and balances",
    def: "Tools each branch of government has to limit the others: a veto on laws, the power to confirm or impeach officials, or courts striking down unlawful acts." },
  { id: "coalition-government", term: "Coalition government",
    def: "A government formed by two or more parties because none won a majority alone. The partners share cabinet posts and must keep agreeing, which gives smaller parties leverage." },
  { id: "cohabitation", term: "Cohabitation",
    def: "When a president and the parliamentary majority, or the government it supports, come from rival political camps and must share power. The term comes from France; Poland has a similar arrangement." },
  { id: "cold-war", term: "Cold War",
    def: "The rivalry between the United States and its allies and the Soviet Union and its allies, from the late 1940s to 1991. It was fought through arms races, alliances and proxy wars rather than direct war between the two." },
  { id: "congress", term: "Congress",
    def: "The US national legislature: the House of Representatives (435 members, two-year terms) and the Senate (100 members, six-year terms). It writes laws, sets taxes and spending, and confirms many appointments." },
  { id: "constructive-vote-of-no-confidence", term: "Constructive vote of no confidence",
    def: "A rule, used in Germany and elsewhere, under which parliament can remove the head of government only by electing a successor in the same vote, so a government can't be toppled without a replacement." },
  { id: "core-inflation", term: "Core inflation",
    def: "Inflation measured without food and energy, whose prices jump around. Economists watch it to see the underlying trend in prices." },
  { id: "debt-brake", term: "Debt brake",
    def: "A rule in Germany's constitution, since 2009, that limits federal structural borrowing to 0.35% of GDP a year, with exceptions for emergencies. A 2025 reform exempted most defence spending above 1% of GDP." },
  { id: "devolution", term: "Devolution",
    def: "Handing powers from a central government to regional bodies while keeping ultimate authority at the centre. In the UK, Scotland, Wales and Northern Ireland have had devolved parliaments and governments since 1999." },
  { id: "electoral-college", term: "Electoral College",
    def: "The system that elects the US president. Each state gets electors equal to its seats in Congress (538 in all, including three for Washington, D.C.); almost every state gives all its electors to its popular-vote winner, and 270 wins." },
  { id: "excessive-deficit-procedure", term: "Excessive deficit procedure",
    def: "The EU's process for member states whose budget deficit exceeds 3% of GDP, or whose debt is too high and not falling. The country must present a plan to correct it and faces regular reviews and, in theory, fines." },
  { id: "executive-order", term: "Executive order",
    def: "A written instruction from a president to the government that has the force of law without a vote in the legislature. It must rest on powers the constitution or existing laws already give the president, and courts can strike it down." },
  { id: "federal-reserve", term: "Federal Reserve",
    def: "The central bank of the United States, often called 'the Fed'. It sets short-term interest rates, supervises banks and aims for stable prices and maximum employment. It is designed to be independent of day-to-day politics." },
  { id: "federalism", term: "Federalism",
    def: "A system that divides power between a national government and regional governments (states or provinces), each with powers of its own that the other cannot simply take away." },
  { id: "filibuster", term: "Filibuster",
    def: "In the US Senate, the ability to block a vote on most bills unless 60 of the 100 senators agree to end debate. It means a slim majority usually needs support from the other party." },
  { id: "firewall", term: "Firewall",
    def: "In Germany, the Brandmauer: the mainstream parties' pledge not to govern with, or rely on the votes of, the far-right AfD. Similar 'cordons sanitaires' against the far right have existed in France and Belgium." },
  { id: "first-past-the-post", term: "First past the post",
    def: "A voting system in which each constituency elects one member, and whoever gets the most votes wins, even without a majority. It tends to give big parties more seats than their vote share and to punish small ones." },
  { id: "five-year-plan", term: "Five-Year Plan",
    def: "China's national blueprint for five years of economic and social policy, drafted by the Communist Party and approved by the National People's Congress. The 15th covers 2026–2030." },
  { id: "generic-ballot", term: "Generic ballot",
    def: "A poll question asking which party people would vote for in congressional elections, without naming candidates. It is a rough guide to the national mood." },
  { id: "gerrymandering", term: "Gerrymandering",
    def: "Drawing election district boundaries to favour one party or group, for example by packing opponents into a few districts or spreading them thinly across many." },
  { id: "gilts", term: "Gilts",
    def: "Bonds issued by the UK government to borrow money. The interest rate, or yield, that investors demand on them sets the government's borrowing costs and influences mortgage rates." },
  { id: "guardian-council", term: "Guardian Council",
    def: "A 12-member Iranian body of six clerics chosen by the Supreme Leader and six jurists approved by parliament. It vets every election candidate and can veto laws it finds incompatible with Islam or the constitution." },
  { id: "ieepa", term: "IEEPA",
    def: "The International Emergency Economic Powers Act (1977), a US law letting a president block transactions and freeze assets to deal with an unusual foreign threat during a declared national emergency. In 2026 the Supreme Court ruled it does not allow tariffs." },
  { id: "impeachment", term: "Impeachment",
    def: "A formal charge of wrongdoing against an official. In the US the House impeaches by majority vote and the Senate holds a trial; removal needs two-thirds of senators." },
  { id: "indus-waters-treaty", term: "Indus Waters Treaty",
    def: "A 1960 agreement, brokered by the World Bank, that shares the rivers of the Indus basin between India and Pakistan. It survived three wars; India suspended it in April 2025." },
  { id: "inflation", term: "Inflation",
    def: "The rate at which prices in general rise, usually measured as the change in a price index over the past year." },
  { id: "irgc", term: "IRGC",
    def: "The Islamic Revolutionary Guard Corps, Iran's elite military force, separate from the regular army. It runs the missile programme, the Basij militia and the Quds Force, which supports allied groups abroad, and controls large parts of the economy. It answers to the Supreme Leader." },
  { id: "jcpoa", term: "JCPOA",
    def: "The Joint Comprehensive Plan of Action, the 2015 nuclear deal between Iran and six powers. Iran accepted strict limits on its nuclear programme in exchange for sanctions relief. The US withdrew in 2018, and the deal's UN sanctions were reimposed in 2025." },
  { id: "judicial-review", term: "Judicial review",
    def: "The power of courts to strike down laws or government actions that break the constitution." },
  { id: "lok-sabha", term: "Lok Sabha",
    def: "The lower house of India's parliament, with 543 elected members. The party or coalition that commands a majority, 272 seats, forms the government and chooses the prime minister." },
  { id: "martial-law", term: "Martial law",
    def: "Temporary rule that gives the state and military emergency powers, such as curfews, travel limits and control of broadcasting. In Ukraine it has been in force since February 2022, and the constitution bars national elections while it lasts." },
  { id: "midterm-elections", term: "Midterm elections",
    def: "US congressional elections held halfway through a president's four-year term. All House seats and about a third of Senate seats are contested." },
  { id: "montreux-convention", term: "Montreux Convention",
    def: "A 1936 treaty that gives Turkey control over the Bosphorus and Dardanelles straits. Merchant ships pass freely, but Turkey can restrict warships, and in wartime it can close the straits to the warring navies." },
  { id: "nabu", term: "NABU",
    def: "Ukraine's National Anti-Corruption Bureau, created in 2015 with Western backing to investigate senior officials. It is independent of the government, and its cases go to a specialised prosecutor (SAPO) and a High Anti-Corruption Court." },
  { id: "nato", term: "NATO",
    def: "The North Atlantic Treaty Organization, a military alliance founded in 1949. Its members, now 32 countries in North America and Europe, pledge that an armed attack on one is an attack on all (Article 5)." },
  { id: "opec-plus", term: "OPEC Plus",
    def: "Usually written OPEC+: the alliance of the Organization of the Petroleum Exporting Countries, led by Saudi Arabia, with other producers led by Russia. Together they agree how much oil to pump, which strongly influences world oil prices." },
  { id: "pkk", term: "PKK",
    def: "The Kurdistan Workers' Party, a Kurdish militant group founded by Abdullah Öcalan that waged an armed insurgency against Turkey from 1984. Turkey, the US and the EU list it as a terrorist organisation. It announced its dissolution in May 2025." },
  { id: "polarization", term: "Polarization",
    def: "The drifting apart of political camps, so that people's views on many issues, and their party, line up together and the two sides trust each other less." },
  { id: "preferential-voting", term: "Preferential voting",
    def: "A system in which voters rank candidates in order. If no one wins a majority of first preferences, the last-placed candidate is eliminated and their ballots pass to the next preference, until someone passes 50%. Used for Australia's House of Representatives; also called ranked-choice or instant-runoff voting." },
  { id: "primary-election", term: "Primary election",
    def: "An election within a party to choose its candidate for a later general election. Turnout is usually lower and more partisan, which pulls candidates toward their base." },
  { id: "quad", term: "Quad",
    def: "The Quadrilateral Security Dialogue: an informal grouping of Australia, India, Japan and the United States that meets at leader and minister level on maritime security, technology, health and supply chains. It is not a military alliance; China sees it as aimed at containing it." },
  { id: "rare-earths", term: "Rare earths",
    def: "A group of 17 metals used in powerful magnets, electronics, electric cars and weapons. They are not especially rare in the ground, but China mines most of them and refines the large majority of the world's supply, which gives it leverage in trade disputes." },
  { id: "redistricting", term: "Redistricting",
    def: "Redrawing the boundaries of election districts, usually after a census to balance populations. When done to favour one party, it is called gerrymandering." },
  { id: "rule-of-law", term: "Rule of law",
    def: "The principle that everyone, including the government, is bound by laws applied by independent courts. The EU can withhold funds from members it judges to have weakened it, as it did with Poland and Hungary." },
  { id: "safe", term: "SAFE",
    def: "Security Action for Europe, an EU programme agreed in 2025 that lends member states up to €150 billion on favourable terms to buy weapons and build defence industry, mostly from European suppliers. Poland received the largest allocation." },
  { id: "sanctions", term: "Sanctions",
    def: "Penalties one country or bloc imposes on another country, company or person without going to war: freezing assets, banning trade or cutting access to banks and markets. They aim to change behaviour or raise the cost of it." },
  { id: "section-122", term: "Section 122",
    def: "A part of the US Trade Act of 1974 letting a president impose a temporary import surcharge of up to 15% for up to 150 days to deal with a serious balance-of-payments problem. Longer use needs Congress." },
  { id: "section-232", term: "Section 232",
    def: "A part of the US Trade Expansion Act of 1962 letting a president restrict imports that threaten national security, after a Commerce Department investigation. Used for tariffs on steel, aluminium, cars and other goods." },
  { id: "section-301", term: "Section 301",
    def: "A part of the US Trade Act of 1974 letting the US trade representative act, including with tariffs, against another country's unfair or unreasonable trade practices after an investigation." },
  { id: "sejm", term: "Sejm",
    def: "The lower and more powerful chamber of Poland's parliament, with 460 members elected by proportional representation. It passes laws, approves the government and can override a presidential veto with three-fifths of the votes." },
  { id: "separation-of-powers", term: "Separation of powers",
    def: "Dividing government into separate branches (legislative, executive and judicial) so that no single person or body holds all power." },
  { id: "shadow-fleet", term: "Shadow fleet",
    def: "Hundreds of ageing oil tankers, often with hidden ownership and doubtful insurance, used to carry Russian (and Iranian) oil around Western sanctions and price caps." },
  { id: "snapback", term: "Snapback",
    def: "A mechanism in the 2015 Iran nuclear deal allowing any participant to restore the UN sanctions lifted under it if Iran was judged to be in breach. The UK, France and Germany triggered it in 2025, and the sanctions returned that September." },
  { id: "state-duma", term: "State Duma",
    def: "The lower and more powerful house of Russia's parliament, with 450 members elected every five years. The upper house, the Federation Council, represents the regions." },
  { id: "strait-of-hormuz", term: "Strait of Hormuz",
    def: "The narrow sea passage between Iran and Oman linking the Persian Gulf to the open ocean. Roughly a fifth of the world's oil normally passes through it, so any threat to shipping there moves global prices." },
  { id: "swing-state", term: "Swing state",
    def: "A US state where either party can realistically win, so presidential campaigns concentrate their money and visits there. In 2024 there were seven: Arizona, Georgia, Michigan, Nevada, North Carolina, Pennsylvania and Wisconsin." },
  { id: "tariff", term: "Tariff",
    def: "A tax on imported goods, paid by the importing business when goods cross the border. The cost is often passed on to buyers through higher prices." },
  { id: "technocratic-government", term: "Technocratic government",
    def: "A government led by non-politicians, such as economists or central bankers, usually installed during a crisis when parties can't agree. Italy has had several, led by Carlo Azeglio Ciampi, Mario Monti and Mario Draghi." },
  { id: "two-round-system", term: "Two-round system",
    def: "An electoral system in which, if no candidate wins a majority in the first round, the leading candidates meet in a run-off. France uses it for presidential and parliamentary elections." },
  { id: "verkhovna-rada", term: "Verkhovna Rada",
    def: "Ukraine's single-chamber parliament, with 450 seats. It passes laws and the budget, approves the prime minister and cabinet, and votes every 90 days on extending martial law." },
  { id: "veto", term: "Veto",
    def: "A leader's power to reject a law passed by the legislature. In the US, Congress can override a presidential veto with two-thirds of both chambers." },
  { id: "voting-rights-act", term: "Voting Rights Act",
    def: "A 1965 US law banning racial discrimination in voting. Section 2 lets people challenge election rules and district maps that dilute minority votes; the Supreme Court narrowed it in Louisiana v. Callais (2026)." },
  { id: "war-powers-resolution", term: "War Powers Resolution",
    def: "A 1973 US law requiring the president to notify Congress within 48 hours of sending forces into hostilities and to end them within 60 days (plus 30 to withdraw) unless Congress authorises them." }
]);
