/* ============================================================
   Political Academy — glossary
   ------------------------------------------------------------
   Terms that briefings link with [[term]] or [[term-id|label]].
   The id is the slug of the term ("Electoral College" →
   "electoral-college"). Definitions stay short (the validator caps
   them at 60 words), general enough to reuse across countries, and
   neutral: describe what a thing is, not whether it is good.
   ============================================================ */
window.POLITICS.addTerms([
  { id: "blockade", term: "Blockade",
    def: "Using naval or military force to stop ships or goods from entering or leaving a country's ports. Under international law a blockade is generally treated as an act of war." },
  { id: "checks-and-balances", term: "Checks and balances",
    def: "Tools each branch of government has to limit the others: a veto on laws, the power to confirm or impeach officials, or courts striking down unlawful acts." },
  { id: "cold-war", term: "Cold War",
    def: "The rivalry between the United States and its allies and the Soviet Union and its allies, from the late 1940s to 1991. It was fought through arms races, alliances and proxy wars rather than direct war between the two." },
  { id: "congress", term: "Congress",
    def: "The US national legislature: the House of Representatives (435 members, two-year terms) and the Senate (100 members, six-year terms). It writes laws, sets taxes and spending, and confirms many appointments." },
  { id: "core-inflation", term: "Core inflation",
    def: "Inflation measured without food and energy, whose prices jump around. Economists watch it to see the underlying trend in prices." },
  { id: "electoral-college", term: "Electoral College",
    def: "The system that elects the US president. Each state gets electors equal to its seats in Congress (538 in all, including three for Washington, D.C.); almost every state gives all its electors to its popular-vote winner, and 270 wins." },
  { id: "executive-order", term: "Executive order",
    def: "A written instruction from a president to the government that has the force of law without a vote in the legislature. It must rest on powers the constitution or existing laws already give the president, and courts can strike it down." },
  { id: "federal-reserve", term: "Federal Reserve",
    def: "The central bank of the United States, often called 'the Fed'. It sets short-term interest rates, supervises banks and aims for stable prices and maximum employment. It is designed to be independent of day-to-day politics." },
  { id: "federalism", term: "Federalism",
    def: "A system that divides power between a national government and regional governments (states or provinces), each with powers of its own that the other cannot simply take away." },
  { id: "filibuster", term: "Filibuster",
    def: "In the US Senate, the ability to block a vote on most bills unless 60 of the 100 senators agree to end debate. It means a slim majority usually needs support from the other party." },
  { id: "generic-ballot", term: "Generic ballot",
    def: "A poll question asking which party people would vote for in congressional elections, without naming candidates. It is a rough guide to the national mood." },
  { id: "gerrymandering", term: "Gerrymandering",
    def: "Drawing election district boundaries to favour one party or group, for example by packing opponents into a few districts or spreading them thinly across many." },
  { id: "ieepa", term: "IEEPA",
    def: "The International Emergency Economic Powers Act (1977), a US law letting a president block transactions and freeze assets to deal with an unusual foreign threat during a declared national emergency. In 2026 the Supreme Court ruled it does not allow tariffs." },
  { id: "impeachment", term: "Impeachment",
    def: "A formal charge of wrongdoing against an official. In the US the House impeaches by majority vote and the Senate holds a trial; removal needs two-thirds of senators." },
  { id: "inflation", term: "Inflation",
    def: "The rate at which prices in general rise, usually measured as the change in a price index over the past year." },
  { id: "judicial-review", term: "Judicial review",
    def: "The power of courts to strike down laws or government actions that break the constitution." },
  { id: "midterm-elections", term: "Midterm elections",
    def: "US congressional elections held halfway through a president's four-year term. All House seats and about a third of Senate seats are contested." },
  { id: "nato", term: "NATO",
    def: "The North Atlantic Treaty Organization, a military alliance founded in 1949. Its members, now 32 countries in North America and Europe, pledge that an armed attack on one is an attack on all (Article 5)." },
  { id: "polarization", term: "Polarization",
    def: "The drifting apart of political camps, so that people's views on many issues, and their party, line up together and the two sides trust each other less." },
  { id: "primary-election", term: "Primary election",
    def: "An election within a party to choose its candidate for a later general election. Turnout is usually lower and more partisan, which pulls candidates toward their base." },
  { id: "redistricting", term: "Redistricting",
    def: "Redrawing the boundaries of election districts, usually after a census to balance populations. When done to favour one party, it is called gerrymandering." },
  { id: "section-122", term: "Section 122",
    def: "A part of the US Trade Act of 1974 letting a president impose a temporary import surcharge of up to 15% for up to 150 days to deal with a serious balance-of-payments problem. Longer use needs Congress." },
  { id: "section-232", term: "Section 232",
    def: "A part of the US Trade Expansion Act of 1962 letting a president restrict imports that threaten national security, after a Commerce Department investigation. Used for tariffs on steel, aluminium, cars and other goods." },
  { id: "section-301", term: "Section 301",
    def: "A part of the US Trade Act of 1974 letting the US trade representative act, including with tariffs, against another country's unfair or unreasonable trade practices after an investigation." },
  { id: "separation-of-powers", term: "Separation of powers",
    def: "Dividing government into separate branches (legislative, executive and judicial) so that no single person or body holds all power." },
  { id: "strait-of-hormuz", term: "Strait of Hormuz",
    def: "The narrow sea passage between Iran and Oman linking the Persian Gulf to the open ocean. Roughly a fifth of the world's oil normally passes through it, so any threat to shipping there moves global prices." },
  { id: "swing-state", term: "Swing state",
    def: "A US state where either party can realistically win, so presidential campaigns concentrate their money and visits there. In 2024 there were seven: Arizona, Georgia, Michigan, Nevada, North Carolina, Pennsylvania and Wisconsin." },
  { id: "tariff", term: "Tariff",
    def: "A tax on imported goods, paid by the importing business when goods cross the border. The cost is often passed on to buyers through higher prices." },
  { id: "veto", term: "Veto",
    def: "A leader's power to reject a law passed by the legislature. In the US, Congress can override a presidential veto with two-thirds of both chambers." },
  { id: "voting-rights-act", term: "Voting Rights Act",
    def: "A 1965 US law banning racial discrimination in voting. Section 2 lets people challenge election rules and district maps that dilute minority votes; the Supreme Court narrowed it in Louisiana v. Callais (2026)." },
  { id: "war-powers-resolution", term: "War Powers Resolution",
    def: "A 1973 US law requiring the president to notify Congress within 48 hours of sending forces into hostilities and to end them within 60 days (plus 30 to withdraw) unless Congress authorises them." }
]);
