/* Changing Live Systems — Unit 7: Two projects */
(function () {
  function L() { return Array.prototype.join.call(arguments, "\n"); }

  /* ---- Project 1: name -> first_name + last_name ---- */
  var SPLIT = L(
    "// \"Mary Ann Smith\" -> [\"Mary\", \"Ann Smith\"]; \"Cher\" -> [\"Cher\", \"\"]",
    "function splitName(name) {",
    "  const i = name.indexOf(\" \");",
    "  return i === -1 ? [name, \"\"] : [name.slice(0, i), name.slice(i + 1)];",
    "}",
    "function joinName(first, last) {",
    "  return last ? first + \" \" + last : first;",
    "}");
  var V1 = L(
    "// v1: in production on every server.",
    "function v1(db, req) {",
    "  if (req.op === \"signup\") return db.insert(\"users\", { name: req.name }).id;",
    "  return db.select(\"users\", { id: req.id }, [\"name\"])[0].name;",
    "}");
  var W1 = L(
    "function world(o) {",
    "  o = o || {};",
    "  var FIRST = ['Ada', 'Grace', 'Alan', 'Cher', 'Mary Ann', 'Linus', 'Edsger', 'Barbara'];",
    "  var LAST = ['Lovelace', 'Hopper', 'Turing', '', 'Smith', 'Torvalds', 'van Dijkstra', 'Liskov'];",
    "  function nameFor(i) { var f = FIRST[i % 8], l = LAST[(i * 3) % 8]; return l ? f + ' ' + l : f; }",
    "  var seed = [];",
    "  for (var i = 1; i <= 1500; i++) seed.push({ id: i, name: nameFor(i) });",
    "  var db = T.db({ users: { columns: { id: { notNull: true }, name: { notNull: true } }, rows: seed } });",
    "  var expected = {}, added = [];",
    "  seed.forEach(function (r) { expected[r.id] = r.name; });",
    "  var every = o.signupEvery || 3;",
    "  function traffic(n) {",
    "    if (n % every === 1) return { op: 'signup', name: nameFor(n + 5) };",
    "    var id = added.length && n % 2 ? added[n % added.length] : (n * 53) % 1500 + 1;",
    "    return { op: 'profile', id: id };",
    "  }",
    "  function check(req, res) {",
    "    if (req.op === 'signup') {",
    "      if (typeof res !== 'number') return 'returned ' + JSON.stringify(res) + ' instead of the new user id';",
    "      expected[res] = req.name; added.push(res); return null;",
    "    }",
    "    if (res !== expected[req.id]) return 'showed ' + JSON.stringify(res) + ' for user ' + req.id + ' (expected ' + JSON.stringify(expected[req.id]) + ')';",
    "    return null;",
    "  }",
    "  return { db: db, traffic: traffic, check: check, expected: expected };",
    "}",
    "function apps() {",
    "  T.expect(typeof v2 === 'function' && typeof v3 === 'function', 'Write v2 and v3.');",
    "  return { v1: v1, v2: v2, v3: v3 };",
    "}");

  /* ---- Project 2: retiring price ---- */
  var DATA = L(
    "const ORDERS = {",
    "  o_1: { id: \"o_1\", amountCents: 1999, currency: \"usd\" },",
    "  o_2: { id: \"o_2\", amountCents: 1005, currency: \"eur\" }",
    "};",
    "const LATEST = \"2026-09-01\";            // price became amount + currency",
    "const DEPRECATED_AT = \"2026-09-01T00:00:00Z\";",
    "const SUNSET_AT = \"2027-03-01T00:00:00Z\";",
    "const DOCS = \"https://docs.example.com/migrate-to-amount\";");
  var REQ = "function req(o) { return Object.assign({ orderId: 'o_1', headers: {}, account: { id: 'acct_1', pinnedVersion: '2026-09-01' }, now: '2026-10-05T12:00:00Z' }, o); }";

  window.CODELAB.addUnit("change", {
    id: "change-u7",
    title: "Two projects",
    icon: "🏗️",
    blurb: "Two changes start to finish, graded the way production grades them. Split a column in two on a table too big for one UPDATE, with live traffic and no failed request. Then retire an API field: old clients keep working, hear about it in every response, and get a clear answer once the sunset passes.",
    cheat: [
      { h: "Project 1: the whole pattern", lang: "text", code:
"expand     add the new columns, nullable\n" +
"migrate    deploy v2: write all, read new-or-old\n" +
"           backfill in batches of ≤ 500\n" +
"contract   relax old NOT NULLs, deploy v3: new only\n" +
"           enforce the new NOT NULLs, drop the old column",
        note: "Ask of every step: what does each version still running do now?" },
      { h: "Project 2: one handler, every version", lang: "text", code:
"version = Api-Version header, else the account's pin\n" +
"new      { id, amount, currency }\n" +
"old      { id, price } + Deprecation, Sunset, Link\n" +
"old, after the sunset   410 Gone, with the docs link",
        note: "Clients that never send a version header are on their pinned version, not the newest one." }
    ],
    lessons: [

      {
        id: "change-u7-1",
        title: "Project: split a column, live",
        kind: "js", chip: "PROJECT", project: true, xp: 60, mins: 45, live: true,
        brief: "`users.name` has to become `first_name` and `last_name`, using `splitName()` (provided): the first word, and the rest. `\"Cher\"` has an empty last name.\n\nThere are **1,500** users and 3 servers on `v1`, with signups and profile views arriving throughout. The database cancels any statement touching more than 500 rows.\n\nWrite `v2`, `v3`, your migrations and the `plan`. When the plan has run:\n\n- no request has failed\n- every server runs `v3`, which never mentions `name`\n- `name` is gone, and `first_name` and `last_name` are both **NOT NULL** and right for every user\n\nA profile shows the full name, `joinName(first, last)`.",
        steps: [
          { text: "No request fails while the plan runs.",
            test: L(W1,
              "var w = world();",
              "T.expectRollout({ db: w.db, apps: apps(), start: 'v1', plan: plan, traffic: w.traffic, check: w.check }, 'Your plan');") },
          { text: "Every server ends on v3, and `v3` works without a `name` column.",
            test: L(W1,
              "var w = world();",
              "var r = T.rollout({ db: w.db, apps: apps(), start: 'v1', plan: plan, traffic: w.traffic, check: w.check });",
              "T.expect(r.ok, 'Make the plan run cleanly first.');",
              "T.eq(r.versions.join(','), 'v3,v3,v3', 'Deploy v3 to every server.');",
              "var bare = T.db({ users: { columns: { id: { notNull: true }, first_name: { notNull: true }, last_name: { notNull: true } }, rows: [] } });",
              "var id = v3(bare, { op: 'signup', name: 'Mary Ann Smith' });",
              "T.eq(v3(bare, { op: 'profile', id: id }), 'Mary Ann Smith', 'v3 should sign up and show users with only first_name and last_name.');") },
          { text: "`name` is gone; `first_name` and `last_name` are NOT NULL and right for every user.",
            test: L(W1,
              "var w = world();",
              "var r = T.rollout({ db: w.db, apps: apps(), start: 'v1', plan: plan, traffic: w.traffic, check: w.check });",
              "T.expect(r.ok, 'Make the plan run cleanly first.');",
              "T.expect(w.db.columns('users').indexOf('name') === -1, 'The name column is still there.');",
              "T.expect(w.db.isNotNull('users', 'first_name') && w.db.isNotNull('users', 'last_name'), 'first_name and last_name should both end NOT NULL.');",
              "function ref(n) { var i = n.indexOf(' '); return i === -1 ? [n, ''] : [n.slice(0, i), n.slice(i + 1)]; }",
              "var wrong = w.db.select('users', null, ['id', 'first_name', 'last_name']).filter(function (u) { var p = ref(w.expected[u.id]); return u.first_name !== p[0] || u.last_name !== p[1]; });",
              "T.expect(wrong.length === 0, wrong.length + ' users are split wrongly (user ' + (wrong[0] && wrong[0].id) + ': ' + JSON.stringify(wrong[0]) + ', from ' + JSON.stringify(wrong[0] && w.expected[wrong[0].id]) + ').');") },
          { text: "It also works on a busier day.", hidden: true,
            test: L(W1,
              "var w = world({ signupEvery: 2 });",
              "T.expectRollout({ db: w.db, apps: apps(), start: 'v1', plan: plan, traffic: w.traffic, check: w.check, instances: 5, perTick: 9 }, 'With 5 servers and more signups');") }
        ],
        files: [{ name: "script.js", content: L(
          SPLIT,
          "",
          V1,
          "",
          "// v2: write both shapes, read the new one where it exists.",
          "function v2(db, req) {",
          "}",
          "",
          "// v3: first_name and last_name only.",
          "function v3(db, req) {",
          "}",
          "",
          "const plan = [",
          "];",
          "") }],
        hints: [
          "v2 signs up with { name, first_name, last_name } and reads all three, falling back to name while first_name is null. v3 never mentions name.",
          "Plan: add both columns; deploy v2; backfill in a loop of db.update(\"users\", { first_name: null }, u => …, 500); make name nullable; deploy v3; then set both new columns NOT NULL and drop name."
        ],
        solution: { "script.js": L(
          SPLIT,
          "",
          V1,
          "",
          "// v2: write both shapes, read the new one where it exists.",
          "function v2(db, req) {",
          "  if (req.op === \"signup\") {",
          "    const [first, last] = splitName(req.name);",
          "    return db.insert(\"users\", { name: req.name, first_name: first, last_name: last }).id;",
          "  }",
          "  const u = db.select(\"users\", { id: req.id }, [\"name\", \"first_name\", \"last_name\"])[0];",
          "  return u.first_name == null ? u.name : joinName(u.first_name, u.last_name);",
          "}",
          "",
          "// v3: first_name and last_name only.",
          "function v3(db, req) {",
          "  if (req.op === \"signup\") {",
          "    const [first, last] = splitName(req.name);",
          "    return db.insert(\"users\", { first_name: first, last_name: last }).id;",
          "  }",
          "  const u = db.select(\"users\", { id: req.id }, [\"first_name\", \"last_name\"])[0];",
          "  return joinName(u.first_name, u.last_name);",
          "}",
          "",
          "function expand(db) {",
          "  db.addColumn(\"users\", \"first_name\");",
          "  db.addColumn(\"users\", \"last_name\");",
          "}",
          "",
          "// After v2 is everywhere; resumable, 500 rows at a time.",
          "function backfill(db) {",
          "  let n;",
          "  do {",
          "    n = db.update(\"users\", { first_name: null }, u => {",
          "      const [first, last] = splitName(u.name);",
          "      return { first_name: first, last_name: last };",
          "    }, 500);",
          "  } while (n > 0);",
          "}",
          "",
          "// v3 doesn't write name.",
          "function relaxName(db) {",
          "  db.dropNotNull(\"users\", \"name\");",
          "}",
          "",
          "function contract(db) {",
          "  db.setNotNull(\"users\", \"first_name\");",
          "  db.setNotNull(\"users\", \"last_name\");",
          "  db.dropColumn(\"users\", \"name\");",
          "}",
          "",
          "const plan = [",
          "  { migrate: expand },",
          "  { deploy: \"v2\" },",
          "  { migrate: backfill },",
          "  { migrate: relaxName },",
          "  { deploy: \"v3\" },",
          "  { migrate: contract }",
          "];",
          "") }
      },

      {
        id: "change-u7-2",
        title: "Project: retire a field",
        kind: "js", chip: "PROJECT", project: true, xp: 60, mins: 40,
        brief: "Since version `2026-09-01` an order's money is `amount` (cents) plus `currency`. Older versions get `price`, in dollars. `price` is deprecated as of 2026-09-01 and its sunset is 2027-03-01.\n\nWrite `handle(req)`. A request is `{ orderId, headers, account: { id, pinnedVersion }, now }`. Return `{ status, headers, body }`:\n\n- the version is the `Api-Version` header if sent, otherwise the account's `pinnedVersion`\n- version `2026-09-01` or later: `200`, body `{ id, amount, currency }`, no deprecation headers\n- older: `200`, body `{ id, price }`, with `Deprecation`, `Sunset` and `Link` headers as in Unit 5\n- older, once `now` has reached the sunset: `410`, body `{ error, docs }`\n- an unknown order: `404`, for any version",
        steps: [
          { text: "Current clients get `amount` and `currency`, with no deprecation headers.",
            test: L(REQ,
              "var r = handle(req({ headers: { 'Api-Version': '2026-09-01' } }));",
              "T.eq(r.status, 200);",
              "T.eq(JSON.stringify(r.body), JSON.stringify({ id: 'o_1', amount: 1999, currency: 'usd' }));",
              "T.expect(!r.headers || !('Deprecation' in r.headers), 'Current clients use nothing deprecated: send no Deprecation header.');") },
          { text: "Older clients get `price` in dollars, and the three headers.",
            test: L(REQ,
              "var r = handle(req({ orderId: 'o_2', headers: { 'Api-Version': '2026-03-01' } }));",
              "T.eq(r.status, 200);",
              "T.eq(JSON.stringify(r.body), JSON.stringify({ id: 'o_2', price: 10.05 }));",
              "T.eq(r.headers.Deprecation, '@1788220800', 'Deprecation: @ and the Unix seconds of DEPRECATED_AT.');",
              "T.eq(r.headers.Sunset, 'Mon, 01 Mar 2027 00:00:00 GMT', 'Sunset: SUNSET_AT as an HTTP date.');",
              "T.eq(r.headers.Link, '<https://docs.example.com/migrate-to-amount>; rel=\"deprecation\"; type=\"text/html\"');") },
          { text: "After the sunset, older clients get `410 Gone` with the docs; current clients don't notice.",
            test: L(REQ,
              "var r = handle(req({ headers: { 'Api-Version': '2025-01-01' }, now: '2027-03-01T00:00:00Z' }));",
              "T.eq(r.status, 410, 'At the sunset, the old shape is gone: 410.');",
              "T.eq(r.body.docs, 'https://docs.example.com/migrate-to-amount', 'Tell them where to go: body.docs.');",
              "T.expect(typeof r.body.error === 'string' && r.body.error.length > 0, 'Explain in body.error.');",
              "T.eq(handle(req({ headers: { 'Api-Version': '2026-09-01' }, now: '2027-06-01T00:00:00Z' })).status, 200, 'Current clients are unaffected by the sunset.');",
              "T.eq(handle(req({ headers: { 'Api-Version': '2025-01-01' }, now: '2027-02-28T23:59:59Z' })).status, 200, 'One second before the sunset it still works.');") },
          { text: "An unknown order is `404` for every version.",
            test: L(REQ,
              "T.eq(handle(req({ orderId: 'o_404', headers: { 'Api-Version': '2026-09-01' } })).status, 404);",
              "T.eq(handle(req({ orderId: 'o_404', headers: { 'Api-Version': '2025-01-01' } })).status, 404);") },
          { text: "Clients that send no version get their account's.", hidden: true,
            test: L(REQ,
              "var r = handle(req({ account: { id: 'acct_old', pinnedVersion: '2025-04-12' } }));",
              "T.eq(JSON.stringify(r.body), JSON.stringify({ id: 'o_1', price: 19.99 }), 'A request with no Api-Version header comes from a client pinned to 2025-04-12, which expects price. Sending the newest shape breaks every integration that never set the header, which is most of them.');",
              "T.expect(r.headers && r.headers.Deprecation, 'and it should be told about the deprecation too.');") }
        ],
        files: [{ name: "script.js", content: L(
          DATA,
          "",
          "function handle(req) {",
          "  const order = ORDERS[req.orderId];",
          "  return {",
          "    status: 200,",
          "    headers: {},",
          "    body: { id: order.id, amount: order.amountCents, currency: order.currency }",
          "  };",
          "}",
          "",
          "console.log(handle({ orderId: \"o_1\", headers: { \"Api-Version\": \"2025-01-01\" }, account: { id: \"acct_1\", pinnedVersion: \"2025-01-01\" }, now: \"2026-10-05T12:00:00Z\" }));",
          "") }],
        hints: [
          "Start with const version = req.headers[\"Api-Version\"] || req.account.pinnedVersion. Dated versions compare as strings: version >= LATEST.",
          "Return 404 first if there's no order. For old versions, return 410 when new Date(req.now) >= new Date(SUNSET_AT); otherwise price = amountCents / 100, with the headers from Unit 5's deprecationHeaders."
        ],
        solution: { "script.js": L(
          DATA,
          "",
          "function deprecationHeaders() {",
          "  return {",
          "    Deprecation: \"@\" + Math.floor(new Date(DEPRECATED_AT).getTime() / 1000),",
          "    Sunset: new Date(SUNSET_AT).toUTCString(),",
          "    Link: \"<\" + DOCS + \">; rel=\\\"deprecation\\\"; type=\\\"text/html\\\"\"",
          "  };",
          "}",
          "",
          "function handle(req) {",
          "  // No header means the version the account was pinned to, not the newest.",
          "  const version = req.headers[\"Api-Version\"] || req.account.pinnedVersion;",
          "  const order = ORDERS[req.orderId];",
          "  if (!order) return { status: 404, headers: {}, body: { error: \"No such order\" } };",
          "  if (version >= LATEST) {",
          "    return { status: 200, headers: {}, body: { id: order.id, amount: order.amountCents, currency: order.currency } };",
          "  }",
          "  if (new Date(req.now).getTime() >= new Date(SUNSET_AT).getTime()) {",
          "    return {",
          "      status: 410,",
          "      headers: { Link: deprecationHeaders().Link },",
          "      body: { error: \"price was removed on \" + SUNSET_AT + \"; use Api-Version \" + LATEST + \" and amount\", docs: DOCS }",
          "    };",
          "  }",
          "  return { status: 200, headers: deprecationHeaders(), body: { id: order.id, price: order.amountCents / 100 } };",
          "}",
          "",
          "console.log(handle({ orderId: \"o_1\", headers: { \"Api-Version\": \"2025-01-01\" }, account: { id: \"acct_1\", pinnedVersion: \"2025-01-01\" }, now: \"2026-10-05T12:00:00Z\" }));",
          "") }
      }
    ]
  });
})();
