/* Full-Stack Capstone — Unit 4: Data in & out */
window.CODELAB.addUnit("cap", {
  id: "cap-u4",
  title: "Data in & out",
  icon: "📦",
  blurb: "Round-trip your data — export it for humans, import it defensively, autosave every change, and boot from the right source.",
  cheat: [
    { h: "Export: pretty JSON", lang: "js", code: "JSON.stringify(items)          // valid — one squished line\nJSON.stringify(items, null, 2) // indented, human-readable\n// arg 2 = filter (null = keep everything)\n// arg 3 = indent width", note: "The exact serializer you already use for localStorage — the 2 just adds line breaks for human eyes." },
    { h: "Import: parse defensively", lang: "js", code: "let parsed = null;\ntry {\n  parsed = JSON.parse(pastedText);   // THROWS on bad input\n} catch (err) {\n  importMsg.textContent = \"Invalid JSON — nothing changed.\";\n}\nif (Array.isArray(parsed)) {\n  items = parsed;\n  render();\n}", note: "Two gates: JSON.parse throws on garbage, and valid JSON is not always an array — check the shape too." },
    { h: "Autosave in one line", lang: "js", code: "function render() {\n  // …rebuild the DOM from items…\n  localStorage.setItem(\"packlist\", JSON.stringify(items));\n}", note: "Every mutation already ends in render() — one save there covers add, toggle, delete, import…" },
    { h: "The boot sequence", lang: "js", code: "async function boot() {\n  const stored = JSON.parse(localStorage.getItem(\"packlist\") || \"null\");\n  if (Array.isArray(stored)) {\n    items = stored;                              // restored\n  } else {\n    const res = await api({ method: \"GET\", path: \"/api/items\" });\n    items = res.body;                            // fresh\n    localStorage.setItem(\"packlist\", JSON.stringify(items));\n  }\n  render();\n}" },
    { h: "Deep copy via round-trip", lang: "js", code: "const copy = JSON.parse(JSON.stringify(data));\n// a fully independent clone of plain data\n// (functions and Dates do not survive the trip)", note: "How the in-page server hands out copies instead of its private store." }
  ],
  lessons: [

    {
      id: "cap-u4-1",
      title: "Export as JSON",
      kind: "web", chip: "WEB", xp: 15, mins: 12,
      brief: "Your app's data has been trapped in one browser long enough — time to let it travel. You have serialized with `JSON.stringify` since Unit 1; today it gets a promotion: **export for humans**.\n\n- `JSON.stringify(items)` — valid JSON, one endless line\n- `JSON.stringify(items, null, 2)` — the same data, indented 2 spaces, actually readable\n\nWire the Export button to dump the **live** state into a textarea — copy it, email it, back it up, paste it into next lesson's importer. The checks parse your export right back and deep-compare it against the state: a perfect round-trip or nothing.",
      example: { lang: "js", code: "JSON.stringify(items)          // \"[{\\\"id\\\":1,\\\"text\\\":\\\"Passport\\\"...\" — squished\nJSON.stringify(items, null, 2) // indented — for humans" },
      steps: [
        { text: "Clicking `#exportBtn` fills `#exportBox` with the items as **valid JSON** — an array of 3 objects.",
          test: "T.click('#exportBtn');\nvar raw = T.val('#exportBox') || '';\nT.expect(raw.trim().length > 0, 'Clicking Export should fill the textarea — in the click handler, set exportBox.value.');\nvar parsed = null;\ntry { parsed = JSON.parse(raw); } catch (err) {}\nT.expect(Array.isArray(parsed) && parsed.length === 3, 'The textarea should hold JSON that parses back into the 3-item array — JSON.stringify(items, ...).');\nT.eq(parsed[0].text, 'Passport', 'Export the REAL items — the first one is Passport.');" },
        { text: "It is **pretty-printed**: multiple lines, 2-space indent — exactly `JSON.stringify(items, null, 2)`.",
          test: "var raw = T.val('#exportBox') || '';\nT.expect(raw.indexOf('\\n') !== -1, 'The export should span multiple lines — pass null, 2 as the 2nd and 3rd arguments of JSON.stringify.');\nvar reparsed = null;\ntry { reparsed = JSON.parse(raw); } catch (err) {}\nT.expect(reparsed !== null, 'The textarea content must still be valid, parseable JSON.');\nT.eq(raw, JSON.stringify(reparsed, null, 2), 'Match the standard 2-space format exactly: JSON.stringify(items, null, 2) — argument 2 is a filter (use null), argument 3 is the indent.');" },
        { text: "Export always reflects the **live** state: add *Sunscreen*, export again — the JSON now deep-matches all 4 items, `id: 4` included.",
          test: "T.type('#itemInput', 'Sunscreen');\nT.submit('#itemForm');\nT.click('#exportBtn');\nvar raw = T.val('#exportBox') || '';\nvar parsed = null;\ntry { parsed = JSON.parse(raw); } catch (err) {}\nT.expect(Array.isArray(parsed), 'After the add, a fresh Export click should refill the textarea with valid JSON.');\nT.eq(parsed.length, 4, 'Read items at CLICK time, not at load time — the export should now hold 4 items.');\nT.eq(parsed[3].text, 'Sunscreen', 'The newcomer rides along.');\nT.eq(parsed[3].id, 4, 'Ids come from the nextId counter — Sunscreen is id 4.');\nvar expected = [{ id: 1, text: 'Passport', packed: true }, { id: 2, text: 'Camera', packed: false }, { id: 3, text: 'Headphones', packed: false }, { id: 4, text: 'Sunscreen', packed: false }];\nT.eq(JSON.stringify(parsed), JSON.stringify(expected), 'Deep-compare: the export should match the live state exactly — same objects, same order, same fields.');" }
      ],
      files: [
        { name: "index.html", content: "<!DOCTYPE html>\n<html>\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n  <h1>Packlist 📦</h1>\n\n  <form id=\"itemForm\">\n    <input id=\"itemInput\" placeholder=\"Add gear…\">\n    <button>Add</button>\n  </form>\n\n  <ul id=\"list\"></ul>\n\n  <section class=\"io\">\n    <button id=\"exportBtn\">Export JSON</button>\n    <textarea id=\"exportBox\" rows=\"9\" placeholder=\"Your data appears here…\" spellcheck=\"false\"></textarea>\n  </section>\n\n  <script src=\"script.js\"></script>\n</body>\n</html>\n" },
        { name: "styles.css", content: "body {\n  font-family: Arial, sans-serif;\n  background: #f1f5f9;\n  max-width: 520px;\n  margin: 0 auto;\n  padding: 20px;\n}\nh1 { margin: 8px 0 16px; }\n#itemForm { display: flex; gap: 8px; }\n#itemInput {\n  flex: 1; padding: 10px 12px;\n  border: 2px solid #cbd5e1; border-radius: 10px; font-size: 15px;\n}\n#itemForm button {\n  padding: 10px 16px; border: none; border-radius: 10px;\n  background: #f59e0b; color: white; font-weight: bold; cursor: pointer;\n}\n#list { list-style: none; padding: 0; }\n#list li {\n  background: white; margin-top: 8px; padding: 12px 14px;\n  border-radius: 10px; display: flex; justify-content: space-between; gap: 8px;\n}\n#list li.packed { opacity: 0.6; }\n.io { margin-top: 18px; display: grid; gap: 8px; }\n#exportBtn {\n  justify-self: start;\n  padding: 8px 14px; border: none; border-radius: 10px;\n  background: #0ea5e9; color: white; font-weight: bold; cursor: pointer;\n}\n#exportBox {\n  width: 100%; box-sizing: border-box;\n  font-family: monospace; font-size: 12px;\n  border: 2px solid #cbd5e1; border-radius: 10px; padding: 10px;\n}\n" },
        { name: "script.js", content: "const itemForm = document.querySelector(\"#itemForm\");\nconst itemInput = document.querySelector(\"#itemInput\");\nconst listEl = document.querySelector(\"#list\");\nconst exportBtn = document.querySelector(\"#exportBtn\");\nconst exportBox = document.querySelector(\"#exportBox\");\n\nlet items = [\n  { id: 1, text: \"Passport\", packed: true },\n  { id: 2, text: \"Camera\", packed: false },\n  { id: 3, text: \"Headphones\", packed: false }\n];\nlet nextId = 4;\n\nfunction render() {\n  listEl.innerHTML = \"\";\n  items.forEach((item) => {\n    const li = document.createElement(\"li\");\n    li.textContent = item.text + (item.packed ? \" ✓\" : \"\");\n    if (item.packed) li.classList.add(\"packed\");\n    listEl.appendChild(li);\n  });\n}\n\nitemForm.addEventListener(\"submit\", (e) => {\n  e.preventDefault();\n  const text = itemInput.value.trim();\n  if (!text) return;\n  items.push({ id: nextId, text: text, packed: false });\n  nextId = nextId + 1;\n  itemInput.value = \"\";\n  render();\n});\n\n// 1) when #exportBtn is clicked:\n//    exportBox.value = the items array as pretty JSON\n//    (JSON.stringify with null and 2 — read items INSIDE the handler,\n//     so the export always shows the current state)\n\nrender();\n" }
      ],
      hints: [
        "The whole feature is one listener: `exportBtn.addEventListener(\"click\", () => { exportBox.value = JSON.stringify(items, null, 2); });`",
        "The extra arguments: slot 2 is a filter — pass `null` to keep everything; slot 3 is the indent width. `JSON.stringify(items)` alone is valid JSON but fails the pretty-print check.",
        "Read `items` INSIDE the handler. If you build the string once at load, the export goes stale the moment the list changes."
      ],
      solution: {
        "script.js": "const itemForm = document.querySelector(\"#itemForm\");\nconst itemInput = document.querySelector(\"#itemInput\");\nconst listEl = document.querySelector(\"#list\");\nconst exportBtn = document.querySelector(\"#exportBtn\");\nconst exportBox = document.querySelector(\"#exportBox\");\n\nlet items = [\n  { id: 1, text: \"Passport\", packed: true },\n  { id: 2, text: \"Camera\", packed: false },\n  { id: 3, text: \"Headphones\", packed: false }\n];\nlet nextId = 4;\n\nfunction render() {\n  listEl.innerHTML = \"\";\n  items.forEach((item) => {\n    const li = document.createElement(\"li\");\n    li.textContent = item.text + (item.packed ? \" ✓\" : \"\");\n    if (item.packed) li.classList.add(\"packed\");\n    listEl.appendChild(li);\n  });\n}\n\nitemForm.addEventListener(\"submit\", (e) => {\n  e.preventDefault();\n  const text = itemInput.value.trim();\n  if (!text) return;\n  items.push({ id: nextId, text: text, packed: false });\n  nextId = nextId + 1;\n  itemInput.value = \"\";\n  render();\n});\n\nexportBtn.addEventListener(\"click\", () => {\n  exportBox.value = JSON.stringify(items, null, 2);\n});\n\nrender();\n"
      }
    },

    {
      id: "cap-u4-2",
      title: "Import from JSON",
      kind: "web", chip: "WEB", xp: 15, mins: 14,
      brief: "Export's twin is trickier, because **any text can arrive**: perfect JSON, half-deleted JSON, or `{\"sneaky\": true}` — valid JSON that is not remotely an array. The import rules, non-negotiable:\n\n1. `JSON.parse` inside `try/catch` — it **throws** on bad input, it never returns an error\n2. parsed fine? still check `Array.isArray(parsed)`\n3. only then: replace `items`, `render()`, celebrate in `#importMsg`\n\nAnd the golden rule: a failed import changes **nothing** — parse into a temp variable first, touch state last. The checks feed you the good, the bad, and the sneaky.",
      example: { lang: "js", code: "try {\n  parsed = JSON.parse(pastedText);\n} catch (err) {\n  // bad JSON lands HERE — old state untouched\n}" },
      steps: [
        { text: "Pasting a valid 2-item array and clicking `#importBtn` **replaces** the list — and `#importMsg` confirms (e.g. *Imported 2 items.*).",
          test: "T.$('#importBox').value = JSON.stringify([{ id: 1, text: 'Tent', packed: false }, { id: 2, text: 'Stove', packed: true }]);\nT.click('#importBtn');\nT.eq(T.count('#list li'), 2, 'A valid 2-item array should REPLACE the 3 seeded items — items = parsed, then render().');\nT.expect((T.text('#list') || '').toLowerCase().indexOf('tent') !== -1, 'The imported Tent should be on screen.');\nT.eq(items.length, 2, 'The items array itself now holds the imported data.');\nT.expect((T.text('#importMsg') || '').toLowerCase().indexOf('imported') !== -1, 'Confirm success in #importMsg — e.g. \"Imported 2 items.\"');" },
        { text: "Broken JSON (`{\"oops\": no quotes}`) shows a message containing **Invalid** — and the page and state stay exactly as they were.",
          test: "T.$('#importBox').value = '{\"oops\": no quotes}';\nT.click('#importBtn');\nT.expect((T.text('#importMsg') || '').toLowerCase().indexOf('invalid') !== -1, 'JSON.parse THROWS on bad JSON — catch it and show a message containing \"Invalid\".');\nT.eq(T.count('#list li'), 2, 'A failed import must leave the page exactly as it was — 2 items.');\nT.eq(items.length, 2, 'And the items array untouched — parse into a temp variable, assign to items only on success.');\nT.expect((T.text('#list') || '').toLowerCase().indexOf('tent') !== -1, 'Tent and Stove should still be here.');" },
        { text: "Valid JSON that is **not an array** (`{\"sneaky\": true}`) gets rejected too — `Array.isArray` is the bouncer.",
          test: "T.$('#importBox').value = JSON.stringify({ sneaky: true });\nT.click('#importBtn');\nT.expect((T.text('#importMsg') || '').toLowerCase().indexOf('invalid') !== -1, 'This parses without throwing — but it is an object, not an array. Check Array.isArray(parsed) and reject it.');\nT.eq(items.length, 2, 'State stays untouched by the sneaky object.');\nT.eq(T.count('#list li'), 2, 'The list holds steady at 2.');" },
        { text: "Back on the happy path: a good 3-item import works — and the **success message replaces the error**.",
          test: "T.$('#importBox').value = JSON.stringify([{ id: 1, text: 'Tent', packed: false }, { id: 2, text: 'Stove', packed: true }, { id: 3, text: 'Lantern', packed: false }]);\nT.click('#importBtn');\nT.eq(T.count('#list li'), 3, '3 items in, 3 rendered.');\nT.expect((T.text('#list') || '').toLowerCase().indexOf('lantern') !== -1, 'Lantern made the trip.');\nvar m = (T.text('#importMsg') || '').toLowerCase();\nT.expect(m.indexOf('imported') !== -1 && m.indexOf('invalid') === -1, 'A successful import should overwrite the old error with the success message.');" }
      ],
      files: [
        { name: "index.html", content: "<!DOCTYPE html>\n<html>\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n  <h1>Packlist 📦</h1>\n\n  <ul id=\"list\"></ul>\n\n  <section class=\"io\">\n    <label for=\"importBox\">Paste JSON</label>\n    <textarea id=\"importBox\" rows=\"9\" placeholder='[{\"id\":1,\"text\":\"Tent\",\"packed\":false}]' spellcheck=\"false\"></textarea>\n    <button id=\"importBtn\">Import</button>\n    <p id=\"importMsg\"></p>\n  </section>\n\n  <script src=\"script.js\"></script>\n</body>\n</html>\n" },
        { name: "styles.css", content: "body {\n  font-family: Arial, sans-serif;\n  background: #f1f5f9;\n  max-width: 520px;\n  margin: 0 auto;\n  padding: 20px;\n}\nh1 { margin: 8px 0 16px; }\n#list { list-style: none; padding: 0; }\n#list li {\n  background: white; margin-top: 8px; padding: 12px 14px;\n  border-radius: 10px; display: flex; justify-content: space-between; gap: 8px;\n}\n#list li.packed { opacity: 0.6; }\n.io { margin-top: 18px; display: grid; gap: 8px; }\n.io label { font-size: 13px; font-weight: bold; color: #64748b; }\n#importBox {\n  width: 100%; box-sizing: border-box;\n  font-family: monospace; font-size: 12px;\n  border: 2px solid #cbd5e1; border-radius: 10px; padding: 10px;\n}\n#importBtn {\n  justify-self: start;\n  padding: 8px 14px; border: none; border-radius: 10px;\n  background: #0ea5e9; color: white; font-weight: bold; cursor: pointer;\n}\n#importMsg { margin: 0; font-size: 14px; color: #64748b; min-height: 18px; }\n" },
        { name: "script.js", content: "const listEl = document.querySelector(\"#list\");\nconst importBox = document.querySelector(\"#importBox\");\nconst importBtn = document.querySelector(\"#importBtn\");\nconst importMsg = document.querySelector(\"#importMsg\");\n\nlet items = [\n  { id: 1, text: \"Passport\", packed: true },\n  { id: 2, text: \"Camera\", packed: false },\n  { id: 3, text: \"Headphones\", packed: false }\n];\n\nfunction render() {\n  listEl.innerHTML = \"\";\n  items.forEach((item) => {\n    const li = document.createElement(\"li\");\n    li.textContent = item.text + (item.packed ? \" ✓\" : \"\");\n    if (item.packed) li.classList.add(\"packed\");\n    listEl.appendChild(li);\n  });\n}\n\n// on #importBtn click:\n// 1) try { parsed = JSON.parse(importBox.value) } catch → importMsg shows\n//    \"Invalid JSON — nothing changed.\" and STOP (state untouched)\n// 2) parsed but not Array.isArray(parsed)? → importMsg shows\n//    \"Invalid JSON — expected an array.\" and STOP\n// 3) all good → items = parsed; importMsg: \"Imported N items.\"; render()\n\nrender();\n" }
      ],
      hints: [
        "Parse into a temp: `let parsed = null; try { parsed = JSON.parse(importBox.value); } catch (err) { importMsg.textContent = \"Invalid JSON — nothing changed.\"; return; }` — the `return` is what protects your state.",
        "Then the shape check: `if (!Array.isArray(parsed)) { importMsg.textContent = \"Invalid JSON — expected an array.\"; return; }`",
        "Happy path last: `items = parsed; importMsg.textContent = \"Imported \" + items.length + \" items.\"; render();` — state changes only after every guard has passed."
      ],
      solution: {
        "script.js": "const listEl = document.querySelector(\"#list\");\nconst importBox = document.querySelector(\"#importBox\");\nconst importBtn = document.querySelector(\"#importBtn\");\nconst importMsg = document.querySelector(\"#importMsg\");\n\nlet items = [\n  { id: 1, text: \"Passport\", packed: true },\n  { id: 2, text: \"Camera\", packed: false },\n  { id: 3, text: \"Headphones\", packed: false }\n];\n\nfunction render() {\n  listEl.innerHTML = \"\";\n  items.forEach((item) => {\n    const li = document.createElement(\"li\");\n    li.textContent = item.text + (item.packed ? \" ✓\" : \"\");\n    if (item.packed) li.classList.add(\"packed\");\n    listEl.appendChild(li);\n  });\n}\n\nimportBtn.addEventListener(\"click\", () => {\n  let parsed = null;\n  try {\n    parsed = JSON.parse(importBox.value);\n  } catch (err) {\n    importMsg.textContent = \"Invalid JSON — nothing changed.\";\n    return;\n  }\n  if (!Array.isArray(parsed)) {\n    importMsg.textContent = \"Invalid JSON — expected an array.\";\n    return;\n  }\n  items = parsed;\n  importMsg.textContent = \"Imported \" + items.length + \" items.\";\n  render();\n});\n\nrender();\n"
      }
    },

    {
      id: "cap-u4-3",
      title: "Autosave",
      kind: "web", chip: "WEB", xp: 15, mins: 12,
      brief: "In Unit 1 you sprinkled `save()` after every mutation — and it worked, but every new feature was one more chance to forget the sprinkle. Here is the pro move: in a state-driven app, **every mutation already ends in `render()`**. Add, toggle, delete, import — all roads lead there. So put ONE `save()` where all roads end, and autosave falls out for free.\n\nWrite `save()` — the items as JSON under the key `\"packlist\"` — and make sure storage is fresh after **every single change**. The checks mutate through the UI, then read storage cold.",
      example: { lang: "js", code: "// every mutation calls render() anyway…\nfunction render() {\n  // …rebuild the DOM…\n  save();   // …so autosave is ONE line\n}" },
      steps: [
        { text: "Write `save()` and wire the autosave: after adding *Sunscreen*, the JSON stored under `\"packlist\"` holds all 4 items.",
          test: "T.type('#itemInput', 'Sunscreen');\nT.submit('#itemForm');\nvar stored = JSON.parse(localStorage.getItem('packlist') || 'null');\nT.expect(Array.isArray(stored), 'Nothing reached storage — save() should localStorage.setItem(\"packlist\", JSON.stringify(items)), and it must actually RUN on every change (the end of render() is the one spot that covers them all).');\nT.eq(stored.length, 4, 'After one add, storage should hold all 4 items.');\nT.eq(stored[3].text, 'Sunscreen', 'Including the newcomer.');\nT.eq(stored[3].id, 4, 'With its counter-issued id 4.');" },
        { text: "Toggling an item saves too: mark *Camera* packed — the stored copy shows `packed: true`.",
          test: "T.$$('#list li')[1].click();\nvar stored = JSON.parse(localStorage.getItem('packlist') || '[]');\nT.expect(stored[1] && stored[1].packed === true, 'Toggling must hit storage as well — after clicking Camera, its stored copy should read packed: true. If you sprinkled save() by hand, did you cover the toggle path?');" },
        { text: "Deleting saves as well: remove *Passport* — storage drops to 3, led by *Camera*.",
          test: "T.click('#list li .del');\nvar stored = JSON.parse(localStorage.getItem('packlist') || '[]');\nT.eq(stored.length, 3, 'Deleting must save too — 3 items should remain in storage.');\nT.eq(stored[0].text, 'Camera', 'Passport is gone, so Camera leads the stored list.');\nT.expect(stored[0].packed === true, 'And Camera keeps the packed flag from the last step.');" }
      ],
      files: [
        { name: "index.html", content: "<!DOCTYPE html>\n<html>\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n  <h1>Packlist 📦</h1>\n\n  <form id=\"itemForm\">\n    <input id=\"itemInput\" placeholder=\"Add gear…\">\n    <button>Add</button>\n  </form>\n\n  <ul id=\"list\"></ul>\n\n  <script src=\"script.js\"></script>\n</body>\n</html>\n" },
        { name: "styles.css", content: "body {\n  font-family: Arial, sans-serif;\n  background: #f1f5f9;\n  max-width: 520px;\n  margin: 0 auto;\n  padding: 20px;\n}\nh1 { margin: 8px 0 16px; }\n#itemForm { display: flex; gap: 8px; }\n#itemInput {\n  flex: 1; padding: 10px 12px;\n  border: 2px solid #cbd5e1; border-radius: 10px; font-size: 15px;\n}\n#itemForm button {\n  padding: 10px 16px; border: none; border-radius: 10px;\n  background: #f59e0b; color: white; font-weight: bold; cursor: pointer;\n}\n#list { list-style: none; padding: 0; }\n#list li {\n  background: white; margin-top: 8px; padding: 12px 14px;\n  border-radius: 10px; display: flex; justify-content: space-between; gap: 8px;\n  cursor: pointer;\n}\n#list li.packed { opacity: 0.6; }\n.del { border: none; background: none; color: #ef4444; font-weight: bold; cursor: pointer; }\n" },
        { name: "script.js", content: "const itemForm = document.querySelector(\"#itemForm\");\nconst itemInput = document.querySelector(\"#itemInput\");\nconst listEl = document.querySelector(\"#list\");\n\nlet items = [\n  { id: 1, text: \"Passport\", packed: true },\n  { id: 2, text: \"Camera\", packed: false },\n  { id: 3, text: \"Headphones\", packed: false }\n];\nlet nextId = 4;\n\n// 1) function save() → write items as JSON under the key \"packlist\"\n\nfunction render() {\n  listEl.innerHTML = \"\";\n  items.forEach((item, index) => {\n    const li = document.createElement(\"li\");\n    li.textContent = item.text + (item.packed ? \" ✓\" : \"\");\n    if (item.packed) li.classList.add(\"packed\");\n    li.addEventListener(\"click\", () => {\n      items[index].packed = !items[index].packed;\n      render();\n    });\n\n    const del = document.createElement(\"button\");\n    del.className = \"del\";\n    del.textContent = \"✕\";\n    del.addEventListener(\"click\", (e) => {\n      e.stopPropagation();\n      items.splice(index, 1);\n      render();\n    });\n    li.appendChild(del);\n\n    listEl.appendChild(li);\n  });\n  // 2) autosave: every mutation above ends here —\n  //    ONE save() call on this line covers add, toggle AND delete\n}\n\nitemForm.addEventListener(\"submit\", (e) => {\n  e.preventDefault();\n  const text = itemInput.value.trim();\n  if (!text) return;\n  items.push({ id: nextId, text: text, packed: false });\n  nextId = nextId + 1;\n  itemInput.value = \"\";\n  render();\n});\n\nrender();\n" }
      ],
      hints: [
        "`function save() { localStorage.setItem(\"packlist\", JSON.stringify(items)); }` — arrays cannot enter storage raw; JSON is the ticket.",
        "Every mutation in this app finishes with `render()` — so a single `save()` on the last line of `render()` covers add, toggle, and delete at once.",
        "Prefer sprinkling `save()` into each handler instead? Also fine — the checks only care that storage is up to date after every change."
      ],
      solution: {
        "script.js": "const itemForm = document.querySelector(\"#itemForm\");\nconst itemInput = document.querySelector(\"#itemInput\");\nconst listEl = document.querySelector(\"#list\");\n\nlet items = [\n  { id: 1, text: \"Passport\", packed: true },\n  { id: 2, text: \"Camera\", packed: false },\n  { id: 3, text: \"Headphones\", packed: false }\n];\nlet nextId = 4;\n\nfunction save() {\n  localStorage.setItem(\"packlist\", JSON.stringify(items));\n}\n\nfunction render() {\n  listEl.innerHTML = \"\";\n  items.forEach((item, index) => {\n    const li = document.createElement(\"li\");\n    li.textContent = item.text + (item.packed ? \" ✓\" : \"\");\n    if (item.packed) li.classList.add(\"packed\");\n    li.addEventListener(\"click\", () => {\n      items[index].packed = !items[index].packed;\n      render();\n    });\n\n    const del = document.createElement(\"button\");\n    del.className = \"del\";\n    del.textContent = \"✕\";\n    del.addEventListener(\"click\", (e) => {\n      e.stopPropagation();\n      items.splice(index, 1);\n      render();\n    });\n    li.appendChild(del);\n\n    listEl.appendChild(li);\n  });\n  save();\n}\n\nitemForm.addEventListener(\"submit\", (e) => {\n  e.preventDefault();\n  const text = itemInput.value.trim();\n  if (!text) return;\n  items.push({ id: nextId, text: text, packed: false });\n  nextId = nextId + 1;\n  itemInput.value = \"\";\n  render();\n});\n\nrender();\n"
      }
    },

    {
      id: "cap-u4-4",
      title: "The boot sequence",
      kind: "web", chip: "WEB", xp: 15, mins: 12,
      brief: "The final round-trip question: when the page wakes up, **where does the data come from?** You have built both answers — localStorage (this browser's copy, instant) and the server (the source of truth). `boot()` picks:\n\n- something stored? use it → `#bootSource` says **restored**\n- nothing yet? `await` the server GET, save what arrives for next time → **fresh**\n\nThe SERVER section below is exactly what you built in Back-End Foundations — it lives in this same file so you can see both halves at once. The checks run your boot three ways: cold start, seeded storage, cleared storage.",
      example: { lang: "js", code: "const stored = JSON.parse(localStorage.getItem(\"packlist\") || \"null\");\n// stored array?  → restore it (instant, works offline)\n// nothing there? → await the server, then save for next time" },
      steps: [
        { text: "Cold start: storage is empty, so `boot()` awaits `GET /api/items`, renders the server's 3 items, and `#bootSource` contains **fresh**.",
          test: "await T.sleep(300);\nT.eq(T.count('#list li'), 3, 'First visit: nothing is stored, so boot() should await api({ method: \"GET\", path: \"/api/items\" }) and render its 3 items.');\nT.expect((T.text('#list') || '').toLowerCase().indexOf('passport') !== -1, 'The server seed (Passport & co) should be on screen.');\nT.expect((T.text('#bootSource') || '').toLowerCase().indexOf('fresh') !== -1, 'Tell the user where the data came from — #bootSource should contain \"fresh\".');" },
        { text: "The server section is a **real server function**: `GET /api/items` answers `200` with the array; unknown routes answer `404`.",
          test: "var res = await api({ method: 'GET', path: '/api/items' });\nT.eq(res.status, 200, 'GET /api/items should answer status 200 — the SERVER section is a function you can call directly.');\nT.expect(Array.isArray(res.body) && res.body.length === 3, 'Its body is the 3-item array.');\nvar missing = await api({ method: 'GET', path: '/api/nope' });\nT.eq(missing.status, 404, 'Unknown routes answer 404 with an error envelope — keep the catch-all return in handleRequest.');" },
        { text: "Restored path: with data already in storage, `boot()` uses **it** — no server needed — and `#bootSource` contains **restored**.",
          test: "localStorage.setItem('packlist', JSON.stringify([{ id: 7, text: 'Tent', packed: false }, { id: 8, text: 'Stove', packed: true }]));\nawait boot();\nawait T.sleep(150);\nT.eq(T.count('#list li'), 2, 'With an array in storage, boot() must use IT — expected the 2 stored items, not the server seed.');\nT.expect((T.text('#list') || '').toLowerCase().indexOf('tent') !== -1, 'The restored Tent should render.');\nT.expect((T.text('#bootSource') || '').toLowerCase().indexOf('restored') !== -1, '#bootSource should now contain \"restored\".');" },
        { text: "Clear storage, boot again: back to **fresh** — and a fresh boot **saves what it fetched**, so the next visit becomes a restore.",
          test: "localStorage.removeItem('packlist');\nawait boot();\nawait T.sleep(300);\nT.eq(T.count('#list li'), 3, 'Storage cleared → boot() falls back to the server again (3 items).');\nT.expect((T.text('#bootSource') || '').toLowerCase().indexOf('fresh') !== -1, 'And reports \"fresh\" again.');\nvar stored = JSON.parse(localStorage.getItem('packlist') || 'null');\nT.expect(Array.isArray(stored) && stored.length === 3, 'A fresh boot should SAVE the fetched items to localStorage — that is what turns the next visit into a restore.');\nT.eq(stored[0].text, 'Passport', 'The stored copy matches the server data.');" }
      ],
      files: [
        { name: "index.html", content: "<!DOCTYPE html>\n<html>\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n  <h1>Packlist 📦</h1>\n  <p class=\"boot-line\">Booted: <strong id=\"bootSource\">…</strong></p>\n\n  <ul id=\"list\"></ul>\n\n  <script src=\"script.js\"></script>\n</body>\n</html>\n" },
        { name: "styles.css", content: "body {\n  font-family: Arial, sans-serif;\n  background: #f1f5f9;\n  max-width: 520px;\n  margin: 0 auto;\n  padding: 20px;\n}\nh1 { margin: 8px 0 4px; }\n.boot-line { margin: 0 0 12px; font-size: 14px; color: #64748b; }\n#bootSource { color: #0ea5e9; }\n#list { list-style: none; padding: 0; }\n#list li {\n  background: white; margin-top: 8px; padding: 12px 14px;\n  border-radius: 10px; display: flex; justify-content: space-between; gap: 8px;\n}\n#list li.packed { opacity: 0.6; }\n" },
        { name: "script.js", content: "/* ============ SERVER (imagine this on another machine) ============ */\nlet serverItems = [\n  { id: 1, text: \"Passport\", packed: true },\n  { id: 2, text: \"Camera\", packed: false },\n  { id: 3, text: \"Headphones\", packed: false }\n];\n\nfunction handleRequest(req) {\n  if (req.method === \"GET\" && req.path === \"/api/items\") {\n    return { status: 200, body: JSON.parse(JSON.stringify(serverItems)) };\n  }\n  return { status: 404, body: { error: { code: \"not_found\", message: \"No route for \" + req.method + \" \" + req.path } } };\n}\n\n/* ============ THE WIRE (fake network: 20 ms) ============ */\nfunction api(req) {\n  return new Promise((resolve) => setTimeout(() => resolve(handleRequest(req)), 20));\n}\n\n/* ============ CLIENT (the page) ============ */\nconst listEl = document.querySelector(\"#list\");\nconst bootSource = document.querySelector(\"#bootSource\");\n\nlet items = [];\n\nfunction render() {\n  listEl.innerHTML = \"\";\n  items.forEach((item) => {\n    const li = document.createElement(\"li\");\n    li.textContent = item.text + (item.packed ? \" ✓\" : \"\");\n    if (item.packed) li.classList.add(\"packed\");\n    listEl.appendChild(li);\n  });\n}\n\nasync function boot() {\n  // 1) const stored = JSON.parse(localStorage.getItem(\"packlist\") || \"null\");\n  // 2) if Array.isArray(stored): items = stored,\n  //    bootSource says \"restored from this browser\"\n  // 3) else: await the wire — api({ method: \"GET\", path: \"/api/items\" }),\n  //    items = res.body, SAVE them under \"packlist\" for next time,\n  //    bootSource says \"fresh from the server\"\n  // 4) either way, finish with render()\n}\n\nboot();\n" }
      ],
      hints: [
        "Read first: `const stored = JSON.parse(localStorage.getItem(\"packlist\") || \"null\");` — the `|| \"null\"` makes a missing key parse cleanly to `null` instead of exploding.",
        "The fork: `if (Array.isArray(stored)) { items = stored; bootSource.textContent = \"restored from this browser\"; } else { … }`",
        "The fresh branch awaits the wire: `const res = await api({ method: \"GET\", path: \"/api/items\" }); items = res.body; localStorage.setItem(\"packlist\", JSON.stringify(items)); bootSource.textContent = \"fresh from the server\";`",
        "Finish with `render()` OUTSIDE the if/else — both paths need it exactly once."
      ],
      solution: {
        "script.js": "/* ============ SERVER (imagine this on another machine) ============ */\nlet serverItems = [\n  { id: 1, text: \"Passport\", packed: true },\n  { id: 2, text: \"Camera\", packed: false },\n  { id: 3, text: \"Headphones\", packed: false }\n];\n\nfunction handleRequest(req) {\n  if (req.method === \"GET\" && req.path === \"/api/items\") {\n    return { status: 200, body: JSON.parse(JSON.stringify(serverItems)) };\n  }\n  return { status: 404, body: { error: { code: \"not_found\", message: \"No route for \" + req.method + \" \" + req.path } } };\n}\n\n/* ============ THE WIRE (fake network: 20 ms) ============ */\nfunction api(req) {\n  return new Promise((resolve) => setTimeout(() => resolve(handleRequest(req)), 20));\n}\n\n/* ============ CLIENT (the page) ============ */\nconst listEl = document.querySelector(\"#list\");\nconst bootSource = document.querySelector(\"#bootSource\");\n\nlet items = [];\n\nfunction render() {\n  listEl.innerHTML = \"\";\n  items.forEach((item) => {\n    const li = document.createElement(\"li\");\n    li.textContent = item.text + (item.packed ? \" ✓\" : \"\");\n    if (item.packed) li.classList.add(\"packed\");\n    listEl.appendChild(li);\n  });\n}\n\nasync function boot() {\n  const stored = JSON.parse(localStorage.getItem(\"packlist\") || \"null\");\n  if (Array.isArray(stored)) {\n    items = stored;\n    bootSource.textContent = \"restored from this browser\";\n  } else {\n    const res = await api({ method: \"GET\", path: \"/api/items\" });\n    items = res.body;\n    localStorage.setItem(\"packlist\", JSON.stringify(items));\n    bootSource.textContent = \"fresh from the server\";\n  }\n  render();\n}\n\nboot();\n"
      }
    },

    {
      id: "cap-quiz-4",
      title: "Unit 4 quiz: Data round-trips",
      kind: "quiz", xp: 10,
      questions: [
        { q: "In `JSON.stringify(items, null, 2)`, what does the `2` do?",
          choices: ["Only exports the first 2 items", "Rounds numbers to 2 decimal places", "Indents the output with 2 spaces per level — pretty-printing for human eyes", "Limits nesting to 2 levels deep"],
          answer: 2, explain: "Argument 3 is the indent. Without it the JSON comes out as one long machine-friendly line — fine for storage, rough for humans. (Argument 2 is a filter — null means \"keep everything\".)" },
        { q: "A user pastes `{oops` and clicks Import. What does this line do?",
          code: "const data = JSON.parse(pastedText);",
          lang: "js",
          choices: ["Returns null so you can check for it", "Returns undefined", "Auto-fixes the missing quotes", "THROWS a SyntaxError — untrusted JSON belongs inside try/catch"],
          answer: 3, explain: "JSON.parse never hands back an error signal — it throws. try { parse } catch { show a message, keep the old state } is THE import pattern." },
        { q: "What actually lands in storage here?",
          code: "localStorage.setItem(\"items\", items);  // items is an array",
          lang: "js",
          choices: ["The array, stored as a real array", "The array squashed through toString() — comma-joined mush, NOT JSON — because storage holds only strings", "Nothing — setItem rejects non-strings", "A binary copy of the array"],
          answer: 1, explain: "localStorage stores strings, period. Anything else gets toString()'d beyond recognition. JSON.stringify going in, JSON.parse coming out — always travel with the pair." },
        { q: "`JSON.parse` succeeded on the pasted text. Why does a careful import STILL check `Array.isArray(parsed)`?",
          choices: ["Because \"hello\" and {\"a\": 1} are perfectly valid JSON — parsing proves it is JSON, not that it is YOUR shape", "Because Array.isArray repairs broken arrays", "Because JSON.parse only works on objects", "No reason — valid JSON is always an array"],
          answer: 0, explain: "Valid JSON can be a string, a number, an object, even null. Your render() expects an array of items — verify the shape before you replace state with it." },
        { q: "First-ever visit — what logs, and why does boot() care?",
          code: "const stored = localStorage.getItem(\"packlist\");\nconsole.log(stored === null);",
          lang: "js",
          choices: ["false — getItem returns an empty string", "It throws — the key does not exist", "true — a missing key reads as null, which is boot()'s cue to fall back to the server", "undefined"],
          answer: 2, explain: "getItem returns null for missing keys. That null IS the fork in the boot sequence: stored data → restore it; null → fetch fresh from the server and save it for next time." },
        { q: "What did we just make?",
          code: "const copy = JSON.parse(JSON.stringify(data));",
          lang: "js",
          choices: ["A reference — copy and data are the same object", "A deep copy — a fully independent clone of plain data (functions and Dates would not survive the trip)", "A syntax error", "A string"],
          answer: 1, explain: "A round-trip through JSON clones nested plain data — handy when the in-page server hands out copies so the client can never mutate its private store. It only carries what JSON can carry: no functions, and Dates flatten to strings." }
      ]
    }
  ]
});
