/* Full-Stack Capstone — Unit 5: Polish & a11y */
window.CODELAB.addUnit("cap", {
  id: "cap-u5",
  title: "Polish & a11y",
  icon: "♿",
  blurb: "Your app works — now make it work for everyone: labels, keyboards, screen readers, and touch-friendly polish.",
  cheat: [
    { h: "Label every input", lang: "html", code: "<label for=\"emailInput\">Email</label>\n<input id=\"emailInput\" type=\"email\">", note: "Clicking the label focuses the input; screen readers read it aloud. for ↔ id must match exactly." },
    { h: "Real buttons only", lang: "html", code: "<div onclick=\"save()\">Save</div>   <!-- ❌ no focus, no keyboard, no role -->\n<button id=\"saveBtn\">Save</button> <!-- ✅ Tab, Enter, Space for free -->", note: "If you click it, it is a button (or a link). Divs are for layout." },
    { h: "alt text", lang: "html", code: "<img src=\"chart.png\" alt=\"Sales doubled from January to March\">\n<img src=\"divider.png\" alt=\"\">  <!-- decorative → EMPTY alt, not missing -->", note: "Describe content or purpose. A MISSING alt makes screen readers read the filename." },
    { h: "Focus styles: replace, never remove", lang: "css", code: "#searchInput:focus {\n  outline: 3px solid #2563eb;   /* the visible ring */\n  outline-offset: 2px;\n}\n/* outline: none with no replacement = invisible keyboard cursor */" },
    { h: "aria-live: announce changes", lang: "html", code: "<p id=\"statusMsg\" role=\"status\" aria-live=\"polite\"></p>\n<!-- JS: statusEl.textContent = \"Added Milk\" → read aloud, no focus stolen -->", note: "polite = announce at the next pause. assertive = interrupt (save it for emergencies)." },
    { h: "Touch targets & empty states", lang: "css", code: ".del {\n  min-height: 44px;   /* fingertip-sized — */\n  min-width: 44px;    /* the Apple & Android floor */\n}\n#emptyMsg { color: #64748b; }   /* muted, not invisible */" }
  ],
  lessons: [

    {
      id: "cap-u5-1",
      title: "Labels, buttons, alt",
      kind: "web", chip: "HTML", xp: 15, mins: 12,
      brief: "Five units in, you can build a full-stack app — but *works on my machine, with my mouse* is not shipped. This unit is the pro polish pass, and it opens with the three cheapest accessibility wins in HTML.\n\nThis packing-list page runs fine… for mouse users with sharp eyesight. For everyone else it is quietly broken:\n\n- the \"button\" is a `<div>` — keyboards cannot press it\n- the input has no `<label>` — screen readers just say *edit text*\n- the mascot image describes nothing\n\nThe JavaScript is already finished. Today is markup surgery: three small cuts, huge quality-of-life wins.",
      steps: [
        { text: "The word **Item** becomes a `<label for=\"itemInput\">` — clicking it now focuses the input.",
          test: "T.expect(T.$('label[for=itemInput]'), 'Replace the span with <label for=\"itemInput\">Item</label> — the for value must match the input id exactly.');\nT.expect((T.text('label[for=itemInput]') || '').toLowerCase().indexOf('item') !== -1, 'Keep the visible word Item inside the label.');" },
        { text: "`#addBtn` becomes a real `<button>` — and still adds items.",
          test: "var b = T.$('#addBtn');\nT.expect(b, 'Keep the id addBtn on the new element.');\nT.eq(b.tagName, 'BUTTON', 'Swap the <div> for <button id=\"addBtn\">Add</button> — a real button gets Tab focus and Enter/Space handling for free.');\nT.type('#itemInput', 'Sunscreen');\nT.click('#addBtn');\nT.eq(T.count('#packList li'), 1, 'The script targets #addBtn by id, so the swap must not break adding — one click, one li.');" },
        { text: "The mascot `<img>` gets descriptive `alt` text.",
          test: "var altText = T.$('#mascot').getAttribute('alt');\nT.expect(altText !== null, 'Add an alt attribute to #mascot — without one, screen readers improvise with the src gibberish.');\nT.expect((altText || '').trim().length >= 3, 'Describe it in a few words, e.g. alt=\"Cartoon backpack mascot\".');" }
      ],
      files: [
        { name: "index.html", content: "<!DOCTYPE html>\n<html>\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n  <h1>Packing list 🎒</h1>\n\n  <!-- 3) the mascot needs alt text -->\n  <img id=\"mascot\" src=\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='72' height='72'><rect width='72' height='72' rx='16' fill='%230ea5e9'/><circle cx='36' cy='26' r='11' fill='white'/><rect x='19' y='40' width='34' height='19' rx='7' fill='white'/></svg>\">\n\n  <div class=\"field\">\n    <!-- 1) this word should be a <label for=\"itemInput\"> -->\n    <span class=\"fake-label\">Item</span>\n    <input id=\"itemInput\" placeholder=\"Sunscreen\">\n  </div>\n\n  <!-- 2) a div is not a button — make it a real <button id=\"addBtn\"> -->\n  <div id=\"addBtn\" class=\"btn\">Add</div>\n\n  <ul id=\"packList\"></ul>\n\n  <script src=\"script.js\"></script>\n</body>\n</html>\n" },
        { name: "styles.css", content: "body {\n  font-family: Arial, sans-serif;\n  max-width: 480px;\n  margin: 0 auto;\n  padding: 20px;\n}\n#mascot { display: block; margin-bottom: 12px; }\n.field { display: flex; align-items: center; gap: 8px; }\nlabel, .fake-label { font-weight: bold; }\n#itemInput {\n  flex: 1;\n  padding: 10px 12px;\n  border: 2px solid #cbd5e1;\n  border-radius: 10px;\n  font-size: 15px;\n}\n/* styled by ID — div or button, it looks the same */\n#addBtn {\n  display: inline-block;\n  margin-top: 10px;\n  padding: 10px 16px;\n  border: none;\n  border-radius: 10px;\n  background: #0ea5e9;\n  color: white;\n  font-weight: bold;\n  font-size: 15px;\n  cursor: pointer;\n}\n#packList { list-style: none; padding: 0; }\n#packList li {\n  background: #f1f5f9;\n  margin-top: 8px;\n  padding: 12px 14px;\n  border-radius: 10px;\n}\n" },
        { name: "script.js", content: "// This file is DONE — today is markup surgery in index.html.\nconst itemInput = document.querySelector(\"#itemInput\");\nconst addBtn = document.querySelector(\"#addBtn\");\nconst packList = document.querySelector(\"#packList\");\n\nlet items = [];\n\nfunction render() {\n  packList.innerHTML = \"\";\n  items.forEach((it) => {\n    const li = document.createElement(\"li\");\n    li.textContent = it;\n    packList.appendChild(li);\n  });\n}\n\naddBtn.addEventListener(\"click\", () => {\n  const text = itemInput.value.trim();\n  if (!text) return;\n  items.push(text);\n  itemInput.value = \"\";\n  render();\n});\n" }
      ],
      hints: [
        "The label swap: `<label for=\"itemInput\">Item</label>` — the `for` value is the input's `id`, character for character.",
        "The button swap: `<button id=\"addBtn\">Add</button>`. The script selects `#addBtn`, so nothing else changes — this is why ids beat tag-based selectors.",
        "Alt text describes what or why, not \"image of…\" — screen readers already announce that it is an image."
      ],
      solution: {
        "index.html": "<!DOCTYPE html>\n<html>\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n  <h1>Packing list 🎒</h1>\n\n  <img id=\"mascot\" alt=\"Cartoon backpack mascot\" src=\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='72' height='72'><rect width='72' height='72' rx='16' fill='%230ea5e9'/><circle cx='36' cy='26' r='11' fill='white'/><rect x='19' y='40' width='34' height='19' rx='7' fill='white'/></svg>\">\n\n  <div class=\"field\">\n    <label for=\"itemInput\">Item</label>\n    <input id=\"itemInput\" placeholder=\"Sunscreen\">\n  </div>\n\n  <button id=\"addBtn\">Add</button>\n\n  <ul id=\"packList\"></ul>\n\n  <script src=\"script.js\"></script>\n</body>\n</html>\n"
      }
    },

    {
      id: "cap-u5-2",
      title: "Keyboard reachable",
      kind: "web", chip: "DOM", xp: 15, mins: 12,
      brief: "Plenty of people never touch a mouse — power users, folks with motor impairments, anyone whose trackpad just died. Your app should be fully drivable from the keyboard, and most of it is free if you lean on the platform:\n\n- a real `<form>` makes **Enter** submit — zero extra code\n- a `keydown` listener adds **Escape** to bail out of a half-typed entry\n- `:focus` styles show *where you are* — and someone committed the classic crime of `outline: none` in this stylesheet\n\nWire the form, catch the key, fix the crime.",
      example: { lang: "js", code: "input.addEventListener(\"keydown\", (e) => {\n  if (e.key === \"Escape\") input.value = \"\";\n});" },
      steps: [
        { text: "Wrap the row in `<form id=\"listForm\">` and move adding into its **submit** handler — pressing **Enter** in the input now adds, for free.",
          test: "T.expect(T.$('form#listForm'), 'In index.html, wrap the label + input + button in <form id=\"listForm\">.');\nT.type('#groceryInput', 'Oat milk');\nT.submit('#listForm');\nT.eq(T.count('#groceryList li'), 1, 'Handle the submit event on the form: e.preventDefault(), then addItem(). Enter and the Add button both trigger it.');\nT.eq(T.val('#groceryInput'), '', 'addItem() clears the input — keep that behavior.');" },
        { text: "**Escape** clears a half-typed entry — a `keydown` listener on the input checks `e.key`.",
          test: "T.type('#groceryInput', 'typo city');\nT.$('#groceryInput').dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true }));\nT.eq(T.val('#groceryInput'), '', 'On keydown: if (e.key === \"Escape\") set groceryInput.value = \"\".');\nT.eq(T.count('#groceryList li'), 1, 'Escape must not add anything — the list still holds exactly 1 item.');" },
        { text: "Fix the focus crime in `styles.css`: `#groceryInput:focus` gets a **visible** `outline: 3px solid #2563eb`.",
          test: "T.expect(T.ruleFor('#groceryInput:focus'), 'Keep the #groceryInput:focus rule in styles.css — you are fixing it, not deleting it.');\nvar d = (T.decl('#groceryInput:focus', 'outline') || '');\nT.expect(d.indexOf('none') === -1, 'Delete outline: none — never remove the focus ring without replacing it.');\nT.expect(d.indexOf('3px') !== -1 && d.indexOf('solid') !== -1, 'Write outline: 3px solid #2563eb — keyboard users need to SEE where they are.');" }
      ],
      files: [
        { name: "index.html", content: "<!DOCTYPE html>\n<html>\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n  <h1>Grocery run 🛒</h1>\n\n  <!-- 1) wrap all three in <form id=\"listForm\"> -->\n  <label for=\"groceryInput\">Item</label>\n  <input id=\"groceryInput\" placeholder=\"What do we need?\">\n  <button id=\"addBtn\">Add</button>\n\n  <ul id=\"groceryList\"></ul>\n\n  <script src=\"script.js\"></script>\n</body>\n</html>\n" },
        { name: "styles.css", content: "body {\n  font-family: Arial, sans-serif;\n  max-width: 480px;\n  margin: 0 auto;\n  padding: 20px;\n}\n/* already waiting for your <form> */\n#listForm { display: flex; gap: 8px; align-items: center; }\nlabel { font-weight: bold; }\n#groceryInput {\n  flex: 1;\n  padding: 10px 12px;\n  border: 2px solid #cbd5e1;\n  border-radius: 10px;\n  font-size: 15px;\n}\n#groceryInput:focus {\n  outline: none;   /* 😱 3) someone \"tidied this away\" — replace it! */\n}\n#addBtn {\n  padding: 10px 16px;\n  border: none;\n  border-radius: 10px;\n  background: #0ea5e9;\n  color: white;\n  font-weight: bold;\n  font-size: 15px;\n  cursor: pointer;\n}\n#groceryList { list-style: none; padding: 0; }\n#groceryList li {\n  background: #f1f5f9;\n  margin-top: 8px;\n  padding: 12px 14px;\n  border-radius: 10px;\n}\n" },
        { name: "script.js", content: "const groceryInput = document.querySelector(\"#groceryInput\");\nconst groceryList = document.querySelector(\"#groceryList\");\n\nlet groceries = [];\n\nfunction render() {\n  groceryList.innerHTML = \"\";\n  groceries.forEach((g) => {\n    const li = document.createElement(\"li\");\n    li.textContent = g;\n    groceryList.appendChild(li);\n  });\n}\n\nfunction addItem() {\n  const text = groceryInput.value.trim();\n  if (!text) return;\n  groceries.push(text);\n  groceryInput.value = \"\";\n  render();\n}\n\n// 1) After wrapping the row in <form id=\"listForm\"> (index.html),\n//    REPLACE this click wiring with a \"submit\" listener on the form:\n//    e.preventDefault(), then addItem() — now Enter submits too.\ndocument.querySelector(\"#addBtn\").addEventListener(\"click\", addItem);\n\n// 2) keydown on groceryInput: if (e.key === \"Escape\") clear the box\n\n// 3) lives in styles.css — hunt down the outline crime\n" }
      ],
      hints: [
        "The wrap: `<form id=\"listForm\"> <label…> <input…> <button…> </form>` — a button inside a form submits it by default.",
        "The swap: `document.querySelector(\"#listForm\").addEventListener(\"submit\", (e) => { e.preventDefault(); addItem(); });` — and delete the old click line, or every click adds twice.",
        "Escape: `groceryInput.addEventListener(\"keydown\", (e) => { if (e.key === \"Escape\") groceryInput.value = \"\"; });`",
        "The fix: `#groceryInput:focus { outline: 3px solid #2563eb; outline-offset: 2px; }` — in real projects `:focus-visible` shows it only for keyboard users."
      ],
      solution: {
        "index.html": "<!DOCTYPE html>\n<html>\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n  <h1>Grocery run 🛒</h1>\n\n  <form id=\"listForm\">\n    <label for=\"groceryInput\">Item</label>\n    <input id=\"groceryInput\" placeholder=\"What do we need?\">\n    <button id=\"addBtn\">Add</button>\n  </form>\n\n  <ul id=\"groceryList\"></ul>\n\n  <script src=\"script.js\"></script>\n</body>\n</html>\n",
        "styles.css": "body {\n  font-family: Arial, sans-serif;\n  max-width: 480px;\n  margin: 0 auto;\n  padding: 20px;\n}\n#listForm { display: flex; gap: 8px; align-items: center; }\nlabel { font-weight: bold; }\n#groceryInput {\n  flex: 1;\n  padding: 10px 12px;\n  border: 2px solid #cbd5e1;\n  border-radius: 10px;\n  font-size: 15px;\n}\n#groceryInput:focus {\n  outline: 3px solid #2563eb;\n  outline-offset: 2px;\n}\n#addBtn {\n  padding: 10px 16px;\n  border: none;\n  border-radius: 10px;\n  background: #0ea5e9;\n  color: white;\n  font-weight: bold;\n  font-size: 15px;\n  cursor: pointer;\n}\n#groceryList { list-style: none; padding: 0; }\n#groceryList li {\n  background: #f1f5f9;\n  margin-top: 8px;\n  padding: 12px 14px;\n  border-radius: 10px;\n}\n",
        "script.js": "const groceryInput = document.querySelector(\"#groceryInput\");\nconst groceryList = document.querySelector(\"#groceryList\");\n\nlet groceries = [];\n\nfunction render() {\n  groceryList.innerHTML = \"\";\n  groceries.forEach((g) => {\n    const li = document.createElement(\"li\");\n    li.textContent = g;\n    groceryList.appendChild(li);\n  });\n}\n\nfunction addItem() {\n  const text = groceryInput.value.trim();\n  if (!text) return;\n  groceries.push(text);\n  groceryInput.value = \"\";\n  render();\n}\n\ndocument.querySelector(\"#listForm\").addEventListener(\"submit\", (e) => {\n  e.preventDefault();\n  addItem();\n});\n\ngroceryInput.addEventListener(\"keydown\", (e) => {\n  if (e.key === \"Escape\") {\n    groceryInput.value = \"\";\n  }\n});\n" }
    },

    {
      id: "cap-u5-3",
      title: "Announce it",
      kind: "web", chip: "DOM", xp: 15, mins: 12,
      brief: "Your app already *shows* what changed — a screen reader user hears… silence. New `<li>` elements appear, but nothing tells assistive tech to look.\n\nEnter **live regions**: mark one element with `aria-live=\"polite\"` and every text change inside it gets announced when the user is idle — no focus stealing, no interruption. One region, updated from the same handlers that already update state:\n\n- add → *Added Milk*\n- remove → *Removed Milk*\n\nYou built the state-and-render machine four units ago; today it learns to speak.",
      example: { lang: "html", code: "<p id=\"statusMsg\" role=\"status\" aria-live=\"polite\"></p>\n<!-- later, in JS: statusEl.textContent = \"Added Milk\" → announced aloud -->" },
      steps: [
        { text: "Make `#statusMsg` a live region: `aria-live=\"polite\"` plus `role=\"status\"`.",
          test: "T.eq(T.attr('#statusMsg', 'aria-live'), 'polite', 'Add aria-live=\"polite\" to #statusMsg in index.html — screen readers will announce whatever text lands in it.');\nT.eq(T.attr('#statusMsg', 'role'), 'status', 'Add role=\"status\" as well — redundancy that older screen readers appreciate.');" },
        { text: "Adding a snack announces it: **Added Milk**.",
          test: "T.type('#snackInput', 'Milk');\nT.submit('#snackForm');\nT.eq(T.count('#snackList li'), 1, 'The add flow still works — one submit, one li.');\nvar m = (T.text('#statusMsg') || '').toLowerCase();\nT.expect(m.indexOf('added') !== -1 && m.indexOf('milk') !== -1, 'In the submit handler, set statusEl.textContent = \"Added \" + text — expected something like Added Milk.');" },
        { text: "Removing announces too: **Removed Milk**.",
          test: "T.type('#snackInput', 'Pretzels');\nT.submit('#snackForm');\nT.eq(T.count('#snackList li'), 2, '(the test added a second snack)');\nT.click('#snackList li .del');\nT.eq(T.count('#snackList li'), 1, 'The first ✕ removes the first snack — querySelector always finds the FIRST match.');\nvar m = (T.text('#statusMsg') || '').toLowerCase();\nT.expect(m.indexOf('removed') !== -1 && m.indexOf('milk') !== -1, 'Deleting Milk should announce Removed Milk — the delete handler already has the snack text in scope.');" }
      ],
      files: [
        { name: "index.html", content: "<!DOCTYPE html>\n<html>\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n  <h1>Snack stash 🍿</h1>\n\n  <form id=\"snackForm\">\n    <label for=\"snackInput\">Snack</label>\n    <input id=\"snackInput\" placeholder=\"Milk\">\n    <button>Add</button>\n  </form>\n\n  <!-- 1) make this a live region: role=\"status\" aria-live=\"polite\" -->\n  <p id=\"statusMsg\"></p>\n\n  <ul id=\"snackList\"></ul>\n\n  <script src=\"script.js\"></script>\n</body>\n</html>\n" },
        { name: "styles.css", content: "body {\n  font-family: Arial, sans-serif;\n  max-width: 480px;\n  margin: 0 auto;\n  padding: 20px;\n}\n#snackForm { display: flex; gap: 8px; align-items: center; }\nlabel { font-weight: bold; }\n#snackInput {\n  flex: 1;\n  padding: 10px 12px;\n  border: 2px solid #cbd5e1;\n  border-radius: 10px;\n  font-size: 15px;\n}\n#snackForm button {\n  padding: 10px 16px;\n  border: none;\n  border-radius: 10px;\n  background: #0ea5e9;\n  color: white;\n  font-weight: bold;\n  font-size: 15px;\n  cursor: pointer;\n}\n#statusMsg {\n  min-height: 20px;\n  margin: 10px 0 0;\n  color: #0369a1;\n  font-size: 14px;\n}\n#snackList { list-style: none; padding: 0; }\n#snackList li {\n  background: #f1f5f9;\n  margin-top: 8px;\n  padding: 8px 8px 8px 14px;\n  border-radius: 10px;\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  gap: 8px;\n}\n.del {\n  border: none;\n  background: none;\n  color: #ef4444;\n  font-weight: bold;\n  font-size: 16px;\n  cursor: pointer;\n}\n" },
        { name: "script.js", content: "const snackForm = document.querySelector(\"#snackForm\");\nconst snackInput = document.querySelector(\"#snackInput\");\nconst snackList = document.querySelector(\"#snackList\");\nconst statusEl = document.querySelector(\"#statusMsg\");\n\nlet snacks = [];\n\nfunction render() {\n  snackList.innerHTML = \"\";\n  snacks.forEach((snack, index) => {\n    const li = document.createElement(\"li\");\n    const span = document.createElement(\"span\");\n    span.textContent = snack;\n    li.appendChild(span);\n\n    const del = document.createElement(\"button\");\n    del.className = \"del\";\n    del.textContent = \"✕\";\n    del.addEventListener(\"click\", () => {\n      snacks.splice(index, 1);\n      // 3) announce it: statusEl.textContent = \"Removed \" + snack\n      render();\n    });\n    li.appendChild(del);\n\n    snackList.appendChild(li);\n  });\n}\n\nsnackForm.addEventListener(\"submit\", (e) => {\n  e.preventDefault();\n  const text = snackInput.value.trim();\n  if (!text) return;\n  snacks.push(text);\n  // 2) announce it: statusEl.textContent = \"Added \" + text\n  snackInput.value = \"\";\n  render();\n});\n\nrender();\n" }
      ],
      hints: [
        "The region: `<p id=\"statusMsg\" role=\"status\" aria-live=\"polite\"></p>` — the attributes go on the element that will RECEIVE the text.",
        "Add: right after `snacks.push(text)`, write `statusEl.textContent = \"Added \" + text;`",
        "Remove: the forEach callback already closed over `snack`, so inside the delete handler: `statusEl.textContent = \"Removed \" + snack;` — no lookup needed.",
        "Nothing visual changes — that is the point. aria-live is UI for ears."
      ],
      solution: {
        "index.html": "<!DOCTYPE html>\n<html>\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n  <h1>Snack stash 🍿</h1>\n\n  <form id=\"snackForm\">\n    <label for=\"snackInput\">Snack</label>\n    <input id=\"snackInput\" placeholder=\"Milk\">\n    <button>Add</button>\n  </form>\n\n  <p id=\"statusMsg\" role=\"status\" aria-live=\"polite\"></p>\n\n  <ul id=\"snackList\"></ul>\n\n  <script src=\"script.js\"></script>\n</body>\n</html>\n",
        "script.js": "const snackForm = document.querySelector(\"#snackForm\");\nconst snackInput = document.querySelector(\"#snackInput\");\nconst snackList = document.querySelector(\"#snackList\");\nconst statusEl = document.querySelector(\"#statusMsg\");\n\nlet snacks = [];\n\nfunction render() {\n  snackList.innerHTML = \"\";\n  snacks.forEach((snack, index) => {\n    const li = document.createElement(\"li\");\n    const span = document.createElement(\"span\");\n    span.textContent = snack;\n    li.appendChild(span);\n\n    const del = document.createElement(\"button\");\n    del.className = \"del\";\n    del.textContent = \"✕\";\n    del.addEventListener(\"click\", () => {\n      snacks.splice(index, 1);\n      statusEl.textContent = \"Removed \" + snack;\n      render();\n    });\n    li.appendChild(del);\n\n    snackList.appendChild(li);\n  });\n}\n\nsnackForm.addEventListener(\"submit\", (e) => {\n  e.preventDefault();\n  const text = snackInput.value.trim();\n  if (!text) return;\n  snacks.push(text);\n  statusEl.textContent = \"Added \" + text;\n  snackInput.value = \"\";\n  render();\n});\n\nrender();\n" }
    },

    {
      id: "cap-u5-4",
      title: "Empty states & touch targets",
      kind: "web", chip: "WEB", xp: 15, mins: 12,
      brief: "Two finishing touches that separate *demo* from *product*.\n\n**Empty states**: a blank list looks broken. When there is nothing to show, say so — warmly — and let `render()` own the toggle, because it is the one function that always knows the count.\n\n**Touch targets**: your ✕ button is a 20px sliver; on a phone that is a rage-tap generator. Apple and Android both say interactive targets should be at least **44px** — `min-height` and `min-width` fix it without redesigning anything.\n\nFinish with a muted `#64748b` on the empty message: present, calm, not shouting.",
      steps: [
        { text: "Zero items → `#emptyMsg` shows; adding the first show hides it. Toggle it inside `render()`.",
          test: "T.expect(T.css('#emptyMsg', 'display') !== 'none', 'With zero shows, #emptyMsg should be visible at load.');\nT.type('#watchInput', 'Cosmos');\nT.submit('#watchForm');\nT.eq(T.count('#watchList li'), 1, 'Adding still works — one submit, one li.');\nT.expect(T.css('#emptyMsg', 'display') === 'none', 'Once the list has items, hide the message: emptyMsg.style.display = shows.length === 0 ? \"block\" : \"none\" inside render().');" },
        { text: "Deleting the last show brings the message back — `render()` is the single source of truth.",
          test: "T.click('#watchList li .del');\nT.eq(T.count('#watchList li'), 0, 'The ✕ removes its show.');\nT.expect(T.css('#emptyMsg', 'display') !== 'none', 'Zero shows again → the message returns. This is why the toggle lives in render(), not in each event handler.');" },
        { text: "Comfortable to tap: the `.del` rule gets `min-height: 44px` **and** `min-width: 44px`.",
          test: "T.expect((T.decl('.del', 'min-height') || '').indexOf('44px') !== -1, 'In the .del rule add min-height: 44px — the Apple/Android touch-target floor.');\nT.expect((T.decl('.del', 'min-width') || '').indexOf('44px') !== -1, 'Add min-width: 44px too — fingertips are round, targets need both dimensions.');" },
        { text: "Mute the empty message: `color: #64748b`.",
          test: "T.eq(T.css('#emptyMsg', 'color'), 'rgb(100, 116, 139)', 'Give #emptyMsg color: #64748b — computed colors always read back as rgb(), and #64748b is rgb(100, 116, 139).');" }
      ],
      files: [
        { name: "index.html", content: "<!DOCTYPE html>\n<html>\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n  <h1>Watchlist 🎬</h1>\n\n  <form id=\"watchForm\">\n    <label for=\"watchInput\">Show</label>\n    <input id=\"watchInput\" placeholder=\"Cosmos\">\n    <button>Add</button>\n  </form>\n\n  <p id=\"emptyMsg\">Nothing here yet — add your first show! 🍿</p>\n\n  <ul id=\"watchList\"></ul>\n\n  <script src=\"script.js\"></script>\n</body>\n</html>\n" },
        { name: "styles.css", content: "body {\n  font-family: Arial, sans-serif;\n  max-width: 480px;\n  margin: 0 auto;\n  padding: 20px;\n}\n#watchForm { display: flex; gap: 8px; align-items: center; }\nlabel { font-weight: bold; }\n#watchInput {\n  flex: 1;\n  padding: 10px 12px;\n  border: 2px solid #cbd5e1;\n  border-radius: 10px;\n  font-size: 15px;\n}\n#watchForm button {\n  padding: 10px 16px;\n  border: none;\n  border-radius: 10px;\n  background: #0ea5e9;\n  color: white;\n  font-weight: bold;\n  font-size: 15px;\n  cursor: pointer;\n  min-height: 44px;\n}\n#watchList { list-style: none; padding: 0; }\n#watchList li {\n  background: #f1f5f9;\n  margin-top: 8px;\n  padding: 8px 8px 8px 14px;\n  border-radius: 10px;\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  gap: 8px;\n}\n/* 3) a 20px sliver — give it min-height: 44px and min-width: 44px */\n.del {\n  border: none;\n  background: none;\n  color: #ef4444;\n  font-weight: bold;\n  font-size: 16px;\n  cursor: pointer;\n}\n/* 4) mute it: color: #64748b */\n#emptyMsg {\n  margin-top: 14px;\n}\n" },
        { name: "script.js", content: "const watchForm = document.querySelector(\"#watchForm\");\nconst watchInput = document.querySelector(\"#watchInput\");\nconst watchList = document.querySelector(\"#watchList\");\nconst emptyMsg = document.querySelector(\"#emptyMsg\");\n\nlet shows = [];\n\nfunction render() {\n  watchList.innerHTML = \"\";\n  shows.forEach((showTitle, index) => {\n    const li = document.createElement(\"li\");\n    const span = document.createElement(\"span\");\n    span.textContent = showTitle;\n    li.appendChild(span);\n\n    const del = document.createElement(\"button\");\n    del.className = \"del\";\n    del.textContent = \"✕\";\n    del.addEventListener(\"click\", () => {\n      shows.splice(index, 1);\n      render();\n    });\n    li.appendChild(del);\n\n    watchList.appendChild(li);\n  });\n\n  // 1+2) toggle the empty state:\n  //      zero shows → emptyMsg.style.display = \"block\"\n  //      otherwise  → \"none\"\n}\n\nwatchForm.addEventListener(\"submit\", (e) => {\n  e.preventDefault();\n  const text = watchInput.value.trim();\n  if (!text) return;\n  shows.push(text);\n  watchInput.value = \"\";\n  render();\n});\n\nrender();\n" }
      ],
      hints: [
        "One line at the bottom of render(): `emptyMsg.style.display = shows.length === 0 ? \"block\" : \"none\";`",
        "Resist toggling it in the submit or delete handlers — every mutation already funnels through render(), so the toggle lives there once, forever correct.",
        "Touch targets: `.del { … min-height: 44px; min-width: 44px; }` — min-* grows the hit area without touching the layout of bigger buttons.",
        "Muted text: `#emptyMsg { color: #64748b; }` — the computed check reads it back as rgb(100, 116, 139)."
      ],
      solution: {
        "styles.css": "body {\n  font-family: Arial, sans-serif;\n  max-width: 480px;\n  margin: 0 auto;\n  padding: 20px;\n}\n#watchForm { display: flex; gap: 8px; align-items: center; }\nlabel { font-weight: bold; }\n#watchInput {\n  flex: 1;\n  padding: 10px 12px;\n  border: 2px solid #cbd5e1;\n  border-radius: 10px;\n  font-size: 15px;\n}\n#watchForm button {\n  padding: 10px 16px;\n  border: none;\n  border-radius: 10px;\n  background: #0ea5e9;\n  color: white;\n  font-weight: bold;\n  font-size: 15px;\n  cursor: pointer;\n  min-height: 44px;\n}\n#watchList { list-style: none; padding: 0; }\n#watchList li {\n  background: #f1f5f9;\n  margin-top: 8px;\n  padding: 8px 8px 8px 14px;\n  border-radius: 10px;\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  gap: 8px;\n}\n.del {\n  border: none;\n  background: none;\n  color: #ef4444;\n  font-weight: bold;\n  font-size: 16px;\n  cursor: pointer;\n  min-height: 44px;\n  min-width: 44px;\n}\n#emptyMsg {\n  margin-top: 14px;\n  color: #64748b;\n}\n",
        "script.js": "const watchForm = document.querySelector(\"#watchForm\");\nconst watchInput = document.querySelector(\"#watchInput\");\nconst watchList = document.querySelector(\"#watchList\");\nconst emptyMsg = document.querySelector(\"#emptyMsg\");\n\nlet shows = [];\n\nfunction render() {\n  watchList.innerHTML = \"\";\n  shows.forEach((showTitle, index) => {\n    const li = document.createElement(\"li\");\n    const span = document.createElement(\"span\");\n    span.textContent = showTitle;\n    li.appendChild(span);\n\n    const del = document.createElement(\"button\");\n    del.className = \"del\";\n    del.textContent = \"✕\";\n    del.addEventListener(\"click\", () => {\n      shows.splice(index, 1);\n      render();\n    });\n    li.appendChild(del);\n\n    watchList.appendChild(li);\n  });\n\n  emptyMsg.style.display = shows.length === 0 ? \"block\" : \"none\";\n}\n\nwatchForm.addEventListener(\"submit\", (e) => {\n  e.preventDefault();\n  const text = watchInput.value.trim();\n  if (!text) return;\n  shows.push(text);\n  watchInput.value = \"\";\n  render();\n});\n\nrender();\n" }
    },

    {
      id: "cap-quiz-5",
      title: "Unit 5 quiz: Accessibility",
      kind: "quiz", xp: 10,
      questions: [
        { q: "This works fine with a mouse. What is broken?",
          code: "<div class=\"btn\" onclick=\"save()\">Save</div>",
          lang: "html",
          choices: ["Nothing — divs and buttons are interchangeable", "divs cannot receive click handlers at all", "Keyboard users cannot reach or press it", "It renders slower than a real button"],
          answer: 2, explain: "A div happily takes an onclick — that is exactly the trap. But it has no role, no Tab stop, and no key handling, so nobody navigating by keyboard can ever reach it and no screen reader will call it a button. A real `<button>` ships Tab focus, Enter/Space activation, and the button role for free, plus form-submit behavior. Rule of thumb: if you click it, it is a button or a link." },
        { q: "What does `<label for=\"emailInput\">Email</label>` actually do?",
          choices: ["Clicking the label focuses the input", "It styles the input's border and font", "It validates the email address format", "Nothing — labels are purely decorative"],
          answer: 0, explain: "`for` ↔ `id` pairs them, and that pairing buys two things: a bigger click target for everyone, and a spoken name — screen readers announce \"Email\" the moment the field gets focus. Styling and validation come from CSS and the input's `type`, not the label. Placeholders vanish as you type; they are hints, not labels." },
        { q: "`aria-live=\"polite\"` on a status region means…",
          choices: ["The region is hidden from screen readers entirely", "Screen readers announce new text at the next pause", "The browser reads it aloud through the speakers", "The element politely rejects invalid input"],
          answer: 1, explain: "`polite` queues the announcement until the user is idle — it never steals focus and never cuts off whatever is being read. (`assertive` interrupts immediately; save that for emergencies.) It is assistive tech doing the speaking, not the browser's speakers. Update the region with `textContent` and the rest happens for you." },
        { q: "This decorative flourish adds no information. The best alt text is…",
          code: "<img src=\"flourish.png\">",
          lang: "html",
          choices: ["alt=\"image\"", "alt=\"flourish.png\"", "No alt attribute at all", "alt=\"\""],
          answer: 3, explain: "Empty alt is a deliberate signal: nothing to see here, move along — screen readers skip the image entirely. A **missing** alt is a different thing: it leaves them to improvise, usually by reading the filename out loud (\"flourish dot p n g\"). And `alt=\"image\"` announces a word the user already knew applied." },
        { q: "A designer calls the focus outline ugly and asks for outline: none. The accessible move is…",
          choices: ["Do it — outlines are optional decoration", "Fade the outline out with a CSS transition", "Restyle it with a visible focus style", "Show outlines only on mobile devices"],
          answer: 2, explain: "The focus indicator is the keyboard cursor — delete it and keyboard users literally cannot tell where they are on the page. Keep something clearly visible: a brand-colored outline works great, and so does thicker, offset, or on-color. The rule is remove only what you replace." },
        { q: "Why do touch guidelines ask for roughly 44px tap targets?",
          choices: ["Bigger buttons load and paint faster", "That is about the size of a fingertip", "CSS cannot render anything smaller", "Search engines reward 44px buttons"],
          answer: 1, explain: "A fingertip covers roughly 44px of screen, so anything smaller invites mis-taps — and that cost lands hardest on users with tremor or limited fine motor control. `min-height` and `min-width` enforce the hit area without inflating the visual design, and both Apple and Android publish this floor." }
      ]
    }
  ]
});
