/* Debugging & Diagnosis — Unit 1: Errors are messages, not failures */
(function () {
  function L() { return Array.prototype.join.call(arguments, "\n"); }

  window.CODELAB.addUnit("debug", {
    id: "debug-u1",
    title: "Errors are messages, not failures",
    icon: "📨",
    blurb: "The three errors you will actually meet, what an error object carries, and how to read the five messages you will see a thousand times.",
    cheat: [
      { h: "The three errors you will actually meet", lang: "js", code: L(
        "const user = null;",
        "user.name;          // TypeError      — right name, wrong KIND of value",
        "totl + 1;           // ReferenceError — that name doesn't exist (typo? scope?)",
        "JSON.parse(\"{a:1}\"); // SyntaxError   — text that isn't valid JSON (or code)"),
        note: "A SyntaxError in your OWN file stops it before line 1 runs. At runtime you mostly meet it through JSON.parse." },
      { h: "Anatomy of an error", lang: "js", code: L(
        "try { applyCoupon({ total: 20 }); } catch (e) {",
        "  e.name;     // \"TypeError\"",
        "  e.message;  // \"Cannot read properties of undefined (reading 'amount')\"",
        "  e.stack;    // name + message, then one \"at fn (file:line:col)\" per frame",
        "}"), note: "The first `at` line is where it was thrown. Read it before you touch the code." },
      { h: "e.name vs instanceof", lang: "js", code: L(
        "class CouponError extends TypeError {}",
        "const e = new CouponError(\"expired\");",
        "e instanceof TypeError   // true  — the family",
        "e.name                   // whatever the author set — just a label"),
        note: "Branch on instanceof when you care about the family; e.name is for printing." },
      { h: "Read the message, then the property", lang: "text", code: L(
        "Cannot read properties of undefined (reading 'name')",
        "   → the thing BEFORE .name was undefined — go find where it came from",
        "cart.map is not a function",
        "   → cart holds something, just not an array",
        "formatPrice is not defined",
        "   → typo, missing import, or declared in another scope"),
        note: "The property in the message is never the problem. The value to its left is." }
    ],
    lessons: [

      {
        id: "debug-u1-1",
        title: "The three errors you will actually meet",
        kind: "js", chip: "DEBUG", xp: 15, mins: 12,
        brief: "You already know how to *handle* an error — Async JavaScript's Unit 3 taught `try`/`catch`. This course is about the part that comes before: **reading** what went wrong, and **finding** where.\n\nIt starts with a surprisingly small vocabulary. Nearly every error you meet in day-to-day JavaScript is one of three types:\n\n- `TypeError` — the name exists, but the **value is the wrong kind** for what you did to it: reading a property of `null`, calling a number like a function.\n- `ReferenceError` — the **name doesn't exist** at all: a typo, a variable from another scope, something never declared.\n- `SyntaxError` — **text that isn't valid** code or valid JSON. A SyntaxError in your own file stops the file before a single line runs; at runtime you mostly meet it through `JSON.parse`.\n\nThe file holds eight one-line bugs, each wrapped in a function so nothing runs yet. Predict what each one throws — `\"TypeError\"`, `\"ReferenceError\"`, `\"SyntaxError\"` or `\"none\"` — *before* you run anything. The checks run each one and show you the real message, so a wrong guess teaches you something.",
        steps: [
          { text: "Predict `a`, `b` and `c` in `PREDICT`.",
            test: L(
              "var actual = function (fn) { try { fn(); return 'none'; } catch (e) { return e.name; } };",
              "var said = function (fn) { try { fn(); return 'nothing — it ran without an error'; } catch (e) { return '\"' + e.message + '\"'; } };",
              "var VOCAB = ['TypeError', 'ReferenceError', 'SyntaxError', 'none'];",
              "['a', 'b', 'c'].forEach(function (k) {",
              "  T.expect(VOCAB.indexOf(PREDICT[k]) !== -1, 'PREDICT.' + k + ' must be one of \"TypeError\", \"ReferenceError\", \"SyntaxError\" or \"none\" — it is ' + JSON.stringify(PREDICT[k]) + '.');",
              "  T.expect(PREDICT[k] === actual(SNIPPETS[k]), 'PREDICT.' + k + ' says ' + PREDICT[k] + '. Running it says ' + said(SNIPPETS[k]) + ' — which of the three is that?');",
              "});") },
          { text: "Predict `d`, `e` and `f`.",
            test: L(
              "var actual = function (fn) { try { fn(); return 'none'; } catch (e) { return e.name; } };",
              "var said = function (fn) { try { fn(); return 'nothing — it ran without an error'; } catch (e) { return '\"' + e.message + '\"'; } };",
              "['d', 'e', 'f'].forEach(function (k) {",
              "  T.expect(PREDICT[k] === actual(SNIPPETS[k]), 'PREDICT.' + k + ' says ' + JSON.stringify(PREDICT[k]) + '. Running it says ' + said(SNIPPETS[k]) + ' — which of the three is that?');",
              "});") },
          { text: "Predict `g` and `h` — including the SyntaxError you *can* meet while the program runs.",
            test: L(
              "var actual = function (fn) { try { fn(); return 'none'; } catch (e) { return e.name; } };",
              "var said = function (fn) { try { fn(); return 'nothing — it ran without an error'; } catch (e) { return '\"' + e.message + '\"'; } };",
              "['g', 'h'].forEach(function (k) {",
              "  T.expect(PREDICT[k] === actual(SNIPPETS[k]), 'PREDICT.' + k + ' says ' + JSON.stringify(PREDICT[k]) + '. Running it says ' + said(SNIPPETS[k]) + ' — which of the three is that?');",
              "});") }
        ],
        files: [
          { name: "script.js", content: L(
            "// Eight one-line bugs, each wrapped in a function so NOTHING runs yet.",
            "// Predict what each one throws BEFORE you run anything:",
            "//   \"TypeError\"      — the value is the wrong kind for what you did to it",
            "//   \"ReferenceError\" — that name doesn't exist (typo, wrong scope)",
            "//   \"SyntaxError\"    — text that isn't valid code or valid JSON",
            "//   \"none\"           — no error at all",
            "const SNIPPETS = {",
            "  a: function () { const user = null; return user.name; },",
            "  b: function () { return totl + 1; },",
            "  c: function () { return JSON.parse(\"{name: 'Ada'}\"); },",
            "  d: function () { const n = 5; return n.toUpperCase(); },",
            "  e: function () { let items; return items.length; },",
            "  f: function () { return [1, 2, 3].map(function (x) { return x * 2; }); },",
            "  g: function () { return formatPrice(9.5); },",
            "  h: function () { return JSON.parse(\"\"); }",
            "};",
            "",
            "const PREDICT = {",
            "  a: \"\", b: \"\", c: \"\",",
            "  d: \"\", e: \"\", f: \"\",",
            "  g: \"\", h: \"\"",
            "};",
            "",
            "// Then check yourself — uncomment to run one and read what it says:",
            "// try { SNIPPETS.a(); } catch (err) { console.log(err.name + \": \" + err.message); }",
            "") }
        ],
        hints: [
          "Reading a property of something that is `null` or `undefined` is always a TypeError — the name exists, the value is just the wrong kind.",
          "`totl` and `formatPrice` are never declared anywhere in the file. A name that doesn't exist is a ReferenceError.",
          "`JSON.parse` throws a SyntaxError for text that isn't valid JSON — and an empty string isn't. `f` maps an array; nothing is wrong with it."
        ],
        solution: {
          "script.js": L(
            "const SNIPPETS = {",
            "  a: function () { const user = null; return user.name; },",
            "  b: function () { return totl + 1; },",
            "  c: function () { return JSON.parse(\"{name: 'Ada'}\"); },",
            "  d: function () { const n = 5; return n.toUpperCase(); },",
            "  e: function () { let items; return items.length; },",
            "  f: function () { return [1, 2, 3].map(function (x) { return x * 2; }); },",
            "  g: function () { return formatPrice(9.5); },",
            "  h: function () { return JSON.parse(\"\"); }",
            "};",
            "",
            "const PREDICT = {",
            "  a: \"TypeError\", b: \"ReferenceError\", c: \"SyntaxError\",",
            "  d: \"TypeError\", e: \"TypeError\", f: \"none\",",
            "  g: \"ReferenceError\", h: \"SyntaxError\"",
            "};",
            "",
            "try { SNIPPETS.a(); } catch (err) { console.log(err.name + \": \" + err.message); }",
            "")
        }
      },

      {
        id: "debug-u1-2",
        title: "Anatomy of an error: name, message, where",
        kind: "js", chip: "DEBUG", xp: 15, mins: 13,
        brief: "An error is not a failure state — it is an **object**, and it was built to tell you three things:\n\n- `e.name` — the type: `\"TypeError\"`, `\"ReferenceError\"`…\n- `e.message` — what went wrong, in the engine's words.\n- `e.stack` — the name and message again, then one line per function that was running, **newest first**: `at applyCoupon (script.js:3:34)` means *thrown inside `applyCoupon`, in `script.js`, line 3, column 34*.\n\nThat first `at` line is where the error was **thrown**. It is the first place to look — not the line that *called* the function, not the line you last edited.\n\nWrite `anatomy(e)`: given an error you caught, return `{ name, message, line }`, where `line` is the number from the first `script.js:LINE:COL` in `e.stack`. When no frame in the stack belongs to your file — an error that came from somewhere else entirely — return `line: null`.\n\n(These line numbers are the editor's own. Run the file with the `console.log(e.stack)` line uncommented and compare.)",
        steps: [
          { text: "`anatomy(e)` returns the error's `name` and `message`.",
            test: L(
              "var e1 = null;",
              "try { applyCoupon({ total: 20 }); } catch (e) { e1 = e; }",
              "T.expect(e1, 'applyCoupon({ total: 20 }) should throw — leave applyCoupon exactly as shipped.');",
              "var a = anatomy(e1);",
              "T.eq(a.name, 'TypeError', 'name is the error type — e.name');",
              "T.eq(a.message, \"Cannot read properties of undefined (reading 'amount')\", 'message is e.message, word for word');") },
          { text: "`line` is the number in the stack's first `script.js:LINE:COL` — where it was thrown.",
            test: L(
              "var e1 = null;",
              "try { applyCoupon({ total: 20 }); } catch (e) { e1 = e; }",
              "var src = __FILES['script.js'].split('\\n');",
              "var want = 0;",
              "for (var i = 0; i < src.length; i++) if (src[i].indexOf('cart.coupon.amount') !== -1 && src[i].indexOf('return') !== -1) { want = i + 1; break; }",
              "T.expect(want > 0, 'Keep applyCoupon as shipped — its line `return cart.total - cart.coupon.amount;` is what the check looks for.');",
              "T.eq(anatomy(e1).line, want, 'The first frame of the stack is: ' + String(e1.stack).split('\\n')[1].trim() + ' — line is the number after script.js:');") },
          { text: "It works for any caught error — and returns `line: null` when no frame belongs to your file.",
            test: L(
              "var e2 = null;",
              "try { lineCount({}); } catch (e) { e2 = e; }",
              "var src = __FILES['script.js'].split('\\n');",
              "var want = 0;",
              "for (var i = 0; i < src.length; i++) if (src[i].indexOf('order.lines.length') !== -1 && src[i].indexOf('return') !== -1) { want = i + 1; break; }",
              "T.expect(want > 0, 'Keep lineCount as shipped.');",
              "T.eq(anatomy(e2), { name: 'TypeError', message: \"Cannot read properties of undefined (reading 'length')\", line: want }, 'anatomy of the lineCount error');",
              "var outside = new Error('thrown by code that is not in your file');",
              "T.eq(anatomy(outside).line, null, 'This error was thrown by the checks, so its stack has no script.js frame: ' + JSON.stringify(outside.stack) + ' — return null rather than a number.');") }
        ],
        files: [
          { name: "script.js", content: L(
            "// Shipped code. Each function has a bug you will CATCH, not fix.",
            "function applyCoupon(cart) {",
            "  return cart.total - cart.coupon.amount;",
            "}",
            "",
            "function lineCount(order) {",
            "  return order.lines.length;",
            "}",
            "",
            "// anatomy(e) takes an error you caught and returns its three parts:",
            "//   name    — the error's type, e.g. \"TypeError\"",
            "//   message — what went wrong, in the engine's words",
            "//   line    — the LINE in the stack's first \"script.js:LINE:COL\",",
            "//             or null when no frame in the stack is from this file",
            "function anatomy(e) {",
            "  return { name: \"\", message: \"\", line: 0 };",
            "}",
            "",
            "// Uncomment to see a real stack, then compare anatomy's answer:",
            "// try { applyCoupon({ total: 20 }); } catch (e) { console.log(e.stack); console.log(anatomy(e)); }",
            "") }
        ],
        hints: [
          "`name` and `message` are straight off the object: `e.name`, `e.message`.",
          "A regex finds the first frame: `/script\\.js:(\\d+):\\d+/.exec(e.stack)` — the line number is the first capture group, `m[1]`, as a string. Wrap it in `Number(...)`.",
          "When `exec` finds nothing it returns `null` — so `line: m ? Number(m[1]) : null`."
        ],
        solution: {
          "script.js": L(
            "function applyCoupon(cart) {",
            "  return cart.total - cart.coupon.amount;",
            "}",
            "",
            "function lineCount(order) {",
            "  return order.lines.length;",
            "}",
            "",
            "function anatomy(e) {",
            "  const m = /script\\.js:(\\d+):\\d+/.exec(e.stack);",
            "  return { name: e.name, message: e.message, line: m ? Number(m[1]) : null };",
            "}",
            "",
            "try { applyCoupon({ total: 20 }); } catch (e) { console.log(e.stack); console.log(anatomy(e)); }",
            "")
        }
      },

      {
        id: "debug-u1-3",
        title: "Classify what you caught: e.name and instanceof",
        kind: "js", chip: "DEBUG", xp: 15, mins: 14,
        brief: "Knowing the **type** of an error tells you what kind of problem you have — and each type points your eyes at a different thing:\n\n- A `TypeError` whose message says `Cannot read properties of null` → the culprit is a value that turned out `null` (or `undefined`). Go find where it came from.\n- A `TypeError` saying `cart.items.map is not a function` → the culprit is `cart.items`: it holds *something*, just not what you called on it.\n- A `ReferenceError` saying `notDeclared is not defined` → the culprit is that name: a typo, or a variable living in another scope.\n- A `SyntaxError` from `JSON.parse` → no culprit in *your* code at all; the input was bad.\n\nWrite `classify(fn)`: call `fn()`, and return `{ kind, culprit }` — `kind` is the error's name (or `\"none\"` if nothing threw), `culprit` is the thing the message blames (or `null`).\n\nThen one more tool. `e.name` is only a label — anyone can set it. **`instanceof`** checks the *family*: a `CouponError` built with `class CouponError extends TypeError` has the name `\"CouponError\"` but is still a TypeError. Write `family(e)` to report the family.",
        example: { lang: "js", code: "classify(() => null.total)        // { kind: \"TypeError\", culprit: \"null\" }\nclassify(() => totl + 1)          // { kind: \"ReferenceError\", culprit: \"totl\" }\nclassify(() => 1 + 1)             // { kind: \"none\", culprit: null }\nfamily(new CouponError(\"expired\"))  // \"TypeError\"" },
        steps: [
          { text: "`classify(fn)` reports the right `kind` for every bug in `BUGS` — and `\"none\"` for code that works.",
            test: L(
              "var want = ['TypeError', 'ReferenceError', 'TypeError', 'SyntaxError', 'TypeError', 'TypeError'];",
              "for (var i = 0; i < BUGS.length; i++) {",
              "  var got = classify(BUGS[i]);",
              "  T.expect(got && typeof got === 'object', 'classify() must return an object { kind, culprit } — for BUGS[' + i + '] it returned ' + JSON.stringify(got) + '.');",
              "  T.eq(got.kind, want[i], 'BUGS[' + i + '] kind');",
              "}",
              "T.eq(classify(function () { return 1 + 1; }).kind, 'none', 'code that runs cleanly');") },
          { text: "`culprit` names what the message blames: `\"null\"`/`\"undefined\"`, the thing that isn't a function, or the undefined name — `null` otherwise.",
            test: L(
              "T.eq(classify(BUGS[0]), { kind: 'TypeError', culprit: 'null' }, 'BUGS[0] reads .name of null');",
              "T.eq(classify(BUGS[1]), { kind: 'ReferenceError', culprit: 'notDeclared' }, 'BUGS[1] uses a name that was never declared');",
              "T.eq(classify(BUGS[2]), { kind: 'TypeError', culprit: 'cart.items.map' }, 'BUGS[2] calls something that is not a function');",
              "T.eq(classify(BUGS[3]), { kind: 'SyntaxError', culprit: null }, 'BUGS[3] is bad input — nothing in your code to blame');",
              "T.eq(classify(BUGS[4]), { kind: 'TypeError', culprit: 'undefined' }, 'BUGS[4] reads [0] of undefined');",
              "T.eq(classify(BUGS[5]), { kind: 'TypeError', culprit: 'cfg.load' }, 'BUGS[5]');",
              "T.eq(classify(function () { return totl * 2; }), { kind: 'ReferenceError', culprit: 'totl' }, 'a bug the file has never seen');",
              "T.eq(classify(function () { var x; x.y = 1; }), { kind: 'TypeError', culprit: 'undefined' }, 'setting a property counts too: \"Cannot set properties of undefined\"');",
              "T.eq(classify(function () { return 1 + 1; }), { kind: 'none', culprit: null }, 'nothing thrown');") },
          { text: "`family(e)` uses `instanceof` — a `CouponError` is a TypeError whatever its name says.",
            test: L(
              "T.expect(typeof CouponError === 'function', 'Keep the CouponError class from the starter.');",
              "var ce = new CouponError('coupon expired');",
              "T.eq(ce.name, 'CouponError', 'the class sets its own name');",
              "T.eq(family(ce), 'TypeError', 'e.name says CouponError, but CouponError extends TypeError — check instanceof');",
              "T.eq(family(new TypeError('x')), 'TypeError', 'a plain TypeError');",
              "T.eq(family(new ReferenceError('x')), 'ReferenceError', 'ReferenceError');",
              "T.eq(family(new SyntaxError('x')), 'SyntaxError', 'SyntaxError');",
              "T.eq(family(new RangeError('x')), 'Error', 'anything outside the three families is just \"Error\"');",
              "var liar = new Error('x'); liar.name = 'TypeError';",
              "T.eq(family(liar), 'Error', 'This error SAYS its name is TypeError but it is a plain Error — family() must check instanceof, not e.name');") }
        ],
        files: [
          { name: "script.js", content: L(
            "// Six bugs, each wrapped in a function so nothing runs until called.",
            "const BUGS = [",
            "  function () { const user = null; return user.name; },",
            "  function () { return notDeclared + 1; },",
            "  function () { const cart = { items: {} }; return cart.items.map(String); },",
            "  function () { return JSON.parse(\"{oops\"); },",
            "  function () { const order = {}; return order.lines[0]; },",
            "  function () { const cfg = {}; return cfg.load(); }",
            "];",
            "",
            "// classify(fn): call fn() and report { kind, culprit }.",
            "//   kind    — the error's name, or \"none\" if nothing threw",
            "//   culprit — \"Cannot read/set properties of X ...\" → X (\"null\" or \"undefined\")",
            "//             \"Y is not a function\"                  → Y",
            "//             \"Y is not defined\"                     → Y",
            "//             anything else                          → null",
            "function classify(fn) {",
            "  return { kind: \"\", culprit: null };",
            "}",
            "",
            "// A custom error: its NAME is CouponError, its FAMILY is TypeError.",
            "class CouponError extends TypeError {",
            "  constructor(message) {",
            "    super(message);",
            "    this.name = \"CouponError\";",
            "  }",
            "}",
            "",
            "// family(e): \"TypeError\", \"ReferenceError\" or \"SyntaxError\" by instanceof,",
            "// and \"Error\" for anything else.",
            "function family(e) {",
            "  return e.name;",
            "}",
            "",
            "console.log(classify(BUGS[0]));",
            "") }
        ],
        hints: [
          "Start with the shape: `try { fn(); } catch (e) { ... return { kind: e.name, culprit }; } return { kind: \"none\", culprit: null };`",
          "Pull the culprit out of `e.message` with one regex per pattern: `/^Cannot (read|set) properties of (null|undefined)/`, `/^(.+) is not a function$/`, `/^(.+) is not defined$/` — the capture group is the culprit.",
          "family: `if (e instanceof TypeError) return \"TypeError\";` — then the same for ReferenceError and SyntaxError, and `return \"Error\";` at the end. Never look at e.name."
        ],
        solution: {
          "script.js": L(
            "const BUGS = [",
            "  function () { const user = null; return user.name; },",
            "  function () { return notDeclared + 1; },",
            "  function () { const cart = { items: {} }; return cart.items.map(String); },",
            "  function () { return JSON.parse(\"{oops\"); },",
            "  function () { const order = {}; return order.lines[0]; },",
            "  function () { const cfg = {}; return cfg.load(); }",
            "];",
            "",
            "function culpritOf(message) {",
            "  let m = /^Cannot (?:read|set) properties of (null|undefined)/.exec(message);",
            "  if (m) return m[1];",
            "  m = /^(.+) is not a function$/.exec(message);",
            "  if (m) return m[1];",
            "  m = /^(.+) is not defined$/.exec(message);",
            "  if (m) return m[1];",
            "  return null;",
            "}",
            "",
            "function classify(fn) {",
            "  try {",
            "    fn();",
            "  } catch (e) {",
            "    return { kind: e.name, culprit: culpritOf(e.message) };",
            "  }",
            "  return { kind: \"none\", culprit: null };",
            "}",
            "",
            "class CouponError extends TypeError {",
            "  constructor(message) {",
            "    super(message);",
            "    this.name = \"CouponError\";",
            "  }",
            "}",
            "",
            "function family(e) {",
            "  if (e instanceof TypeError) return \"TypeError\";",
            "  if (e instanceof ReferenceError) return \"ReferenceError\";",
            "  if (e instanceof SyntaxError) return \"SyntaxError\";",
            "  return \"Error\";",
            "}",
            "",
            "console.log(classify(BUGS[0]));",
            "")
        }
      },

      {
        id: "debug-u1-4",
        title: "The messages you will see a thousand times",
        kind: "js", chip: "DEBUG", xp: 15, mins: 13,
        brief: "A handful of messages make up most of the errors you will ever read. Each has a fixed shape, and each shape translates into one concrete thing to go check:\n\n- `Cannot read properties of X (reading 'p')` → `the thing before .p was X`\n- `Cannot set properties of X (setting 'p')` → `the thing before .p was X`\n- `Y is not a function` → `Y is not a function: check what it holds`\n- `Y is not defined` → `Y was never declared`\n- `Cannot access 'Y' before initialization` → `Y was used above its let/const line`\n- `Assignment to constant variable.` → `a const was reassigned`\n- any message mentioning `JSON` → `the text is not valid JSON`\n- anything else → `unknown`\n\nThe first rule is the big one. In `Cannot read properties of undefined (reading 'name')`, the property **`name` is not the problem** — nothing is wrong with `.name`. The value to its *left* was undefined, and the real question is where that value came from.\n\nWrite `explain(message)` returning exactly those translations. It is a translator you are building for your own head: once you have written it, you stop reading these messages as noise.",
        example: { lang: "js", code: "explain(\"Cannot read properties of undefined (reading 'name')\")\n// \"the thing before .name was undefined\"\nexplain(\"formatPrice is not defined\")\n// \"formatPrice was never declared\"" },
        steps: [
          { text: "The read/set messages: `the thing before .p was X`.",
            test: L(
              "T.eq(explain(\"Cannot read properties of undefined (reading 'name')\"), 'the thing before .name was undefined');",
              "T.eq(explain(\"Cannot read properties of null (reading 'total')\"), 'the thing before .total was null');",
              "T.eq(explain(\"Cannot set properties of null (setting 'textContent')\"), 'the thing before .textContent was null');",
              "T.eq(explain(\"Cannot read properties of undefined (reading '0')\"), 'the thing before .0 was undefined', 'array indexes show up the same way');") },
          { text: "Functions, names and declarations: *not a function*, *not defined*, *before initialization*, *constant*.",
            test: L(
              "T.eq(explain('cart.items.map is not a function'), 'cart.items.map is not a function: check what it holds');",
              "T.eq(explain('formatPrice is not defined'), 'formatPrice was never declared');",
              "T.eq(explain(\"Cannot access 'total' before initialization\"), 'total was used above its let/const line');",
              "T.eq(explain('Assignment to constant variable.'), 'a const was reassigned');",
              "T.eq(explain('onSave is not a function'), 'onSave is not a function: check what it holds', 'a name the list never showed you');") },
          { text: "JSON and everything else — then prove it on errors thrown for real.",
            test: L(
              "T.eq(explain('Unexpected end of JSON input'), 'the text is not valid JSON');",
              "T.eq(explain('Unexpected token \\'h\\', \"hello\" is not valid JSON'), 'the text is not valid JSON');",
              "T.eq(explain('Invalid array length'), 'unknown', 'a message outside the list');",
              "var live = [",
              "  [function () { var u; return u.email; }, 'the thing before .email was undefined'],",
              "  [function () { return taxRate * 2; }, 'taxRate was never declared'],",
              "  [function () { return JSON.parse('{bad'); }, 'the text is not valid JSON'],",
              "  [function () { var p = 3; return p.trim(); }, 'p.trim is not a function: check what it holds']",
              "];",
              "live.forEach(function (pair) {",
              "  var msg = '';",
              "  try { pair[0](); } catch (e) { msg = e.message; }",
              "  T.eq(explain(msg), pair[1], 'explaining a real error, \"' + msg + '\"');",
              "});") }
        ],
        files: [
          { name: "script.js", content: L(
            "// explain(message) → a translation you can act on:",
            "//   \"Cannot read properties of X (reading 'p')\"  → \"the thing before .p was X\"",
            "//   \"Cannot set properties of X (setting 'p')\"   → \"the thing before .p was X\"",
            "//   \"Y is not a function\"             → \"Y is not a function: check what it holds\"",
            "//   \"Y is not defined\"                → \"Y was never declared\"",
            "//   \"Cannot access 'Y' before initialization\" → \"Y was used above its let/const line\"",
            "//   \"Assignment to constant variable.\" → \"a const was reassigned\"",
            "//   any message containing \"JSON\"    → \"the text is not valid JSON\"",
            "//   anything else                     → \"unknown\"",
            "function explain(message) {",
            "  return \"unknown\";",
            "}",
            "",
            "console.log(explain(\"Cannot read properties of undefined (reading 'name')\"));",
            "") }
        ],
        hints: [
          "One `if` per rule, each with a regex and a capture group: `let m = /^(.+) is not defined$/.exec(message); if (m) return m[1] + \" was never declared\";`",
          "The read/set rule needs two captures — the value and the property: `/^Cannot (?:read|set) properties of (null|undefined) \\((?:reading|setting) '(.+)'\\)$/`.",
          "Check `message === \"Assignment to constant variable.\"` exactly (note the full stop), and `message.includes(\"JSON\")` for the JSON rule. Return `\"unknown\"` last."
        ],
        solution: {
          "script.js": L(
            "function explain(message) {",
            "  let m = /^Cannot (?:read|set) properties of (null|undefined) \\((?:reading|setting) '(.+)'\\)$/.exec(message);",
            "  if (m) return \"the thing before .\" + m[2] + \" was \" + m[1];",
            "  m = /^(.+) is not a function$/.exec(message);",
            "  if (m) return m[1] + \" is not a function: check what it holds\";",
            "  m = /^(.+) is not defined$/.exec(message);",
            "  if (m) return m[1] + \" was never declared\";",
            "  m = /^Cannot access '(.+)' before initialization$/.exec(message);",
            "  if (m) return m[1] + \" was used above its let/const line\";",
            "  if (message === \"Assignment to constant variable.\") return \"a const was reassigned\";",
            "  if (message.includes(\"JSON\")) return \"the text is not valid JSON\";",
            "  return \"unknown\";",
            "}",
            "",
            "console.log(explain(\"Cannot read properties of undefined (reading 'name')\"));",
            "")
        }
      },

      {
        id: "debug-quiz-1",
        title: "Unit 1 quiz: Errors are messages",
        kind: "quiz", xp: 10,
        brief: "Error types, what an error object carries, and reading the messages you meet every day. 80% to pass.",
        questions: [
          { q: "Which error does this line throw?",
            code: "const order = { lines: [] };\norder.line.length;",
            lang: "js",
            choices: ["ReferenceError — order.line is not defined", "TypeError — reading .length of undefined", "SyntaxError — the dot after line is unexpected", "No error — it quietly evaluates to undefined"],
            answer: 1, explain: "`order` exists, so this is not a ReferenceError. `order.line` (a typo for `lines`) is a missing property, which quietly evaluates to `undefined` — no error yet. Reading `.length` OF that undefined is what throws a TypeError. The message names `length`, but the bug is the typo one step to its left." },
          { q: "What does the `line` in the first `at … (script.js:LINE:COL)` of a stack tell you?",
            choices: ["The line where you most recently edited the file", "The line that called the function that failed", "The line where the error was thrown", "The last line the program ran before starting"],
            answer: 2, explain: "A stack trace lists frames newest first, so the top frame is the function that was running when the error was thrown, and its line is the throw site. The line that CALLED it is the next frame down. Start reading at the top, then walk down to find where the bad value came from." },
          { q: "Your file contains a missing closing brace. What happens when you run it?",
            choices: ["Nothing runs: a SyntaxError is raised first", "Every line before the brace runs, then it throws", "Only the function missing its brace is skipped", "It runs, and the brace is inserted automatically"],
            answer: 0, explain: "JavaScript parses the whole file before running any of it. Text that can't be parsed is a SyntaxError, and nothing runs at all — not even line 1. That's why the SyntaxErrors you meet while a program is running almost always come from JSON.parse or similar, where the bad text is data rather than your code." },
          { q: "`cart.items.map is not a function` — where should you look first?",
            choices: ["At the definition of the `map` method", "At the array prototype, which failed to load", "At the callback you passed into `.map()`", "At what `cart.items` holds at that moment"],
            answer: 3, explain: "`map` is fine — arrays have it. The message says the thing you called it on doesn't: `cart.items` holds something that isn't an array (an object, a string, undefined). The fix is upstream, where cart.items got its value. A callback bug would throw later, from inside map, with a different message." },
          { q: "Why prefer `e instanceof TypeError` over `e.name === \"TypeError\"` when deciding how to handle an error?",
            choices: ["`instanceof` is faster in every modern JavaScript engine", "`e.name` is just a label; `instanceof` checks the family", "`e.name` is undefined for the built-in error types", "They always give the same answer, so style decides"],
            answer: 1, explain: "`name` is an ordinary writable property: a custom `class CouponError extends TypeError` usually sets it to \"CouponError\", and any code can overwrite it. `instanceof` walks the prototype chain, so subclasses still count as TypeErrors and a relabelled plain Error doesn't. Use name for display, instanceof for decisions." },
          { q: "`Cannot access 'total' before initialization` — what happened?",
            choices: ["It's a let/const, used above its declaration line", "`total` was never declared anywhere in this scope", "`total` holds null, so its value can't be read yet", "`total` is a const that some later line tried to change"],
            answer: 0, explain: "This is the temporal dead zone: a `let` or `const` exists from the start of its block but can't be touched until its declaration line has run. Using it earlier throws this ReferenceError. \"Not declared at all\" reads `total is not defined`; reassigning a const reads `Assignment to constant variable.`" }
        ]
      }
    ]
  });
})();
