/* Debugging & Diagnosis — Unit 4: Instrument — print debugging, done well */
(function () {
  function L() { return Array.prototype.join.call(arguments, "\n"); }

  var CART_SRC = L(
    "const CART = [",
    "  { id: 1, title: \"Mug\",     price: 12,     qty: 1 },",
    "  { id: 2, title: \"Poster\",  price: 20,     qty: 2 },",
    "  { id: 3, title: \"Sticker\", price: \"4.50\", qty: 1 },",
    "  { id: 4, title: \"Tote\",    price: 18,     qty: 1 }",
    "];");

  var INV_SRC = L(
    "const INVENTORY = [",
    "  { sku: \"SKU-1\", title: \"Mug\",      stock: 12 },",
    "  { sku: \"SKU-2\", title: \"Pen\",      stock: 40 },",
    "  { sku: \"SKU-3\", title: \"Tote\",     stock: 7 },",
    "  { sku: \"SKU-7\", title: \"Poster\",   stock: 3 },",
    "  { sku: \"SKU-5\", title: \"Sticker\",  stock: 120 },",
    "  { sku: \"SKU-6\", title: \"Notebook\", stock: 18 },",
    "  { sku: \"SKU-7\", title: \"Lamp\",     stock: 2 },",
    "  { sku: \"SKU-8\", title: \"Candle\",   stock: 9 }",
    "];");

  var ORDERS_SRC = L(
    "const ORDERS = [",
    "  { id: \"A1\", lines: [{ title: \"Mug\", qty: 2 }, { title: \"Pen\", qty: 1 }] },",
    "  { id: \"A2\", lines: [{ title: \"Tote\", qty: 1 }] }",
    "];");

  var SUMS_SRC = L(
    "const DATA = [1, 2, 3, 3, 4];",
    "",
    "// A colleague's version that \"skips duplicate readings\" — somewhere",
    "// its running total parts ways with the real one. Don't fix it.",
    "function buggySum(nums) {",
    "  let sum = 0;",
    "  for (let i = 0; i < nums.length; i++) {",
    "    if (nums[i] === nums[i - 1]) continue;",
    "    sum += nums[i];",
    "  }",
    "  return sum;",
    "}");

  window.CODELAB.addUnit("debug", {
    id: "debug-u4",
    title: "Instrument: print debugging, done well",
    icon: "🔦",
    blurb: "console.log isn't shameful — it's usually just done badly. Labelled logs, the console methods nobody uses, invariants that scream on their own, and watchpoints that remember what a value WAS.",
    cheat: [
      { h: "Label every log", lang: "js", code: L(
        "console.log(running);                          // 12, 52, 524.50 — which is which?",
        "console.log(\"item \" + item.id + \":\", running); // item 3: 524.50 — found it"),
        note: "A log you can't attribute to a line of code is noise." },
      { h: "The console methods nobody uses", lang: "js", code: L(
        "console.table(rows);           // one row per object, one column per key",
        "console.group(\"order A1\");     // indent everything until…",
        "console.groupEnd();",
        "console.count(\"retry\");        // retry: 1, retry: 2 …",
        "console.time(\"sync\"); /* … */ console.timeEnd(\"sync\");   // sync: 41ms"),
        note: "In this sandbox console.table prints as \"sku | title | stock\" lines." },
      { h: "Invariants that scream", lang: "js", code: L(
        "balance += tx.amount;",
        "console.assert(balance >= 0, \"balance went negative at \" + tx.id);",
        "// silent while true — \"Assertion failed: …\" the moment it isn't"),
        note: "console.assert never throws. It reports, and the program keeps going." },
      { h: "probe(): a watchpoint by hand", lang: "js", code: L(
        "const total = probe(\"total\", sum(items));  // records a COPY, returns the value",
        "probe(\"cart\", cart);",
        "cart.items.push(\"poster\");                 // the probe still shows the old cart"),
        note: "CodeLab's probe() isn't a browser API — in real DevTools, use console.log(structuredClone(x)) or a logpoint." },
      { h: "Live objects in real DevTools", lang: "js", code: L(
        "const cart = { items: [\"mug\"] };",
        "console.log(cart);             // expand it LATER in DevTools…",
        "cart.items.push(\"poster\");     // …and it shows BOTH items"),
        note: "DevTools evaluates an object when you expand it, not when it was logged. Log a copy when timing matters." }
    ],
    lessons: [

      {
        id: "debug-u4-1",
        title: "Label your logs, or you are reading soup",
        kind: "js", chip: "DEBUG", xp: 15, mins: 13,
        brief: "There's a persistent myth that `console.log` debugging is what beginners do before they learn a real debugger. Working engineers log all the time. What separates useful logging from noise is almost entirely one habit: **labels**.\n\nThe cart total below comes out as `\"524.5018\"` — a string, and nonsense. Someone has already dropped a `console.log(running)` into the loop, and the console shows `12`, `52`, `524.50`, `524.5018`. Four numbers and no way to tell which line of the cart produced which. That's soup.\n\nLabel it: every line should say **which item** it's about and **what** the number is — `item 3: running = 524.50`. The moment you do, the bug points at itself: one item is where the running total stops being a number and starts being text glued onto text.\n\nLabel the log, read what it tells you, record the culprit's id in `FIRST_BAD`, then fix `cartTotal` so it returns the real total.",
        steps: [
          { text: "Every pass through the loop logs a line that starts with `item <id>:` and includes the running total.",
            test: L(
              "__LOGS.length = 0;",
              "cartTotal(CART);",
              "var lines = T.logLines();",
              "CART.forEach(function (it) {",
              "  var hit = lines.filter(function (l) { return l.indexOf('item ' + it.id + ':') === 0; });",
              "  T.expect(hit.length === 1, 'Expected exactly one log line starting \"item ' + it.id + ':\" — the console had: ' + JSON.stringify(lines));",
              "});",
              "T.expect(!lines.some(function (l) { return /^-?[\\d.]+$/.test(l.trim()); }), 'A bare number is still in the console: label every line.');",
              "T.expect(!T.logged('[object Object]'), 'Something logged [object Object] — log fields, not string-glued objects.');") },
          { text: "Read your own logs: `FIRST_BAD` is the id of the item where the running total stops being a number.",
            test: "T.eq(FIRST_BAD, 3, 'Look at the labelled lines: after which item does the running total turn into glued-together text?');" },
          { text: "Fix it: `cartTotal(CART)` returns the number `74.5`.",
            test: L(
              "var t = cartTotal(CART);",
              "T.eq(typeof t, 'number', 'the total must be a number, not text — something is being added as a string');",
              "T.eq(t, 74.5, '12 + 20×2 + 4.50 + 18');",
              "T.eq(cartTotal([{ id: 9, title: 'x', price: '2.25', qty: 2 }]), 4.5, 'a string price with qty > 1 works too');") }
        ],
        files: [
          { name: "script.js", content: L(
            CART_SRC,
            "",
            "function cartTotal(items) {",
            "  let running = 0;",
            "  for (const item of items) {",
            "    // skip the multiply for single items (a \"performance\" tweak from 2019)",
            "    const line = item.qty > 1 ? item.price * item.qty : item.price;",
            "    running = running + line;",
            "    console.log(running);",
            "  }",
            "  return running;",
            "}",
            "",
            "// After you've labelled the log and read it: the id of the item",
            "// where the running total stops being a number.",
            "const FIRST_BAD = 0;",
            "",
            "console.log(\"total:\", cartTotal(CART));",
            "") }
        ],
        hints: [
          "Give each line a label and a value: `console.log(\"item \" + item.id + \":\", \"running =\", running);`",
          "In the labelled output, one running total suddenly looks like two numbers stuck together. Which item's line is that? That id goes in FIRST_BAD.",
          "Sticker's price is the string `\"4.50\"`. `item.price * item.qty` would convert it — but the single-item shortcut adds the string itself. `Number(item.price) * item.qty` for every item fixes it."
        ],
        solution: {
          "script.js": L(
            CART_SRC,
            "",
            "function cartTotal(items) {",
            "  let running = 0;",
            "  for (const item of items) {",
            "    const line = Number(item.price) * item.qty;",
            "    running = running + line;",
            "    console.log(\"item \" + item.id + \":\", \"running =\", running);",
            "  }",
            "  return running;",
            "}",
            "",
            "const FIRST_BAD = 3;",
            "",
            "console.log(\"total:\", cartTotal(CART));",
            "")
        }
      },

      {
        id: "debug-u4-2",
        title: "console.table, group, count and time",
        kind: "js", chip: "DEBUG", xp: 15, mins: 15,
        brief: "`console.log` is one tool on a shelf of them, and the rest are built for exactly the jobs people use `log` badly for:\n\n- `console.table(rows)` — an array of objects as a **table**, one row each. Duplicates and outliers jump out of a column in a way they never do from a wall of `{…}`. (In this sandbox it prints as `sku | title | stock` lines.)\n- `console.group(label)` … `console.groupEnd()` — everything logged in between is **indented** under the label, so the output has the same shape as the work.\n- `console.count(label)` — prints `label: 1`, `label: 2`… How many times did that retry actually run?\n- `console.time(label)` … `console.timeEnd(label)` — prints how long the stretch in between took: `sync: 41ms`.\n\nThe inventory sync has a duplicate SKU somewhere, and nobody knows how often the flaky fetch retries. Instrument it with the right tool for each job.",
        steps: [
          { text: "`showInventory()` prints `INVENTORY` with `console.table` — a header line, then one line per row.",
            test: L(
              "__LOGS.length = 0;",
              "showInventory();",
              "var lines = T.logLines();",
              "T.eq(lines[0], 'sku | title | stock', 'console.table(INVENTORY) prints a header of the column names first');",
              "T.eq(lines.length, 1 + INVENTORY.length, 'a header and one line per inventory row — nothing else');",
              "T.eq(lines[1], 'SKU-1 | Mug | 12', 'then one line per row');") },
          { text: "Read the table: `DUPLICATE` is the SKU that appears twice.",
            test: "T.eq(DUPLICATE, 'SKU-7', 'Scan the sku column of your table — one value is on two rows');" },
          { text: "`syncAll(ORDERS)` puts each order in a `console.group`, its lines indented inside, and times the whole run with `console.time`.",
            test: L(
              "__LOGS.length = 0;",
              "syncAll(ORDERS);",
              "var lines = T.logLines().filter(function (l) { return !/^sync: \\d+ms$/.test(l); });",
              "T.eq(lines, ['order A1', '  Mug x2', '  Pen x1', 'order A2', '  Tote x1'], 'a group per order, its lines indented under it, and each group closed before the next');",
              "T.expect(T.logLines().some(function (l) { return /^sync: \\d+ms$/.test(l); }), 'Time the whole run: console.time(\"sync\") before the loop, console.timeEnd(\"sync\") after it.');") },
          { text: "`fetchWithRetry(attempt)` calls `console.count(\"retry\")` on every retry — never on the first try.",
            test: L(
              "function flaky(failures) { var n = 0; return function () { n++; if (n <= failures) throw new Error('503'); return 'ok'; }; }",
              "__LOGS.length = 0;",
              "T.eq(fetchWithRetry(flaky(2)), 'ok', 'it still returns the result');",
              "T.eq(T.countLogged('retry: '), 2, 'failed twice, so two retries — count retries, not attempts');",
              "__LOGS.length = 0;",
              "fetchWithRetry(flaky(0));",
              "T.eq(T.countLogged('retry: '), 0, 'succeeded first time: no retries, so no count lines');") }
        ],
        files: [
          { name: "script.js", content: L(
            INV_SRC,
            "",
            "// 1) Print the inventory as a table.",
            "function showInventory() {",
            "  INVENTORY.forEach(function (row) { console.log(row); });",
            "}",
            "",
            "// 2) Which SKU appears twice? Read your table.",
            "const DUPLICATE = \"\";",
            "",
            ORDERS_SRC,
            "",
            "// 3) One console.group per order (\"order A1\"), each line inside it",
            "//    (\"Mug x2\"), console.groupEnd() — and time the whole run as \"sync\".",
            "function syncAll(orders) {",
            "  for (const order of orders) {",
            "    for (const line of order.lines) {",
            "      console.log(line.title + \" x\" + line.qty);",
            "    }",
            "  }",
            "}",
            "",
            "// 4) Try attempt() up to 5 times. console.count(\"retry\") on each RETRY.",
            "function fetchWithRetry(attempt) {",
            "  for (let i = 0; i < 5; i++) {",
            "    try {",
            "      return attempt();",
            "    } catch (e) {",
            "      // failed — the loop goes round again",
            "    }",
            "  }",
            "  throw new Error(\"gave up after 5 attempts\");",
            "}",
            "",
            "showInventory();",
            "") }
        ],
        hints: [
          "`console.table(INVENTORY);` replaces the whole forEach. For syncAll: `console.group(\"order \" + order.id);` before the inner loop and `console.groupEnd();` after it.",
          "Wrap the outer loop in `console.time(\"sync\");` … `console.timeEnd(\"sync\");` — same label on both.",
          "A retry is an attempt after a failure. Count inside the loop but only when `i > 0`: `if (i > 0) console.count(\"retry\");` just before `return attempt();`."
        ],
        solution: {
          "script.js": L(
            INV_SRC,
            "",
            "function showInventory() {",
            "  console.table(INVENTORY);",
            "}",
            "",
            "const DUPLICATE = \"SKU-7\";",
            "",
            ORDERS_SRC,
            "",
            "function syncAll(orders) {",
            "  console.time(\"sync\");",
            "  for (const order of orders) {",
            "    console.group(\"order \" + order.id);",
            "    for (const line of order.lines) {",
            "      console.log(line.title + \" x\" + line.qty);",
            "    }",
            "    console.groupEnd();",
            "  }",
            "  console.timeEnd(\"sync\");",
            "}",
            "",
            "function fetchWithRetry(attempt) {",
            "  for (let i = 0; i < 5; i++) {",
            "    try {",
            "      if (i > 0) console.count(\"retry\");",
            "      return attempt();",
            "    } catch (e) {",
            "      // failed — the loop goes round again",
            "    }",
            "  }",
            "  throw new Error(\"gave up after 5 attempts\");",
            "}",
            "",
            "showInventory();",
            "")
        }
      },

      {
        id: "debug-u4-3",
        title: "console.assert and the invariant that screams",
        kind: "js", chip: "DEBUG", xp: 15, mins: 13,
        brief: "Logging answers questions you already thought to ask. An **invariant** answers the ones you didn't: a statement that must *always* be true at a given point — *the balance is never negative*, *every order has at least one line* — checked every time the code passes that point.\n\n`console.assert(condition, message)` is the lightest way to write one. While the condition holds, it is completely silent. The moment it fails, it prints `Assertion failed: …` — and, unlike the `assert()` you'd write for a test, it **does not throw**: the program carries on, so you learn *when* things went wrong without changing *what* happens.\n\nTwo things make an assertion useful rather than noisy. It must be **tight** — true for every legitimate state, including the edges (a balance of exactly `0` is fine). And its message must say **where** — which transaction broke the rule.\n\nAdd the invariant to `settle()`: after every transaction, the balance must be `>= 0`, and when it isn't, the message reads `balance went negative at <id>`.",
        example: { lang: "js", code: "console.assert(balance >= 0, \"balance went negative at \" + tx.id);" },
        steps: [
          { text: "On the poisoned ledger, the assertion fires once, naming the transaction: `Assertion failed: balance went negative at t4`.",
            test: L(
              "T.expect(/console\\.assert\\s*\\(/.test(String(settle)), 'Use console.assert inside settle() — that is the tool this lesson is about.');",
              "__LOGS.length = 0;",
              "settle(POISONED);",
              "T.eq(T.countLogged('Assertion failed: balance went negative at t4'), 1, 'After t4 the balance is -5 — the assertion should fire exactly then, and say so. The console had: ' + JSON.stringify(T.logLines()));",
              "T.eq(T.countLogged('Assertion failed'), 1, 'only t4 breaks the rule; by t5 the balance is back to 25');") },
          { text: "It's tight: silent on a clean ledger — even when the balance touches exactly `0`.",
            test: L(
              "__LOGS.length = 0;",
              "settle(CLEAN);",
              "T.eq(T.countLogged('Assertion failed'), 0, 'The clean ledger reaches a balance of exactly 0 after t3. Zero is not negative — the invariant is balance >= 0.');") },
          { text: "It observes without interfering: `settle()` still returns the final balance, and never throws.",
            test: L(
              "var a, b, threw = false;",
              "try { a = settle(POISONED); b = settle(CLEAN); } catch (e) { threw = true; }",
              "T.expect(!threw, 'settle() threw — console.assert only REPORTS; a thrown error would stop the whole run.');",
              "T.eq(a, 25, 'settle(POISONED)');",
              "T.eq(b, 10, 'settle(CLEAN)');") }
        ],
        files: [
          { name: "script.js", content: L(
            "const CLEAN = [",
            "  { id: \"t1\", amount: 50 },",
            "  { id: \"t2\", amount: -20 },",
            "  { id: \"t3\", amount: -30 },   // balance is exactly 0 here — that's fine",
            "  { id: \"t4\", amount: 10 }",
            "];",
            "",
            "const POISONED = [",
            "  { id: \"t1\", amount: 50 },",
            "  { id: \"t2\", amount: -20 },",
            "  { id: \"t3\", amount: 5 },",
            "  { id: \"t4\", amount: -40 },",
            "  { id: \"t5\", amount: 30 }",
            "];",
            "",
            "function settle(txs) {",
            "  let balance = 0;",
            "  for (const tx of txs) {",
            "    balance += tx.amount;",
            "    // invariant: the balance is never negative",
            "  }",
            "  return balance;",
            "}",
            "",
            "console.log(settle(CLEAN), settle(POISONED));",
            "") }
        ],
        hints: [
          "The assertion goes right after the line that changes the balance, inside the loop.",
          "`console.assert(balance >= 0, \"balance went negative at \" + tx.id);` — `>=`, not `>`: zero is a legitimate balance.",
          "Don't `throw` and don't `return` early — the lesson checks that settle() still finishes and returns the balance."
        ],
        solution: {
          "script.js": L(
            "const CLEAN = [",
            "  { id: \"t1\", amount: 50 },",
            "  { id: \"t2\", amount: -20 },",
            "  { id: \"t3\", amount: -30 },",
            "  { id: \"t4\", amount: 10 }",
            "];",
            "",
            "const POISONED = [",
            "  { id: \"t1\", amount: 50 },",
            "  { id: \"t2\", amount: -20 },",
            "  { id: \"t3\", amount: 5 },",
            "  { id: \"t4\", amount: -40 },",
            "  { id: \"t5\", amount: 30 }",
            "];",
            "",
            "function settle(txs) {",
            "  let balance = 0;",
            "  for (const tx of txs) {",
            "    balance += tx.amount;",
            "    console.assert(balance >= 0, \"balance went negative at \" + tx.id);",
            "  }",
            "  return balance;",
            "}",
            "",
            "console.log(settle(CLEAN), settle(POISONED));",
            "")
        }
      },

      {
        id: "debug-u4-4",
        title: "Watchpoints by hand: probe() and the timeline",
        kind: "js", chip: "DEBUG", xp: 15, mins: 15,
        brief: "A debugger can *watch* a variable and show you every value it takes. You can get most of that with one function. This sandbox gives you `probe(name, value)`: it records a **copy** of the value under a name, prints it to the console (`◆ sum = 3`), and **returns the value unchanged** — so it drops into the middle of any expression: `const total = probe(\"total\", add(a, b));`.\n\nProbe the same variable at every step and you get its **timeline**. Put two timelines side by side — the working version and the broken one — and the bug is at the first **tick** where they disagree. Before that tick, both agree; after it, everything is contaminated. That first divergence is the only place worth reading.\n\nThe copy matters too. In real DevTools, `console.log(cart)` hands the console a *live* object: expand it after the code has changed `cart` and you see the new contents, not what it held when the line ran. A probe records what it **was**.\n\n(`probe` is a CodeLab tool, not a browser API. In real DevTools the same moves are a *logpoint* — a breakpoint that logs instead of pausing — or `console.log(structuredClone(value))`.)",
        steps: [
          { text: "Instrument `runningSum`: probe `\"sum\"` once before the loop and again after every addition.",
            test: L(
              "__TRACE.length = 0;",
              "var r = runningSum([1, 2, 3, 4, 5]);",
              "T.eq(r, 15, 'runningSum still returns the total');",
              "T.eq(T.traceOf('sum'), [0, 1, 3, 6, 10, 15], 'the timeline of sum: its starting value, then its value after each addition');") },
          { text: "Instrument `buggySum` the same way under the name `\"buggy\"`, run both on `DATA`, and record the first tick where they disagree in `FIRST_BAD`.",
            test: L(
              "__TRACE.length = 0;",
              "runningSum(DATA);",
              "buggySum(DATA);",
              "T.eq(T.traceOf('sum'), [0, 1, 3, 6, 9, 13], 'the correct timeline on DATA');",
              "var b = T.traceOf('buggy');",
              "T.eq(b.length, 6, 'probe \"buggy\" before buggySum\\'s loop and on every pass through it — including passes where it skips — so the ticks line up with sum. Got ' + JSON.stringify(b));",
              "T.eq(FIRST_BAD, T.firstDivergence('buggy', T.traceOf('sum')), 'FIRST_BAD is the index of the first tick where the two timelines disagree — compare the ◆ lines in the console');") },
          { text: "A probe keeps a **copy**: probe the cart in `addPoster` before it changes, and the timeline still shows the old contents.",
            test: L(
              "__TRACE.length = 0;",
              "var c = { items: ['mug'] };",
              "var back = addPoster(c);",
              "T.eq(c.items, ['mug', 'poster'], 'addPoster still adds the poster');",
              "T.eq(back, c, 'and still returns the cart');",
              "T.eq(T.traceOf('cart'), [{ items: ['mug'] }], 'probe(\"cart\", cart) BEFORE the push — the recorded copy must still show just the mug, even though the cart has since changed');") }
        ],
        files: [
          { name: "script.js", content: L(
            "// probe(name, value): records a COPY of value, prints it, returns value.",
            "",
            "function runningSum(nums) {",
            "  let sum = 0;",
            "  for (const n of nums) {",
            "    sum += n;",
            "  }",
            "  return sum;",
            "}",
            "",
            SUMS_SRC,
            "",
            "// The first tick (index) where buggy's timeline disagrees with sum's.",
            "const FIRST_BAD = -1;",
            "",
            "function addPoster(cart) {",
            "  cart.items.push(\"poster\");",
            "  return cart;",
            "}",
            "",
            "runningSum(DATA);",
            "buggySum(DATA);",
            "") }
        ],
        hints: [
          "One probe before the loop, one after `sum += n;`: `probe(\"sum\", sum);` — for five numbers that's six ticks.",
          "In buggySum, `continue` jumps past everything after it — a probe placed after `sum += nums[i];` never runs on a skipped pass, and the ticks stop lining up with sum. Probe on the skip path too: `if (nums[i] === nums[i - 1]) { probe(\"buggy\", sum); continue; }`.",
          "Read the ◆ lines: sum goes 0 1 3 6 9 13 and buggy goes 0 1 3 6 6 10 — the first index where they differ is FIRST_BAD. In addPoster, `probe(\"cart\", cart);` goes on the line before the push."
        ],
        solution: {
          "script.js": L(
            "function runningSum(nums) {",
            "  let sum = 0;",
            "  probe(\"sum\", sum);",
            "  for (const n of nums) {",
            "    sum += n;",
            "    probe(\"sum\", sum);",
            "  }",
            "  return sum;",
            "}",
            "",
            "const DATA = [1, 2, 3, 3, 4];",
            "",
            "function buggySum(nums) {",
            "  let sum = 0;",
            "  probe(\"buggy\", sum);",
            "  for (let i = 0; i < nums.length; i++) {",
            "    if (nums[i] === nums[i - 1]) { probe(\"buggy\", sum); continue; }",
            "    sum += nums[i];",
            "    probe(\"buggy\", sum);",
            "  }",
            "  return sum;",
            "}",
            "",
            "const FIRST_BAD = 4;",
            "",
            "function addPoster(cart) {",
            "  probe(\"cart\", cart);",
            "  cart.items.push(\"poster\");",
            "  return cart;",
            "}",
            "",
            "runningSum(DATA);",
            "buggySum(DATA);",
            "")
        }
      },

      {
        id: "debug-quiz-4",
        title: "Unit 4 quiz: Instrument",
        kind: "quiz", xp: 10,
        brief: "Labelled logs, the console toolkit, assertions and watchpoints. 80% to pass.",
        questions: [
          { q: "Which console call makes a duplicate value in a list of 200 objects easiest to spot?",
            choices: ["`console.log(rows)`", "`console.table(rows)`", "`console.count(rows)`", "`console.dir(rows)`"],
            answer: 1, explain: "`console.table` lays the objects out as rows with one column per property, so a repeated value sits visibly in the same column. `console.log` and `console.dir` show a collapsed tree you'd have to expand item by item, and `console.count` counts calls to itself, not values in your data." },
          { q: "What happens when this line runs with `balance` equal to -5?",
            code: "console.assert(balance >= 0, \"balance went negative\");",
            lang: "js",
            choices: ["It throws an error and the function stops", "It returns false to the caller", "It logs \"Assertion failed: balance went negative\" and carries on", "Nothing at all — assertions only ever run inside test runners like Jest"],
            answer: 2, explain: "`console.assert` is a reporting tool, not a control-flow one: a false condition prints \"Assertion failed:\" plus your message, and execution continues. That's what makes it safe to leave invariants in running code while you investigate. The `assert()` you write for a test throws; this one never does." },
          { q: "You log `cart` in real DevTools, the code then pushes a new item, and you expand the logged object. What do you see?",
            choices: ["The cart as it was when the line ran", "An error: the object has since changed", "Nothing — objects can't be expanded later", "The cart as it is now, new item included"],
            answer: 3, explain: "DevTools keeps a live reference and reads the object's properties when you expand it, so later mutations show up — a classic way to be misled. To see what a value WAS at a moment, log a copy (structuredClone, JSON round-trip) or use something that snapshots, like the probe() timeline in this unit." },
          { q: "Two timelines of the same variable agree for ticks 0–3 and differ from tick 4 on. Where should you look?",
            choices: ["At whatever happened between tick 3 and tick 4", "At the last tick, where the difference is largest", "At tick 0, where the variable was created", "At every tick after 4, one by one"],
            answer: 0, explain: "Everything up to tick 3 is shared, so the bug hasn't struck yet; everything from tick 4 on is contaminated by it. The first divergence pins the fault to the code that ran between those two ticks. Differences later in the timeline are consequences, not causes, and reading them first wastes time." },
          { q: "Why does this log line help less than it looks like it should?",
            code: "for (const item of cart) {\n  console.log(running);\n}",
            lang: "js",
            choices: ["`console.log` is far too slow to call on every pass of a loop", "Numbers can't be printed without a label", "The output has no label to tie each number to an item", "It logs `running` before the loop has started"],
            answer: 2, explain: "Each line is just a bare number, so when one looks wrong you still have to reconstruct which pass through the loop printed it. Adding the item's id and the variable's name — `item 3: running = 524.50` — makes every line self-explaining. The cost of a label is a few characters; the saving is the whole investigation." },
          { q: "An invariant says `balance >= 0`. Why is `balance > 0` the wrong assertion?",
            choices: ["`>` is slower than `>=` inside console.assert", "It fires on a legitimate zero balance, so it cries wolf", "It can never fire at all, because every balance starts out at 0", "Assertions don't accept the `>` operator"],
            answer: 1, explain: "A balance of exactly zero is a normal state, and `> 0` would flag it as a violation. An assertion that fires on legitimate states trains you to ignore it — then it's worthless when it finally catches a real bug. Write the tightest condition that is still true for every valid state, edges included." }
        ]
      }
    ]
  });
})();
