/* CodeLab interface — Spanish.
   Keys are the English strings exactly as app.js writes them (see i18n.js).
   Keep every {0}, {1}… placeholder; tools/validate-i18n.js checks them and
   fails on any key app.js uses that is missing here, or any key here that
   app.js no longer uses.

   Style: neutral Latin American Spanish, informal "tú". Technical words a
   learner will meet in English (HTML, CSS, JavaScript, XP, commit…) stay
   in English. */
window.CODELAB.i18n.addStrings("es", {
  /* ---- names app.js passes through a variable ---- */
  "Full-Stack Engineer Path": "Ruta de Ingeniería Full-Stack",
  "Base": "Base",
  "Professional": "Profesional",
  "Dark": "Oscuro",
  "Alternative Light": "Claro alternativo",
  "Beginner": "Principiante",
  "Intermediate": "Intermedio",
  "Advanced": "Avanzado",
  "PROJECT": "PROYECTO",
  "QUIZ": "CUESTIONARIO",
  "THEORY": "TEORÍA",
  "SHELL": "TERMINAL",
  "JS": "JS",
  "WEB": "WEB",

  /* ---- theme, language, top bar ---- */
  "Choose Theme": "Elige un tema",
  "Language": "Idioma",
  "Lessons are written in English first. Where a translation isn't ready yet, you'll see the English. Code always stays in English.":
    "Las lecciones se escriben primero en inglés. Donde la traducción todavía no está lista, verás el texto en inglés. El código siempre queda en inglés.",
  "{0} to recall": "{0} por repasar",
  "Switch theme": "Cambiar tema",
  "Switch profile": "Cambiar de perfil",
  "Theme": "Tema",

  /* ---- profiles ---- */
  "Who's coding?": "¿Quién va a programar?",
  "Welcome! Create your profile": "¡Bienvenido! Crea tu perfil",
  "{0} done · {1} XP": "{0} completadas · {1} XP",
  "From your Academy app": "De tu app Academy",
  "New": "Nuevo",
  "Remove this profile from CodeLab": "Quitar este perfil de CodeLab",
  "Remove \"{0}\" from CodeLab? (Academy app data is untouched.)": "¿Quitar a \"{0}\" de CodeLab? (Los datos de la app Academy no se tocan.)",
  "Add learner": "Agregar estudiante",
  "New profile": "Perfil nuevo",
  "Your name": "Tu nombre",
  "Create": "Crear",
  "Connected to your Academy app — profiles, XP and streaks are shared on this device.":
    "Conectado a tu app Academy: los perfiles, el XP y las rachas se comparten en este dispositivo.",
  "Progress saves automatically on this device.": "Tu progreso se guarda automáticamente en este dispositivo.",

  /* ---- catalog ---- */
  "{0} COURSES · ~{1} HOURS · {2} CREDITS": "{0} CURSOS · ~{1} HORAS · {2} CRÉDITOS",
  "Learn to code, qualify for the job": "Aprende a programar y califica para el empleo",
  "Every course is a full, Codecademy-scale course, and finishing one pays credits toward every job position that needs it. Take them in order, or go straight at the position you want.":
    "Cada curso es un curso completo, del tamaño de los de Codecademy, y al terminarlo ganas créditos para todos los puestos de trabajo que lo piden. Tómalos en orden o ve directo al puesto que quieres.",
  "Recall": "Repaso",
  "{0} card": "{0} tarjeta",
  "{0} cards": "{0} tarjetas",
  "Path certificate": "Certificado de la ruta",
  "Start: {0}": "Empezar: {0}",
  "Continue: {0}": "Continuar: {0}",
  "Careers": "Empleos",
  "Which job positions your credits qualify you for": "Para qué puestos de trabajo te califican tus créditos",
  "Free sandbox": "Zona de pruebas libre",
  "Handoff": "Traspaso",
  "Move this profile between your phone and desktop": "Pasa este perfil entre tu teléfono y tu computadora",
  "GOAL": "META",
  "You meet every requirement — open Careers for the sheet.": "Cumples todos los requisitos: abre Empleos para ver la ficha.",
  "{0} / {1} credits": "{0} / {1} créditos",
  "next: {0}": "siguiente: {0}",
  "Sharing profiles & XP with your Academy app": "Compartiendo perfiles y XP con tu app Academy",
  "Roadmap": "Próximamente",
  "{0} cr": "{0} cr",
  "Course {0}": "Curso {0}",
  "Counts toward: {0}": "Cuenta para: {0}",
  "Not written yet": "Todavía no está escrito",
  "{0} is on the roadmap — no lessons yet.": "{0} está en la hoja de ruta: todavía no tiene lecciones.",
  "Complete": "Completado",
  "{0} items": "{0} actividades",
  "{0} credits expired — refresh with Recall": "{0} créditos vencidos: renuévalos con Repaso",
  "{0} credits expire in {1} days": "{0} créditos vencen en {1} días",
  "{0} credits on your transcript": "{0} créditos en tu historial",
  "Review · certificate": "Repasar · certificado",
  "Continue →": "Continuar →",
  "Start course →": "Empezar el curso →",
  "{0} courses · ~{1} hours of hands-on material · you hold {2} of {3} credits · progress saves automatically":
    "{0} cursos · ~{1} horas de práctica · tienes {2} de {3} créditos · el progreso se guarda automáticamente",
  "Reset my CodeLab progress": "Reiniciar mi progreso en CodeLab",
  "Reset {0}'s CodeLab progress, XP, streak and saved code? (Academy app tracks are untouched.)":
    "¿Reiniciar el progreso, el XP, la racha y el código guardado de {0} en CodeLab? (Las rutas de la app Academy no se tocan.)",

  /* ---- careers ---- */
  "{0} credit": "{0} crédito",
  "{0} credits": "{0} créditos",
  "Qualified": "Calificas",
  "Needs new courses": "Faltan cursos",
  "{0} to go": "faltan {0}",
  "Almost there": "Ya casi",
  "CAREERS · {0} POSITIONS": "EMPLEOS · {0} PUESTOS",
  "What you qualify for": "Para qué calificas",
  "Every course you finish pays credits into your transcript. Positions unlock when you hold enough — one course counts toward every position that needs it.":
    "Cada curso que terminas suma créditos a tu historial. Los puestos se desbloquean cuando tienes suficientes, y un mismo curso cuenta para todos los puestos que lo piden.",
  "credits held": "créditos obtenidos",
  "{0} expired": "{0} vencidos",
  "Courses": "Cursos",
  "Transcript": "Historial",
  "You meet every requirement on this sheet.": "Cumples todos los requisitos de esta ficha.",
  "{0} tops out at {1} credits in the catalog so far — this sheet needs {2}.":
    "{0} llega a un máximo de {1} créditos en el catálogo por ahora; esta ficha pide {2}.",
  "Requires a course that has not been written yet.": "Requiere un curso que todavía no está escrito.",
  "Next: {0}": "Siguiente: {0}",
  "Finish what you have started.": "Termina lo que empezaste.",
  "Credits expire after {0} years — keeping a course's Recall drills current resets its clock.":
    "Los créditos vencen a los {0} años. Mantener al día los repasos de un curso reinicia su plazo.",
  "Screened on:": "Se evalúa en:",
  "Credits": "Créditos",
  "{0} of {1} required": "{0} de {1} requeridos",
  "{0} short": "faltan {0}",
  "Category minimums": "Mínimos por categoría",
  "Required courses": "Cursos obligatorios",
  "not written yet": "todavía no está escrito",
  "expired": "vencido",
  "Why this is blocked": "Por qué está bloqueado",
  "{0} needs {1} credits but every course written so far supplies only {2}. Short {3}.":
    "{0} pide {1} créditos, pero todos los cursos escritos hasta ahora suman solo {2}. Faltan {3}.",
  "{0} is required but has no lessons yet.": "{0} es obligatorio, pero todavía no tiene lecciones.",
  "On the roadmap: {0}.": "En la hoja de ruta: {0}.",
  "Unpin goal": "Quitar meta",
  "Pin as my goal": "Fijar como mi meta",
  "Goal cleared": "Meta quitada",
  "Goal set: {0}": "Meta fijada: {0}",
  "Close": "Cerrar",
  "{0} currently held": "{0} en este momento",
  "No credits yet. Finish a course — credits are awarded for the whole course, never for single lessons.":
    "Todavía no tienes créditos. Termina un curso: los créditos se dan por el curso completo, nunca por lecciones sueltas.",
  "{0}d left": "quedan {0} d",
  "Current": "Vigentes",
  "Expired — refresh with Recall to restore": "Vencidos: renuévalos con Repaso para recuperarlos",
  "By category": "Por categoría",
  "Print / save as PDF": "Imprimir / guardar como PDF",

  /* ---- course screen ---- */
  "That course has not been written yet.": "Ese curso todavía no está escrito.",
  "Loading {0}…": "Cargando {0}…",
  "{0} — check your connection and try again": "{0}: revisa tu conexión e inténtalo de nuevo",
  "All courses": "Todos los cursos",
  "COURSE · ~{0} HOURS · {1}": "CURSO · ~{0} HORAS · {1}",
  "View certificate": "Ver certificado",
  "Unit {0}": "Unidad {0}",
  "Cheatsheet": "Guía rápida",
  "+{0} XP · ~{1} min": "+{0} XP · ~{1} min",
  "Finish the previous lesson first": "Primero termina la lección anterior",
  "{0} items in this course · ~{1} hours": "{0} actividades en este curso · ~{1} horas",
  "Done": "Listo",
  "{0} — cheatsheet": "{0}: guía rápida",
  "Glossary": "Glosario",

  /* ---- certificate ---- */
  "{0} items · {1} projects · ~{2} hours": "{0} actividades · {1} proyectos · ~{2} horas",
  "{0} courses · {1} items · {2} XP": "{0} cursos · {1} actividades · {2} XP",
  "Certificate of Completion": "Certificado de finalización",
  "awarded to": "otorgado a",

  /* ---- lesson workspace ---- */
  "Sandbox": "Zona de pruebas",
  "Your own scratchpad — build anything. **Run** shows your page in Result. Code autosaves per profile.\n\nNothing is graded here; it's just you and the browser.":
    "Tu propio espacio para experimentar: construye lo que quieras. **Ejecutar** muestra tu página en Resultado. El código se guarda solo, en tu perfil.\n\nAquí nada se califica; solo estás tú y el navegador.",
  "Leave this drill? It counts as a miss and comes back tomorrow.": "¿Salir de este ejercicio? Cuenta como fallo y vuelve mañana.",
  "RECALL · DRILL {0}/{1}": "REPASO · EJERCICIO {0}/{1}",
  "PLAYGROUND": "ZONA DE PRUEBAS",
  "UNIT {0}": "UNIDAD {0}",
  "Terminal": "Terminal",
  "Output": "Salida",
  "Result": "Resultado",
  "Commands": "Comandos",
  "Code": "Código",
  "Learn": "Aprende",
  "More explanation": "Más explicación",
  "Checkpoints": "Puntos de control",
  "Hint ({0})": "Pista ({0})",
  "Next hint ({0} left)": "Siguiente pista (quedan {0})",
  "That's every hint": "Ya viste todas las pistas",
  "View solution": "Ver la solución",
  "Solution (after a run)": "Solución (después de ejecutar)",
  "Load the solution into the editor? Your current code for this lesson will be replaced (try the hints first!).":
    "¿Cargar la solución en el editor? Se reemplazará tu código actual de esta lección (¡prueba primero las pistas!).",
  "Solution loaded — read it, run it, tweak it 🧠": "Solución cargada: léela, ejecútala, modifícala 🧠",
  "Reset code": "Restablecer código",
  "Reset this lesson's files back to the starter code?": "¿Volver los archivos de esta lección al código inicial?",
  "Starter code restored": "Código inicial restablecido",
  "Practice from scratch": "Practicar desde cero",
  "Practice — not saving": "Práctica: no se guarda",
  "Practice mode — your saved solution is safe 🔒": "Modo práctica: tu solución guardada está a salvo 🔒",
  "Saved ✓": "Guardado ✓",
  "Preview": "Vista previa",
  "Your tests": "Tus pruebas",
  "Console": "Consola",
  "Run": "Ejecutar",
  "Drill cleared 🎯": "Ejercicio superado 🎯",
  "Cleared — logged as close": "Superado: registrado como \"casi\"",
  "Couldn't save your code — storage may be full": "No se pudo guardar tu código: puede que el almacenamiento esté lleno",
  "Hide solution": "Ocultar la solución",
  "Show solution": "Mostrar la solución",
  "line {0}": "línea {0}",
  "No new code for this checkpoint: it passes once {0} passes.": "Este punto de control no necesita código nuevo: se cumple cuando se cumple {0}.",
  "checkpoint {0}": "el punto de control {0}",
  " and ": " y ",
  "No new code for this checkpoint: the starter already passes it. If it fails now, compare your file with the starter (↺ Reset code).":
    "Este punto de control no necesita código nuevo: el código inicial ya lo cumple. Si ahora falla, compara tu archivo con el inicial (↺ Restablecer código).",
  "no tests registered — write one with it()": "no hay pruebas registradas: escribe una con it()",
  "{0} failed, {1} passed": "{0} fallaron, {1} pasaron",
  "{0} passed": "{0} pasaron",
  "Running…": "Ejecutando…",
  "Your code ran too long — check for an infinite loop.": "Tu código tardó demasiado: revisa si hay un ciclo infinito.",
  "Your code crashed: {0}": "Tu código falló: {0}",
  "This check never ran.": "Esta comprobación no llegó a ejecutarse.",
  "Check failed": "La comprobación falló",
  "Took too long — maybe an infinite loop?": "Tardó demasiado: ¿quizás un ciclo infinito?",
  "The starter already passed that far — going one deeper 🎯": "El código inicial ya llegaba hasta ahí: vamos un paso más 🎯",
  "Run again": "Ejecutar de nuevo",
  "Still passing ✓ nice": "Sigue pasando ✓ bien hecho",
  "Back to course": "Volver al curso",

  /* ---- completion ---- */
  "PATH COMPLETE!": "¡RUTA COMPLETADA!",
  "Course complete!": "¡Curso completado!",
  "Project complete!": "¡Proyecto completado!",
  "Lesson complete!": "¡Lección completada!",
  "XP earned": "XP ganado",
  "Streak": "Racha",
  "{0} added {1} to your transcript": "{0} sumó {1} a tu historial",
  " — you now qualify for {0}": ": ahora calificas para {0}",
  "{0} position": "{0} puesto",
  "{0} positions": "{0} puestos",
  "Synced to your Academy profile": "Sincronizado con tu perfil de Academy",
  "View your certificate": "Ver tu certificado",
  "Back to all courses": "Volver a todos los cursos",
  "Stay & tinker": "Quedarme y experimentar",

  /* ---- quiz ---- */
  "Question {0}": "Pregunta {0}",
  "Correct!": "¡Correcto!",
  "Not quite.": "No exactamente.",
  "Continue": "Continuar",
  "Quiz passed!": "¡Cuestionario aprobado!",
  "Almost there": "Ya casi",
  "You scored {0}% ({1}/{2})": "Obtuviste {0}% ({1}/{2})",
  " — you need {0}% to pass.": ": necesitas {0}% para aprobar.",
  "Claim +{0} XP": "Reclamar +{0} XP",
  "Try again": "Intentar de nuevo",

  /* ---- theory lessons ---- */
  "Tap the lines in order to build your answer. Tap a placed line to take it back.":
    "Toca las líneas en orden para armar tu respuesta. Toca una línea ya colocada para quitarla.",
  "Not every line belongs.": "No todas las líneas van.",
  "Your answer appears here": "Tu respuesta aparece aquí",
  "{0}, row {1}": "{0}, fila {1}",
  "TEST OUT": "PRUEBA DE NIVEL",
  "Theory lesson": "Lección de teoría",
  "{0} · about {1} min": "{0} · unos {1} min",
  "{0} question": "{0} pregunta",
  "{0} questions": "{0} preguntas",
  "You answer before each explanation appears, so expect to get some wrong at first. That's how it's meant to work.":
    "Respondes antes de que aparezca cada explicación, así que es normal fallar algunas al principio. Así está pensado.",
  "Start": "Empezar",
  "Test out · {0}": "Prueba de nivel · {0}",
  "Already know this? Answer the test-out questions with no reading. Get them all right the first time and the lesson is done; miss one and you start the lesson.":
    "¿Ya sabes esto? Responde las preguntas de la prueba de nivel sin leer. Si aciertas todas a la primera, la lección queda completa; si fallas una, empiezas la lección.",
  "Finish": "Terminar",
  "This lab didn't load. Reload the page to try again.": "Este laboratorio no cargó. Recarga la página para intentarlo de nuevo.",
  "Try again.": "Inténtalo de nuevo.",
  "That's it.": "Eso es.",
  "Your answer": "Tu respuesta",
  "Check": "Comprobar",
  "The answer is {0}.": "La respuesta es {0}.",
  "Type it to continue.": "Escríbela para continuar.",
  "The right answer is outlined. Tap it to continue.": "La respuesta correcta está marcada. Tócala para continuar.",
  "Use the correct order": "Usar el orden correcto",
  "The first line out of place is marked.": "Está marcada la primera línea fuera de lugar.",
  "Some lines are still missing.": "Todavía faltan algunas líneas.",
  "Tap **Use the correct order**, read it, then Check.": "Toca **Usar el orden correcto**, léelo y luego Comprobar.",
  "Fill in the answers": "Completar las respuestas",
  "The first cell that's off is marked.": "Está marcada la primera celda incorrecta.",
  "Tap **Fill in the answers**, read them, then Check.": "Toca **Completar las respuestas**, léelas y luego Comprobar.",
  "One or two sentences, in your own words": "Una o dos oraciones, con tus propias palabras",
  "Show the model answer": "Mostrar la respuesta modelo",
  "Model answer": "Respuesta modelo",
  "Tick what your answer covered. This is your own check: it isn't graded, and it's reported separately.":
    "Marca lo que cubrió tu respuesta. Es tu propia revisión: no se califica y se informa por separado.",
  "Done checking": "Ya revisé",
  "Not yet": "Todavía no",
  "That answer was off, so the full lesson is the quicker route. Nothing was recorded.":
    "Esa respuesta no era correcta, así que la lección completa es el camino más rápido. No se registró nada.",
  "Start the lesson": "Empezar la lección",
  "Tested out!": "¡Prueba de nivel superada!",
  "Lesson finished": "Lección terminada",
  "Right the first time: {0} of {1} graded answers": "Correctas a la primera: {0} de {1} respuestas calificadas",
  "Explanations: you ticked {0} of {1} rubric points (self-checked, not graded)":
    "Explicaciones: marcaste {0} de {1} puntos de la rúbrica (autorrevisión, sin calificación)",

  /* ---- Recall ---- */
  "Couldn't find that lesson": "No se encontró esa lección",
  "Couldn't load that course": "No se pudo cargar ese curso",
  "Loading your cards…": "Cargando tus tarjetas…",
  "RECALL": "REPASO",
  "{0} card today": "{0} tarjeta hoy",
  "{0} cards today": "{0} tarjetas hoy",
  "Nothing due": "Nada pendiente",
  "About {0} minute.": "Cerca de {0} minuto.",
  "About {0} minutes.": "Cerca de {0} minutos.",
  "Answers are hidden — say it before you look.": "Las respuestas están ocultas: dila antes de mirar.",
  "Start recall": "Empezar el repaso",
  "Finish a quiz or a theory lesson to start building your recall deck.": "Termina un cuestionario o una lección de teoría para empezar a armar tu mazo de repaso.",
  "Next review in {0} day.": "Próximo repaso en {0} día.",
  "Next review in {0} days.": "Próximo repaso en {0} días.",
  "Practice 5 anyway": "Practicar 5 de todos modos",
  "Nothing to practice yet": "Todavía no hay nada para practicar",
  "Code drill ready": "Ejercicio de código listo",
  "rebuild {1} of {0} checkpoint from the starter files": "reconstruye {1} de {0} punto de control desde los archivos iniciales",
  "rebuild {1} of {0} checkpoints from the starter files": "reconstruye {1} de {0} puntos de control desde los archivos iniciales",
  "Start drill": "Empezar el ejercicio",
  "{0} of {1} questions introduced": "{0} de {1} preguntas presentadas",
  "{0} set aside": "{0} apartadas",
  "Holding at {0}+ days: {1}": "Firmes a {0}+ días: {1}",
  "Lifetime — typed {0}/{1} · self-reported {2}/{3}": "En total: escritas {0}/{1} · autoevaluadas {2}/{3}",
  "Say it before you look": "Dilo antes de mirar",
  "{0} to redo": "{0} por repetir",
  "Open the cheatsheet": "Abrir la guía rápida",
  "A full answer covers:": "Una respuesta completa incluye:",
  "Answer": "Respuesta",
  "Type your answer…": "Escribe tu respuesta…",
  "That should have counted": "Eso debió contar",
  "Noted — it'll count next time": "Anotado: contará la próxima vez",
  "Show answer": "Mostrar respuesta",
  "Missed": "Fallé",
  "grade|Close": "Casi",
  "Got it": "La sabía",
  "Can't answer this one": "No puedo responder esta",
  "Set this card aside for good": "Apartar esta tarjeta para siempre",
  "Set aside 🗂": "Apartada 🗂",
  "Couldn't save — storage may be full": "No se pudo guardar: puede que el almacenamiento esté lleno",
  "Recall done": "Repaso terminado",
  "{0} of {1} remembered": "Recordaste {0} de {1}",
  "Holding {0}+ days": "Firmes {0}+ días",
  "{0} answer you flagged as should-have-counted — see CODELAB.dev.rev.alts()": "{0} respuesta que marcaste como \"debió contar\": ver CODELAB.dev.rev.alts()",
  "{0} answers you flagged as should-have-counted — see CODELAB.dev.rev.alts()": "{0} respuestas que marcaste como \"debió contar\": ver CODELAB.dev.rev.alts()",
  "Drill: {0}": "Ejercicio: {0}",
  "Rebuild {1} of {0} checkpoint from the starter files": "Reconstruye {1} de {0} punto de control desde los archivos iniciales",
  "Rebuild {1} of {0} checkpoints from the starter files": "Reconstruye {1} de {0} puntos de control desde los archivos iniciales",
  "Back to courses": "Volver a los cursos",

  /* ---- Handoff ---- */
  "HANDOFF": "TRASPASO",
  "Move this profile": "Mover este perfil",
  "Your phone and your desktop keep separate storage — nothing crosses on its own. Copy the code below, send it to yourself however you like, and paste it on the other device. Importing the same code twice does nothing.":
    "Tu teléfono y tu computadora guardan los datos por separado: nada pasa de uno a otro por sí solo. Copia el código de abajo, envíatelo como prefieras y pégalo en el otro dispositivo. Importar el mismo código dos veces no cambia nada.",
  "Copy from this device": "Copiar desde este dispositivo",
  "{0} lessons · {1} cards · {2} study days · {3}KB": "{0} lecciones · {1} tarjetas · {2} días de estudio · {3} KB",
  "Copy code": "Copiar código",
  "Copied ✓ paste it on the other device": "Copiado ✓ pégalo en el otro dispositivo",
  "Select the code and copy it manually": "Selecciona el código y cópialo a mano",
  "Copied ✓": "Copiado ✓",
  "Save as file": "Guardar como archivo",
  "Couldn't save a file — copy the code instead": "No se pudo guardar el archivo: copia el código en su lugar",
  "Saved lesson code is not included — it is most of the bytes and none of what gets stranded.":
    "No incluye el código guardado de las lecciones: ocupa casi todo el espacio y no es lo que se queda varado.",
  "Paste a code from the other device": "Pega un código del otro dispositivo",
  "Paste the code here…": "Pega el código aquí…",
  "Check this code": "Revisar este código",
  "Undo the last merge": "Deshacer la última combinación",
  "Restores this profile to exactly how it was before you imported on {0}. Anything you have studied since then would be rolled back too.":
    "Deja este perfil exactamente como estaba antes de importar el {0}. Todo lo que hayas estudiado desde entonces también se revertiría.",
  "Undo that merge": "Deshacer esa combinación",
  "Roll this profile back to before the last import? Anything studied since is lost.":
    "¿Volver este perfil a como estaba antes de la última importación? Se pierde todo lo estudiado desde entonces.",
  "Rolled back ↩": "Revertido ↩",
  "From {0}": "Desde {0}",
  "another device": "otro dispositivo",
  "profile \"{0}\"": "perfil \"{0}\"",
  "That code is from the profile \"{0}\" and you are signed in as \"{1}\". It will merge into {1}.":
    "Ese código es del perfil \"{0}\" y entraste como \"{1}\". Se combinará en {1}.",
  "That code is dated in the future — the other device's clock may be wrong. Future-dated study days are ignored.":
    "Ese código tiene fecha futura: puede que el reloj del otro dispositivo esté mal. Los días de estudio con fecha futura se ignoran.",
  "Nothing to change — this profile already has everything in that code.": "No hay nada que cambiar: este perfil ya tiene todo lo de ese código.",
  "{1} lesson marked complete": "{1} lección marcada como completada",
  "{1} lessons marked complete": "{1} lecciones marcadas como completadas",
  "{0} lesson whose course isn't loaded — XP arrives when it is": "{0} lección cuyo curso no está cargado: el XP llega cuando se cargue",
  "{0} lessons whose course isn't loaded — XP arrives when it is": "{0} lecciones cuyo curso no está cargado: el XP llega cuando se cargue",
  "{1} new review card": "{1} tarjeta de repaso nueva",
  "{1} new review cards": "{1} tarjetas de repaso nuevas",
  "{1} card schedule updated": "{1} calendario de tarjeta actualizado",
  "{1} card schedules updated": "{1} calendarios de tarjetas actualizados",
  "{1} quiz score improved": "{1} puntaje de cuestionario mejorado",
  "{1} quiz scores improved": "{1} puntajes de cuestionario mejorados",
  "{1} extra study day": "{1} día de estudio adicional",
  "{1} extra study days": "{1} días de estudio adicionales",
  "Streak {0} → {1}": "Racha {0} → {1}",
  "The higher number was a run that had already ended — it would have reset on your next study day anyway.":
    "El número más alto era una racha que ya había terminado: se habría reiniciado en tu próximo día de estudio de todos modos.",
  "Merge this in": "Combinar",
  "Cancel": "Cancelar",
  "Merged ✓": "Combinado ✓",
  "No courses found. Make sure courses.js is present.": "No se encontraron cursos. Asegúrate de que courses.js esté presente.",

  /* ---- sync.js parse errors ---- */
  "Nothing pasted.": "No pegaste nada.",
  "That is not a valid sync code — it looks truncated or partly copied.": "Ese no es un código de sincronización válido: parece cortado o copiado a medias.",
  "That code is not from CodeLab.": "Ese código no es de CodeLab.",
  "Expected a progress code, got \"{0}\".": "Se esperaba un código de progreso, pero llegó \"{0}\".",
  "That code is version {0}; this app reads version {1}. Update the other device.": "Ese código es de la versión {0}; esta app lee la versión {1}. Actualiza el otro dispositivo.",
  "That code has no progress in it.": "Ese código no tiene progreso.",
  "That code is damaged — the checksum does not match. Copy it again, all of it.": "Ese código está dañado: la suma de verificación no coincide. Cópialo otra vez, completo."
});
