#!/usr/bin/env node
/* ============================================================
   Build the world map data for the Map screen (#/map).

     npm install                  (once, in politics/)
     node tools/build-world.js

   Writes maps/world.js: projected SVG path data for the land, the
   borders and each of the 30 countries, plus where each country's
   badge sits. The app draws the badges, colours, progress and
   relationship lines itself, so the file only changes when this
   script does. Like the locator maps, it's made from Natural Earth
   (public domain), never generated by an image model, and it hatches
   the same disputed areas (tools/disputes.js).

   Badges sit on each country's main landmass. Where countries are
   too close for their badges to fit (Europe, the Middle East, the
   Koreas), LABEL moves the badge to nearby open space and the app
   draws a thin leader line back to the country. LINK_LABEL does the
   same for relationships between near neighbours.
   ============================================================ */
const fs = require("fs");
const path = require("path");
const d3 = require("d3-geo");
const topojson = require("topojson-client");
const coarse = require("world-atlas/countries-110m.json");
const { load, ROOT } = require("./load");
const { CONTESTED_FEATURES, splitDisputed } = require("./disputes");

const { P } = load({ units: false });
const W = 1000;
const NORTH = 84, SOUTH = -57;   // crop the Arctic Ocean and Antarctica

/* Badge positions [lon, lat] for crowded places; everything else sits
   on the centroid of the country's main landmass. */
const LABEL = {
  gb: [-21, 56], fr: [-17, 43], de: [4, 63], pl: [19, 63], it: [5, 38.5], ua: [35, 55],
  tr: [38.5, 40.5], il: [28.5, 34], eg: [27, 24.5], ae: [58, 19.5],
  kr: [124.5, 33], kp: [127.5, 41.5], jp: [146, 37], tw: [123.5, 20.5]
};
/* Where a relationship's "⇄ n" badge sits [lon, lat], for links between
   near neighbours, whose arcs would otherwise put the badge on top of a
   country's. The app draws the arc through this point, so it bows into
   open sea. Links not listed use a default arc (see app.js). */
const LINK_LABEL = {
  us_mx: [-127, 26], us_ca: [-60, 50], il_ir: [55, 46], in_pk: [70, 10.5], cn_tw: [113, 14],
  jp_cn: [140, 26], kr_kp: [140, 53], sa_ir: [48, 9], us_ru: [10, 77],
  gb_fr: [-34, 49.5], jp_kr: [153, 44], pl_de: [12, 51], cn_in: [84, 34],
  id_au: [100, -18], br_ar: [-33, -30], eg_il: [20, 15]
};

const features = topojson.feature(coarse, coarse.objects.countries).features;
const disputed = splitDisputed(features);
const land = topojson.feature(coarse, coarse.objects.land);
const borders = topojson.mesh(coarse, coarse.objects.countries, (a, b) => a !== b);

const proj = d3.geoNaturalEarth1().rotate([-10, 0]);
proj.fitWidth(W, { type: "Sphere" });
const top = proj([-10, NORTH])[1], bottom = proj([-10, SOUTH])[1];
proj.translate([proj.translate()[0], proj.translate()[1] - top]);
const H = Math.round(bottom - top);
proj.clipExtent([[0, 0], [W, H]]);
const geo = d3.geoPath(proj).digits(1);
const r1 = (n) => Math.round(n * 10) / 10;

/* The largest polygon: the mainland, so Alaska, overseas territories and
   far islands don't drag a badge into the sea. */
function mainland(f) {
  if (f.geometry.type === "Polygon") return f;
  let best = null, bestArea = -1;
  f.geometry.coordinates.forEach((coords) => {
    const poly = { type: "Feature", geometry: { type: "Polygon", coordinates: coords } };
    const a = d3.geoArea(poly);
    if (a > bestArea) { bestArea = a; best = poly; }
  });
  return best;
}

const out = { w: W, h: H, land: geo(land), borders: geo(borders), hatched: [], contested: [], countries: {}, links: {} };
Object.keys(LINK_LABEL).forEach((id) => {
  if (!P.link(id)) throw new Error("LINK_LABEL: no relationship '" + id + "' in links.js");
  const at = proj(LINK_LABEL[id]);
  out.links[id] = { x: r1(at[0]), y: r1(at[1]) };
});
P.countries.forEach((c) => {
  const f = features.find((x) => x.id === c.iso);
  if (!f) throw new Error(c.id + ": no Natural Earth feature with ISO numeric id " + c.iso);
  const [cx, cy] = geo.centroid(mainland(f));
  const at = LABEL[c.id] ? proj(LABEL[c.id]) : [cx, cy];
  out.countries[c.id] = { d: geo(f), cx: r1(cx), cy: r1(cy), lx: r1(at[0]), ly: r1(at[1]) };
});
/* Disputed areas split out of their holder (Crimea, the southern Kurils),
   drawn hatched; `of` lists which of our countries are party to each. */
const idOfIso = {};
P.countries.forEach((c) => { idOfIso[c.iso] = c.id; });
disputed.forEach((a) => {
  const d = geo(a);
  if (d) out.hatched.push({ d, name: a.dispute.name, of: [idOfIso[a.dispute.holder], idOfIso[a.dispute.claimant]].filter(Boolean) });
});
features.filter((x) => CONTESTED_FEATURES.indexOf(x.id) > -1).forEach((x) => {
  const d = geo(x);
  if (d) out.contested.push(d);
});

const js = "/* Generated by tools/build-world.js from Natural Earth (public domain). Don't edit by hand. */\n" +
  "window.POLITICS.world = " + JSON.stringify(out) + ";\n";
const file = path.join(ROOT, "maps", "world.js");
fs.writeFileSync(file, js);
console.log("wrote maps/world.js (" + Math.round(Buffer.byteLength(js) / 1024) + " KB, " + W + "×" + H + ")");
