#!/usr/bin/env node
/* ============================================================
   Build the world map data for the Map screen (#/map).

     npm install                  (once, in politics/)
     node tools/build-world.js

   Writes maps/world.js: projected SVG path data for the land, the
   borders and each of the 30 countries, plus the centroid of each
   country's main landmass, where its relationship lines meet. The app
   draws the colours, lines and labels itself, so the file only changes
   when this script does. Like the locator maps, it's made from Natural
   Earth (public domain), never generated by an image model, and it
   hatches the same disputed areas (tools/disputes.js).
   ============================================================ */
const fs = require("fs");
const path = require("path");
const d3 = require("d3-geo");
const topojson = require("topojson-client");
const coarse = require("world-atlas/countries-110m.json");
const { load, ROOT } = require("./load");
const { CONTESTED_FEATURES, splitDisputed } = require("./disputes");

const { P } = load({ units: false });
const W = 1000;
const NORTH = 84, SOUTH = -57;   // crop the Arctic Ocean and Antarctica

const features = topojson.feature(coarse, coarse.objects.countries).features;
const disputed = splitDisputed(features);
const land = topojson.feature(coarse, coarse.objects.land);
const borders = topojson.mesh(coarse, coarse.objects.countries, (a, b) => a !== b);

const proj = d3.geoNaturalEarth1().rotate([-10, 0]);
proj.fitWidth(W, { type: "Sphere" });
const top = proj([-10, NORTH])[1], bottom = proj([-10, SOUTH])[1];
proj.translate([proj.translate()[0], proj.translate()[1] - top]);
const H = Math.round(bottom - top);
proj.clipExtent([[0, 0], [W, H]]);
const geo = d3.geoPath(proj).digits(1);
const r1 = (n) => Math.round(n * 10) / 10;

/* The largest polygon: the mainland, so Alaska, overseas territories and
   far islands don't drag a line's end into the sea. */
function mainland(f) {
  if (f.geometry.type === "Polygon") return f;
  let best = null, bestArea = -1;
  f.geometry.coordinates.forEach((coords) => {
    const poly = { type: "Feature", geometry: { type: "Polygon", coordinates: coords } };
    const a = d3.geoArea(poly);
    if (a > bestArea) { bestArea = a; best = poly; }
  });
  return best;
}

const out = { w: W, h: H, land: geo(land), borders: geo(borders), hatched: [], contested: [], countries: {} };
P.countries.forEach((c) => {
  const f = features.find((x) => x.id === c.iso);
  if (!f) throw new Error(c.id + ": no Natural Earth feature with ISO numeric id " + c.iso);
  const [cx, cy] = geo.centroid(mainland(f));
  out.countries[c.id] = { d: geo(f), cx: r1(cx), cy: r1(cy) };
});
/* Disputed areas split out of their holder (Crimea, the southern Kurils),
   drawn hatched; `of` lists which of our countries are party to each. */
const idOfIso = {};
P.countries.forEach((c) => { idOfIso[c.iso] = c.id; });
disputed.forEach((a) => {
  const d = geo(a);
  if (d) out.hatched.push({ d, name: a.dispute.name, of: [idOfIso[a.dispute.holder], idOfIso[a.dispute.claimant]].filter(Boolean) });
});
features.filter((x) => CONTESTED_FEATURES.indexOf(x.id) > -1).forEach((x) => {
  const d = geo(x);
  if (d) out.contested.push(d);
});

const js = "/* Generated by tools/build-world.js from Natural Earth (public domain). Don't edit by hand. */\n" +
  "window.POLITICS.world = " + JSON.stringify(out) + ";\n";
const file = path.join(ROOT, "maps", "world.js");
fs.writeFileSync(file, js);
console.log("wrote maps/world.js (" + Math.round(Buffer.byteLength(js) / 1024) + " KB, " + W + "×" + H + ")");
