/* GENERATED by tools/build-step-solutions.js — do not edit by hand.
   Explanations come from tools/step-why/auth.json. validate.js fails
   when a lesson changes without a rebuild. */
window.CODELAB.addStepSolutions("auth", {
 "auth-u1-1": {
  "hash": "452be4fd07639794",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 11,
      "del": [
       "  // It works, and anyone can type it. Make the id unguessable: randHex(16).",
       "  const id = \"token-\" + userName;"
      ],
      "add": [
       "  const id = randHex(16); // 128 random bits: nothing to derive, nothing to guess"
      ]
     }
    ],
    "after": [],
    "fail": "A session id should be 32 lowercase hex characters, from randHex(16) — yours was \"token-ada\"",
    "why": "The starter builds the id from the user name, so anyone who has seen `token-ada` can type `token-bo`. A session id is a bearer credential: whoever presents it is that user. It has to come from a random source, and `randHex(16)` gives 128 bits nobody can derive or guess."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 12,
      "del": [
       "  // TODO: the row also records created and lastSeen, both now()",
       "  sessions.set(id, { userName: userName });"
      ],
      "add": [
       "  sessions.set(id, { userName: userName, created: now(), lastSeen: now() });"
      ]
     }
    ],
    "after": [],
    "fail": "The row for bo should be { userName, created: now(), lastSeen: now() }, in that order — expected {\"userName\":\"bo\",\"created\":1700000005000,\"lastSeen\":1700000005000} but got {\"userName\":\"bo\"}",
    "why": "The starter's row records only who the session belongs to. Without `created` and `lastSeen` the server can't tell how old a session is or when it was last used, so the timeouts later in this unit would have nothing to measure."
   },
   {
    "chunks": [],
    "after": [],
    "why": null
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   }
  ]
 },
 "auth-u1-2": {
  "hash": "5ac51d1e2ceefcc3",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 12,
      "del": [
       "  let out = name + \"=\" + value;",
       "  if (opts.path) out += \"; Path=\" + opts.path;",
       "  if (opts.maxAge) out += \"; Max-Age=\" + opts.maxAge;",
       "  if (opts.httpOnly) out += \"; HttpOnly\";",
       "  // TODO: Secure, and SameSite (Strict | Lax | None — None requires Secure)",
       "  // TODO: throw a TypeError for a name or value the cookie grammar forbids",
       "  return out;"
      ],
      "add": [
       "  const parts = [name + \"=\" + value];",
       "  if (opts.path != null) parts.push(\"Path=\" + opts.path);",
       "  if (opts.maxAge != null) parts.push(\"Max-Age=\" + Math.floor(opts.maxAge));",
       "  if (opts.httpOnly) parts.push(\"HttpOnly\");",
       "  if (opts.secure) parts.push(\"Secure\");",
       "  if (opts.sameSite != null) {",
       "    if ([\"Strict\", \"Lax\", \"None\"].indexOf(opts.sameSite) === -1) throw new TypeError(\"SameSite must be Strict, Lax or None\");",
       "    if (opts.sameSite === \"None\" && !opts.secure) throw new TypeError(\"SameSite=None requires Secure\");",
       "    parts.push(\"SameSite=\" + opts.sameSite);",
       "  }",
       "  return parts.join(\"; \");"
      ]
     }
    ],
    "after": [],
    "fail": "Expected exactly Path=/, Max-Age=1800, HttpOnly, Secure and SameSite=Lax, in any order, joined with \"; \" — yours: \"sid=abc123; Path=/; Max-Age=1800; HttpOnly\" — expected [\"HttpOnly\",\"Max-Age=1800\",\"Path=/\",\"SameSite=Lax\",\"Secure\"] but got [\"HttpOnly\",\"Max-Age=1800\",\"Path=/\"]",
    "why": "The starter writes only `Path`, `Max-Age` and `HttpOnly`, so the cookie never gets `Secure` or `SameSite`. It also tests `opts.maxAge` for truthiness, which silently drops `maxAge: 0`. Collecting the parts in an array and checking `!= null` writes every attribute that was set, including a zero."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 4,
      "del": [],
      "add": [
       "const COOKIE_NAME = /^[!#$%&'*+\\-.^_`|~0-9A-Za-z]+$/;",
       "const COOKIE_VALUE = /^[\\x21\\x23-\\x2B\\x2D-\\x3A\\x3C-\\x5B\\x5D-\\x7E]*$/;",
       ""
      ]
     },
     {
      "file": "script.js",
      "line": 9,
      "del": [],
      "add": [
       "  value = String(value);",
       "  if (typeof name !== \"string\" || !COOKIE_NAME.test(name)) throw new TypeError(\"invalid cookie name: \" + JSON.stringify(name));",
       "  if (!COOKIE_VALUE.test(value)) throw new TypeError(\"invalid cookie value: \" + JSON.stringify(value));"
      ]
     }
    ],
    "after": [],
    "fail": "A value of \"abc; Domain=evil.example\" must throw: it would break the header or smuggle in an attribute",
    "why": "The starter puts any name and value straight into the header. A value like `abc; Domain=evil.example` then adds an attribute the server never chose. Checking both against the cookie grammar, and throwing a `TypeError` when they don't match, keeps the header exactly what the caller asked for."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 29,
      "del": [
       "    const [key, val] = part.split(\"=\");",
       "    jar[key.trim()] = val;"
      ],
      "add": [
       "    const eq = part.indexOf(\"=\");",
       "    if (eq === -1) continue;",
       "    const key = part.slice(0, eq).trim();",
       "    if (key && !Object.prototype.hasOwnProperty.call(jar, key)) jar[key] = part.slice(eq + 1).trim();"
      ]
     }
    ],
    "after": [],
    "fail": "Split on the FIRST = only, since a value may contain = itself — yours: {\"next\":\"/a?b\",\"sid\":\"xyz\"} — expected {\"next\":\"/a?b=c\",\"sid\":\"xyz\"} but got {\"next\":\"/a?b\",\"sid\":\"xyz\"}",
    "why": "`part.split(\"=\")` splits on every `=`, and destructuring keeps only the first two pieces, so `next=/a?b=c` loses its `=c`. Cutting at the first `=` with `indexOf` keeps the rest of the value intact. Skipping pieces with no `=` and names already seen stops odd headers from overwriting a real cookie."
   }
  ]
 },
 "auth-u1-3": {
  "hash": "ef510c72e66934bd",
  "steps": [
   {
    "chunks": [],
    "after": [],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 76,
      "del": [
       "    const id = currentId(req);",
       "    if (id) {",
       "      // The id the visitor arrived with is now logged in. So is whoever chose it.",
       "      sessions.get(id).userName = user.userName;",
       "      return { status: 200, body: { ok: true } };",
       "    }"
      ],
      "add": [
       "    const oldId = currentId(req);",
       "    const cart = oldId ? sessions.get(oldId).cart : [];",
       "    if (oldId) sessions.delete(oldId);             // the planted id now points at nothing",
       "    const id = createSession(user.userName, cart);  // a fresh id for the new privilege level"
      ]
     }
    ],
    "after": [],
    "fail": "The attacker replayed the id they planted and got {\"status\":200,\"body\":{\"userName\":\"ada\",\"cart\":[]}}, the account ada just signed into. Login must rotate the id — expected {\"status\":401,\"body\":{\"error\":\"unauthorized\"}} but got {\"status\":200,\"body\":{\"userName\":\"ada\",\"cart\":[]}}",
    "why": "The starter finds the session the visitor arrived with and marks it as logged in. If an attacker planted that id, the attacker's copy now opens the victim's account. Deleting the old row and creating a fresh one at login leaves the planted id pointing at nothing."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 80,
      "del": [
       "    return { status: 200, headers: { \"Set-Cookie\": sessionCookie(createSession(user.userName, [])) }, body: { ok: true } };"
      ],
      "add": [
       "    return { status: 200, headers: { \"Set-Cookie\": sessionCookie(id) }, body: { ok: true } };"
      ]
     }
    ],
    "after": [],
    "fail": "The new sid should be ada, still holding the lamp added before signing in — expected {\"status\":200,\"body\":{\"userName\":\"ada\",\"cart\":[\"lamp\"]}} but got {\"status\":200,\"body\":{\"userName\":\"ada\",\"cart\":[]}}",
    "why": "The starter's login answers with a brand-new session and an empty cart, so anything the visitor added before signing in is lost. Carrying `cart` from the old row into the new one, and sending that new id in `Set-Cookie`, makes the rotation invisible to the shopper."
   },
   {
    "chunks": [],
    "after": [],
    "why": null
   }
  ]
 },
 "auth-u1-4": {
  "hash": "9a7674bd0168322a",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 55,
      "del": [
       "  // TODO: idle timeout, measured from row.lastSeen",
       "  // TODO: absolute timeout, measured from row.created",
       "  // TODO: still alive? slide lastSeen forward to now()"
      ],
      "add": [
       "  const t = now();",
       "  if (t - row.lastSeen >= IDLE_MS || t - row.created >= ABSOLUTE_MS) {",
       "    sessions.delete(id);  // dead rows don't linger",
       "    return null;",
       "  }",
       "  row.lastSeen = t;       // only a live session slides"
      ]
     }
    ],
    "after": [],
    "fail": "A successful request slides lastSeen forward to now() — expected 1700001740000 but got 1700000000000",
    "why": "The starter's `touchSession` returns any row it finds, however old, and never updates it. A session nobody checks against the clock never ends, and one whose `lastSeen` never moves can't have an idle timeout. Read `now()` once, end the session when either limit is reached, and only then slide `lastSeen` forward."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [],
    "after": [],
    "why": null
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   }
  ]
 },
 "auth-u1-5": {
  "hash": "419b4c01e136b29b",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 62,
      "del": [
       "    return { status: 200, headers: { \"Set-Cookie\": \"sid=; Max-Age=0\" }, body: { ok: true } };"
      ],
      "add": [
       "    return { status: 200, headers: { \"Set-Cookie\": clearCookie() }, body: { ok: true } };"
      ]
     },
     {
      "file": "script.js",
      "line": 72,
      "del": [],
      "add": [
       "  function clearCookie() {  // browser half: same Path it was set with",
       "    return serializeCookie(\"sid\", \"\", { path: \"/\", maxAge: 0, httpOnly: true, secure: true, sameSite: \"Lax\" });",
       "  }"
      ]
     }
    ],
    "after": [],
    "fail": "A cookie is matched by name AND path. Without Path=/ the browser keeps the original sid — yours: \"sid=; Max-Age=0\"",
    "why": "The starter's clearing cookie is `sid=; Max-Age=0` with no `Path`. Browsers match a cookie by name and path, so that header can leave the original `sid` in place. Building it with `serializeCookie` and the same `Path=/` the session cookie was set with actually replaces it."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 60,
      "del": [
       "    // Tells the browser to forget the cookie. The server forgets nothing."
      ],
      "add": [
       "    const id = currentId(req);",
       "    if (id) sessions.delete(id);  // server half: the id means nothing now"
      ]
     }
    ],
    "after": [],
    "fail": "The copied id still opened the account after logout ({\"status\":200,\"body\":{\"userName\":\"ada\"}}). Clearing the cookie in one browser does nothing to a copy; delete the row — expected {\"status\":401,\"body\":{\"error\":\"unauthorized\"}} but got {\"status\":200,\"body\":{\"userName\":\"ada\"}}",
    "why": "The starter only tells the browser to forget the cookie; the row stays on the server. Anyone holding a copy of the id (a proxy log, malware, the fixation attacker) keeps using it until it times out. Deleting the row is what makes logout real."
   },
   {
    "chunks": [],
    "after": [],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 64,
      "del": [
       "  // TODO: POST /api/logout-all ends every session the caller's user has"
      ],
      "add": [
       "  if (req.method === \"POST\" && req.path === \"/api/logout-all\") {",
       "    const id = currentId(req);",
       "    if (!id) return { status: 401, body: { error: \"unauthorized\" } };",
       "    const userName = sessions.get(id).userName;",
       "    for (const [sid, row] of sessions) if (row.userName === userName) sessions.delete(sid);",
       "    return { status: 200, headers: { \"Set-Cookie\": clearCookie() }, body: { ok: true } };",
       "  }",
       ""
      ]
     }
    ],
    "after": [],
    "fail": "POST /api/logout-all with a valid session → 200 — got {\"status\":404,\"body\":\"Not found\"} — expected 200 but got 404",
    "why": "The starter has no `/api/logout-all` route, so it answers 404. Signing out everywhere means finding every row with the caller's `userName` and deleting them all, which is only possible because a session is a row the server can search."
   }
  ]
 },
 "auth-u4-1": {
  "hash": "98d87a197feb340d",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 7,
      "del": [
       "  // TODO: take the bytes 3 at a time and join them into one 24-bit number;",
       "  // write 4 characters for a full group, 3 for 2 bytes, 2 for 1 byte"
      ],
      "add": [
       "  for (let i = 0; i < bytes.length; i += 3) {",
       "    const n = (bytes[i] << 16) | ((bytes[i + 1] || 0) << 8) | (bytes[i + 2] || 0);",
       "    const chars = Math.min(bytes.length - i, 3) + 1; // 1 byte -> 2 chars, 2 -> 3, 3 -> 4",
       "    for (let j = 0; j < chars; j++) out += B64URL[(n >> (18 - 6 * j)) & 63];",
       "  }"
      ]
     }
    ],
    "after": [],
    "fail": "b64urlEncode of the bytes of \"f\" (1 bytes, so 2 characters) — expected \"Zg\" but got \"\"",
    "why": "The starter's encoder never reads the bytes, so it returns an empty string. base64url takes the bytes three at a time as one 24-bit number and writes four 6-bit characters, or two or three for a short final group, with no `=` padding."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 17,
      "del": [
       "  // TODO: throw for length % 4 === 1 or any character outside B64URL;",
       "  // collect 6 bits per character and emit a byte whenever 8 have built up",
       "  return new Uint8Array(0);"
      ],
      "add": [
       "  if (typeof str !== \"string\" || str.length % 4 === 1) throw new Error(\"not base64url: \" + JSON.stringify(str));",
       "  const out = new Uint8Array(Math.floor(str.length * 3 / 4));",
       "  let n = 0, bits = 0, o = 0;",
       "  for (let i = 0; i < str.length; i++) {",
       "    const v = B64URL.indexOf(str[i]);",
       "    if (v === -1) throw new Error(\"not base64url: \" + JSON.stringify(str));",
       "    n = ((n << 6) | v) & 0xffffff;",
       "    bits += 6;",
       "    if (bits >= 8) { bits -= 8; out[o++] = (n >> bits) & 255; }",
       "  }",
       "  return out;"
      ]
     }
    ],
    "after": [],
    "fail": "Zm9vYmFy decodes to the bytes of foobar — expected [102,111,111,98,97,114] but got []",
    "why": "The starter's decoder returns an empty array for every input. Decoding runs the encoder backwards: each character is worth 6 bits, and a byte comes out whenever 8 bits have built up. It also has to throw for a character outside the alphabet and for a length that leaves one stray character."
   },
   {
    "chunks": [],
    "after": [
     2
    ],
    "why": null
   }
  ]
 },
 "auth-u4-2": {
  "hash": "ebecfab62cb6f162",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 35,
      "del": [],
      "add": [
       "function mac(text) {",
       "  return b64urlEncode(hmac(\"sha256\", SECRET, text));",
       "}",
       ""
      ]
     },
     {
      "file": "script.js",
      "line": 41,
      "del": [
       "  // TODO: add a dot and the base64url HMAC of the payload part",
       "  return payload;"
      ],
      "add": [
       "  return payload + \".\" + mac(payload);"
      ]
     }
    ],
    "after": [],
    "fail": "sign() should return base64url(JSON) + \".\" + base64url(HMAC-SHA256(SECRET, that first part)) — expected \"eyJzdWIiOiJhZGEiLCJyb2xlIjoidXNlciJ9.2XH8urf0hWjEuIY6MBYBjy1MaknjwJl8lizyiUMyMtE\" but got \"eyJzdWIiOiJhZGEiLCJyb2xlIjoidXNlciJ9\"",
    "why": "The starter's `sign` returns only the encoded payload, with no signature, so anyone could write their own token. Appending a dot and the base64url HMAC of the payload means only a holder of `SECRET` can produce a token that matches."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 46,
      "del": [
       "  const [payload] = String(token).split(\".\");",
       "  // TODO: recompute the signature and refuse anything that doesn't match",
       "  return JSON.parse(fromBytes(b64urlDecode(payload)));"
      ],
      "add": [
       "  const parts = String(token).split(\".\");",
       "  if (parts.length !== 2) return null;",
       "  if (mac(parts[0]) !== parts[1]) return null; // signature first: the payload is untrusted text until then",
       "  try {",
       "    return JSON.parse(fromBytes(b64urlDecode(parts[0])));",
       "  } catch (e) {",
       "    return null;",
       "  }"
      ]
     }
    ],
    "after": [],
    "fail": "Someone edited the payload to role admin and kept the old signature. Your verify returned {\"sub\":\"ada\",\"role\":\"admin\"}: recompute the HMAC and compare — expected null but got {\"sub\":\"ada\",\"role\":\"admin\"}",
    "why": "The starter's `verify` decodes whatever payload it gets and never checks a signature, so an edited `role: \"admin\"` goes straight through. Recompute the HMAC and refuse a mismatch first; only then parse the payload, inside a `try`, so a malformed token is `null` rather than an exception."
   },
   {
    "chunks": [],
    "after": [
     0,
     2
    ],
    "why": null
   }
  ]
 },
 "auth-u4-3": {
  "hash": "a14718ef1f00ec71",
  "steps": [
   {
    "chunks": [],
    "after": [
     1
    ],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 39,
      "del": [
       "// Compares two byte arrays. Right answer, wrong timing: it stops at the first difference."
      ],
      "add": [
       "// Every byte is read, whatever the first difference. Only the length can leak,",
       "// and every HMAC-SHA256 is 32 bytes."
      ]
     },
     {
      "file": "script.js",
      "line": 43,
      "del": [
       "  for (let i = 0; i < a.length; i++) {",
       "    if (a[i] !== b[i]) return false;",
       "  }",
       "  return true;"
      ],
      "add": [
       "  let diff = 0;",
       "  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];",
       "  return diff === 0;"
      ]
     }
    ],
    "after": [],
    "fail": "A mismatch at byte 0 cost 2 reads, a mismatch at byte 31 cost 64, a match cost 64. That difference is the timing leak: read every byte, whatever you find",
    "why": "The starter's loop returns at the first byte that differs, so a signature wrong in byte 0 is rejected sooner than one wrong in byte 31. Measured over many requests, that difference gives a valid signature away byte by byte. OR-ing every byte's XOR into one number and checking it once at the end costs the same whatever the input."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 51,
      "del": [
       "  const expected = b64urlEncode(hmac(\"sha256\", SECRET, parts[0]));",
       "  if (expected !== parts[1]) return null; // TODO: decode parts[1] and compare BYTES with safeEqual"
      ],
      "add": [
       "  let given;",
       "  try { given = b64urlDecode(parts[1]); } catch (e) { return null; }",
       "  if (!safeEqual(given, hmac(\"sha256\", SECRET, parts[0]))) return null;"
      ]
     }
    ],
    "after": [],
    "fail": "verify should compare the signature bytes with safeEqual exactly once. It was called 0 times, so the comparison is still a === that stops at the first different character",
    "why": "The starter's `verify` still compares base64url strings with `!==`, which stops at the first different character and never calls `safeEqual`. Decoding the given signature to bytes (refusing one that won't decode) and comparing with `safeEqual` closes the leak where it matters."
   },
   {
    "chunks": [],
    "after": [
     1
    ],
    "why": null
   }
  ]
 },
 "auth-u4-4": {
  "hash": "29d89accd3b1424a",
  "steps": [
   {
    "chunks": [],
    "after": [],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 52,
      "del": [
       "// Starter: ignores the kid and tries every key until one matches."
      ],
      "add": []
     },
     {
      "file": "script.js",
      "line": 55,
      "del": [],
      "add": [
       "  const kid = parts[0];",
       "  if (!Object.prototype.hasOwnProperty.call(KEYS, kid)) return null; // unknown kid: refuse, don't go hunting"
      ]
     },
     {
      "file": "script.js",
      "line": 59,
      "del": [
       "  const signed = parts[0] + \".\" + parts[1];",
       "  for (const kid in KEYS) {",
       "    if (safeEqual(given, hmac(\"sha256\", KEYS[kid], signed))) {",
       "      try { return JSON.parse(fromBytes(b64urlDecode(parts[1]))); } catch (e) { return null; }",
       "    }"
      ],
      "add": [
       "  if (!safeEqual(given, hmac(\"sha256\", KEYS[kid], kid + \".\" + parts[1]))) return null;",
       "  try {",
       "    return JSON.parse(fromBytes(b64urlDecode(parts[1])));",
       "  } catch (e) {",
       "    return null;"
      ]
     },
     {
      "file": "script.js",
      "line": 65,
      "del": [
       "  return null;"
      ],
      "add": []
     }
    ],
    "after": [],
    "fail": "This token says 2026-09 but was signed with the August key. Your verify returned {\"sub\":\"ada\"}: check the signature with the key the kid names, and only that key — expected null but got {\"sub\":\"ada\"}",
    "why": "The starter ignores the `kid` and tries every key until one matches, so the label means nothing: a token that says `2026-09` but was signed with August's key still passes, and an unknown `kid` costs one HMAC per key. Looking the `kid` up with `hasOwnProperty` and checking only that key fixes both."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 68,
      "del": [
       "  // TODO: throw if kid already exists; add the key; sign with it from now on"
      ],
      "add": [
       "  if (Object.prototype.hasOwnProperty.call(KEYS, kid)) throw new Error(\"kid already exists: \" + kid);",
       "  KEYS[kid] = secret;",
       "  currentKid = kid; // new tokens use it; old tokens still verify under their own kid"
      ]
     }
    ],
    "after": [],
    "fail": "After rotateKey, sign should use the new key, so tokens start \"2026-10.\" — yours: 2026-09.eyJzdWIiOiJhZGEifQ.bpxMFB4s2QnaFIvqoxmNJTpXQ0NcGKjY88tuHEugOI0",
    "why": "The starter's `rotateKey` does nothing, so `sign` keeps using the old key. Rotating adds the new secret and switches `currentKid` to it, and it refuses a `kid` that already exists, because silently replacing a secret breaks every token it signed."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 74,
      "del": [
       "  // TODO: throw if kid is the key sign() uses; otherwise delete it"
      ],
      "add": [
       "  if (kid === currentKid) throw new Error(\"cannot retire the key sign() is using: \" + kid);",
       "  delete KEYS[kid];"
      ]
     }
    ],
    "after": [],
    "fail": "After retireKey(\"2026-08\"), August tokens must stop verifying — expected null but got {\"sub\":\"bo\"}",
    "why": "The starter's `retireKey` does nothing, so a retired key keeps verifying its tokens forever. Deleting it from `KEYS` ends them, and refusing to delete `currentKid` stops every newly signed token from failing at once."
   }
  ]
 },
 "auth-u5-1": {
  "hash": "5d862413c48504c2",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 60,
      "del": [
       "  // TODO: three parts; the first two are base64url JSON (readPart); keep the signature as text",
       "  return null;"
      ],
      "add": [
       "  const parts = String(token).split(\".\");",
       "  if (parts.length !== 3) return null;",
       "  try {",
       "    return { header: readPart(parts[0]), payload: readPart(parts[1]), signature: parts[2] };",
       "  } catch (e) {",
       "    return null;",
       "  }"
      ]
     }
    ],
    "after": [],
    "fail": "decodeJwt should return { header, payload, signature }. No key is needed to read a JWT — expected {\"header\":{\"alg\":\"HS256\",\"typ\":\"JWT\"},\"payload\":{\"sub\":\"ada\",\"exp\":1700000000},\"signature\":\"fV-HwGz830YHmMilXlswsjAFDg8mJmcqKa4Znyv7ZzU\"} but got null",
    "why": "The starter's `decodeJwt` returns `null` for every token, so it never shows what a JWT carries. A JWT is three base64url parts: the first two are JSON anyone can read with `readPart`, and the third is the signature, kept as text. Reading them inside a `try` makes a malformed token `null` instead of an exception."
   },
   {
    "chunks": [],
    "after": [],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 72,
      "del": [
       "  // The whole user record goes into the token.",
       "  return mint(Object.assign({}, user, { sub: user.userName, iat: iat, exp: iat + 900 }));"
      ],
      "add": [
       "  // Only what the next request needs. Everything here is readable by anyone.",
       "  return mint({ sub: user.userName, role: user.role, iat: iat, exp: iat + 900 });"
      ]
     }
    ],
    "after": [],
    "fail": "Anyone holding the token can read every claim. Yours carries [\"userName\",\"role\",\"email\",\"passwordHash\",\"resetToken\",\"sub\",\"iat\",\"exp\"] — expected [\"exp\",\"iat\",\"role\",\"sub\"] but got [\"email\",\"exp\",\"iat\",\"passwordHash\",\"resetToken\",\"role\",\"sub\",\"userName\"]",
    "why": "The starter copies the whole user record into the token, so the email, password hash and reset token travel with every request, readable by anyone who decodes it. Building the claims by hand keeps the token to what the server needs next time: who (`sub`), what they may do (`role`) and when (`iat`, `exp`)."
   },
   {
    "chunks": [],
    "after": [
     2
    ],
    "why": null
   }
  ]
 },
 "auth-u5-2": {
  "hash": "675d0a20d5669fe5",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 68,
      "del": [
       "  // TODO: part() the header { alg: \"none\", typ: \"JWT\" } and the claims, then add a dot and nothing else",
       "  return \"\";"
      ],
      "add": [
       "  return part({ alg: \"none\", typ: \"JWT\" }) + \".\" + part(claims) + \".\";"
      ]
     }
    ],
    "after": [],
    "fail": "A JWT always has three parts, even an unsigned one — yours: \"\" — expected 3 but got 1",
    "why": "The starter's `forgeNone` returns an empty string, which isn't a JWT at all. An unsecured JWT is still three parts: a header saying `alg: \"none\"`, the claims, and an empty signature after the last dot."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 77,
      "del": [
       "  if (header.alg === \"none\") return payload; // \"unsecured JWTs are part of the spec\"",
       "  if (header.alg !== \"HS256\") return null;"
      ],
      "add": [
       "  if (!header || header.alg !== \"HS256\") return null; // the server decides; the token only claims"
      ]
     }
    ],
    "after": [],
    "fail": "The alg none token must be refused — expected null but got {\"sub\":\"admin\",\"role\":\"admin\"}",
    "why": "The starter keeps the legacy rule that returns the payload whenever the header says `none`, so the token decides how it gets checked. Allowing exactly `HS256`, and refusing a header that isn't an object, puts that decision back on the server: `none` in any spelling, `HS512` and a missing `alg` all fall out."
   },
   {
    "chunks": [],
    "after": [],
    "why": null
   }
  ]
 },
 "auth-u5-3": {
  "hash": "4f5e025aab195624",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 73,
      "del": [
       "  // TODO: exp (required) and nbf (if present), in seconds, with LEEWAY either way",
       "  // TODO: iss must be ISSUER; aud (a string or an array) must include AUDIENCE"
      ],
      "add": [
       "  const t = Math.floor(now() / 1000);",
       "  if (typeof claims.exp !== \"number\" || t > claims.exp + LEEWAY) return null;",
       "  if (claims.nbf != null && (typeof claims.nbf !== \"number\" || t < claims.nbf - LEEWAY)) return null;",
       "  if (claims.iss !== ISSUER) return null;",
       "  const aud = Array.isArray(claims.aud) ? claims.aud : [claims.aud];",
       "  if (aud.indexOf(AUDIENCE) === -1) return null;"
      ]
     }
    ],
    "after": [],
    "fail": "90 seconds past exp is outside the leeway: refused — expected null but got {\"sub\":\"ada\",\"iss\":\"https://auth.example\",\"aud\":\"notes-api\",\"iat\":1700000000,\"exp\":1700000300}",
    "why": "The starter's `acceptToken` returns any correctly signed token, so an expired one, one not valid yet, one from another issuer and one meant for another API all get in. Each claim needs its own check, in seconds (`Math.floor(now() / 1000)`) with `LEEWAY` for clock drift. All four checks live in this one block, which is why the later checkpoints pass once this one does."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   }
  ]
 },
 "auth-u5-4": {
  "hash": "3d7d407236c8b9c5",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 91,
      "del": [],
      "add": [
       "  return issuePair(userName, randHex(8)); // a new login starts a new family",
       "}",
       "",
       "function issuePair(userName, family) {"
      ]
     },
     {
      "file": "script.js",
      "line": 96,
      "del": [
       "  refreshTokens.set(refresh, { userName: userName }); // TODO: store sha256(refresh), a family id and used: false"
      ],
      "add": [
       "  refreshTokens.set(sha256(refresh), { userName: userName, family: family, used: false });"
      ]
     }
    ],
    "after": [],
    "fail": "The raw refresh token is a key in refreshTokens, so a leaked table would hand out working tokens. Store sha256(refresh) instead",
    "why": "The starter stores the raw refresh token as the Map key and records no family or `used` flag. A leaked table would hand out working tokens, and there would be nothing to rotate or revoke. Keying by `sha256(refresh)` and recording the family with `used: false` gives each refresh token a row the server can reason about."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 101,
      "del": [
       "  const row = refreshTokens.get(oldRefresh);"
      ],
      "add": [
       "  const row = refreshTokens.get(sha256(String(oldRefresh)));"
      ]
     },
     {
      "file": "script.js",
      "line": 103,
      "del": [
       "  // TODO: rotate: mark this token used and hand out a new one in the same family",
       "  // TODO: a used token presented again means it was copied: revoke the whole family",
       "  return { access: issueAccess(row.userName), refresh: oldRefresh };"
      ],
      "add": [
       "  if (row.used) {",
       "    // Presented twice: someone else holds a copy. End every token in this family.",
       "    for (const [key, r] of refreshTokens) if (r.family === row.family) refreshTokens.delete(key);",
       "    return null;",
       "  }",
       "  row.used = true;",
       "  return issuePair(row.userName, row.family);"
      ]
     }
    ],
    "after": [],
    "fail": "refreshSession should return { access, refresh } for a valid refresh token — got null",
    "why": "The starter hands back the same refresh token every time and never notices one being used twice. Rotation marks the old row `used` and issues a new token in the same family, and a used token that comes back means someone copied it, so every token in that family is deleted. The lookup also has to go by `sha256`, since that is how the rows are stored."
   },
   {
    "chunks": [],
    "after": [
     0,
     1
    ],
    "why": null
   },
   {
    "chunks": [],
    "after": [
     0,
     1
    ],
    "why": null
   }
  ]
 },
 "auth-u5-p": {
  "hash": "79eaf2f6042e816e",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 67,
      "del": [
       "  if (header.alg === \"none\") return checkClaims(claims);"
      ],
      "add": [
       "  if (header.alg !== \"HS256\") return null;                                  // the server decides"
      ]
     }
    ],
    "after": [],
    "fail": "An alg:none token with no signature was accepted as admin. The server decides the algorithm — expected null but got {\"sub\":\"admin\",\"iss\":\"https://auth.example\",\"aud\":\"notes-api\",\"iat\":1700000000,\"exp\":1700000300,\"role\":\"admin\"}",
    "why": "The starter returns the claims for any token whose header says `alg: none`, so an unsigned token claiming to be admin gets in. The server allows exactly `HS256` and refuses everything else."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 81,
      "del": [],
      "add": [
       "  const aud = Array.isArray(claims.aud) ? claims.aud : [claims.aud];",
       "  if (aud.indexOf(AUDIENCE) === -1) return null;"
      ]
     }
    ],
    "after": [],
    "fail": "A token for billing-api opened notes-api. Check aud — expected null but got {\"sub\":\"ada\",\"iss\":\"https://auth.example\",\"aud\":\"billing-api\",\"iat\":1700000000,\"exp\":1700000300}",
    "why": "The starter checks `exp` and `iss` but never `aud`, so a token the same auth server issued for `billing-api` opens `notes-api` too. Normalise `aud` to an array and refuse a token that doesn't name this API."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 50,
      "del": [
       "const LEEWAY = 60000; // allowed clock drift"
      ],
      "add": [
       "const LEEWAY = 60; // allowed clock drift, in seconds like every JWT time"
      ]
     }
    ],
    "after": [],
    "fail": "This token expired two hours ago and was accepted. Look at the unit of every number compared with exp — expected null but got {\"sub\":\"ada\",\"iss\":\"https://auth.example\",\"aud\":\"notes-api\",\"iat\":1699992500,\"exp\":1699992800}",
    "why": "The starter's `LEEWAY` is 60000, a millisecond-sized number used in a check where every time is in seconds. That is almost 17 hours of drift allowance, so a token that expired two hours ago still passes. JWT times are seconds, so the leeway is 60."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 70,
      "del": [
       "  const key = KEYS[header.kid] || Object.values(KEYS)[0];",
       "  const expected = b64urlEncode(hmac(\"sha256\", key, parts[0] + \".\" + parts[1]));",
       "  if (expected !== parts[2]) return null;"
      ],
      "add": [
       "  let given;",
       "  try { given = b64urlDecode(parts[2]); } catch (e) { return null; }",
       "  if (!safeEqual(given, hmac(\"sha256\", KEYS[header.kid], parts[0] + \".\" + parts[1]))) return null;"
      ]
     }
    ],
    "after": [],
    "fail": "The signature should be compared with safeEqual exactly once. It was called 0 times, so a === still stops at the first different character",
    "why": "The starter compares base64url strings with `!==`, which stops at the first different character, so rejecting a bad signature takes longer the more of it is right. Decode the signature to bytes (a bad encoding is `null`) and compare with `safeEqual`, which reads every byte whatever it finds."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 68,
      "del": [],
      "add": [
       "  if (!Object.prototype.hasOwnProperty.call(KEYS, header.kid)) return null; // unknown kid: refuse"
      ]
     }
    ],
    "after": [],
    "fail": "verifyAccessToken threw on a token with an unknown kid (\"expected a string or an array of bytes, got undefined\"). Return null instead",
    "why": "The starter falls back to the first key in `KEYS` when it doesn't recognise the token's `kid`, so a token naming a key that doesn't exist is still checked, and accepted, against some other key. Refuse a `kid` that isn't one of `KEYS`' own properties before any HMAC runs."
   }
  ]
 }
});
