/* GENERATED by tools/build-step-solutions.js — do not edit by hand.
   Explanations come from tools/step-why/auth.json. validate.js fails
   when a lesson changes without a rebuild. */
window.CODELAB.addStepSolutions("auth", {
 "auth-u1-1": {
  "hash": "452be4fd07639794",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 11,
      "del": [
       "  // It works, and anyone can type it. Make the id unguessable: randHex(16).",
       "  const id = \"token-\" + userName;"
      ],
      "add": [
       "  const id = randHex(16); // 128 random bits: nothing to derive, nothing to guess"
      ]
     }
    ],
    "after": [],
    "fail": "A session id should be 32 lowercase hex characters, from randHex(16) — yours was \"token-ada\"",
    "why": "The starter builds the id from the user name, so anyone who has seen `token-ada` can type `token-bo`. A session id is a bearer credential: whoever presents it is that user. It has to come from a random source, and `randHex(16)` gives 128 bits nobody can derive or guess."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 12,
      "del": [
       "  // TODO: the row also records created and lastSeen, both now()",
       "  sessions.set(id, { userName: userName });"
      ],
      "add": [
       "  sessions.set(id, { userName: userName, created: now(), lastSeen: now() });"
      ]
     }
    ],
    "after": [],
    "fail": "The row for bo should be { userName, created: now(), lastSeen: now() }, in that order — expected {\"userName\":\"bo\",\"created\":1700000005000,\"lastSeen\":1700000005000} but got {\"userName\":\"bo\"}",
    "why": "The starter's row records only who the session belongs to. Without `created` and `lastSeen` the server can't tell how old a session is or when it was last used, so the timeouts later in this unit would have nothing to measure."
   },
   {
    "chunks": [],
    "after": [],
    "why": null
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   }
  ]
 },
 "auth-u1-2": {
  "hash": "5ac51d1e2ceefcc3",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 12,
      "del": [
       "  let out = name + \"=\" + value;",
       "  if (opts.path) out += \"; Path=\" + opts.path;",
       "  if (opts.maxAge) out += \"; Max-Age=\" + opts.maxAge;",
       "  if (opts.httpOnly) out += \"; HttpOnly\";",
       "  // TODO: Secure, and SameSite (Strict | Lax | None — None requires Secure)",
       "  // TODO: throw a TypeError for a name or value the cookie grammar forbids",
       "  return out;"
      ],
      "add": [
       "  const parts = [name + \"=\" + value];",
       "  if (opts.path != null) parts.push(\"Path=\" + opts.path);",
       "  if (opts.maxAge != null) parts.push(\"Max-Age=\" + Math.floor(opts.maxAge));",
       "  if (opts.httpOnly) parts.push(\"HttpOnly\");",
       "  if (opts.secure) parts.push(\"Secure\");",
       "  if (opts.sameSite != null) {",
       "    if ([\"Strict\", \"Lax\", \"None\"].indexOf(opts.sameSite) === -1) throw new TypeError(\"SameSite must be Strict, Lax or None\");",
       "    if (opts.sameSite === \"None\" && !opts.secure) throw new TypeError(\"SameSite=None requires Secure\");",
       "    parts.push(\"SameSite=\" + opts.sameSite);",
       "  }",
       "  return parts.join(\"; \");"
      ]
     }
    ],
    "after": [],
    "fail": "Expected exactly Path=/, Max-Age=1800, HttpOnly, Secure and SameSite=Lax, in any order, joined with \"; \" — yours: \"sid=abc123; Path=/; Max-Age=1800; HttpOnly\" — expected [\"HttpOnly\",\"Max-Age=1800\",\"Path=/\",\"SameSite=Lax\",\"Secure\"] but got [\"HttpOnly\",\"Max-Age=1800\",\"Path=/\"]",
    "why": "The starter writes only `Path`, `Max-Age` and `HttpOnly`, so the cookie never gets `Secure` or `SameSite`. It also tests `opts.maxAge` for truthiness, which silently drops `maxAge: 0`. Collecting the parts in an array and checking `!= null` writes every attribute that was set, including a zero."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 4,
      "del": [],
      "add": [
       "const COOKIE_NAME = /^[!#$%&'*+\\-.^_`|~0-9A-Za-z]+$/;",
       "const COOKIE_VALUE = /^[\\x21\\x23-\\x2B\\x2D-\\x3A\\x3C-\\x5B\\x5D-\\x7E]*$/;",
       ""
      ]
     },
     {
      "file": "script.js",
      "line": 9,
      "del": [],
      "add": [
       "  value = String(value);",
       "  if (typeof name !== \"string\" || !COOKIE_NAME.test(name)) throw new TypeError(\"invalid cookie name: \" + JSON.stringify(name));",
       "  if (!COOKIE_VALUE.test(value)) throw new TypeError(\"invalid cookie value: \" + JSON.stringify(value));"
      ]
     }
    ],
    "after": [],
    "fail": "A value of \"abc; Domain=evil.example\" must throw: it would break the header or smuggle in an attribute",
    "why": "The starter puts any name and value straight into the header. A value like `abc; Domain=evil.example` then adds an attribute the server never chose. Checking both against the cookie grammar, and throwing a `TypeError` when they don't match, keeps the header exactly what the caller asked for."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 29,
      "del": [
       "    const [key, val] = part.split(\"=\");",
       "    jar[key.trim()] = val;"
      ],
      "add": [
       "    const eq = part.indexOf(\"=\");",
       "    if (eq === -1) continue;",
       "    const key = part.slice(0, eq).trim();",
       "    if (key && !Object.prototype.hasOwnProperty.call(jar, key)) jar[key] = part.slice(eq + 1).trim();"
      ]
     }
    ],
    "after": [],
    "fail": "Split on the FIRST = only, since a value may contain = itself — yours: {\"next\":\"/a?b\",\"sid\":\"xyz\"} — expected {\"next\":\"/a?b=c\",\"sid\":\"xyz\"} but got {\"next\":\"/a?b\",\"sid\":\"xyz\"}",
    "why": "`part.split(\"=\")` splits on every `=`, and destructuring keeps only the first two pieces, so `next=/a?b=c` loses its `=c`. Cutting at the first `=` with `indexOf` keeps the rest of the value intact. Skipping pieces with no `=` and names already seen stops odd headers from overwriting a real cookie."
   }
  ]
 },
 "auth-u1-3": {
  "hash": "ef510c72e66934bd",
  "steps": [
   {
    "chunks": [],
    "after": [],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 76,
      "del": [
       "    const id = currentId(req);",
       "    if (id) {",
       "      // The id the visitor arrived with is now logged in. So is whoever chose it.",
       "      sessions.get(id).userName = user.userName;",
       "      return { status: 200, body: { ok: true } };",
       "    }"
      ],
      "add": [
       "    const oldId = currentId(req);",
       "    const cart = oldId ? sessions.get(oldId).cart : [];",
       "    if (oldId) sessions.delete(oldId);             // the planted id now points at nothing",
       "    const id = createSession(user.userName, cart);  // a fresh id for the new privilege level"
      ]
     }
    ],
    "after": [],
    "fail": "The attacker replayed the id they planted and got {\"status\":200,\"body\":{\"userName\":\"ada\",\"cart\":[]}}, the account ada just signed into. Login must rotate the id — expected {\"status\":401,\"body\":{\"error\":\"unauthorized\"}} but got {\"status\":200,\"body\":{\"userName\":\"ada\",\"cart\":[]}}",
    "why": "The starter finds the session the visitor arrived with and marks it as logged in. If an attacker planted that id, the attacker's copy now opens the victim's account. Deleting the old row and creating a fresh one at login leaves the planted id pointing at nothing."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 80,
      "del": [
       "    return { status: 200, headers: { \"Set-Cookie\": sessionCookie(createSession(user.userName, [])) }, body: { ok: true } };"
      ],
      "add": [
       "    return { status: 200, headers: { \"Set-Cookie\": sessionCookie(id) }, body: { ok: true } };"
      ]
     }
    ],
    "after": [],
    "fail": "The new sid should be ada, still holding the lamp added before signing in — expected {\"status\":200,\"body\":{\"userName\":\"ada\",\"cart\":[\"lamp\"]}} but got {\"status\":200,\"body\":{\"userName\":\"ada\",\"cart\":[]}}",
    "why": "The starter's login answers with a brand-new session and an empty cart, so anything the visitor added before signing in is lost. Carrying `cart` from the old row into the new one, and sending that new id in `Set-Cookie`, makes the rotation invisible to the shopper."
   },
   {
    "chunks": [],
    "after": [],
    "why": null
   }
  ]
 },
 "auth-u1-4": {
  "hash": "9a7674bd0168322a",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 55,
      "del": [
       "  // TODO: idle timeout, measured from row.lastSeen",
       "  // TODO: absolute timeout, measured from row.created",
       "  // TODO: still alive? slide lastSeen forward to now()"
      ],
      "add": [
       "  const t = now();",
       "  if (t - row.lastSeen >= IDLE_MS || t - row.created >= ABSOLUTE_MS) {",
       "    sessions.delete(id);  // dead rows don't linger",
       "    return null;",
       "  }",
       "  row.lastSeen = t;       // only a live session slides"
      ]
     }
    ],
    "after": [],
    "fail": "A successful request slides lastSeen forward to now() — expected 1700001740000 but got 1700000000000",
    "why": "The starter's `touchSession` returns any row it finds, however old, and never updates it. A session nobody checks against the clock never ends, and one whose `lastSeen` never moves can't have an idle timeout. Read `now()` once, end the session when either limit is reached, and only then slide `lastSeen` forward."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [],
    "after": [],
    "why": null
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   }
  ]
 },
 "auth-u1-5": {
  "hash": "419b4c01e136b29b",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 62,
      "del": [
       "    return { status: 200, headers: { \"Set-Cookie\": \"sid=; Max-Age=0\" }, body: { ok: true } };"
      ],
      "add": [
       "    return { status: 200, headers: { \"Set-Cookie\": clearCookie() }, body: { ok: true } };"
      ]
     },
     {
      "file": "script.js",
      "line": 72,
      "del": [],
      "add": [
       "  function clearCookie() {  // browser half: same Path it was set with",
       "    return serializeCookie(\"sid\", \"\", { path: \"/\", maxAge: 0, httpOnly: true, secure: true, sameSite: \"Lax\" });",
       "  }"
      ]
     }
    ],
    "after": [],
    "fail": "A cookie is matched by name AND path. Without Path=/ the browser keeps the original sid — yours: \"sid=; Max-Age=0\"",
    "why": "The starter's clearing cookie is `sid=; Max-Age=0` with no `Path`. Browsers match a cookie by name and path, so that header can leave the original `sid` in place. Building it with `serializeCookie` and the same `Path=/` the session cookie was set with actually replaces it."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 60,
      "del": [
       "    // Tells the browser to forget the cookie. The server forgets nothing."
      ],
      "add": [
       "    const id = currentId(req);",
       "    if (id) sessions.delete(id);  // server half: the id means nothing now"
      ]
     }
    ],
    "after": [],
    "fail": "The copied id still opened the account after logout ({\"status\":200,\"body\":{\"userName\":\"ada\"}}). Clearing the cookie in one browser does nothing to a copy; delete the row — expected {\"status\":401,\"body\":{\"error\":\"unauthorized\"}} but got {\"status\":200,\"body\":{\"userName\":\"ada\"}}",
    "why": "The starter only tells the browser to forget the cookie; the row stays on the server. Anyone holding a copy of the id (a proxy log, malware, the fixation attacker) keeps using it until it times out. Deleting the row is what makes logout real."
   },
   {
    "chunks": [],
    "after": [],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 64,
      "del": [
       "  // TODO: POST /api/logout-all ends every session the caller's user has"
      ],
      "add": [
       "  if (req.method === \"POST\" && req.path === \"/api/logout-all\") {",
       "    const id = currentId(req);",
       "    if (!id) return { status: 401, body: { error: \"unauthorized\" } };",
       "    const userName = sessions.get(id).userName;",
       "    for (const [sid, row] of sessions) if (row.userName === userName) sessions.delete(sid);",
       "    return { status: 200, headers: { \"Set-Cookie\": clearCookie() }, body: { ok: true } };",
       "  }",
       ""
      ]
     }
    ],
    "after": [],
    "fail": "POST /api/logout-all with a valid session → 200 — got {\"status\":404,\"body\":\"Not found\"} — expected 200 but got 404",
    "why": "The starter has no `/api/logout-all` route, so it answers 404. Signing out everywhere means finding every row with the caller's `userName` and deleting them all, which is only possible because a session is a row the server can search."
   }
  ]
 },
 "auth-u2-1": {
  "hash": "81decacf31486d9a",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 6,
      "del": [
       "    \"sid=7f3a9c21; Domain=app.example; Path=/; Secure; HttpOnly; SameSite=Lax\","
      ],
      "add": [
       "    \"sid=7f3a9c21; Path=/; Secure; HttpOnly; SameSite=Lax\",                  // host-only: never leaves app.example"
      ]
     }
    ],
    "after": [],
    "fail": "blog.app.example received the session cookie ({\"sid\":\"7f3a9c21\",\"theme\":\"dark\"}). A Domain cookie goes to every subdomain: leave Domain off the session",
    "why": "The starter's session line has `Domain=app.example`, and a Domain cookie goes to that domain and every subdomain, so `blog.app.example` (another team's server) receives the session. Leaving Domain off makes the cookie host-only: it only ever goes back to `app.example`."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 7,
      "del": [
       "    \"theme=dark; Path=/; Secure; SameSite=Lax\","
      ],
      "add": [
       "    \"theme=dark; Domain=app.example; Path=/; Secure; SameSite=Lax\",         // every subdomain may read the theme"
      ]
     }
    ],
    "after": [],
    "fail": "The blog should receive theme=dark. A host-only cookie never leaves app.example; this one needs Domain=app.example — expected \"dark\" but got undefined",
    "why": "The starter's theme line has no Domain, so the theme is host-only and never reaches the blog. A preference every subdomain should share is exactly what `Domain=app.example` is for."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 8,
      "del": [
       "    \"docs-lang=fr; Path=/doc; Secure; SameSite=Lax\""
      ],
      "add": [
       "    \"docs-lang=fr; Path=/docs; Secure; SameSite=Lax\""
      ]
     }
    ],
    "after": [],
    "fail": "docs-lang should reach /docs — expected \"fr\" but got undefined",
    "why": "The starter scopes `docs-lang` to `Path=/doc`. Paths match only at a `/` boundary, so `/doc` covers `/doc` and `/doc/...` but not `/docs`. The cookie belongs under `Path=/docs`."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   }
  ]
 },
 "auth-u2-2": {
  "hash": "f9aee4ed24370a91",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 5,
      "del": [
       "    \"__Host-sid=7f3a9c21; Domain=app.example; Path=/; Secure; HttpOnly; SameSite=Lax\","
      ],
      "add": [
       "    \"__Host-sid=7f3a9c21; Path=/; Secure; HttpOnly; SameSite=Lax\",  // no Domain, Path=/, Secure"
      ]
     }
    ],
    "after": [],
    "fail": "The browser refused __Host-sid: __Host- cookies must not have a Domain attribute",
    "why": "The starter gives `__Host-sid` a `Domain` attribute. A `__Host-` name promises the cookie came from exactly this host, so the browser refuses any `__Host-` line that has a Domain at all. Removing it (keeping `Secure` and `Path=/`) makes the line acceptable."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 6,
      "del": [
       "    \"__Secure-pref=compact; Path=/; SameSite=Lax\","
      ],
      "add": [
       "    \"__Secure-pref=compact; Path=/; Secure; SameSite=Lax\","
      ]
     }
    ],
    "after": [],
    "fail": "The browser refused __Secure-pref: __Secure- cookies need the Secure attribute and an https page",
    "why": "The starter's `__Secure-pref` line has no `Secure` attribute, and the `__Secure-` prefix is a promise that it does. The browser refuses the line until `Secure` is added."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 7,
      "del": [
       "    \"__Host-csrf=c5e1; Path=/account; Secure; SameSite=Strict\""
      ],
      "add": [
       "    \"__Host-csrf=c5e1; Path=/; Secure; SameSite=Strict\""
      ]
     }
    ],
    "after": [],
    "fail": "The browser refused __Host-csrf: __Host- cookies must have Path=/",
    "why": "The starter scopes `__Host-csrf` to `Path=/account`. A `__Host-` cookie must have exactly `Path=/`, so the browser refuses the line; with `Path=/` it is stored and sent to every path, `/account` included."
   },
   {
    "chunks": [],
    "after": [
     0,
     1,
     2
    ],
    "why": null
   }
  ]
 },
 "auth-u2-3": {
  "hash": "6cb74c46ffa5ffc3",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 5,
      "del": [
       "  return \"sid=; Expires=Fri, 31 Dec 9999 23:59:59 GMT\";"
      ],
      "add": [
       "  return \"sid=; Path=/; Max-Age=0\"; // same name and Path as the cookie it deletes"
      ]
     }
    ],
    "after": [],
    "fail": "After logout the jar still holds [{\"name\":\"sid\",\"value\":\"\",\"domain\":\"app.example\",\"hostOnly\":true,\"path\":\"/\",\"secure\":false,\"httpOnly\":false,\"sameSite\":\"Default\",\"expires\":253402300799000,\"created\":1700000000000}]. An Expires date in the future keeps the cookie; Max-Age=0 deletes it — expected 0 but got 1",
    "why": "The starter's logout sends an `Expires` date in the year 9999, which does not delete anything: the browser stores an empty `sid` that lasts for centuries. It also has no `Path`, so from `/account/logout` it would be filed under `/account` as a separate cookie. `Path=/` with `Max-Age=0` replaces the real `sid` and deletes it at once, which is why checkpoint 2 passes with the same line."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 9,
      "del": [
       "  return \"remember=\" + token + \"; Path=/; Max-Age=\" + (30 * DAY * 1000) + \"; Secure; HttpOnly; SameSite=Lax\";"
      ],
      "add": [
       "  return \"remember=\" + token + \"; Path=/; Max-Age=\" + (30 * DAY) + \"; Secure; HttpOnly; SameSite=Lax\";"
      ]
     }
    ],
    "after": [],
    "fail": "31 days after login the remember cookie should be gone. Max-Age counts seconds: 30 * DAY, not 30 * DAY * 1000 — expected false but got true",
    "why": "The starter multiplies by 1000, but `Max-Age` counts seconds and `DAY` already is seconds, so the cookie lasts about 82 years instead of 30 days. `Max-Age` is `30 * DAY`."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 17,
      "del": [
       "  // TODO: a visit that carries a remember cookie renews it for another 30 days"
      ],
      "add": [
       "  if (req.cookies.remember) // every visit slides the 30 days forward",
       "    return { status: 200, headers: { \"Set-Cookie\": rememberCookie(req.cookies.remember) }, body: { cookies: req.cookies } };"
      ]
     }
    ],
    "after": [],
    "fail": "Day 45: ada visited on day 20, so the remember cookie should have been renewed until day 50",
    "why": "The starter never sends the remember cookie again after login, so it expires 30 days after sign-in however often ada visits. Sending it again on each visit that carries it slides the 30 days forward, the way Unit 1 slid `lastSeen`."
   }
  ]
 },
 "auth-u2-4": {
  "hash": "e28bc2d8e1e5e509",
  "steps": [
   {
    "chunks": [],
    "after": [],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 5,
      "del": [
       "  return \"sid=\" + sid + \"; Path=/; Secure; HttpOnly; SameSite=None\";"
      ],
      "add": [
       "  return \"sid=\" + sid + \"; Path=/; Secure; HttpOnly; SameSite=Lax\"; // links in, forged POSTs out"
      ]
     }
    ],
    "after": [],
    "fail": "The forged POST from evil.example moved money: the session cookie rode along. A cross-site form POST must not carry it — expected 50 but got 0",
    "why": "The starter's session is `SameSite=None`, so the browser attaches it to every cross-site request, a form on `evil.example` included, and the forged transfer goes through. `Lax` keeps cross-site top-level GET navigations (the email link) and drops cross-site POSTs and fetches; checkpoint 3 tests the fetch half of the same change."
   },
   {
    "chunks": [],
    "after": [
     1
    ],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 10,
      "del": [
       "  return \"widget=on; Path=/; SameSite=None\";"
      ],
      "add": [
       "  return \"widget=on; Path=/; Secure; SameSite=None\";              // None only ever with Secure"
      ]
     }
    ],
    "after": [],
    "fail": "The widget flag did not reach the bank from shop.example: the browser refused a line (SameSite=None requires the Secure attribute) — expected {\"ready\":true} but got {\"ready\":false}",
    "why": "The starter's widget line asks for `SameSite=None` without `Secure`, and browsers refuse that combination, so the flag is never stored and the embedded button never sees it. A cookie meant to ride cross-site requests has to be `Secure`."
   }
  ]
 },
 "auth-u3-1": {
  "hash": "41708011ed5b9eeb",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 25,
      "del": [
       "  // TODO: from a page on evil.example, POST to the bank's /transfer, moving 50 to eve.",
       "  // Use victim.submitForm(pageUrl, { action, fields })."
      ],
      "add": [
       "  // No token, no password — the browser supplies ada's cookie for us.",
       "  return victim.submitForm(\"https://evil.example/prize\", {",
       "    action: \"https://bank.example/transfer\",",
       "    fields: { to: \"eve\", amount: \"50\" }",
       "  });"
      ]
     }
    ],
    "after": [],
    "fail": "The forged POST should move 50 from ada. Her balance is still 100 — is forgeTransfer posting to https://bank.example/transfer with amount 50? — expected 50 but got 100",
    "why": "The starter's `forgeTransfer` does nothing, so no request is made and the balance stays put. The attack is a single cross-site form POST from a page on `evil.example` to the bank's `/transfer`. It needs no token and no password: the browser attaches ada's session cookie to the request on its own. The later checkpoints inspect that same request."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   }
  ]
 },
 "auth-u3-2": {
  "hash": "51d6b242971a4019",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 10,
      "del": [
       "  // TODO: mint with randHex(16) the first time, store in csrfTokens, and reuse it after",
       "  return \"token\";"
      ],
      "add": [
       "  if (!csrfTokens.has(sid)) csrfTokens.set(sid, randHex(16)); // one token per session",
       "  return csrfTokens.get(sid);"
      ]
     }
    ],
    "after": [],
    "fail": "GET /form should return a csrf token — got \"token\"",
    "why": "The starter returns the fixed string \"token\", so every session shares one guessable value. Minting `randHex(16)` on first use and storing it per session gives each session its own unguessable token, stable across the requests that read it."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 16,
      "del": [
       "  // TODO: 403 unless req.body.csrf is this session's token; otherwise null"
      ],
      "add": [
       "  if (!req.body || req.body.csrf !== csrfFor(sid)) // must be THIS session's token",
       "    return { status: 403, body: { error: \"bad csrf token\" } };"
      ]
     }
    ],
    "after": [],
    "fail": "The forged POST carries no csrf token, so it must be refused — got {\"status\":200,\"headers\":{},\"body\":{\"balance\":50},\"url\":\"https://bank.example/transfer\"} — expected 403 but got 200",
    "why": "The starter's `checkCsrf` allows every request, so the forged POST goes through. Requiring `req.body.csrf` to equal this session's token refuses a forgery, which arrives without the token because the attacker's page can't read it off your origin's form."
   },
   {
    "chunks": [],
    "after": [
     0,
     1
    ],
    "why": null
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   }
  ]
 },
 "auth-u3-3": {
  "hash": "010e7976c4f6c45b",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 10,
      "del": [
       "  // TODO: nonce = randHex(8); token = nonce + \".\" + hex(hmac(\"sha256\", CSRF_KEY, sid + \"!\" + nonce))",
       "  return randHex(8);"
      ],
      "add": [
       "  const nonce = randHex(8);",
       "  return nonce + \".\" + hex(hmac(\"sha256\", CSRF_KEY, sid + \"!\" + nonce)); // bound to this session"
      ]
     },
     {
      "file": "script.js",
      "line": 16,
      "del": [
       "  // Naive double-submit: the caller compares this against the cookie. It ignores the session.",
       "  // TODO: split off the nonce, recompute the signature from sid, and compare",
       "  return typeof token === \"string\";"
      ],
      "add": [
       "  const parts = String(token).split(\".\");",
       "  if (parts.length !== 2) return false;",
       "  const want = hex(hmac(\"sha256\", CSRF_KEY, sid + \"!\" + parts[0])); // recompute from the SESSION's sid",
       "  return parts[1] === want;"
      ]
     }
    ],
    "after": [],
    "fail": "A token is randHex(8) + \".\" + hex of an HMAC-SHA256 — got \"631752e6d021df7f\"",
    "why": "The starter returns a bare nonce as the token and, in `tokenValid`, accepts any string, which is the naive double-submit that a sibling subdomain defeats by setting both halves. Signing the nonce with `hmac(\"sha256\", CSRF_KEY, sid + \"!\" + nonce)` binds the token to the session, and verifying by recomputing that signature from the request's own `sid` rejects any value the attacker invents, since they lack the key. The other checkpoints exercise this same pair."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   }
  ]
 },
 "auth-u3-4": {
  "hash": "0aaa89de83fa0035",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 12,
      "del": [
       "  // TODO: if site is present, block only when it is \"cross-site\"",
       "  // TODO: if site is absent, block when Origin is set and not in ALLOWED_ORIGINS"
      ],
      "add": [
       "  if (site) {",
       "    if (site === \"cross-site\") return { status: 403, body: { error: \"cross-site request refused\" } };",
       "    return null; // same-origin, same-site or none",
       "  }",
       "  const origin = req.headers.origin; // older browser: fall back to Origin",
       "  if (origin && ALLOWED_ORIGINS.indexOf(origin) === -1) return { status: 403, body: { error: \"cross-site request refused\" } };"
      ]
     }
    ],
    "after": [],
    "fail": "cross-site must be blocked with a 403 — got null",
    "why": "The starter's `csrfGuard` allows everything, so a cross-site POST still lands. Blocking when `Sec-Fetch-Site` is `cross-site`, and falling back to an `Origin` allow-list when that header is absent, refuses the forgery while leaving same-origin and same-site requests alone. The remaining checkpoints test this same guard through the browser."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [],
    "after": [],
    "why": null
   }
  ]
 },
 "auth-u4-1": {
  "hash": "98d87a197feb340d",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 7,
      "del": [
       "  // TODO: take the bytes 3 at a time and join them into one 24-bit number;",
       "  // write 4 characters for a full group, 3 for 2 bytes, 2 for 1 byte"
      ],
      "add": [
       "  for (let i = 0; i < bytes.length; i += 3) {",
       "    const n = (bytes[i] << 16) | ((bytes[i + 1] || 0) << 8) | (bytes[i + 2] || 0);",
       "    const chars = Math.min(bytes.length - i, 3) + 1; // 1 byte -> 2 chars, 2 -> 3, 3 -> 4",
       "    for (let j = 0; j < chars; j++) out += B64URL[(n >> (18 - 6 * j)) & 63];",
       "  }"
      ]
     }
    ],
    "after": [],
    "fail": "b64urlEncode of the bytes of \"f\" (1 bytes, so 2 characters) — expected \"Zg\" but got \"\"",
    "why": "The starter's encoder never reads the bytes, so it returns an empty string. base64url takes the bytes three at a time as one 24-bit number and writes four 6-bit characters, or two or three for a short final group, with no `=` padding."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 17,
      "del": [
       "  // TODO: throw for length % 4 === 1 or any character outside B64URL;",
       "  // collect 6 bits per character and emit a byte whenever 8 have built up",
       "  return new Uint8Array(0);"
      ],
      "add": [
       "  if (typeof str !== \"string\" || str.length % 4 === 1) throw new Error(\"not base64url: \" + JSON.stringify(str));",
       "  const out = new Uint8Array(Math.floor(str.length * 3 / 4));",
       "  let n = 0, bits = 0, o = 0;",
       "  for (let i = 0; i < str.length; i++) {",
       "    const v = B64URL.indexOf(str[i]);",
       "    if (v === -1) throw new Error(\"not base64url: \" + JSON.stringify(str));",
       "    n = ((n << 6) | v) & 0xffffff;",
       "    bits += 6;",
       "    if (bits >= 8) { bits -= 8; out[o++] = (n >> bits) & 255; }",
       "  }",
       "  return out;"
      ]
     }
    ],
    "after": [],
    "fail": "Zm9vYmFy decodes to the bytes of foobar — expected [102,111,111,98,97,114] but got []",
    "why": "The starter's decoder returns an empty array for every input. Decoding runs the encoder backwards: each character is worth 6 bits, and a byte comes out whenever 8 bits have built up. It also has to throw for a character outside the alphabet and for a length that leaves one stray character."
   },
   {
    "chunks": [],
    "after": [
     2
    ],
    "why": null
   }
  ]
 },
 "auth-u4-2": {
  "hash": "ebecfab62cb6f162",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 35,
      "del": [],
      "add": [
       "function mac(text) {",
       "  return b64urlEncode(hmac(\"sha256\", SECRET, text));",
       "}",
       ""
      ]
     },
     {
      "file": "script.js",
      "line": 41,
      "del": [
       "  // TODO: add a dot and the base64url HMAC of the payload part",
       "  return payload;"
      ],
      "add": [
       "  return payload + \".\" + mac(payload);"
      ]
     }
    ],
    "after": [],
    "fail": "sign() should return base64url(JSON) + \".\" + base64url(HMAC-SHA256(SECRET, that first part)) — expected \"eyJzdWIiOiJhZGEiLCJyb2xlIjoidXNlciJ9.2XH8urf0hWjEuIY6MBYBjy1MaknjwJl8lizyiUMyMtE\" but got \"eyJzdWIiOiJhZGEiLCJyb2xlIjoidXNlciJ9\"",
    "why": "The starter's `sign` returns only the encoded payload, with no signature, so anyone could write their own token. Appending a dot and the base64url HMAC of the payload means only a holder of `SECRET` can produce a token that matches."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 46,
      "del": [
       "  const [payload] = String(token).split(\".\");",
       "  // TODO: recompute the signature and refuse anything that doesn't match",
       "  return JSON.parse(fromBytes(b64urlDecode(payload)));"
      ],
      "add": [
       "  const parts = String(token).split(\".\");",
       "  if (parts.length !== 2) return null;",
       "  if (mac(parts[0]) !== parts[1]) return null; // signature first: the payload is untrusted text until then",
       "  try {",
       "    return JSON.parse(fromBytes(b64urlDecode(parts[0])));",
       "  } catch (e) {",
       "    return null;",
       "  }"
      ]
     }
    ],
    "after": [],
    "fail": "Someone edited the payload to role admin and kept the old signature. Your verify returned {\"sub\":\"ada\",\"role\":\"admin\"}: recompute the HMAC and compare — expected null but got {\"sub\":\"ada\",\"role\":\"admin\"}",
    "why": "The starter's `verify` decodes whatever payload it gets and never checks a signature, so an edited `role: \"admin\"` goes straight through. Recompute the HMAC and refuse a mismatch first; only then parse the payload, inside a `try`, so a malformed token is `null` rather than an exception."
   },
   {
    "chunks": [],
    "after": [
     0,
     2
    ],
    "why": null
   }
  ]
 },
 "auth-u4-3": {
  "hash": "a14718ef1f00ec71",
  "steps": [
   {
    "chunks": [],
    "after": [
     1
    ],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 39,
      "del": [
       "// Compares two byte arrays. Right answer, wrong timing: it stops at the first difference."
      ],
      "add": [
       "// Every byte is read, whatever the first difference. Only the length can leak,",
       "// and every HMAC-SHA256 is 32 bytes."
      ]
     },
     {
      "file": "script.js",
      "line": 43,
      "del": [
       "  for (let i = 0; i < a.length; i++) {",
       "    if (a[i] !== b[i]) return false;",
       "  }",
       "  return true;"
      ],
      "add": [
       "  let diff = 0;",
       "  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];",
       "  return diff === 0;"
      ]
     }
    ],
    "after": [],
    "fail": "A mismatch at byte 0 cost 2 reads, a mismatch at byte 31 cost 64, a match cost 64. That difference is the timing leak: read every byte, whatever you find",
    "why": "The starter's loop returns at the first byte that differs, so a signature wrong in byte 0 is rejected sooner than one wrong in byte 31. Measured over many requests, that difference gives a valid signature away byte by byte. OR-ing every byte's XOR into one number and checking it once at the end costs the same whatever the input."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 51,
      "del": [
       "  const expected = b64urlEncode(hmac(\"sha256\", SECRET, parts[0]));",
       "  if (expected !== parts[1]) return null; // TODO: decode parts[1] and compare BYTES with safeEqual"
      ],
      "add": [
       "  let given;",
       "  try { given = b64urlDecode(parts[1]); } catch (e) { return null; }",
       "  if (!safeEqual(given, hmac(\"sha256\", SECRET, parts[0]))) return null;"
      ]
     }
    ],
    "after": [],
    "fail": "verify should compare the signature bytes with safeEqual exactly once. It was called 0 times, so the comparison is still a === that stops at the first different character",
    "why": "The starter's `verify` still compares base64url strings with `!==`, which stops at the first different character and never calls `safeEqual`. Decoding the given signature to bytes (refusing one that won't decode) and comparing with `safeEqual` closes the leak where it matters."
   },
   {
    "chunks": [],
    "after": [
     1
    ],
    "why": null
   }
  ]
 },
 "auth-u4-4": {
  "hash": "29d89accd3b1424a",
  "steps": [
   {
    "chunks": [],
    "after": [],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 52,
      "del": [
       "// Starter: ignores the kid and tries every key until one matches."
      ],
      "add": []
     },
     {
      "file": "script.js",
      "line": 55,
      "del": [],
      "add": [
       "  const kid = parts[0];",
       "  if (!Object.prototype.hasOwnProperty.call(KEYS, kid)) return null; // unknown kid: refuse, don't go hunting"
      ]
     },
     {
      "file": "script.js",
      "line": 59,
      "del": [
       "  const signed = parts[0] + \".\" + parts[1];",
       "  for (const kid in KEYS) {",
       "    if (safeEqual(given, hmac(\"sha256\", KEYS[kid], signed))) {",
       "      try { return JSON.parse(fromBytes(b64urlDecode(parts[1]))); } catch (e) { return null; }",
       "    }"
      ],
      "add": [
       "  if (!safeEqual(given, hmac(\"sha256\", KEYS[kid], kid + \".\" + parts[1]))) return null;",
       "  try {",
       "    return JSON.parse(fromBytes(b64urlDecode(parts[1])));",
       "  } catch (e) {",
       "    return null;"
      ]
     },
     {
      "file": "script.js",
      "line": 65,
      "del": [
       "  return null;"
      ],
      "add": []
     }
    ],
    "after": [],
    "fail": "This token says 2026-09 but was signed with the August key. Your verify returned {\"sub\":\"ada\"}: check the signature with the key the kid names, and only that key — expected null but got {\"sub\":\"ada\"}",
    "why": "The starter ignores the `kid` and tries every key until one matches, so the label means nothing: a token that says `2026-09` but was signed with August's key still passes, and an unknown `kid` costs one HMAC per key. Looking the `kid` up with `hasOwnProperty` and checking only that key fixes both."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 68,
      "del": [
       "  // TODO: throw if kid already exists; add the key; sign with it from now on"
      ],
      "add": [
       "  if (Object.prototype.hasOwnProperty.call(KEYS, kid)) throw new Error(\"kid already exists: \" + kid);",
       "  KEYS[kid] = secret;",
       "  currentKid = kid; // new tokens use it; old tokens still verify under their own kid"
      ]
     }
    ],
    "after": [],
    "fail": "After rotateKey, sign should use the new key, so tokens start \"2026-10.\" — yours: 2026-09.eyJzdWIiOiJhZGEifQ.bpxMFB4s2QnaFIvqoxmNJTpXQ0NcGKjY88tuHEugOI0",
    "why": "The starter's `rotateKey` does nothing, so `sign` keeps using the old key. Rotating adds the new secret and switches `currentKid` to it, and it refuses a `kid` that already exists, because silently replacing a secret breaks every token it signed."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 74,
      "del": [
       "  // TODO: throw if kid is the key sign() uses; otherwise delete it"
      ],
      "add": [
       "  if (kid === currentKid) throw new Error(\"cannot retire the key sign() is using: \" + kid);",
       "  delete KEYS[kid];"
      ]
     }
    ],
    "after": [],
    "fail": "After retireKey(\"2026-08\"), August tokens must stop verifying — expected null but got {\"sub\":\"bo\"}",
    "why": "The starter's `retireKey` does nothing, so a retired key keeps verifying its tokens forever. Deleting it from `KEYS` ends them, and refusing to delete `currentKid` stops every newly signed token from failing at once."
   }
  ]
 },
 "auth-u5-1": {
  "hash": "5d862413c48504c2",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 60,
      "del": [
       "  // TODO: three parts; the first two are base64url JSON (readPart); keep the signature as text",
       "  return null;"
      ],
      "add": [
       "  const parts = String(token).split(\".\");",
       "  if (parts.length !== 3) return null;",
       "  try {",
       "    return { header: readPart(parts[0]), payload: readPart(parts[1]), signature: parts[2] };",
       "  } catch (e) {",
       "    return null;",
       "  }"
      ]
     }
    ],
    "after": [],
    "fail": "decodeJwt should return { header, payload, signature }. No key is needed to read a JWT — expected {\"header\":{\"alg\":\"HS256\",\"typ\":\"JWT\"},\"payload\":{\"sub\":\"ada\",\"exp\":1700000000},\"signature\":\"fV-HwGz830YHmMilXlswsjAFDg8mJmcqKa4Znyv7ZzU\"} but got null",
    "why": "The starter's `decodeJwt` returns `null` for every token, so it never shows what a JWT carries. A JWT is three base64url parts: the first two are JSON anyone can read with `readPart`, and the third is the signature, kept as text. Reading them inside a `try` makes a malformed token `null` instead of an exception."
   },
   {
    "chunks": [],
    "after": [],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 72,
      "del": [
       "  // The whole user record goes into the token.",
       "  return mint(Object.assign({}, user, { sub: user.userName, iat: iat, exp: iat + 900 }));"
      ],
      "add": [
       "  // Only what the next request needs. Everything here is readable by anyone.",
       "  return mint({ sub: user.userName, role: user.role, iat: iat, exp: iat + 900 });"
      ]
     }
    ],
    "after": [],
    "fail": "Anyone holding the token can read every claim. Yours carries [\"userName\",\"role\",\"email\",\"passwordHash\",\"resetToken\",\"sub\",\"iat\",\"exp\"] — expected [\"exp\",\"iat\",\"role\",\"sub\"] but got [\"email\",\"exp\",\"iat\",\"passwordHash\",\"resetToken\",\"role\",\"sub\",\"userName\"]",
    "why": "The starter copies the whole user record into the token, so the email, password hash and reset token travel with every request, readable by anyone who decodes it. Building the claims by hand keeps the token to what the server needs next time: who (`sub`), what they may do (`role`) and when (`iat`, `exp`)."
   },
   {
    "chunks": [],
    "after": [
     2
    ],
    "why": null
   }
  ]
 },
 "auth-u5-2": {
  "hash": "675d0a20d5669fe5",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 68,
      "del": [
       "  // TODO: part() the header { alg: \"none\", typ: \"JWT\" } and the claims, then add a dot and nothing else",
       "  return \"\";"
      ],
      "add": [
       "  return part({ alg: \"none\", typ: \"JWT\" }) + \".\" + part(claims) + \".\";"
      ]
     }
    ],
    "after": [],
    "fail": "A JWT always has three parts, even an unsigned one — yours: \"\" — expected 3 but got 1",
    "why": "The starter's `forgeNone` returns an empty string, which isn't a JWT at all. An unsecured JWT is still three parts: a header saying `alg: \"none\"`, the claims, and an empty signature after the last dot."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 77,
      "del": [
       "  if (header.alg === \"none\") return payload; // \"unsecured JWTs are part of the spec\"",
       "  if (header.alg !== \"HS256\") return null;"
      ],
      "add": [
       "  if (!header || header.alg !== \"HS256\") return null; // the server decides; the token only claims"
      ]
     }
    ],
    "after": [],
    "fail": "The alg none token must be refused — expected null but got {\"sub\":\"admin\",\"role\":\"admin\"}",
    "why": "The starter keeps the legacy rule that returns the payload whenever the header says `none`, so the token decides how it gets checked. Allowing exactly `HS256`, and refusing a header that isn't an object, puts that decision back on the server: `none` in any spelling, `HS512` and a missing `alg` all fall out."
   },
   {
    "chunks": [],
    "after": [],
    "why": null
   }
  ]
 },
 "auth-u5-3": {
  "hash": "4f5e025aab195624",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 73,
      "del": [
       "  // TODO: exp (required) and nbf (if present), in seconds, with LEEWAY either way",
       "  // TODO: iss must be ISSUER; aud (a string or an array) must include AUDIENCE"
      ],
      "add": [
       "  const t = Math.floor(now() / 1000);",
       "  if (typeof claims.exp !== \"number\" || t > claims.exp + LEEWAY) return null;",
       "  if (claims.nbf != null && (typeof claims.nbf !== \"number\" || t < claims.nbf - LEEWAY)) return null;",
       "  if (claims.iss !== ISSUER) return null;",
       "  const aud = Array.isArray(claims.aud) ? claims.aud : [claims.aud];",
       "  if (aud.indexOf(AUDIENCE) === -1) return null;"
      ]
     }
    ],
    "after": [],
    "fail": "90 seconds past exp is outside the leeway: refused — expected null but got {\"sub\":\"ada\",\"iss\":\"https://auth.example\",\"aud\":\"notes-api\",\"iat\":1700000000,\"exp\":1700000300}",
    "why": "The starter's `acceptToken` returns any correctly signed token, so an expired one, one not valid yet, one from another issuer and one meant for another API all get in. Each claim needs its own check, in seconds (`Math.floor(now() / 1000)`) with `LEEWAY` for clock drift. All four checks live in this one block, which is why the later checkpoints pass once this one does."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   }
  ]
 },
 "auth-u5-4": {
  "hash": "3d7d407236c8b9c5",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 91,
      "del": [],
      "add": [
       "  return issuePair(userName, randHex(8)); // a new login starts a new family",
       "}",
       "",
       "function issuePair(userName, family) {"
      ]
     },
     {
      "file": "script.js",
      "line": 96,
      "del": [
       "  refreshTokens.set(refresh, { userName: userName }); // TODO: store sha256(refresh), a family id and used: false"
      ],
      "add": [
       "  refreshTokens.set(sha256(refresh), { userName: userName, family: family, used: false });"
      ]
     }
    ],
    "after": [],
    "fail": "The raw refresh token is a key in refreshTokens, so a leaked table would hand out working tokens. Store sha256(refresh) instead",
    "why": "The starter stores the raw refresh token as the Map key and records no family or `used` flag. A leaked table would hand out working tokens, and there would be nothing to rotate or revoke. Keying by `sha256(refresh)` and recording the family with `used: false` gives each refresh token a row the server can reason about."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 101,
      "del": [
       "  const row = refreshTokens.get(oldRefresh);"
      ],
      "add": [
       "  const row = refreshTokens.get(sha256(String(oldRefresh)));"
      ]
     },
     {
      "file": "script.js",
      "line": 103,
      "del": [
       "  // TODO: rotate: mark this token used and hand out a new one in the same family",
       "  // TODO: a used token presented again means it was copied: revoke the whole family",
       "  return { access: issueAccess(row.userName), refresh: oldRefresh };"
      ],
      "add": [
       "  if (row.used) {",
       "    // Presented twice: someone else holds a copy. End every token in this family.",
       "    for (const [key, r] of refreshTokens) if (r.family === row.family) refreshTokens.delete(key);",
       "    return null;",
       "  }",
       "  row.used = true;",
       "  return issuePair(row.userName, row.family);"
      ]
     }
    ],
    "after": [],
    "fail": "refreshSession should return { access, refresh } for a valid refresh token — got null",
    "why": "The starter hands back the same refresh token every time and never notices one being used twice. Rotation marks the old row `used` and issues a new token in the same family, and a used token that comes back means someone copied it, so every token in that family is deleted. The lookup also has to go by `sha256`, since that is how the rows are stored."
   },
   {
    "chunks": [],
    "after": [
     0,
     1
    ],
    "why": null
   },
   {
    "chunks": [],
    "after": [
     0,
     1
    ],
    "why": null
   }
  ]
 },
 "auth-u5-p": {
  "hash": "79eaf2f6042e816e",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 67,
      "del": [
       "  if (header.alg === \"none\") return checkClaims(claims);"
      ],
      "add": [
       "  if (header.alg !== \"HS256\") return null;                                  // the server decides"
      ]
     }
    ],
    "after": [],
    "fail": "An alg:none token with no signature was accepted as admin. The server decides the algorithm — expected null but got {\"sub\":\"admin\",\"iss\":\"https://auth.example\",\"aud\":\"notes-api\",\"iat\":1700000000,\"exp\":1700000300,\"role\":\"admin\"}",
    "why": "The starter returns the claims for any token whose header says `alg: none`, so an unsigned token claiming to be admin gets in. The server allows exactly `HS256` and refuses everything else."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 81,
      "del": [],
      "add": [
       "  const aud = Array.isArray(claims.aud) ? claims.aud : [claims.aud];",
       "  if (aud.indexOf(AUDIENCE) === -1) return null;"
      ]
     }
    ],
    "after": [],
    "fail": "A token for billing-api opened notes-api. Check aud — expected null but got {\"sub\":\"ada\",\"iss\":\"https://auth.example\",\"aud\":\"billing-api\",\"iat\":1700000000,\"exp\":1700000300}",
    "why": "The starter checks `exp` and `iss` but never `aud`, so a token the same auth server issued for `billing-api` opens `notes-api` too. Normalise `aud` to an array and refuse a token that doesn't name this API."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 50,
      "del": [
       "const LEEWAY = 60000; // allowed clock drift"
      ],
      "add": [
       "const LEEWAY = 60; // allowed clock drift, in seconds like every JWT time"
      ]
     }
    ],
    "after": [],
    "fail": "This token expired two hours ago and was accepted. Look at the unit of every number compared with exp — expected null but got {\"sub\":\"ada\",\"iss\":\"https://auth.example\",\"aud\":\"notes-api\",\"iat\":1699992500,\"exp\":1699992800}",
    "why": "The starter's `LEEWAY` is 60000, a millisecond-sized number used in a check where every time is in seconds. That is almost 17 hours of drift allowance, so a token that expired two hours ago still passes. JWT times are seconds, so the leeway is 60."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 70,
      "del": [
       "  const key = KEYS[header.kid] || Object.values(KEYS)[0];",
       "  const expected = b64urlEncode(hmac(\"sha256\", key, parts[0] + \".\" + parts[1]));",
       "  if (expected !== parts[2]) return null;"
      ],
      "add": [
       "  let given;",
       "  try { given = b64urlDecode(parts[2]); } catch (e) { return null; }",
       "  if (!safeEqual(given, hmac(\"sha256\", KEYS[header.kid], parts[0] + \".\" + parts[1]))) return null;"
      ]
     }
    ],
    "after": [],
    "fail": "The signature should be compared with safeEqual exactly once. It was called 0 times, so a === still stops at the first different character",
    "why": "The starter compares base64url strings with `!==`, which stops at the first different character, so rejecting a bad signature takes longer the more of it is right. Decode the signature to bytes (a bad encoding is `null`) and compare with `safeEqual`, which reads every byte whatever it finds."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 68,
      "del": [],
      "add": [
       "  if (!Object.prototype.hasOwnProperty.call(KEYS, header.kid)) return null; // unknown kid: refuse"
      ]
     }
    ],
    "after": [],
    "fail": "verifyAccessToken threw on a token with an unknown kid (\"expected a string or an array of bytes, got undefined\"). Return null instead",
    "why": "The starter falls back to the first key in `KEYS` when it doesn't recognise the token's `kid`, so a token naming a key that doesn't exist is still checked, and accepted, against some other key. Refuse a `kid` that isn't one of `KEYS`' own properties before any HMAC runs."
   }
  ]
 },
 "auth-u6-1": {
  "hash": "176f8b9d28427cb1",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 71,
      "del": [
       "  // TODO: return the IdP /authorize URL with response_type=code, client_id,",
       "  // redirect_uri (URL-encoded), and scope=openid.",
       "  return \"https://idp.example/authorize\";"
      ],
      "add": [
       "  return \"https://idp.example/authorize?response_type=code\" +",
       "    \"&client_id=\" + CLIENT_ID +",
       "    \"&redirect_uri=\" + encodeURIComponent(REDIRECT_URI) +",
       "    \"&scope=openid\";"
      ]
     }
    ],
    "after": [],
    "fail": "response_type must be code — expected \"code\" but got null",
    "why": "The starter's `buildAuthorizeUrl` returns the bare endpoint with no query, so the IdP has nothing to act on. The authorize URL has to name the flow (`response_type=code`), the app (`client_id`), where to send the code (`redirect_uri`, URL-encoded) and what it wants (`scope=openid`). Checkpoint 2's redirect chain depends on this same URL being right."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 80,
      "del": [
       "    // TODO: read req.query.code, exchange it with idpToken({...}), and on success",
       "    // store tokens.sub in a session and redirect to \"/\".",
       "    return { status: 200, body: { todo: true } };"
      ],
      "add": [
       "    const tokens = idpToken({ grant_type: \"authorization_code\", code: req.query.code, client_id: CLIENT_ID, redirect_uri: REDIRECT_URI });",
       "    if (tokens.error) return { status: 400, body: tokens };",
       "    const s = \"app-\" + (++appSeq); sessions.set(s, tokens.sub); // the app's own session, for the IdP user",
       "    return { status: 303, headers: { \"Set-Cookie\": \"appsid=\" + s + \"; Path=/; Secure; HttpOnly; SameSite=Lax\" }, Location: \"/\" };"
      ]
     }
    ],
    "after": [],
    "fail": "After the flow the app session should hold the IdP sub. Did the callback call idpToken and store tokens.sub? — expected \"idp-ada-42\" but got null",
    "why": "The starter's `/callback` returns a placeholder and never exchanges the code, so no session is created. Calling `idpToken` with the code on the back channel, then storing `tokens.sub` in a session cookie, is what actually signs the user in."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   }
  ]
 },
 "auth-u6-2": {
  "hash": "34b57de276628867",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 74,
      "del": [
       "    // TODO: make a state (newState()), set it in an oauth_state cookie (SameSite=Lax),",
       "    // and add &state=<value> to the authorize URL."
      ],
      "add": [
       "    const state = newState();"
      ]
     },
     {
      "file": "script.js",
      "line": 76,
      "del": [
       "      \"&redirect_uri=\" + encodeURIComponent(REDIRECT_URI) + \"&scope=openid\";",
       "    return { status: 302, headers: { Location: url } };"
      ],
      "add": [
       "      \"&redirect_uri=\" + encodeURIComponent(REDIRECT_URI) + \"&scope=openid&state=\" + state;",
       "    return { status: 302, headers: { \"Set-Cookie\": \"oauth_state=\" + state + \"; Path=/; Secure; HttpOnly; SameSite=Lax\", Location: url } };"
      ]
     }
    ],
    "after": [],
    "fail": "The authorize URL needs a state parameter",
    "why": "The starter's `/login` sends no `state` at all, so there is nothing to check on the way back. Minting a state, setting it in a `SameSite=Lax` `oauth_state` cookie, and putting the same value on the authorize URL gives the callback something bound to this browser to compare against."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 81,
      "del": [
       "    // TODO: reject with 403 unless q.state matches the oauth_state cookie."
      ],
      "add": [
       "    if (!q.state || q.state !== req.cookies.oauth_state) return { status: 403, body: { error: \"bad state\" } }; // bound to this browser"
      ]
     }
    ],
    "after": [],
    "fail": "The victim was signed in from an injected callback. Reject a callback whose state does not match the oauth_state cookie — expected null but got \"idp-attacker-666\"",
    "why": "The starter's `/callback` exchanges any code it is handed, so an attacker's code injected via a lured link logs the victim into the attacker's account. Refusing the request unless `req.query.state` equals the `oauth_state` cookie — before calling `idpToken` — rejects a callback the app didn't start."
   },
   {
    "chunks": [],
    "after": [
     0,
     2
    ],
    "why": null
   }
  ]
 },
 "auth-u6-3": {
  "hash": "b71104160a3998bf",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 77,
      "del": [
       "  // TODO: base64url(SHA-256(verifier)). sha256Bytes and b64url are provided.",
       "  return verifier;"
      ],
      "add": [
       "  return b64url(sha256Bytes(toBytes(verifier)));"
      ]
     }
    ],
    "after": [],
    "fail": "The S256 challenge is base64url(SHA-256(verifier)) — this is the RFC 7636 App. B vector — expected \"E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM\" but got \"dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk\"",
    "why": "The starter's `challengeFor` returns the verifier unchanged, so the challenge equals the verifier and PKCE proves nothing. The S256 challenge is `base64url(SHA-256(verifier))`: a one-way hash, so the value in the authorize URL can't be turned back into the verifier the exchange needs."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 81,
      "del": [
       "  // TODO: include code_challenge and code_challenge_method=S256."
      ],
      "add": []
     },
     {
      "file": "script.js",
      "line": 82,
      "del": [
       "    \"&redirect_uri=\" + encodeURIComponent(REDIRECT_URI) + \"&scope=openid\";"
      ],
      "add": [
       "    \"&redirect_uri=\" + encodeURIComponent(REDIRECT_URI) + \"&scope=openid\" +",
       "    \"&code_challenge=\" + challengeFor(CODE_VERIFIER) + \"&code_challenge_method=S256\";"
      ]
     }
    ],
    "after": [],
    "fail": "Name the method: S256 — expected \"S256\" but got null",
    "why": "The starter's authorize URL omits the challenge, so the IdP stores none and can't bind the code to this app. Adding `code_challenge` (the hash) and `code_challenge_method=S256`, while keeping the verifier out of the URL, is what makes a stolen code useless. Checkpoint 3's exchange relies on this challenge being present."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 89,
      "del": [
       "    // TODO: pass code_verifier: CODE_VERIFIER in the exchange.",
       "    const tokens = idpToken({ grant_type: \"authorization_code\", code: req.query.code, client_id: CLIENT_ID, redirect_uri: REDIRECT_URI });"
      ],
      "add": [
       "    const tokens = idpToken({ grant_type: \"authorization_code\", code: req.query.code, client_id: CLIENT_ID, redirect_uri: REDIRECT_URI, code_verifier: CODE_VERIFIER });"
      ]
     }
    ],
    "after": [],
    "fail": "With the matching verifier the exchange succeeds — expected \"idp-ada-42\" but got null",
    "why": "The starter's exchange sends no `code_verifier`, so the IdP's PKCE check fails and no session is created. Passing `code_verifier: CODE_VERIFIER` on the back channel proves the app that redeems the code is the one that started the flow."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   }
  ]
 },
 "auth-u6-4": {
  "hash": "88df6b2c3e84bb85",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 45,
      "del": [
       "      return { status: 400, body: \"bad redirect_uri\" };"
      ],
      "add": [
       "    if (q.redirect_uri !== REDIRECT_URI) return { status: 400, body: \"bad redirect_uri\" }; // exact match only"
      ]
     }
    ],
    "after": [],
    "fail": "The registered redirect_uri should receive the redirect — expected \"https://app.example/callback\" but got \"https://idp.example/authorize\"",
    "why": "The starter matches `redirect_uri` with a prefix check, so a genuine sign-in still works but the door is open. Comparing the whole string against the registered `REDIRECT_URI` keeps the honest case working while it closes checkpoint 2's attack."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 45,
      "del": [
       "    // Starter: a prefix match. It also passes https://app.example.evil.example/callback.",
       "    if (q.redirect_uri.indexOf(REDIRECT_URI.replace(\"/callback\", \"\")) !== 0)"
      ],
      "add": []
     }
    ],
    "after": [],
    "fail": "The IdP redirected the code to app.example.evil.example. A startsWith check passes that host — compare the whole string",
    "why": "The prefix check accepts `https://app.example.evil.example/callback`, because it begins with `https://app.example`, and the IdP then redirects a live code to the attacker's host. An exact `!==` comparison rejects any redirect_uri that isn't the registered one, so the code is never issued."
   },
   {
    "chunks": [],
    "after": [
     1
    ],
    "why": null
   },
   {
    "chunks": [],
    "after": [],
    "why": null
   }
  ]
 },
 "auth-u6-5": {
  "hash": "556973b6655c50fa",
  "steps": [
   {
    "chunks": [],
    "after": [
     1
    ],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 81,
      "del": [
       "  // TODO: check the HS256 signature with IDP_SECRET, then the claims:",
       "  //   iss === \"https://idp.example\", aud === CLIENT_ID, nonce === expectedNonce,",
       "  //   and exp is in the future (now() is milliseconds; exp is seconds).",
       "  return decodePayload(token);"
      ],
      "add": [
       "  let header;",
       "  try { header = JSON.parse(fromBytes(b64urlDecode(parts[0]))); } catch (e) { return null; }",
       "  if (!header || header.alg !== \"HS256\") return null;",
       "  if (b64url(hmac(\"sha256\", IDP_SECRET, parts[0] + \".\" + parts[1])) !== parts[2]) return null; // opaque access tokens fail here",
       "  const c = decodePayload(token);",
       "  if (!c || c.iss !== \"https://idp.example\" || c.aud !== CLIENT_ID || c.nonce !== expectedNonce) return null;",
       "  if (typeof c.exp !== \"number\" || Math.floor(now() / 1000) >= c.exp) return null;",
       "  return c;"
      ]
     }
    ],
    "after": [],
    "fail": "A token minted for some-other-app must not sign anyone into your client (check aud) — expected null but got {\"iss\":\"https://idp.example\",\"sub\":\"idp-ada-42\",\"aud\":\"some-other-app\",\"nonce\":\"n\",\"iat\":1700000000,\"exp\":1700000300}",
    "why": "The starter's `verifyIdToken` just decodes the payload, checking neither the signature nor the claims, so a token forged for another client, a tampered one, an expired one, or even an opaque access token would all be accepted. Verifying the HS256 signature and then requiring the right `iss`, `aud`, `nonce` and a future `exp` is what makes the token proof of who signed in. The other checkpoints exercise these same checks."
   },
   {
    "chunks": [],
    "after": [
     1
    ],
    "why": null
   },
   {
    "chunks": [],
    "after": [
     1
    ],
    "why": null
   }
  ]
 },
 "auth-u7-1": {
  "hash": "947f4d16c782a1f6",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 9,
      "del": [
       "  // TODO: the counter as 8 bytes, most significant first (it can be bigger than 2^32)",
       "  // TODO: mac = hmac(\"sha1\", secret, those bytes): 20 bytes",
       "  // TODO: offset = low 4 bits of the last byte; read 4 bytes there as a number, top bit cleared",
       "  // TODO: that number modulo 10^digits, as a string padded with leading zeros",
       "  return \"\";"
      ],
      "add": [
       "  const msg = new Uint8Array(8);",
       "  let c = counter;",
       "  for (let i = 7; i >= 0; i--) { msg[i] = c % 256; c = Math.floor(c / 256); } // division, not shifts",
       "  const mac = hmac(\"sha1\", secret, msg);",
       "  const offset = mac[19] & 0x0f;",
       "  const bin = ((mac[offset] & 0x7f) << 24) | (mac[offset + 1] << 16) | (mac[offset + 2] << 8) | mac[offset + 3];",
       "  return String(bin % Math.pow(10, digits)).padStart(digits, \"0\");"
      ]
     }
    ],
    "after": [],
    "fail": "hotp(SECRET, 0), from RFC 4226 Appendix D — expected \"755224\" but got \"\"",
    "why": "The starter's `hotp` returns an empty string, so there is no code to compare. HOTP writes the counter as 8 bytes using division (shifts stop at 32 bits), takes `hmac(\"sha1\", ...)`, reads 4 bytes at the offset given by the last byte's low 4 bits with the top bit cleared, and keeps the last `digits` digits as a zero-padded string. Checkpoints 2 and 3 exercise this same code, which is why they pass once this one does."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 25,
      "del": [
       "  // TODO: now() is in milliseconds; TOTP wants whole seconds",
       "  return totp(secret, now());"
      ],
      "add": [
       "  return totp(secret, Math.floor(now() / 1000));"
      ]
     }
    ],
    "after": [],
    "fail": "now() is 1700000000000 milliseconds; TOTP counts 30-second steps of Unix SECONDS — expected \"921300\" but got \"604551\"",
    "why": "The starter passes `now()` straight to `totp`, but `now()` counts milliseconds and TOTP counts seconds. The step comes out a thousand times too large, so the code never matches the one on the phone. Convert with `Math.floor(now() / 1000)` first."
   }
  ]
 },
 "auth-u7-2": {
  "hash": "b5b292220c92308d",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 31,
      "del": [
       "  if (!user) return false;",
       "  // TODO: accept the code for any step from now - WINDOW to now + WINDOW",
       "  // TODO: refuse a step that isn't newer than user.lastStep; remember the step that was used",
       "  return code === currentCode(user.secret);"
      ],
      "add": [
       "  if (!user || !/^\\d{6}$/.test(String(code))) return false;",
       "  const step = Math.floor(now() / 1000 / 30);",
       "  for (let s = step - WINDOW; s <= step + WINDOW; s++) {",
       "    if (hotp(user.secret, s) === code && s > user.lastStep) {",
       "      user.lastStep = s; // this step, and every earlier one, is spent",
       "      return true;",
       "    }",
       "  }",
       "  return false;"
      ]
     }
    ],
    "after": [],
    "fail": "The code for the previous 30-second step is inside the window: accept it",
    "why": "The starter compares only against the current code and never records a use. A phone clock 30 seconds off is locked out, and a code that just worked can be sent again. Checking every step within `WINDOW`, and accepting only a step newer than `lastStep`, fixes both; the later checkpoints test the same loop."
   },
   {
    "chunks": [],
    "after": [],
    "why": null
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   }
  ]
 },
 "auth-u7-3": {
  "hash": "857123c319981316",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 26,
      "del": [
       "  if (!account) return { status: 404, body: { error: \"No account with that email\" } };",
       "  const token = randHex(16);"
      ],
      "add": [
       "  if (account) {",
       "    const token = randHex(16);"
      ]
     },
     {
      "file": "script.js",
      "line": 29,
      "del": [
       "  outbox.push({ to: email, link: \"https://app.example/reset?token=\" + token });",
       "  return { status: 200, body: { message: \"Reset link sent to \" + email } };"
      ],
      "add": [
       "    outbox.push({ to: email, link: \"https://app.example/reset?token=\" + token });",
       "  }",
       "  // One answer whether or not the address has an account.",
       "  return { status: 200, body: { message: \"If that address has an account, a reset link is on its way.\" } };"
      ]
     }
    ],
    "after": [],
    "fail": "An address with no account must get a byte-identical response, or the form tells anyone which emails have accounts. Known: {\"status\":200,\"body\":{\"message\":\"Reset link sent to ada@example.com\"}} Unknown: {\"status\":404,\"body\":{\"error\":\"No account with that email\"}} — expected \"{\\\"status\\\":200,\\\"body\\\":{\\\"message\\\":\\\"Reset link sent to ada@example.com\\\"}}\" but got \"{\\\"status\\\":404,\\\"body\\\":{\\\"error\\\":\\\"No account with that email\\\"}}\"",
    "why": "The starter answers 404 \"No account with that email\" for unknown addresses and names the address for known ones, so the form tells anyone which emails have accounts. Send the email only when the account exists, but return one identical response either way."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 28,
      "del": [
       "  resetTokens.set(token, { email: email }); // TODO: store sha256(token), an expiry and used: false"
      ],
      "add": [
       "    resetTokens.set(sha256(token), { email: email, expires: now() + RESET_TTL_MS, used: false });"
      ]
     }
    ],
    "after": [],
    "fail": "The raw token is a key in resetTokens, so anyone who reads the table can reset the password. Store sha256(token)",
    "why": "The starter keys `resetTokens` by the raw token, so anyone who can read the table can reset any account with a pending link. Store `sha256(token)` with an expiry and a `used` flag. The token is 128 random bits, so a single SHA-256 is enough."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 37,
      "del": [
       "  const row = resetTokens.get(token);",
       "  if (!row) return { status: 400, body: { error: \"invalid or expired token\" } };",
       "  // TODO: refuse a used or expired token, and mark this one used"
      ],
      "add": [
       "  const row = resetTokens.get(sha256(String(token)));",
       "  if (!row || row.used || now() >= row.expires) return { status: 400, body: { error: \"invalid or expired token\" } };",
       "  row.used = true; // a link works once"
      ]
     }
    ],
    "after": [],
    "fail": "A fresh token resets the password — expected {\"status\":200,\"body\":{\"ok\":true}} but got {\"status\":400,\"body\":{\"error\":\"invalid or expired token\"}}",
    "why": "The starter's `resetPassword` never marks a token used or checks its age, so one link resets the password again and again for as long as the server runs. Look the row up by `sha256`, refuse it when it is used or past `expires`, and mark it used before changing the password. The expiry check here is what checkpoint 4 tests."
   },
   {
    "chunks": [],
    "after": [
     1,
     2
    ],
    "why": null
   }
  ]
 },
 "auth-u7-4": {
  "hash": "395bf78239a09648",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 9,
      "del": [
       "  recoveryCodes.set(userName, new Set(codes)); // TODO: store sha256 of each code, never the code",
       "  return codes;"
      ],
      "add": [
       "  recoveryCodes.set(userName, new Set(codes.map(c => sha256(c)))); // replaces any older set",
       "  return codes; // shown once; the server keeps only the hashes"
      ]
     }
    ],
    "after": [],
    "fail": "The codes are stored as themselves, so a leaked table is a list of working codes. Store sha256(code)",
    "why": "The starter stores the recovery codes themselves, so a leaked table is a list of working codes. Store `sha256` of each code instead: the codes are shown to the user once and never kept."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 14,
      "del": [
       "  const codes = recoveryCodes.get(userName);",
       "  // TODO: tidy what was typed, compare by hash, and a code works only once",
       "  return !!codes && codes.has(code);"
      ],
      "add": [
       "  const hashes = recoveryCodes.get(userName);",
       "  const h = sha256(String(code).trim().toLowerCase());",
       "  if (!hashes || !hashes.has(h)) return false;",
       "  hashes.delete(h); // single use",
       "  return true;"
      ]
     }
    ],
    "after": [],
    "fail": "People type codes from paper: trim and lowercase before hashing",
    "why": "The starter checks the typed text as-is against the stored set, so a code copied with spaces or in capitals fails, and a code that does match keeps working forever. Trim and lowercase, compare by `sha256`, and delete the hash once it has been used."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 54,
      "del": [
       "  // TODO: owner, type, challenge (used once), origin, rpIdHash, signCount — then store signCount",
       "  return !!cred && verifySignature(cred.publicKey, assertion);"
      ],
      "add": [
       "  if (!cred || cred.userName !== userName) return false;",
       "  const expected = challenges.get(userName);",
       "  challenges.delete(userName); // a challenge is good for one attempt",
       "  const cd = assertion.clientData || {};",
       "  if (cd.type !== \"webauthn.get\") return false;",
       "  if (!expected || cd.challenge !== expected) return false;",
       "  if (cd.origin !== ORIGIN) return false;",
       "  if (assertion.rpIdHash !== sha256(RP_ID)) return false;",
       "  if (!verifySignature(cred.publicKey, assertion)) return false;",
       "  if ((assertion.signCount !== 0 || cred.signCount !== 0) && !(assertion.signCount > cred.signCount)) return false;",
       "  cred.signCount = assertion.signCount;",
       "  return true;"
      ]
     }
    ],
    "after": [],
    "fail": "Store the new signCount after a successful sign-in — expected 8 but got 7",
    "why": "The starter trusts any assertion whose signature verifies, so a reused challenge, a lookalike origin, a key scoped to another site and a cloned authenticator all get through, and the new `signCount` is never recorded. Check the owner, the type, the one-time challenge, the origin, `rpIdHash` and the counter around the signature, then store the counter. Checkpoint 4 tests the rest of these same checks."
   },
   {
    "chunks": [],
    "after": [
     2
    ],
    "why": null
   }
  ]
 }
});
