/* GENERATED by tools/build-step-solutions.js — do not edit by hand.
   Explanations come from tools/step-why/auth.json. validate.js fails
   when a lesson changes without a rebuild. */
window.CODELAB.addStepSolutions("auth", {
 "auth-u1-1": {
  "hash": "452be4fd07639794",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 11,
      "del": [
       "  // It works, and anyone can type it. Make the id unguessable: randHex(16).",
       "  const id = \"token-\" + userName;"
      ],
      "add": [
       "  const id = randHex(16); // 128 random bits: nothing to derive, nothing to guess"
      ]
     }
    ],
    "after": [],
    "fail": "A session id should be 32 lowercase hex characters, from randHex(16) — yours was \"token-ada\"",
    "why": "The starter builds the id from the user name, so anyone who has seen `token-ada` can type `token-bo`. A session id is a bearer credential: whoever presents it is that user. It has to come from a random source, and `randHex(16)` gives 128 bits nobody can derive or guess."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 12,
      "del": [
       "  // TODO: the row also records created and lastSeen, both now()",
       "  sessions.set(id, { userName: userName });"
      ],
      "add": [
       "  sessions.set(id, { userName: userName, created: now(), lastSeen: now() });"
      ]
     }
    ],
    "after": [],
    "fail": "The row for bo should be { userName, created: now(), lastSeen: now() }, in that order — expected {\"userName\":\"bo\",\"created\":1700000005000,\"lastSeen\":1700000005000} but got {\"userName\":\"bo\"}",
    "why": "The starter's row records only who the session belongs to. Without `created` and `lastSeen` the server can't tell how old a session is or when it was last used, so the timeouts later in this unit would have nothing to measure."
   },
   {
    "chunks": [],
    "after": [],
    "why": null
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   }
  ]
 },
 "auth-u1-2": {
  "hash": "5ac51d1e2ceefcc3",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 12,
      "del": [
       "  let out = name + \"=\" + value;",
       "  if (opts.path) out += \"; Path=\" + opts.path;",
       "  if (opts.maxAge) out += \"; Max-Age=\" + opts.maxAge;",
       "  if (opts.httpOnly) out += \"; HttpOnly\";",
       "  // TODO: Secure, and SameSite (Strict | Lax | None — None requires Secure)",
       "  // TODO: throw a TypeError for a name or value the cookie grammar forbids",
       "  return out;"
      ],
      "add": [
       "  const parts = [name + \"=\" + value];",
       "  if (opts.path != null) parts.push(\"Path=\" + opts.path);",
       "  if (opts.maxAge != null) parts.push(\"Max-Age=\" + Math.floor(opts.maxAge));",
       "  if (opts.httpOnly) parts.push(\"HttpOnly\");",
       "  if (opts.secure) parts.push(\"Secure\");",
       "  if (opts.sameSite != null) {",
       "    if ([\"Strict\", \"Lax\", \"None\"].indexOf(opts.sameSite) === -1) throw new TypeError(\"SameSite must be Strict, Lax or None\");",
       "    if (opts.sameSite === \"None\" && !opts.secure) throw new TypeError(\"SameSite=None requires Secure\");",
       "    parts.push(\"SameSite=\" + opts.sameSite);",
       "  }",
       "  return parts.join(\"; \");"
      ]
     }
    ],
    "after": [],
    "fail": "Expected exactly Path=/, Max-Age=1800, HttpOnly, Secure and SameSite=Lax, in any order, joined with \"; \" — yours: \"sid=abc123; Path=/; Max-Age=1800; HttpOnly\" — expected [\"HttpOnly\",\"Max-Age=1800\",\"Path=/\",\"SameSite=Lax\",\"Secure\"] but got [\"HttpOnly\",\"Max-Age=1800\",\"Path=/\"]",
    "why": "The starter writes only `Path`, `Max-Age` and `HttpOnly`, so the cookie never gets `Secure` or `SameSite`. It also tests `opts.maxAge` for truthiness, which silently drops `maxAge: 0`. Collecting the parts in an array and checking `!= null` writes every attribute that was set, including a zero."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 4,
      "del": [],
      "add": [
       "const COOKIE_NAME = /^[!#$%&'*+\\-.^_`|~0-9A-Za-z]+$/;",
       "const COOKIE_VALUE = /^[\\x21\\x23-\\x2B\\x2D-\\x3A\\x3C-\\x5B\\x5D-\\x7E]*$/;",
       ""
      ]
     },
     {
      "file": "script.js",
      "line": 9,
      "del": [],
      "add": [
       "  value = String(value);",
       "  if (typeof name !== \"string\" || !COOKIE_NAME.test(name)) throw new TypeError(\"invalid cookie name: \" + JSON.stringify(name));",
       "  if (!COOKIE_VALUE.test(value)) throw new TypeError(\"invalid cookie value: \" + JSON.stringify(value));"
      ]
     }
    ],
    "after": [],
    "fail": "A value of \"abc; Domain=evil.example\" must throw: it would break the header or smuggle in an attribute",
    "why": "The starter puts any name and value straight into the header. A value like `abc; Domain=evil.example` then adds an attribute the server never chose. Checking both against the cookie grammar, and throwing a `TypeError` when they don't match, keeps the header exactly what the caller asked for."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 29,
      "del": [
       "    const [key, val] = part.split(\"=\");",
       "    jar[key.trim()] = val;"
      ],
      "add": [
       "    const eq = part.indexOf(\"=\");",
       "    if (eq === -1) continue;",
       "    const key = part.slice(0, eq).trim();",
       "    if (key && !Object.prototype.hasOwnProperty.call(jar, key)) jar[key] = part.slice(eq + 1).trim();"
      ]
     }
    ],
    "after": [],
    "fail": "Split on the FIRST = only, since a value may contain = itself — yours: {\"next\":\"/a?b\",\"sid\":\"xyz\"} — expected {\"next\":\"/a?b=c\",\"sid\":\"xyz\"} but got {\"next\":\"/a?b\",\"sid\":\"xyz\"}",
    "why": "`part.split(\"=\")` splits on every `=`, and destructuring keeps only the first two pieces, so `next=/a?b=c` loses its `=c`. Cutting at the first `=` with `indexOf` keeps the rest of the value intact. Skipping pieces with no `=` and names already seen stops odd headers from overwriting a real cookie."
   }
  ]
 },
 "auth-u1-3": {
  "hash": "ef510c72e66934bd",
  "steps": [
   {
    "chunks": [],
    "after": [],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 76,
      "del": [
       "    const id = currentId(req);",
       "    if (id) {",
       "      // The id the visitor arrived with is now logged in. So is whoever chose it.",
       "      sessions.get(id).userName = user.userName;",
       "      return { status: 200, body: { ok: true } };",
       "    }"
      ],
      "add": [
       "    const oldId = currentId(req);",
       "    const cart = oldId ? sessions.get(oldId).cart : [];",
       "    if (oldId) sessions.delete(oldId);             // the planted id now points at nothing",
       "    const id = createSession(user.userName, cart);  // a fresh id for the new privilege level"
      ]
     }
    ],
    "after": [],
    "fail": "The attacker replayed the id they planted and got {\"status\":200,\"body\":{\"userName\":\"ada\",\"cart\":[]}}, the account ada just signed into. Login must rotate the id — expected {\"status\":401,\"body\":{\"error\":\"unauthorized\"}} but got {\"status\":200,\"body\":{\"userName\":\"ada\",\"cart\":[]}}",
    "why": "The starter finds the session the visitor arrived with and marks it as logged in. If an attacker planted that id, the attacker's copy now opens the victim's account. Deleting the old row and creating a fresh one at login leaves the planted id pointing at nothing."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 80,
      "del": [
       "    return { status: 200, headers: { \"Set-Cookie\": sessionCookie(createSession(user.userName, [])) }, body: { ok: true } };"
      ],
      "add": [
       "    return { status: 200, headers: { \"Set-Cookie\": sessionCookie(id) }, body: { ok: true } };"
      ]
     }
    ],
    "after": [],
    "fail": "The new sid should be ada, still holding the lamp added before signing in — expected {\"status\":200,\"body\":{\"userName\":\"ada\",\"cart\":[\"lamp\"]}} but got {\"status\":200,\"body\":{\"userName\":\"ada\",\"cart\":[]}}",
    "why": "The starter's login answers with a brand-new session and an empty cart, so anything the visitor added before signing in is lost. Carrying `cart` from the old row into the new one, and sending that new id in `Set-Cookie`, makes the rotation invisible to the shopper."
   },
   {
    "chunks": [],
    "after": [],
    "why": null
   }
  ]
 },
 "auth-u1-4": {
  "hash": "9a7674bd0168322a",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 55,
      "del": [
       "  // TODO: idle timeout, measured from row.lastSeen",
       "  // TODO: absolute timeout, measured from row.created",
       "  // TODO: still alive? slide lastSeen forward to now()"
      ],
      "add": [
       "  const t = now();",
       "  if (t - row.lastSeen >= IDLE_MS || t - row.created >= ABSOLUTE_MS) {",
       "    sessions.delete(id);  // dead rows don't linger",
       "    return null;",
       "  }",
       "  row.lastSeen = t;       // only a live session slides"
      ]
     }
    ],
    "after": [],
    "fail": "A successful request slides lastSeen forward to now() — expected 1700001740000 but got 1700000000000",
    "why": "The starter's `touchSession` returns any row it finds, however old, and never updates it. A session nobody checks against the clock never ends, and one whose `lastSeen` never moves can't have an idle timeout. Read `now()` once, end the session when either limit is reached, and only then slide `lastSeen` forward."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [],
    "after": [],
    "why": null
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   }
  ]
 },
 "auth-u1-5": {
  "hash": "419b4c01e136b29b",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 62,
      "del": [
       "    return { status: 200, headers: { \"Set-Cookie\": \"sid=; Max-Age=0\" }, body: { ok: true } };"
      ],
      "add": [
       "    return { status: 200, headers: { \"Set-Cookie\": clearCookie() }, body: { ok: true } };"
      ]
     },
     {
      "file": "script.js",
      "line": 72,
      "del": [],
      "add": [
       "  function clearCookie() {  // browser half: same Path it was set with",
       "    return serializeCookie(\"sid\", \"\", { path: \"/\", maxAge: 0, httpOnly: true, secure: true, sameSite: \"Lax\" });",
       "  }"
      ]
     }
    ],
    "after": [],
    "fail": "A cookie is matched by name AND path. Without Path=/ the browser keeps the original sid — yours: \"sid=; Max-Age=0\"",
    "why": "The starter's clearing cookie is `sid=; Max-Age=0` with no `Path`. Browsers match a cookie by name and path, so that header can leave the original `sid` in place. Building it with `serializeCookie` and the same `Path=/` the session cookie was set with actually replaces it."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 60,
      "del": [
       "    // Tells the browser to forget the cookie. The server forgets nothing."
      ],
      "add": [
       "    const id = currentId(req);",
       "    if (id) sessions.delete(id);  // server half: the id means nothing now"
      ]
     }
    ],
    "after": [],
    "fail": "The copied id still opened the account after logout ({\"status\":200,\"body\":{\"userName\":\"ada\"}}). Clearing the cookie in one browser does nothing to a copy; delete the row — expected {\"status\":401,\"body\":{\"error\":\"unauthorized\"}} but got {\"status\":200,\"body\":{\"userName\":\"ada\"}}",
    "why": "The starter only tells the browser to forget the cookie; the row stays on the server. Anyone holding a copy of the id (a proxy log, malware, the fixation attacker) keeps using it until it times out. Deleting the row is what makes logout real."
   },
   {
    "chunks": [],
    "after": [],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 64,
      "del": [
       "  // TODO: POST /api/logout-all ends every session the caller's user has"
      ],
      "add": [
       "  if (req.method === \"POST\" && req.path === \"/api/logout-all\") {",
       "    const id = currentId(req);",
       "    if (!id) return { status: 401, body: { error: \"unauthorized\" } };",
       "    const userName = sessions.get(id).userName;",
       "    for (const [sid, row] of sessions) if (row.userName === userName) sessions.delete(sid);",
       "    return { status: 200, headers: { \"Set-Cookie\": clearCookie() }, body: { ok: true } };",
       "  }",
       ""
      ]
     }
    ],
    "after": [],
    "fail": "POST /api/logout-all with a valid session → 200 — got {\"status\":404,\"body\":\"Not found\"} — expected 200 but got 404",
    "why": "The starter has no `/api/logout-all` route, so it answers 404. Signing out everywhere means finding every row with the caller's `userName` and deleting them all, which is only possible because a session is a row the server can search."
   }
  ]
 },
 "auth-u4-1": {
  "hash": "98d87a197feb340d",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 7,
      "del": [
       "  // TODO: take the bytes 3 at a time and join them into one 24-bit number;",
       "  // write 4 characters for a full group, 3 for 2 bytes, 2 for 1 byte"
      ],
      "add": [
       "  for (let i = 0; i < bytes.length; i += 3) {",
       "    const n = (bytes[i] << 16) | ((bytes[i + 1] || 0) << 8) | (bytes[i + 2] || 0);",
       "    const chars = Math.min(bytes.length - i, 3) + 1; // 1 byte -> 2 chars, 2 -> 3, 3 -> 4",
       "    for (let j = 0; j < chars; j++) out += B64URL[(n >> (18 - 6 * j)) & 63];",
       "  }"
      ]
     }
    ],
    "after": [],
    "fail": "b64urlEncode of the bytes of \"f\" (1 bytes, so 2 characters) — expected \"Zg\" but got \"\"",
    "why": "The starter's encoder never reads the bytes, so it returns an empty string. base64url takes the bytes three at a time as one 24-bit number and writes four 6-bit characters, or two or three for a short final group, with no `=` padding."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 17,
      "del": [
       "  // TODO: throw for length % 4 === 1 or any character outside B64URL;",
       "  // collect 6 bits per character and emit a byte whenever 8 have built up",
       "  return new Uint8Array(0);"
      ],
      "add": [
       "  if (typeof str !== \"string\" || str.length % 4 === 1) throw new Error(\"not base64url: \" + JSON.stringify(str));",
       "  const out = new Uint8Array(Math.floor(str.length * 3 / 4));",
       "  let n = 0, bits = 0, o = 0;",
       "  for (let i = 0; i < str.length; i++) {",
       "    const v = B64URL.indexOf(str[i]);",
       "    if (v === -1) throw new Error(\"not base64url: \" + JSON.stringify(str));",
       "    n = ((n << 6) | v) & 0xffffff;",
       "    bits += 6;",
       "    if (bits >= 8) { bits -= 8; out[o++] = (n >> bits) & 255; }",
       "  }",
       "  return out;"
      ]
     }
    ],
    "after": [],
    "fail": "Zm9vYmFy decodes to the bytes of foobar — expected [102,111,111,98,97,114] but got []",
    "why": "The starter's decoder returns an empty array for every input. Decoding runs the encoder backwards: each character is worth 6 bits, and a byte comes out whenever 8 bits have built up. It also has to throw for a character outside the alphabet and for a length that leaves one stray character."
   },
   {
    "chunks": [],
    "after": [
     2
    ],
    "why": null
   }
  ]
 },
 "auth-u4-2": {
  "hash": "ebecfab62cb6f162",
  "steps": [
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 35,
      "del": [],
      "add": [
       "function mac(text) {",
       "  return b64urlEncode(hmac(\"sha256\", SECRET, text));",
       "}",
       ""
      ]
     },
     {
      "file": "script.js",
      "line": 41,
      "del": [
       "  // TODO: add a dot and the base64url HMAC of the payload part",
       "  return payload;"
      ],
      "add": [
       "  return payload + \".\" + mac(payload);"
      ]
     }
    ],
    "after": [],
    "fail": "sign() should return base64url(JSON) + \".\" + base64url(HMAC-SHA256(SECRET, that first part)) — expected \"eyJzdWIiOiJhZGEiLCJyb2xlIjoidXNlciJ9.2XH8urf0hWjEuIY6MBYBjy1MaknjwJl8lizyiUMyMtE\" but got \"eyJzdWIiOiJhZGEiLCJyb2xlIjoidXNlciJ9\"",
    "why": "The starter's `sign` returns only the encoded payload, with no signature, so anyone could write their own token. Appending a dot and the base64url HMAC of the payload means only a holder of `SECRET` can produce a token that matches."
   },
   {
    "chunks": [],
    "after": [
     0
    ],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 46,
      "del": [
       "  const [payload] = String(token).split(\".\");",
       "  // TODO: recompute the signature and refuse anything that doesn't match",
       "  return JSON.parse(fromBytes(b64urlDecode(payload)));"
      ],
      "add": [
       "  const parts = String(token).split(\".\");",
       "  if (parts.length !== 2) return null;",
       "  if (mac(parts[0]) !== parts[1]) return null; // signature first: the payload is untrusted text until then",
       "  try {",
       "    return JSON.parse(fromBytes(b64urlDecode(parts[0])));",
       "  } catch (e) {",
       "    return null;",
       "  }"
      ]
     }
    ],
    "after": [],
    "fail": "Someone edited the payload to role admin and kept the old signature. Your verify returned {\"sub\":\"ada\",\"role\":\"admin\"}: recompute the HMAC and compare — expected null but got {\"sub\":\"ada\",\"role\":\"admin\"}",
    "why": "The starter's `verify` decodes whatever payload it gets and never checks a signature, so an edited `role: \"admin\"` goes straight through. Recompute the HMAC and refuse a mismatch first; only then parse the payload, inside a `try`, so a malformed token is `null` rather than an exception."
   },
   {
    "chunks": [],
    "after": [
     0,
     2
    ],
    "why": null
   }
  ]
 },
 "auth-u4-3": {
  "hash": "a14718ef1f00ec71",
  "steps": [
   {
    "chunks": [],
    "after": [
     1
    ],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 39,
      "del": [
       "// Compares two byte arrays. Right answer, wrong timing: it stops at the first difference."
      ],
      "add": [
       "// Every byte is read, whatever the first difference. Only the length can leak,",
       "// and every HMAC-SHA256 is 32 bytes."
      ]
     },
     {
      "file": "script.js",
      "line": 43,
      "del": [
       "  for (let i = 0; i < a.length; i++) {",
       "    if (a[i] !== b[i]) return false;",
       "  }",
       "  return true;"
      ],
      "add": [
       "  let diff = 0;",
       "  for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i];",
       "  return diff === 0;"
      ]
     }
    ],
    "after": [],
    "fail": "A mismatch at byte 0 cost 2 reads, a mismatch at byte 31 cost 64, a match cost 64. That difference is the timing leak: read every byte, whatever you find",
    "why": "The starter's loop returns at the first byte that differs, so a signature wrong in byte 0 is rejected sooner than one wrong in byte 31. Measured over many requests, that difference gives a valid signature away byte by byte. OR-ing every byte's XOR into one number and checking it once at the end costs the same whatever the input."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 51,
      "del": [
       "  const expected = b64urlEncode(hmac(\"sha256\", SECRET, parts[0]));",
       "  if (expected !== parts[1]) return null; // TODO: decode parts[1] and compare BYTES with safeEqual"
      ],
      "add": [
       "  let given;",
       "  try { given = b64urlDecode(parts[1]); } catch (e) { return null; }",
       "  if (!safeEqual(given, hmac(\"sha256\", SECRET, parts[0]))) return null;"
      ]
     }
    ],
    "after": [],
    "fail": "verify should compare the signature bytes with safeEqual exactly once. It was called 0 times, so the comparison is still a === that stops at the first different character",
    "why": "The starter's `verify` still compares base64url strings with `!==`, which stops at the first different character and never calls `safeEqual`. Decoding the given signature to bytes (refusing one that won't decode) and comparing with `safeEqual` closes the leak where it matters."
   },
   {
    "chunks": [],
    "after": [
     1
    ],
    "why": null
   }
  ]
 },
 "auth-u4-4": {
  "hash": "29d89accd3b1424a",
  "steps": [
   {
    "chunks": [],
    "after": [],
    "why": null
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 52,
      "del": [
       "// Starter: ignores the kid and tries every key until one matches."
      ],
      "add": []
     },
     {
      "file": "script.js",
      "line": 55,
      "del": [],
      "add": [
       "  const kid = parts[0];",
       "  if (!Object.prototype.hasOwnProperty.call(KEYS, kid)) return null; // unknown kid: refuse, don't go hunting"
      ]
     },
     {
      "file": "script.js",
      "line": 59,
      "del": [
       "  const signed = parts[0] + \".\" + parts[1];",
       "  for (const kid in KEYS) {",
       "    if (safeEqual(given, hmac(\"sha256\", KEYS[kid], signed))) {",
       "      try { return JSON.parse(fromBytes(b64urlDecode(parts[1]))); } catch (e) { return null; }",
       "    }"
      ],
      "add": [
       "  if (!safeEqual(given, hmac(\"sha256\", KEYS[kid], kid + \".\" + parts[1]))) return null;",
       "  try {",
       "    return JSON.parse(fromBytes(b64urlDecode(parts[1])));",
       "  } catch (e) {",
       "    return null;"
      ]
     },
     {
      "file": "script.js",
      "line": 65,
      "del": [
       "  return null;"
      ],
      "add": []
     }
    ],
    "after": [],
    "fail": "This token says 2026-09 but was signed with the August key. Your verify returned {\"sub\":\"ada\"}: check the signature with the key the kid names, and only that key — expected null but got {\"sub\":\"ada\"}",
    "why": "The starter ignores the `kid` and tries every key until one matches, so the label means nothing: a token that says `2026-09` but was signed with August's key still passes, and an unknown `kid` costs one HMAC per key. Looking the `kid` up with `hasOwnProperty` and checking only that key fixes both."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 68,
      "del": [
       "  // TODO: throw if kid already exists; add the key; sign with it from now on"
      ],
      "add": [
       "  if (Object.prototype.hasOwnProperty.call(KEYS, kid)) throw new Error(\"kid already exists: \" + kid);",
       "  KEYS[kid] = secret;",
       "  currentKid = kid; // new tokens use it; old tokens still verify under their own kid"
      ]
     }
    ],
    "after": [],
    "fail": "After rotateKey, sign should use the new key, so tokens start \"2026-10.\" — yours: 2026-09.eyJzdWIiOiJhZGEifQ.bpxMFB4s2QnaFIvqoxmNJTpXQ0NcGKjY88tuHEugOI0",
    "why": "The starter's `rotateKey` does nothing, so `sign` keeps using the old key. Rotating adds the new secret and switches `currentKid` to it, and it refuses a `kid` that already exists, because silently replacing a secret breaks every token it signed."
   },
   {
    "chunks": [
     {
      "file": "script.js",
      "line": 74,
      "del": [
       "  // TODO: throw if kid is the key sign() uses; otherwise delete it"
      ],
      "add": [
       "  if (kid === currentKid) throw new Error(\"cannot retire the key sign() is using: \" + kid);",
       "  delete KEYS[kid];"
      ]
     }
    ],
    "after": [],
    "fail": "After retireKey(\"2026-08\"), August tokens must stop verifying — expected null but got {\"sub\":\"bo\"}",
    "why": "The starter's `retireKey` does nothing, so a retired key keeps verifying its tokens forever. Deleting it from `KEYS` ends them, and refusing to delete `currentKid` stops every newly signed token from failing at once."
   }
  ]
 }
});
