/* Building Interactive Websites — Unit 8: Capstone: Memory game */
window.CODELAB.addUnit("dom", {
  id: "dom-u8",
  title: "Capstone: Memory game",
  icon: "🎮",
  blurb: "Everything you learned becomes one real game: render the board, flip, match, win — then ship the deluxe version.",
  cheat: [
    { h: "Render cards from a deck", lang: "js", code: "for (const icon of deck) {\n  const card = document.createElement(\"button\");\n  card.className = \"card\";\n  card.dataset.icon = icon;   // the game logic reads this\n  card.textContent = icon;    // CSS hides it until .flipped\n  board.appendChild(card);\n}", note: "The array is the source of truth; the DOM is its display." },
    { h: "One listener runs the whole board", lang: "js", code: "board.addEventListener(\"click\", (e) => {\n  const card = e.target.closest(\".card\");\n  if (!card) return;                              // not a card\n  if (card.classList.contains(\"flipped\")) return; // same card twice\n  if (flippedCards.length === 2) return;          // two already up\n  // …flip it\n});", note: "Game rules = guard clauses. Each early return is one rule — and delegation survives a board rebuild." },
    { h: "Resolve a pair", lang: "js", code: "if (first.dataset.icon === second.dataset.icon) {\n  first.classList.add(\"matched\");\n  second.classList.add(\"matched\");\n  flippedCards = [];\n} else {\n  setTimeout(() => {\n    first.classList.remove(\"flipped\");\n    second.classList.remove(\"flipped\");\n    flippedCards = [];   // reset only after they flip back\n  }, 300);\n}" },
    { h: "Best score in localStorage", lang: "js", code: "const best = localStorage.getItem(\"bestScore\"); // string or null!\nif (best === null || moves < Number(best)) {\n  localStorage.setItem(\"bestScore\", String(moves));\n}" },
    { h: "Restart = reset state, re-render", lang: "js", code: "function startGame() {\n  moves = 0; matchedCount = 0; flippedCards = [];\n  movesEl.textContent = \"0\";\n  messageEl.textContent = \"\";\n  renderBoard();\n}", note: "Reset the variables, not just the screen — stale state is the #1 restart bug." }
  ],
  lessons: [

    {
      id: "dom-u8-1",
      title: "Build the board",
      kind: "web", chip: "DOM", xp: 15, mins: 14,
      brief: "Welcome to the capstone: over four lessons you build a full **memory game**. First, the render step. A 16-entry `deck` array (8 emoji, each twice) is the source of truth; the DOM is just its display:\n\n- `document.createElement(\"button\")` — one card per deck entry\n- `card.dataset.icon = icon` — the game logic reads this later\n- `card.textContent = icon` — the provided CSS keeps it invisible until the card gets the class `flipped`\n\nThe deck order is fixed so your checks are predictable — shuffling is the classic end-of-project bonus, not part of the grade.",
      steps: [
        { text: "Loop over `deck` and append one `<button class=\"card\">` per entry into `#board` — 16 cards total.",
          test: "T.eq(T.count('#board .card'), 16, 'Loop over all 16 deck entries and append a button with class \"card\" for each — the board currently has ' + T.count('#board .card') + '.');" },
        { text: "Each card carries its icon in `data-icon` (set `card.dataset.icon`), in deck order.",
          test: "var cards = T.$$('#board .card');\nT.eq(cards[0] && cards[0].dataset.icon, '🍕', 'Card 1 should carry data-icon=\"🍕\" — set card.dataset.icon = icon inside the loop.');\nT.eq(cards[4] && cards[4].dataset.icon, '🍕', 'Card 5 is the second 🍕 — render the deck IN ORDER, one card per entry.');\nT.eq(cards[9] && cards[9].dataset.icon, '🥑', 'Card 10 should be 🥑 — no shuffling yet, keep the fixed order.');\nT.eq(cards[15] && cards[15].dataset.icon, '🍒', 'The last card should be 🍒.');" },
        { text: "Cards also show the icon as text (the CSS hides it), and every card starts face-down — no `flipped` class anywhere.",
          test: "var cards = T.$$('#board .card');\nT.eq(cards[0] && cards[0].textContent, '🍕', 'Also set card.textContent = icon — the CSS keeps it invisible (font-size 0) until the card is flipped.');\nT.eq(T.count('#board .card.flipped'), 0, 'No card should start with the class flipped — they all begin face-down.');" }
      ],
      files: [
        { name: "index.html", content: "<!DOCTYPE html>\n<html>\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n  <h1>Memory 🎮</h1>\n  <div id=\"board\"></div>\n\n  <script src=\"script.js\"></script>\n</body>\n</html>\n" },
        { name: "styles.css", content: "body {\n  font-family: Arial, sans-serif;\n  padding: 20px;\n  text-align: center;\n}\n#board {\n  display: grid;\n  grid-template-columns: repeat(4, 64px);\n  gap: 8px;\n  justify-content: center;\n  margin-top: 16px;\n}\n.card {\n  height: 64px;\n  font-size: 0; /* hides the emoji until flipped */\n  border: 2px solid #94a3b8;\n  border-radius: 10px;\n  background: #6366f1;\n  cursor: pointer;\n}\n.card.flipped,\n.card.matched {\n  font-size: 28px;\n  background: white;\n}\n.card.matched {\n  background: #dcfce7;\n  border-color: #22c55e;\n}\n" },
        { name: "script.js", content: "// The deck: 8 icons, each twice, in a FIXED order (pairs sit 4 apart).\nconst deck = [\n  \"🍕\", \"🌮\", \"🍩\", \"🍎\",\n  \"🍕\", \"🌮\", \"🍩\", \"🍎\",\n  \"🍇\", \"🥑\", \"🍪\", \"🍒\",\n  \"🍇\", \"🥑\", \"🍪\", \"🍒\"\n];\n\nconst board = document.querySelector(\"#board\");\n\n// 1) loop over deck; for each icon:\n//    - create a <button>, className \"card\"\n//    - card.dataset.icon = icon\n//    - card.textContent = icon  (the CSS hides it while face-down)\n//    - append it to board\n" }
      ],
      hints: [
        "Same loop as the crew roster in Unit 1: `for (const icon of deck) { … }` with `document.createElement(\"button\")`.",
        "Three settings per card, then mount it: `card.className = \"card\"; card.dataset.icon = icon; card.textContent = icon; board.appendChild(card);`"
      ],
      solution: {
        "script.js": "// The deck: 8 icons, each twice, in a FIXED order (pairs sit 4 apart).\nconst deck = [\n  \"🍕\", \"🌮\", \"🍩\", \"🍎\",\n  \"🍕\", \"🌮\", \"🍩\", \"🍎\",\n  \"🍇\", \"🥑\", \"🍪\", \"🍒\",\n  \"🍇\", \"🥑\", \"🍪\", \"🍒\"\n];\n\nconst board = document.querySelector(\"#board\");\n\nfor (const icon of deck) {\n  const card = document.createElement(\"button\");\n  card.className = \"card\";\n  card.dataset.icon = icon;\n  card.textContent = icon;\n  board.appendChild(card);\n}\n"
      }
    },

    {
      id: "dom-u8-2",
      title: "Flip logic",
      kind: "web", chip: "DOM", xp: 15, mins: 14,
      brief: "Time to make the board playable. Instead of 16 listeners, put **one** on `#board` (event delegation, from Unit 3) and find the card with `e.target.closest(\".card\")`.\n\nThe rules of memory are just **guard clauses** — early returns before any flipping happens:\n\n- not a card? `return`\n- already flipped? `return` — a card must never count against itself\n- two cards up? `return` — the pair has to resolve first\n\nPast the guards: add the class `flipped` and push the card into the `flippedCards` array. Next lesson decides whether the pair lives or dies.",
      steps: [
        { text: "One click listener on `#board` flips the clicked card: add the class `flipped` and push the card into `flippedCards`.",
          test: "var cards = T.$$('#board .card');\ncards[0].click();\nT.expect(cards[0].classList.contains('flipped'), 'Clicking a card should add the class flipped — one listener on #board, then e.target.closest(\".card\") to find the card.');\nT.eq(T.count('#board .card.flipped'), 1, 'Exactly one card should be face-up so far.');" },
        { text: "Guard 1: clicking an already-flipped card does nothing — it must not land in `flippedCards` twice.",
          test: "var cards = T.$$('#board .card');\ncards[0].click();\nT.eq(T.count('#board .card.flipped'), 1, 'Clicking the SAME card again must not unflip it or flip anything new.');\nT.expect(typeof flippedCards !== 'undefined' && flippedCards.length === 1, 'flippedCards should still hold ONE card — guard with card.classList.contains(\"flipped\") BEFORE pushing, or a card could match itself.');\ncards[1].click();\nT.eq(T.count('#board .card.flipped'), 2, 'A different card should still flip — two cards are now face-up.');" },
        { text: "Guard 2: with two cards already up, clicks on other cards are ignored.",
          test: "var cards = T.$$('#board .card');\ncards[2].click();\nT.expect(!cards[2].classList.contains('flipped'), 'With two cards up, further clicks are ignored — guard: if (flippedCards.length === 2) return;');\nT.eq(T.count('#board .card.flipped'), 2, 'Still exactly two face-up cards.');" }
      ],
      files: [
        { name: "index.html", content: "<!DOCTYPE html>\n<html>\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n  <h1>Memory 🎮</h1>\n  <div id=\"board\"></div>\n\n  <script src=\"script.js\"></script>\n</body>\n</html>\n" },
        { name: "styles.css", content: "body {\n  font-family: Arial, sans-serif;\n  padding: 20px;\n  text-align: center;\n}\n#board {\n  display: grid;\n  grid-template-columns: repeat(4, 64px);\n  gap: 8px;\n  justify-content: center;\n  margin-top: 16px;\n}\n.card {\n  height: 64px;\n  font-size: 0; /* hides the emoji until flipped */\n  border: 2px solid #94a3b8;\n  border-radius: 10px;\n  background: #6366f1;\n  cursor: pointer;\n}\n.card.flipped,\n.card.matched {\n  font-size: 28px;\n  background: white;\n}\n.card.matched {\n  background: #dcfce7;\n  border-color: #22c55e;\n}\n" },
        { name: "script.js", content: "// Board render — done last lesson.\nconst deck = [\n  \"🍕\", \"🌮\", \"🍩\", \"🍎\",\n  \"🍕\", \"🌮\", \"🍩\", \"🍎\",\n  \"🍇\", \"🥑\", \"🍪\", \"🍒\",\n  \"🍇\", \"🥑\", \"🍪\", \"🍒\"\n];\n\nconst board = document.querySelector(\"#board\");\n\nfor (const icon of deck) {\n  const card = document.createElement(\"button\");\n  card.className = \"card\";\n  card.dataset.icon = icon;\n  card.textContent = icon;\n  board.appendChild(card);\n}\n\n// The face-up, not-yet-resolved cards live here (keep this name!):\nlet flippedCards = [];\n\n// 1) ONE click listener on board (delegation):\n//    const card = e.target.closest(\".card\");\n// 2) guards, in order — each is one early return:\n//    - no card found\n//    - card already has the class \"flipped\"\n//    - flippedCards already holds 2 cards\n// 3) past the guards: add \"flipped\", push the card into flippedCards\n" }
      ],
      hints: [
        "`board.addEventListener(\"click\", (e) => { const card = e.target.closest(\".card\"); … });` — one listener covers every card.",
        "Guards go first, in order: `if (!card) return; if (card.classList.contains(\"flipped\")) return; if (flippedCards.length === 2) return;`",
        "Then the happy path is two lines: `card.classList.add(\"flipped\"); flippedCards.push(card);`"
      ],
      solution: {
        "script.js": "// Board render — done last lesson.\nconst deck = [\n  \"🍕\", \"🌮\", \"🍩\", \"🍎\",\n  \"🍕\", \"🌮\", \"🍩\", \"🍎\",\n  \"🍇\", \"🥑\", \"🍪\", \"🍒\",\n  \"🍇\", \"🥑\", \"🍪\", \"🍒\"\n];\n\nconst board = document.querySelector(\"#board\");\n\nfor (const icon of deck) {\n  const card = document.createElement(\"button\");\n  card.className = \"card\";\n  card.dataset.icon = icon;\n  card.textContent = icon;\n  board.appendChild(card);\n}\n\n// The face-up, not-yet-resolved cards live here (keep this name!):\nlet flippedCards = [];\n\nboard.addEventListener(\"click\", (e) => {\n  const card = e.target.closest(\".card\");\n  if (!card) return;\n  if (card.classList.contains(\"flipped\")) return;\n  if (flippedCards.length === 2) return;\n\n  card.classList.add(\"flipped\");\n  flippedCards.push(card);\n});\n"
      }
    },

    {
      id: "dom-u8-3",
      title: "Match & win",
      kind: "web", chip: "DOM", xp: 15, mins: 15,
      brief: "The heart of the game: the moment `flippedCards` reaches 2, the attempt resolves.\n\n- **Same** `dataset.icon` → both cards get the class `matched` and stay revealed\n- **Different** → `setTimeout(..., 300)` flips them back (real games wait ~800 ms; we keep it snappy)\n- Either way that was one **move** — bump the counter shown in `#moves`\n- All 16 cards matched? Announce it in `#message` — any text containing **\"win\"**\n\nGotcha from Unit 5: never name a JS variable `status` — the browser owns `window.status`. Use `messageEl` for the announcement element.",
      steps: [
        { text: "A matching pair (cards 1 and 5 are both 🍕) instantly gets the class `matched` on both cards, and `#moves` shows `1`.",
          test: "var cards = T.$$('#board .card');\ncards[0].click();\ncards[4].click();\nT.expect(cards[0].classList.contains('matched') && cards[4].classList.contains('matched'), 'Cards 1 and 5 are both 🍕 — when the two flipped icons match, add the class matched to both and reset flippedCards to [].');\nT.eq(T.text('#moves'), '1', 'Every completed pair-attempt increments the moves counter — show it in #moves.');" },
        { text: "A mismatch (🌮 vs 🍩) shows both cards briefly, counts the move, then flips them back after ~300 ms.",
          test: "var cards = T.$$('#board .card');\ncards[1].click();\ncards[2].click();\nT.expect(cards[1].classList.contains('flipped') && cards[2].classList.contains('flipped'), '🌮 vs 🍩 should both be face-up for a moment — the player needs to SEE the mismatch before it hides.');\nT.eq(T.text('#moves'), '2', 'The mismatch still counts as a pair-attempt: #moves should show 2.');\nawait T.sleep(500);\nT.expect(!cards[1].classList.contains('flipped') && !cards[2].classList.contains('flipped'), 'After ~300 ms remove flipped from BOTH cards (setTimeout) and reset flippedCards so the player can try again.');" },
        { text: "Match the remaining 7 pairs — all 16 cards end `matched`, `#moves` shows `9`, and `#message` contains \"win\".",
          test: "var cards = T.$$('#board .card');\nvar pairs = [[1, 5], [2, 6], [3, 7], [8, 12], [9, 13], [10, 14], [11, 15]];\nfor (var i = 0; i < pairs.length; i++) {\n  cards[pairs[i][0]].click();\n  cards[pairs[i][1]].click();\n}\nT.eq(T.count('#board .card.matched'), 16, 'Clicking the 7 remaining pairs should leave every card matched — check your dataset.icon comparison.');\nT.eq(T.text('#moves'), '9', 'Running total: 1 match + 1 mismatch + 7 matches = 9 pair-attempts.');\nT.expect((T.text('#message') || '').toLowerCase().indexOf('win') !== -1, 'All 16 matched → put a message containing the word \"win\" into #message (e.g. You win in 9 moves!).');" }
      ],
      files: [
        { name: "index.html", content: "<!DOCTYPE html>\n<html>\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n  <h1>Memory 🎮</h1>\n  <p>Moves: <span id=\"moves\">0</span></p>\n  <p id=\"message\"></p>\n  <div id=\"board\"></div>\n\n  <script src=\"script.js\"></script>\n</body>\n</html>\n" },
        { name: "styles.css", content: "body {\n  font-family: Arial, sans-serif;\n  padding: 20px;\n  text-align: center;\n}\n#board {\n  display: grid;\n  grid-template-columns: repeat(4, 64px);\n  gap: 8px;\n  justify-content: center;\n  margin-top: 16px;\n}\n.card {\n  height: 64px;\n  font-size: 0; /* hides the emoji until flipped */\n  border: 2px solid #94a3b8;\n  border-radius: 10px;\n  background: #6366f1;\n  cursor: pointer;\n}\n.card.flipped,\n.card.matched {\n  font-size: 28px;\n  background: white;\n}\n.card.matched {\n  background: #dcfce7;\n  border-color: #22c55e;\n}\n#message {\n  min-height: 1.2em;\n  font-weight: bold;\n  color: #16a34a;\n}\n" },
        { name: "script.js", content: "const deck = [\n  \"🍕\", \"🌮\", \"🍩\", \"🍎\",\n  \"🍕\", \"🌮\", \"🍩\", \"🍎\",\n  \"🍇\", \"🥑\", \"🍪\", \"🍒\",\n  \"🍇\", \"🥑\", \"🍪\", \"🍒\"\n];\n\nconst board = document.querySelector(\"#board\");\nconst movesEl = document.querySelector(\"#moves\");\nconst messageEl = document.querySelector(\"#message\"); // NOT \"status\"!\n\nfor (const icon of deck) {\n  const card = document.createElement(\"button\");\n  card.className = \"card\";\n  card.dataset.icon = icon;\n  card.textContent = icon;\n  board.appendChild(card);\n}\n\nlet flippedCards = [];\nlet moves = 0;\nlet matchedCount = 0;\n\nboard.addEventListener(\"click\", (e) => {\n  const card = e.target.closest(\".card\");\n  if (!card) return;\n  if (card.classList.contains(\"flipped\") || card.classList.contains(\"matched\")) return;\n  if (flippedCards.length === 2) return;\n\n  card.classList.add(\"flipped\");\n  flippedCards.push(card);\n\n  if (flippedCards.length === 2) {\n    // 1) moves++ and show it in movesEl\n    // 2) const [first, second] = flippedCards;\n    //    same dataset.icon → swap \"flipped\" for \"matched\" on both,\n    //      matchedCount += 2, flippedCards = []\n    //    different → setTimeout 300 ms: remove \"flipped\" from both,\n    //      flippedCards = []\n    // 3) when matchedCount === deck.length, show a win message\n    //    (containing \"win\") in messageEl\n  }\n});\n" }
      ],
      hints: [
        "Grab the pair with destructuring: `const [first, second] = flippedCards;` then compare `first.dataset.icon === second.dataset.icon`.",
        "Match branch: `first.classList.remove(\"flipped\"); first.classList.add(\"matched\");` (same for second), `matchedCount += 2; flippedCards = [];`. Mismatch branch: `setTimeout(() => { first.classList.remove(\"flipped\"); second.classList.remove(\"flipped\"); flippedCards = []; }, 300);`",
        "Win check lives inside the match branch: `if (matchedCount === deck.length) messageEl.textContent = \"You win in \" + moves + \" moves!\";` — and `moves++; movesEl.textContent = moves;` runs before the comparison so both branches count it."
      ],
      solution: {
        "script.js": "const deck = [\n  \"🍕\", \"🌮\", \"🍩\", \"🍎\",\n  \"🍕\", \"🌮\", \"🍩\", \"🍎\",\n  \"🍇\", \"🥑\", \"🍪\", \"🍒\",\n  \"🍇\", \"🥑\", \"🍪\", \"🍒\"\n];\n\nconst board = document.querySelector(\"#board\");\nconst movesEl = document.querySelector(\"#moves\");\nconst messageEl = document.querySelector(\"#message\"); // NOT \"status\"!\n\nfor (const icon of deck) {\n  const card = document.createElement(\"button\");\n  card.className = \"card\";\n  card.dataset.icon = icon;\n  card.textContent = icon;\n  board.appendChild(card);\n}\n\nlet flippedCards = [];\nlet moves = 0;\nlet matchedCount = 0;\n\nboard.addEventListener(\"click\", (e) => {\n  const card = e.target.closest(\".card\");\n  if (!card) return;\n  if (card.classList.contains(\"flipped\") || card.classList.contains(\"matched\")) return;\n  if (flippedCards.length === 2) return;\n\n  card.classList.add(\"flipped\");\n  flippedCards.push(card);\n\n  if (flippedCards.length === 2) {\n    moves++;\n    movesEl.textContent = moves;\n\n    const [first, second] = flippedCards;\n    if (first.dataset.icon === second.dataset.icon) {\n      first.classList.remove(\"flipped\");\n      second.classList.remove(\"flipped\");\n      first.classList.add(\"matched\");\n      second.classList.add(\"matched\");\n      matchedCount += 2;\n      flippedCards = [];\n      if (matchedCount === deck.length) {\n        messageEl.textContent = `You win in ${moves} moves!`;\n      }\n    } else {\n      setTimeout(() => {\n        first.classList.remove(\"flipped\");\n        second.classList.remove(\"flipped\");\n        flippedCards = [];\n      }, 300);\n    }\n  }\n});\n"
      }
    },

    {
      id: "dom-u8-p",
      title: "Project: Memory game deluxe",
      kind: "web", chip: "DOM", xp: 60, mins: 45, project: true,
      brief: "The moment the course built toward: the **whole game from a blank script** — render, flip, match, win… plus the deluxe features every real game ships:\n\n- 🔄 **Restart** rebuilds the board and zeroes the counter (reset the *variables*, not just the screen)\n- 🏆 **Best score** — fewest moves — saved in `localStorage` under the key `\"bestScore\"`, shown in `#best`\n\nThe deck keeps its fixed order so the checks are predictable. When everything passes, play a full round in the preview — then shuffle the deck as your victory lap (not graded!).",
      steps: [
        { text: "`renderBoard()` fills `#board` with 16 `.card` buttons carrying `data-icon` in deck order; `#moves` starts at `0`.",
          test: "T.eq(T.count('#board .card'), 16, 'renderBoard() should append one .card button per deck entry — 16 total.');\nvar cards = T.$$('#board .card');\nT.eq(cards[0] && cards[0].dataset.icon, '🍕', 'Each card carries data-icon from the deck, in order — card 1 is 🍕.');\nT.eq(cards[15] && cards[15].dataset.icon, '🍒', 'Last card is 🍒 — keep the fixed deck order; shuffle only AFTER the checks pass.');\nT.eq(T.text('#moves'), '0', 'The moves counter starts at 0.');" },
        { text: "Flip rules hold: a card flips once, the same card never counts twice, a third card is ignored while two are up — and a mismatch flips back and counts one move.",
          test: "var cards = T.$$('#board .card');\ncards[0].click();\nT.expect(cards[0].classList.contains('flipped'), 'Clicking a face-down card should add the class flipped.');\ncards[0].click();\nT.eq(T.count('#board .card.flipped'), 1, 'Clicking the SAME card again must change nothing — guard with classList.contains(\"flipped\").');\ncards[1].click();\nT.eq(T.count('#board .card.flipped'), 2, 'A second card flips — the pair attempt is on.');\ncards[2].click();\nT.expect(!cards[2].classList.contains('flipped'), 'With two cards up, other clicks are ignored until the pair resolves.');\nawait T.sleep(500);\nT.eq(T.count('#board .card.flipped'), 0, '🍕 vs 🌮 is a mismatch — after ~300 ms both flip back (setTimeout).');\nT.eq(T.text('#moves'), '1', 'The mismatched pair still counts: #moves shows 1.');" },
        { text: "Matches resolve instantly: cards 1 and 5 (both 🍕) become `matched` and `#moves` shows `2`.",
          test: "var cards = T.$$('#board .card');\ncards[0].click();\ncards[4].click();\nT.expect(cards[0].classList.contains('matched') && cards[4].classList.contains('matched'), 'Two 🍕 cards should get the class matched immediately and stay revealed.');\nT.eq(T.text('#moves'), '2', 'Second pair-attempt → #moves shows 2.');" },
        { text: "Winning works: matching every remaining pair leaves all 16 cards `matched`, `#moves` at `9`, and a message containing \"win\" in `#message`.",
          test: "var cards = T.$$('#board .card');\nvar pairs = [[1, 5], [2, 6], [3, 7], [8, 12], [9, 13], [10, 14], [11, 15]];\nfor (var i = 0; i < pairs.length; i++) {\n  cards[pairs[i][0]].click();\n  cards[pairs[i][1]].click();\n}\nT.eq(T.count('#board .card.matched'), 16, 'Matching the 7 remaining pairs should leave all 16 cards matched.');\nT.eq(T.text('#moves'), '9', 'Total: 1 mismatch + 8 matches = 9 pair-attempts.');\nT.expect((T.text('#message') || '').toLowerCase().indexOf('win') !== -1, 'All matched → show a message containing \"win\" in #message (e.g. You win in 9 moves!).');" },
        { text: "The win saves the best score: `localStorage` key `bestScore` holds `\"9\"` and `#best` shows it.",
          test: "T.eq(localStorage.getItem('bestScore'), '9', 'On a win, save the move count under the localStorage key \"bestScore\" (save when it beats the stored best — or when there is no best yet).');\nT.expect((T.text('#best') || '').indexOf('9') !== -1, 'Show the best score in #best after saving it.');" },
        { text: "`#restart` starts a fresh game — board rebuilt, counters and message zeroed, best score kept — and the new board still plays.",
          test: "T.click('#restart');\nT.eq(T.text('#moves'), '0', 'Restart should zero the moves counter — the VARIABLE too, not just the text.');\nT.eq(T.count('#board .card'), 16, 'Restart rebuilds a fresh 16-card board.');\nT.eq(T.count('#board .card.matched'), 0, 'No card is matched right after a restart.');\nT.eq(T.count('#board .card.flipped'), 0, 'No card is flipped right after a restart.');\nT.expect((T.text('#message') || '').toLowerCase().indexOf('win') === -1, 'Clear the win message on restart.');\nT.eq(localStorage.getItem('bestScore'), '9', 'The best score SURVIVES a restart — that is the whole point of localStorage.');\nvar cards = T.$$('#board .card');\ncards[0].click();\ncards[4].click();\nT.expect(cards[0].classList.contains('matched'), 'The rebuilt board must still play — a delegated listener on #board keeps working after innerHTML is cleared.');\nT.eq(T.text('#moves'), '1', 'Moves count again from zero on the new game.');" }
      ],
      files: [
        { name: "index.html", content: "<!DOCTYPE html>\n<html>\n<head>\n  <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n  <h1>Memory deluxe 🎮</h1>\n  <p>Moves: <span id=\"moves\">0</span> · Best: <span id=\"best\">—</span></p>\n  <p id=\"message\"></p>\n  <div id=\"board\"></div>\n  <button id=\"restart\">🔄 Restart</button>\n\n  <script src=\"script.js\"></script>\n</body>\n</html>\n" },
        { name: "styles.css", content: "body {\n  font-family: Arial, sans-serif;\n  padding: 20px;\n  text-align: center;\n}\n#board {\n  display: grid;\n  grid-template-columns: repeat(4, 64px);\n  gap: 8px;\n  justify-content: center;\n  margin: 16px auto;\n}\n.card {\n  height: 64px;\n  font-size: 0; /* hides the emoji until flipped */\n  border: 2px solid #94a3b8;\n  border-radius: 10px;\n  background: #6366f1;\n  cursor: pointer;\n}\n.card.flipped,\n.card.matched {\n  font-size: 28px;\n  background: white;\n}\n.card.matched {\n  background: #dcfce7;\n  border-color: #22c55e;\n}\n#message {\n  min-height: 1.2em;\n  font-weight: bold;\n  color: #16a34a;\n}\n#restart {\n  font-size: 15px;\n  padding: 8px 14px;\n  border-radius: 10px;\n  border: 2px solid #cbd5e1;\n  background: white;\n  cursor: pointer;\n}\n" },
        { name: "script.js", content: "/* Memory deluxe — the whole game. The deck is FIXED so the checks are\n   predictable; shuffling is your bonus at the end. */\n\nconst deck = [\n  \"🍕\", \"🌮\", \"🍩\", \"🍎\",\n  \"🍕\", \"🌮\", \"🍩\", \"🍎\",\n  \"🍇\", \"🥑\", \"🍪\", \"🍒\",\n  \"🍇\", \"🥑\", \"🍪\", \"🍒\"\n];\n\nconst board = document.querySelector(\"#board\");\nconst movesEl = document.querySelector(\"#moves\");\nconst bestEl = document.querySelector(\"#best\");\nconst messageEl = document.querySelector(\"#message\"); // never name it \"status\"!\nconst restartBtn = document.querySelector(\"#restart\");\n\nlet flippedCards = [];\nlet moves = 0;\nlet matchedCount = 0;\n\n// 1) renderBoard(): board.innerHTML = \"\", then one <button class=\"card\">\n//    per deck icon with dataset.icon + textContent set\n\n// 2) ONE delegated click listener on board:\n//    guards: not a card / already flipped or matched / two already up.\n//    Flip + push; when it is the SECOND card:\n//      - moves++ → show in movesEl\n//      - same icon → both get \"matched\" (drop \"flipped\"), matchedCount += 2,\n//        flippedCards = []; all 16 matched? → win message (word \"win\") in\n//        messageEl + save best score to localStorage key \"bestScore\"\n//        (only when there is no best yet, or moves beats it), show it in bestEl\n//      - different → setTimeout(300): un-flip both, flippedCards = []\n\n// 3) startGame(): reset moves / matchedCount / flippedCards, zero movesEl,\n//    clear messageEl, renderBoard(), show the stored best in bestEl\n\n// 4) wire restartBtn to startGame, and call startGame() once at load\n" }
      ],
      hints: [
        "Reuse lesson 3's listener wholesale — the deluxe additions are just `startGame()` and the best-score block inside the win branch.",
        "Best score: `const best = localStorage.getItem(\"bestScore\"); if (best === null || moves < Number(best)) localStorage.setItem(\"bestScore\", String(moves));` — getItem returns a STRING (or null), so convert before comparing.",
        "Restart bugs are almost always state bugs: startGame must reset the VARIABLES (`moves = 0; matchedCount = 0; flippedCards = [];`), then repaint (`movesEl.textContent = \"0\"; messageEl.textContent = \"\"; renderBoard();`). Keep the click listener on #board so it survives the rebuild."
      ],
      solution: {
        "script.js": "/* Memory deluxe — the whole game. */\n\nconst deck = [\n  \"🍕\", \"🌮\", \"🍩\", \"🍎\",\n  \"🍕\", \"🌮\", \"🍩\", \"🍎\",\n  \"🍇\", \"🥑\", \"🍪\", \"🍒\",\n  \"🍇\", \"🥑\", \"🍪\", \"🍒\"\n];\n\nconst board = document.querySelector(\"#board\");\nconst movesEl = document.querySelector(\"#moves\");\nconst bestEl = document.querySelector(\"#best\");\nconst messageEl = document.querySelector(\"#message\"); // never name it \"status\"!\nconst restartBtn = document.querySelector(\"#restart\");\n\nlet flippedCards = [];\nlet moves = 0;\nlet matchedCount = 0;\n\nfunction renderBoard() {\n  board.innerHTML = \"\";\n  for (const icon of deck) {\n    const card = document.createElement(\"button\");\n    card.className = \"card\";\n    card.dataset.icon = icon;\n    card.textContent = icon;\n    board.appendChild(card);\n  }\n}\n\nfunction showBest() {\n  const best = localStorage.getItem(\"bestScore\");\n  bestEl.textContent = best === null ? \"—\" : best;\n}\n\nfunction startGame() {\n  flippedCards = [];\n  moves = 0;\n  matchedCount = 0;\n  movesEl.textContent = \"0\";\n  messageEl.textContent = \"\";\n  renderBoard();\n  showBest();\n}\n\nboard.addEventListener(\"click\", (e) => {\n  const card = e.target.closest(\".card\");\n  if (!card) return;\n  if (card.classList.contains(\"flipped\") || card.classList.contains(\"matched\")) return;\n  if (flippedCards.length === 2) return;\n\n  card.classList.add(\"flipped\");\n  flippedCards.push(card);\n  if (flippedCards.length < 2) return;\n\n  moves++;\n  movesEl.textContent = moves;\n\n  const [first, second] = flippedCards;\n  if (first.dataset.icon === second.dataset.icon) {\n    first.classList.remove(\"flipped\");\n    second.classList.remove(\"flipped\");\n    first.classList.add(\"matched\");\n    second.classList.add(\"matched\");\n    matchedCount += 2;\n    flippedCards = [];\n    if (matchedCount === deck.length) {\n      messageEl.textContent = `You win in ${moves} moves! 🎉`;\n      const best = localStorage.getItem(\"bestScore\");\n      if (best === null || moves < Number(best)) {\n        localStorage.setItem(\"bestScore\", String(moves));\n      }\n      showBest();\n    }\n  } else {\n    setTimeout(() => {\n      first.classList.remove(\"flipped\");\n      second.classList.remove(\"flipped\");\n      flippedCards = [];\n    }, 300);\n  }\n});\n\nrestartBtn.addEventListener(\"click\", startGame);\n\nstartGame();\n"
      }
    },

    {
      id: "dom-quiz-8",
      title: "Final quiz: Interactive websites",
      kind: "quiz", xp: 10,
      brief: "Selection, delegation, state, timers, forms — the whole course in seven questions. 80% to pass.",
      questions: [
        { q: "You need EVERY .card on the board. Which call?",
          choices: ["document.querySelector(\".card\") — it returns all matches", "document.getElementByAll(\".card\")", "document.querySelectorAll(\".card\") — then loop or index the result", "document.select(\".card\")"],
          answer: 2, explain: "querySelector stops at the FIRST match; querySelectorAll returns them all. (getElementByAll and select do not exist.)" },
        { q: "Why put ONE click listener on #board instead of 16 — one per card?",
          choices: ["Clicks bubble up, so the parent hears them all — even on cards created AFTER the listener was attached", "Multiple listeners on one page are not allowed", "It makes clicks fire faster", "Parent listeners skip the event object"],
          answer: 0, explain: "That is event delegation: bubbling carries the click up, and e.target.closest(\".card\") tells you which card. A rebuilt board keeps working for free." },
        { q: "You update your array but the page does not change. Why?",
          code: "items.push(\"🍇\");\n// …screen unchanged",
          lang: "js",
          choices: ["Arrays cannot hold emoji", "push() only works inside a listener", "The DOM blocks JS writes after page load", "State and screen are separate — nothing re-rendered; call render() after every change"],
          answer: 3, explain: "The array is the source of truth, but the DOM only changes when you tell it to. Change state → render() is the loop every framework automates." },
        { q: "setTimeout vs setInterval?",
          choices: ["Both repeat until cleared", "setTimeout runs once after the delay; setInterval repeats every delay until clearInterval", "setInterval runs once; setTimeout repeats", "setTimeout blocks the page while it waits"],
          answer: 1, explain: "One-shot vs repeating. The memory game's flip-back is a one-shot job — setTimeout." },
        { q: "Spot the memory-game bug:",
          code: "board.addEventListener(\"click\", (e) => {\n  const card = e.target.closest(\".card\");\n  if (!card) return;\n  card.classList.add(\"flipped\");\n  flippedCards.push(card);\n});",
          lang: "js",
          choices: ["closest() cannot find .card from a click", "classList.add throws if the class is already there", "Clicking the same card twice pushes it twice — it would \"match\" itself; guard with classList.contains(\"flipped\") first", "e.target is always #board"],
          answer: 2, explain: "classList.add silently ignores duplicates, so the DOM looks fine — but the array now holds the same card twice. Guard clauses protect your state, not just your pixels." },
        { q: "First line of almost every submit handler?",
          choices: ["e.preventDefault(); — stop the browser reloading the page", "e.stopPropagation();", "form.reset();", "return false;"],
          answer: 0, explain: "Default form submission navigates away and wipes your app's state. preventDefault keeps your JS in charge: read values, update state, render." },
        { q: "After localStorage.setItem(\"bestScore\", 9), what does getItem(\"bestScore\") return?",
          choices: ["The number 9", "The string \"9\" — localStorage stores strings only", "null until the page reloads", "A JSON object"],
          answer: 1, explain: "Everything is stringified going in. Convert on the way out: Number(localStorage.getItem(\"bestScore\")) before comparing scores." }
      ]
    }
  ]
});
