/* Web Security Basics — Unit 6: Authorization, passwords & abuse */
window.CODELAB.addUnit("sec", {
  id: "sec-u6",
  title: "Authorization, passwords & abuse",
  icon: "🔐",
  blurb: "Course 7 taught authentication — who you are. This is authorization — what you may do. 401 vs 403, IDOR, hashing passwords, and rate-limiting the login. Same ada/bo/token world; you already have the tokens.",
  cheat: [
    { h: "401 vs 403 — two different envelopes", lang: "js", code: "// no/invalid token → I don't know who you are\n{ status: 401, body: { error: \"unauthorized\" } }\n// valid token, wrong role → I know you, and no\n{ status: 403, body: { error: \"forbidden\" } }", note: "Authentication is 401, authorization is 403. Never collapse them into one envelope — they answer different questions." },
    { h: "Guard BEFORE you mutate", lang: "js", code: "const denied = requireRole(req, \"admin\");\nif (denied) return denied;   // 401 or 403, unchanged store\nposts = posts.filter(p => p.id !== 1);  // only trusted code below", note: "A failed permission check must leave the store byte-for-byte untouched. If you delete first and check after, the check is theater." },
    { h: "IDOR: the miss is a 404, never a 403", lang: "js", code: "const note = notes.find(n => n.id === id);\nif (!note || note.ownerName !== me)\n  return { status: 404, body: { error: \"not found\" } };", note: "A row you may not see must look identical to a row that doesn't exist. A 403 confirms the id is real — that's the leak." },
    { h: "Never store a password", lang: "js", code: "const salt = randHex(16);          // per-user, unique\nconst rounds = 10000;              // slow on purpose\nconst hash = slowHash(pw, salt, rounds);\nreturn { name, salt, rounds, hash }; // no plaintext, ever", note: "Store salt + rounds + hash. Same password, different user → different hash. Verify by re-hashing the attempt. Ship bcrypt/argon2 — this is the shape, not the library." },
    { h: "Rate-limit on identity, not outcome", lang: "js", code: "const rl = rateLimit(attempts, userName, 5, 60000);\nif (rl.limited)\n  return { status: 429, body: { error: \"too many attempts\", retryAfter: rl.retryAfter } };", note: "Count every attempt for a username. Once tripped, even the CORRECT password is refused — or the limit is a guessing budget with a reset button." },
    { h: "A 500 leaks nothing", lang: "js", code: "try { return dispatch(req); }\ncatch (e) {\n  // log e server-side; send the client a blank wall\n  return { status: 500, body: { error: \"internal error\" } };\n}", note: "No stack frames (\"at \"), no file paths (\".js\"), no echo of the error's own text — the message may hold a secret or a query." }
  ],
  lessons: [

    {
      id: "sec-u6-1",
      title: "401 vs 403: roles",
      kind: "js", chip: "SEC", xp: 15, mins: 12,
      brief: "Course 7's Auth-lite answered *who are you?* — a token, a 401 for strangers. This is the next question: *what may you do?* You inherit that world unchanged — `token-ada` and `token-bo` are already live — but now users carry a **role**, and only an admin may `DELETE /api/posts/1`.\n\nThree outcomes, three shapes. No token (or a bogus one) → **401** `{ error: \"unauthorized\" }` — I can't tell who you are. A valid token whose user isn't an admin → **403** `{ error: \"forbidden\" }` — I know exactly who you are, and the answer is still no. An admin → **204** and the post is gone.\n\nWrite `requireRole(req, role)`: it returns the blocking response (`401` or `403`), or `null` to let the request through. One trap with teeth: the guard must run **before** the delete, so a forbidden caller leaves the store untouched.\n\n*A lab against your own sandbox — the store and tokens are all in-memory fixtures.*",
      steps: [
        { text: "No token, or a token you never issued → the exact **401** envelope. Nothing is deleted.",
          test: "T.expect(typeof requireRole === 'function', 'Define requireRole(req, role).');\nvar res = handleRequest({ method: 'DELETE', path: '/api/posts/1', body: null });\nT.eq(res, { status: 401, body: { error: 'unauthorized' } }, 'No token at all → { status: 401, body: { error: \"unauthorized\" } } — yours returned ' + JSON.stringify(res));\nvar res2 = handleRequest({ method: 'DELETE', path: '/api/posts/1', headers: { authorization: 'token-hax' }, body: null });\nT.eq(res2, { status: 401, body: { error: 'unauthorized' } }, 'A token you never issued → the same 401');" },
        { text: "A valid **non-admin** token (bo) → **403** `{ error: \"forbidden\" }` — a genuinely different envelope from the 401.",
          test: "var res = handleRequest({ method: 'DELETE', path: '/api/posts/1', headers: { authorization: 'token-bo' }, body: null });\nT.eq(res, { status: 403, body: { error: 'forbidden' } }, 'bo is a valid user but not an admin → 403 forbidden — yours returned ' + JSON.stringify(res));\nT.expect(JSON.stringify(res) !== JSON.stringify({ status: 401, body: { error: 'unauthorized' } }), 'The 403 must NOT reuse the 401 envelope — authenticated is not the same as authorized');" },
        { text: "That forbidden DELETE left the store **untouched** — post 1 is still there. The guard runs before the mutation.",
          test: "var before = handleRequest({ method: 'GET', path: '/api/posts', body: null });\nT.expect(before.body.some(function (p) { return p.id === 1; }), 'bo was forbidden, so post 1 must still exist — did your guard run BEFORE the delete?');\nT.eq(before.body.length, 2, 'Nothing was removed — the store still holds both posts');" },
        { text: "The **admin** (ada) → **204** and post 1 is actually gone from the store.",
          test: "var res = handleRequest({ method: 'DELETE', path: '/api/posts/1', headers: { authorization: 'token-ada' }, body: null });\nT.eq(res.status, 204, 'ada is an admin → 204 No Content — yours returned ' + JSON.stringify(res));\nT.eq(res.body, null, 'A 204 carries no body');\nvar after = handleRequest({ method: 'GET', path: '/api/posts', body: null });\nT.expect(!after.body.some(function (p) { return p.id === 1; }), 'After an admin DELETE, post 1 must be gone');\nT.eq(after.body.length, 1, 'Exactly one post should remain');" }
      ],
      files: [
        { name: "script.js", content: "// Auth is done (Course 7): these tokens are live, and every user has a role.\nlet activeTokens = [\"token-ada\", \"token-bo\"];\nconst users = [\n  { name: \"ada\", role: \"admin\" },\n  { name: \"bo\",  role: \"user\" }\n];\n\nlet posts = [\n  { id: 1, text: \"hello world\" },\n  { id: 2, text: \"second post\" }\n];\n\n// GIVEN: token → user object (or null). Reuses the Course 7 \"token-\" + name trick.\nfunction tokenToUser(req) {\n  const token = req.headers && req.headers.authorization;\n  if (!activeTokens.includes(token)) return null;\n  const userName = token.slice(6); // \"token-ada\" -> \"ada\"\n  return users.find(u => u.name === userName) || null;\n}\n\nfunction requireRole(req, role) {\n  // Return the BLOCKING response, or null to allow:\n  //   no/invalid token       -> { status: 401, body: { error: \"unauthorized\" } }\n  //   valid token, wrong role -> { status: 403, body: { error: \"forbidden\" } }\n  //   right role              -> null\n}\n\nfunction handleRequest(req) {\n  if (req.method === \"GET\" && req.path === \"/api/posts\") {\n    return { status: 200, body: posts };\n  }\n  if (req.method === \"DELETE\" && req.path === \"/api/posts/1\") {\n    const denied = requireRole(req, \"admin\");\n    if (denied) return denied;              // <- guard BEFORE the mutation\n    posts = posts.filter(p => p.id !== 1);\n    return { status: 204, body: null };\n  }\n  return { status: 404, body: \"Not found\" };\n}\n\nconsole.log(handleRequest({ method: \"DELETE\", path: \"/api/posts/1\", headers: { authorization: \"token-bo\" }, body: null }));\n" }
      ],
      hints: [
        "Start from the identity: `const user = tokenToUser(req);` — if it's null you don't know the caller, so `return { status: 401, body: { error: \"unauthorized\" } };`.",
        "Then check the role: `if (user.role !== role) return { status: 403, body: { error: \"forbidden\" } };` — a known caller without the role is a 403, a different envelope on purpose.",
        "If both checks pass, `return null;` so the route knows it may proceed. The handler already deletes only when `requireRole` returns a falsy value — that ordering is what keeps a forbidden request from mutating the store."
      ],
      solution: {
        "script.js": "// Auth is done (Course 7): these tokens are live, and every user has a role.\nlet activeTokens = [\"token-ada\", \"token-bo\"];\nconst users = [\n  { name: \"ada\", role: \"admin\" },\n  { name: \"bo\",  role: \"user\" }\n];\n\nlet posts = [\n  { id: 1, text: \"hello world\" },\n  { id: 2, text: \"second post\" }\n];\n\nfunction tokenToUser(req) {\n  const token = req.headers && req.headers.authorization;\n  if (!activeTokens.includes(token)) return null;\n  const userName = token.slice(6);\n  return users.find(u => u.name === userName) || null;\n}\n\nfunction requireRole(req, role) {\n  const user = tokenToUser(req);\n  if (!user) return { status: 401, body: { error: \"unauthorized\" } };\n  if (user.role !== role) return { status: 403, body: { error: \"forbidden\" } };\n  return null;\n}\n\nfunction handleRequest(req) {\n  if (req.method === \"GET\" && req.path === \"/api/posts\") {\n    return { status: 200, body: posts };\n  }\n  if (req.method === \"DELETE\" && req.path === \"/api/posts/1\") {\n    const denied = requireRole(req, \"admin\");\n    if (denied) return denied;\n    posts = posts.filter(p => p.id !== 1);\n    return { status: 204, body: null };\n  }\n  return { status: 404, body: \"Not found\" };\n}\n\nconsole.log(handleRequest({ method: \"DELETE\", path: \"/api/posts/1\", headers: { authorization: \"token-bo\" }, body: null }));\n"
      }
    },

    {
      id: "sec-u6-2",
      title: "IDOR: an id is a request, not a permission",
      kind: "js", chip: "SEC", xp: 15, mins: 13,
      brief: "Course 7's *Per-user data* filtered a **list** by the token — ada's `/api/mynotes` never showed bo's ferns. This is the other shape: a **direct fetch** of one object by an id the attacker types. `GET /api/notes/2` — and note 2 belongs to someone else.\n\nThe starter authenticates (bad token → 401) but then hands back any note that exists. That's **IDOR** — Insecure Direct Object Reference — the id in the URL is a *request*, not a *permission*. Ada changes a `2` to a `3` in the address bar and reads a stranger's note.\n\nClose it, but mind the response. The obvious fix returns **403** when the owner doesn't match — and a 403 quietly confirms *the note exists*. An attacker walks the ids and maps your whole database by which ones 403 and which 404. The graded insight: a note you may not see must be **byte-identical** to a note that was never there. Same 404, same body.\n\n*Break your own app: the notes are in-memory fixtures.*",
      steps: [
        { text: "ada fetches **her own** note (id 1) → **200** with the note.",
          test: "var res = handleRequest({ method: 'GET', path: '/api/notes/1', headers: { authorization: 'token-ada' }, body: null });\nT.eq(res, { status: 200, body: { id: 1, ownerName: 'ada', text: 'buy milk' } }, 'ada owns note 1 → 200 with the note — yours returned ' + JSON.stringify(res));" },
        { text: "ada fetches **bo's** note (id 2) → **404**, never 403.",
          test: "var res = handleRequest({ method: 'GET', path: '/api/notes/2', headers: { authorization: 'token-ada' }, body: null });\nT.eq(res.status, 404, \"ada does not own note 2 → 404, not 200 — yours returned status \" + (res && res.status));\nT.expect(res.status !== 403, 'A 403 confirms the note exists — the miss must be a 404 so ownership stays invisible');" },
        { text: "The insight: a **forbidden** note and a **non-existent** note are byte-identical.",
          test: "var hidden = handleRequest({ method: 'GET', path: '/api/notes/2', headers: { authorization: 'token-ada' }, body: null });\nvar ghost = handleRequest({ method: 'GET', path: '/api/notes/999', headers: { authorization: 'token-ada' }, body: null });\nT.eq(JSON.stringify(hidden), JSON.stringify(ghost), 'A note ada may not see must be byte-identical to a note that does not exist — any difference leaks which ids are real');" },
        { text: "bo still reads **his own** note; an invalid token is a 401 before any lookup.",
          test: "var res = handleRequest({ method: 'GET', path: '/api/notes/2', headers: { authorization: 'token-bo' }, body: null });\nT.eq(res, { status: 200, body: { id: 2, ownerName: 'bo', text: 'water plants' } }, 'bo owns note 2 → he still gets it (you closed the hole without breaking the feature)');\nT.eq(handleRequest({ method: 'GET', path: '/api/notes/1', headers: { authorization: 'token-hax' }, body: null }), { status: 401, body: { error: 'unauthorized' } }, 'An invalid token → 401 before any note is fetched');" }
      ],
      files: [
        { name: "script.js", content: "let activeTokens = [\"token-ada\", \"token-bo\"];\n\n// ONE shared store — each note names its owner:\nconst notes = [\n  { id: 1, ownerName: \"ada\", text: \"buy milk\" },\n  { id: 2, ownerName: \"bo\",  text: \"water plants\" },\n  { id: 3, ownerName: \"ada\", text: \"call the bank\" }\n];\n\nfunction tokenToUserName(token) {\n  if (!activeTokens.includes(token)) return null;\n  return token.slice(6); // \"token-ada\" -> \"ada\"\n}\n\nfunction handleRequest(req) {\n  if (req.method === \"GET\" && req.path.startsWith(\"/api/notes/\")) {\n    const authToken = req.headers && req.headers.authorization;\n    const me = tokenToUserName(authToken);\n    if (!me) return { status: 401, body: { error: \"unauthorized\" } };\n\n    const id = Number(req.path.split(\"/\")[3]);\n    const note = notes.find(n => n.id === id);\n\n    // BUG (IDOR): any authenticated user can read ANY note that exists.\n    // The id in the URL is being treated as a permission. It isn't.\n    if (!note) return { status: 404, body: { error: \"not found\" } };\n    return { status: 200, body: note };\n  }\n  return { status: 404, body: { error: \"not found\" } };\n}\n\n// ada peeks at bo's note — and the starter lets her:\nconsole.log(handleRequest({ method: \"GET\", path: \"/api/notes/2\", headers: { authorization: \"token-ada\" }, body: null }));\n" }
      ],
      hints: [
        "Fold ownership INTO the miss, don't branch after it. One condition: `if (!note || note.ownerName !== me) return { status: 404, body: { error: \"not found\" } };`.",
        "That single line is the whole fix: a note that doesn't exist and a note you don't own take the exact same exit, so their responses are identical.",
        "Never answer a 403 here — a 403 says \"this exists but isn't yours,\" which is precisely the fact you're trying to hide. Only after the combined check passes do you `return { status: 200, body: note };`."
      ],
      solution: {
        "script.js": "let activeTokens = [\"token-ada\", \"token-bo\"];\n\n// ONE shared store — each note names its owner:\nconst notes = [\n  { id: 1, ownerName: \"ada\", text: \"buy milk\" },\n  { id: 2, ownerName: \"bo\",  text: \"water plants\" },\n  { id: 3, ownerName: \"ada\", text: \"call the bank\" }\n];\n\nfunction tokenToUserName(token) {\n  if (!activeTokens.includes(token)) return null;\n  return token.slice(6);\n}\n\nfunction handleRequest(req) {\n  if (req.method === \"GET\" && req.path.startsWith(\"/api/notes/\")) {\n    const authToken = req.headers && req.headers.authorization;\n    const me = tokenToUserName(authToken);\n    if (!me) return { status: 401, body: { error: \"unauthorized\" } };\n\n    const id = Number(req.path.split(\"/\")[3]);\n    const note = notes.find(n => n.id === id);\n\n    // A note you may not see is indistinguishable from a note that isn't there.\n    if (!note || note.ownerName !== me) {\n      return { status: 404, body: { error: \"not found\" } };\n    }\n    return { status: 200, body: note };\n  }\n  return { status: 404, body: { error: \"not found\" } };\n}\n\nconsole.log(handleRequest({ method: \"GET\", path: \"/api/notes/2\", headers: { authorization: \"token-ada\" }, body: null }));\n"
      }
    },

    {
      id: "sec-u6-3",
      title: "Never store a password",
      kind: "js", chip: "SEC", xp: 15, mins: 14, crypto: true,
      brief: "Course 7's `users` array held passwords in plain text and its own quiz called that a crime. Here's the payoff: store a **hash**, never the password.\n\nThe sandbox hands you three primitives (like a real crypto library would): `sha256(str)`, `randHex(n)` for random bytes, and `slowHash(str, salt, rounds)` — an *iterated* hash that's deliberately slow, so guessing is expensive. Build three functions on top:\n\n- `makeUser(name, password)` → a record with a **per-user random salt**, a **rounds** count (≥ 10000), and the `hash`. No plaintext anywhere in it.\n- `hashPassword(password, salt, rounds)` → the hash, via `slowHash`.\n- `checkPassword(user, attempt)` → re-hash the attempt with the user's stored salt and rounds; `true` only on an exact match.\n\nWhy per-user salt? Two people pick the same password; a **global** salt gives them the same hash, and cracking one cracks both. A fresh salt each time makes identical passwords look unrelated.\n\n*This is the shape of the thing. In production you ship bcrypt, scrypt or argon2 — never hand-rolled crypto.*",
      steps: [
        { text: "`makeUser` returns a record; the plaintext password — and every 4-character run of it — is **absent** from it.",
          test: "T.expect(typeof makeUser === 'function', 'Define makeUser(name, password).');\nvar pw = 'correct horse battery';\nvar u = makeUser('ada', pw);\nT.expect(typeof u.hash === 'string' && u.hash.length > 0, 'The record must carry a non-empty .hash string');\nvar blob = JSON.stringify(u);\nT.expect(blob.indexOf(pw) === -1, 'The plaintext password must never appear in the stored record');\nvar leaked = null;\nfor (var i = 0; i + 4 <= pw.length; i++) { var frag = pw.slice(i, i + 4); if (blob.indexOf(frag) !== -1) { leaked = frag; break; } }\nT.expect(leaked === null, 'No 4-character run of the password may survive in the record — found: ' + JSON.stringify(leaked));" },
        { text: "Two users, **same password**, get **different** hashes — the salt is per-user, not global.",
          test: "var u1 = makeUser('ada', 'hunter2horse');\nvar u2 = makeUser('bo', 'hunter2horse');\nT.expect(u1.salt !== u2.salt, 'Each user needs its OWN random salt — u1.salt and u2.salt must differ');\nT.expect(u1.hash !== u2.hash, 'Same password + different salt → different hash. A GLOBAL salt would make these equal — that is the bug this catches');" },
        { text: "`checkPassword` is true for the right password, false for the right password with **one character changed**.",
          test: "T.expect(typeof checkPassword === 'function', 'Define checkPassword(user, attempt).');\nvar u = makeUser('ada', 'S3cret-Pass');\nT.expect(checkPassword(u, 'S3cret-Pass') === true, 'The exact password must verify true');\nT.expect(checkPassword(u, 'S3cret-Pasz') === false, 'One character off must verify false');\nT.expect(checkPassword(u, '') === false, 'An empty attempt must be false');" },
        { text: "The record stores `salt` and `rounds` (≥ 10000), and `hashPassword` reproduces the stored hash.",
          test: "T.expect(typeof hashPassword === 'function', 'Define hashPassword(password, salt, rounds).');\nvar u = makeUser('ada', 'whatever-pw');\nT.expect(typeof u.salt === 'string' && u.salt.length > 0, 'The record must store the per-user salt (checkPassword needs it later)');\nT.expect(typeof u.rounds === 'number', 'The record must store the rounds count');\nT.expect(u.rounds >= 10000, 'Use at least 10000 rounds — a fast hash is a cheap hash to crack. Yours: ' + u.rounds);\nT.eq(hashPassword('whatever-pw', u.salt, u.rounds), u.hash, 'hashPassword(password, salt, rounds) must deterministically reproduce the stored hash');" }
      ],
      files: [
        { name: "script.js", content: "// The sandbox provides these primitives (a stand-in for a real crypto library):\n//   sha256(str)                 -> 64-char hex\n//   randHex(n)                  -> n random bytes as 2n hex chars\n//   slowHash(str, salt, rounds) -> iterated hash, deliberately slow\n//\n// NEVER ship hand-rolled crypto — this is the SHAPE. Production = bcrypt/scrypt/argon2.\n\nfunction hashPassword(password, salt, rounds) {\n  // Return the slow, salted, iterated hash of `password`.\n}\n\nfunction makeUser(name, password) {\n  // 1) a per-user RANDOM salt (randHex)\n  // 2) a rounds count >= 10000\n  // 3) the hash of the password with THIS salt and rounds\n  // Return { name, salt, rounds, hash } — and NO plaintext.\n}\n\nfunction checkPassword(user, attempt) {\n  // Re-hash `attempt` with the user's stored salt + rounds; true only on an exact match.\n}\n\n// A password check, for the console:\nconst u = makeUser(\"ada\", \"mainframe\");\nconsole.log(\"stored:\", JSON.stringify(u));\nconsole.log(\"right password?\", checkPassword(u, \"mainframe\"));\nconsole.log(\"wrong password?\", checkPassword(u, \"mainfram3\"));\n" }
      ],
      hints: [
        "`hashPassword` is a thin wrapper: `return slowHash(password, salt, rounds);` — the slowness is the whole security property, so never fall back to a bare `sha256`.",
        "In `makeUser`, generate the salt FIRST and keep it: `const salt = randHex(16); const rounds = 10000; const hash = hashPassword(password, salt, rounds); return { name, salt, rounds, hash };`. The salt must come from `randHex` each call, never a constant.",
        "`checkPassword` re-runs the same recipe on the attempt: `return hashPassword(attempt, user.salt, user.rounds) === user.hash;`. You compare hashes, never decrypt — there's nothing to decrypt."
      ],
      solution: {
        "script.js": "// The sandbox provides sha256, randHex and slowHash — a stand-in for a crypto library.\n// NEVER ship hand-rolled crypto: production = bcrypt/scrypt/argon2.\n\nfunction hashPassword(password, salt, rounds) {\n  return slowHash(password, salt, rounds);\n}\n\nfunction makeUser(name, password) {\n  const salt = randHex(16);       // per-user, unique on every call\n  const rounds = 10000;           // deliberately slow\n  const hash = hashPassword(password, salt, rounds);\n  return { name: name, salt: salt, rounds: rounds, hash: hash };\n}\n\nfunction checkPassword(user, attempt) {\n  return hashPassword(attempt, user.salt, user.rounds) === user.hash;\n}\n\nconst u = makeUser(\"ada\", \"mainframe\");\nconsole.log(\"stored:\", JSON.stringify(u));\nconsole.log(\"right password?\", checkPassword(u, \"mainframe\"));\nconsole.log(\"wrong password?\", checkPassword(u, \"mainfram3\"));\n"
      }
    },

    {
      id: "sec-u6-4",
      title: "Rate limits, lockouts & identical failures",
      kind: "js", chip: "SEC", xp: 15, mins: 14,
      brief: "A login with no throttle is a free guessing machine. Close it three ways at once.\n\n**Rate limit.** Write `rateLimit(store, key, max, windowMs)`: count attempts per `key`, and once they pass `max`, report `limited` with a `retryAfter`. Wire it into `POST /api/login` so five wrong passwords return **401** each, the sixth returns **429** with `retryAfter` in the body — and the *correct* password on the seventh try **also** returns 429. The limit keys on **identity, not outcome**: a lockout you can escape by finally guessing right isn't a lockout.\n\n**Identical failures.** \"No such user\" and \"wrong password\" must return a **byte-identical** 401. Two different messages hand an attacker a username oracle — one probe tells them which accounts are real.\n\n**Don't leak on 500.** When a handler throws, the client gets a blank `{ error: \"internal error\" }`. The error's own message may carry a stack frame, a file path, or a secret — none of it may reach the client. (Course 7's *Never crash* wrapped throws in a 500; this adds the rule that the 500 says *nothing*.)\n\n*A lab against your own sandbox — fixed fixtures, fake secrets.*",
      steps: [
        { text: "Five wrong passwords for ada → **401** each; the sixth trips the limit → **429** with a positive `retryAfter`.",
          test: "T.expect(typeof rateLimit === 'function', 'Define rateLimit(store, key, max, windowMs).');\nfor (var i = 1; i <= 5; i++) {\n  var r = handleRequest({ method: 'POST', path: '/api/login', body: { userName: 'ada', password: 'nope' + i } });\n  T.eq(r.status, 401, 'Wrong-password attempt #' + i + ' is still under the limit → 401 (got ' + (r && r.status) + ')');\n}\nvar sixth = handleRequest({ method: 'POST', path: '/api/login', body: { userName: 'ada', password: 'nope6' } });\nT.eq(sixth.status, 429, 'The sixth attempt trips the limit → 429');\nT.expect(sixth.body && typeof sixth.body.retryAfter === 'number' && sixth.body.retryAfter > 0, 'The 429 body must carry a positive retryAfter so the client knows when to try again');" },
        { text: "The point: the **correct** password on the seventh try is **still 429** — the limit ignores the outcome.",
          test: "var seventh = handleRequest({ method: 'POST', path: '/api/login', body: { userName: 'ada', password: 'mainframe' } });\nT.eq(seventh.status, 429, 'ada is already locked out, so even the CORRECT password is refused → 429. If this returned 200, your limit checks credentials before the cap — a guessing budget with a reset button');" },
        { text: "\"Unknown user\" and \"wrong password\" return **byte-identical** 401s (fresh accounts, still under the cap).",
          test: "var unknown = handleRequest({ method: 'POST', path: '/api/login', body: { userName: 'ghost', password: 'x' } });\nvar wrong = handleRequest({ method: 'POST', path: '/api/login', body: { userName: 'bo', password: 'x' } });\nT.eq(unknown.status, 401, 'Unknown user → 401');\nT.eq(wrong.status, 401, 'Known user, wrong password → 401');\nT.eq(JSON.stringify(unknown), JSON.stringify(wrong), 'The two 401s must be byte-identical — a different reply tells an attacker which usernames exist');" },
        { text: "A handler that throws → **500** whose body leaks **nothing**: no stack, no file path, no echo of the error text.",
          test: "var res = handleRequest({ method: 'POST', path: '/api/report', headers: { authorization: 'token-ada' }, body: { text: 'hi' } });\nT.eq(res.status, 500, 'A thrown internal error must become a 500, not an uncaught crash');\nvar blob = JSON.stringify(res.body);\nT.expect(blob.indexOf('at ') === -1, 'No stack frames in the 500 body — strip anything containing \"at \"');\nT.expect(blob.indexOf('.js') === -1, 'No file paths in the 500 body — nothing ending \".js\"');\nT.expect(blob.indexOf('sk_live_') === -1, \"The 500 must not echo the error's own text — it held a fake secret\");\nT.expect(blob.toLowerCase().indexOf('secret') === -1, 'None of the raw error message may reach the client');" }
      ],
      files: [
        { name: "script.js", content: "const users = [\n  { name: \"ada\", password: \"mainframe\" },\n  { name: \"bo\",  password: \"hunter2\" }\n];\n\n// Per-key attempt tallies live here (survives across requests):\nlet loginAttempts = {};\n\n// GIVEN: pretend this hit a datastore and blew up. Its message is a LEAK waiting to happen.\nfunction riskyLookup(req) {\n  throw new Error(\"sk_live_51H8xFAKE db connect failed at /srv/app/handlers.js:88\");\n}\n\nfunction rateLimit(store, key, max, windowMs) {\n  // Count attempts for `key` in `store`. Once the count passes `max`, report the block:\n  //   over the cap -> { limited: true, retryAfter: <positive seconds> }\n  //   under        -> { limited: false }\n  // Deterministic sandbox: no Date.now() — the count alone decides.\n}\n\nfunction dispatch(req) {\n  if (req.method === \"POST\" && req.path === \"/api/login\") {\n    const userName = req.body && req.body.userName;\n    const rl = rateLimit(loginAttempts, userName, 5, 60000);\n    if (rl.limited) {\n      return { status: 429, body: { error: \"too many attempts\", retryAfter: rl.retryAfter } };\n    }\n    // Credentials come AFTER the cap. One vague 401 for every failure:\n    const user = users.find(u => u.name === userName);\n    if (!user || user.password !== (req.body && req.body.password)) {\n      return { status: 401, body: { error: \"invalid credentials\" } };\n    }\n    return { status: 200, body: { token: \"token-\" + userName } };\n  }\n  if (req.method === \"POST\" && req.path === \"/api/report\") {\n    return riskyLookup(req); // throws — your wrapper must contain the damage\n  }\n  return { status: 404, body: { error: \"not found\" } };\n}\n\nfunction handleRequest(req) {\n  // Call dispatch(req), but never let a thrown error escape to the client.\n  // On a throw: log server-side if you like, but RETURN { status: 500, body: { error: \"internal error\" } }\n  // — no stack, no path, no secret from the error's message.\n}\n\nconsole.log(handleRequest({ method: \"POST\", path: \"/api/login\", body: { userName: \"demo\", password: \"nope\" } }));\n" }
      ],
      hints: [
        "`rateLimit` just tallies: `const hits = (store[key] || 0) + 1; store[key] = hits; if (hits > max) return { limited: true, retryAfter: Math.ceil(windowMs / 1000) }; return { limited: false };`. Because it runs BEFORE the credential check, a locked-out key never even reaches the password compare.",
        "The identical 401 is already in `dispatch`: one `{ error: \"invalid credentials\" }` for both the unknown-user and wrong-password branches. Don't split it into two messages.",
        "`handleRequest` is the safety wrapper: `try { return dispatch(req); } catch (e) { return { status: 500, body: { error: \"internal error\" } }; }`. The client gets a blank wall; the error object (with its secret and file path) never leaves the server."
      ],
      solution: {
        "script.js": "const users = [\n  { name: \"ada\", password: \"mainframe\" },\n  { name: \"bo\",  password: \"hunter2\" }\n];\n\nlet loginAttempts = {};\n\nfunction riskyLookup(req) {\n  throw new Error(\"sk_live_51H8xFAKE db connect failed at /srv/app/handlers.js:88\");\n}\n\nfunction rateLimit(store, key, max, windowMs) {\n  const hits = (store[key] || 0) + 1;\n  store[key] = hits;\n  if (hits > max) {\n    return { limited: true, retryAfter: Math.ceil(windowMs / 1000) };\n  }\n  return { limited: false };\n}\n\nfunction dispatch(req) {\n  if (req.method === \"POST\" && req.path === \"/api/login\") {\n    const userName = req.body && req.body.userName;\n    const rl = rateLimit(loginAttempts, userName, 5, 60000);\n    if (rl.limited) {\n      return { status: 429, body: { error: \"too many attempts\", retryAfter: rl.retryAfter } };\n    }\n    const user = users.find(u => u.name === userName);\n    if (!user || user.password !== (req.body && req.body.password)) {\n      return { status: 401, body: { error: \"invalid credentials\" } };\n    }\n    return { status: 200, body: { token: \"token-\" + userName } };\n  }\n  if (req.method === \"POST\" && req.path === \"/api/report\") {\n    return riskyLookup(req);\n  }\n  return { status: 404, body: { error: \"not found\" } };\n}\n\nfunction handleRequest(req) {\n  try {\n    return dispatch(req);\n  } catch (e) {\n    // Log e server-side. The client gets a blank wall — nothing from e's message.\n    return { status: 500, body: { error: \"internal error\" } };\n  }\n}\n\nconsole.log(handleRequest({ method: \"POST\", path: \"/api/login\", body: { userName: \"demo\", password: \"nope\" } }));\n"
      }
    },

    {
      id: "sec-quiz-6",
      title: "Unit 6 quiz: Authz & credentials",
      kind: "quiz", xp: 10,
      brief: "Roles, IDOR, hashing and abuse — the difference between knowing who someone is and deciding what they may do. 80% to pass.",
      questions: [
        { q: "Your API used to reject only missing tokens with **401**. Now you add admin-only delete, and a normal logged-in user tries it. What should they get?",
          choices: [
            "401 unauthorized — the server genuinely cannot identify the caller at all",
            "200 — let the request through and undo the change later if needed",
            "404 — pretend the route does not exist for this user",
            "403 forbidden — a valid login without the required role"
          ],
          answer: 3, explain: "401 and 403 answer different questions: 401 is \"I don't know who you are\" (no or bad token), 403 is \"I know exactly who you are, and you still may not do this.\" A logged-in non-admin is authenticated but not authorized, so it's a 403. Returning 200 defeats the guard entirely, and a 404 here is only warranted when you're deliberately hiding a resource's existence — not the case for a known action a user simply lacks the role for." },
        { q: "You fetch `/api/notes/2`, but note 2 belongs to another user. Why answer **404** instead of 403?",
          choices: [
            "404 is cheaper for the server to compute than 403",
            "Because a 403 confirms the note exists, letting an attacker map which ids are real by walking the numbers",
            "The two codes are interchangeable, so pick whichever reads nicer",
            "Browsers refuse to cache 403 responses"
          ],
          answer: 1, explain: "A 403 says \"this exists, but it isn't yours\" — which quietly leaks that the id is real. An attacker increments the id and reads your database's shape from which numbers 403 and which 404. Returning the same 404 for \"not yours\" and \"never existed\" makes ownership invisible. This is distinct from list filtering: here the id is attacker-chosen, so the response itself must not confirm the row." },
        { q: "You must never store a user's password as plain text. What do you store and compare against instead?",
          choices: [
            "a salted hash",
            "the password encrypted with a shared server key so it can be decrypted and compared at login",
            "the password reversed and base64-encoded so it isn't human-readable in the database",
            "a plain SHA-256 of the password with no salt, which is fast to verify"
          ],
          answer: 0, explain: "Store a per-user salted hash from a deliberately slow function (bcrypt, scrypt, argon2) and verify by re-hashing the attempt — you never recover the original. Reversible encryption is the wrong tool: one leaked key exposes every password. A plain unsalted SHA-256 is far too fast to compute and lets identical passwords share a hash, so a single rainbow table or one cracked account breaks many at once." },
        { q: "Login returns \"no such user\" for unknown names and \"wrong password\" for bad passwords. Making both replies byte-identical stops which attack?",
          choices: [
            "Cross-site scripting",
            "Username enumeration",
            "Clickjacking of the login form",
            "A distributed denial-of-service flood"
          ],
          answer: 1, explain: "Two different messages turn your login into a username oracle: an attacker submits a name with any password and learns from the wording whether that account exists, then focuses guessing on the real ones. One identical 401 for every failure removes the signal. It has nothing to do with XSS, clickjacking or DoS — those are separate defenses (escaping, frame headers, rate limits)." },
        { q: "Your login rate limit counts attempts per username. On the 7th try the user finally submits the **correct** password. What happens?",
          choices: [
            "It succeeds — a correct password always overrides an active lockout",
            "Still refused with 429, because the limit counts attempts and ignores whether a guess was right",
            "The counter resets to zero the moment the password matches",
            "The account is permanently deleted as a safety measure"
          ],
          answer: 1, explain: "The whole point of keying on identity rather than outcome is that a lockout you can escape by finally guessing right is just a guessing budget with a reset button. The cap has to be checked before the credential compare, so once tripped, every further attempt — right or wrong — returns 429 until the window elapses. Nothing resets on a match, and locking out is not the same as deleting the account." },
        { q: "A handler throws mid-request and the error's message is `\"sk_live_… failed at /srv/app/db.js:42\"`. What belongs in the **500** body sent to the client?",
          choices: [
            "The full stack trace, so the user can paste it into a bug report",
            "The exact error message and the file path, for transparency",
            "A generic message with no stack frames, file paths, or secrets",
            "The database query that failed, so the client can retry it correctly"
          ],
          answer: 2, explain: "Log the full error server-side, but send the client a blank wall — `{ error: \"internal error\" }` and nothing more. That message held a secret key and an internal file path; echoing any of it (the stack's \"at \" frames, the \".js\" path, the raw text) hands an attacker reconnaissance for free. Course 7 taught you to catch the throw into a 500; the security rule is that the 500 reveals nothing about what broke." }
      ]
    }
  ]
});
