/* Web Security Basics — Unit 7: Browser defenses & the hardening capstone */
window.CODELAB.addUnit("sec", {
  id: "sec-u7",
  title: "Browser defenses & the hardening capstone",
  icon: "🛡️",
  blurb: "The headers a shipped app sets and why — CSP, X-Frame-Options, nosniff, Referrer-Policy, HSTS — then the whole course applied at once to a deliberately broken app.",
  cheat: [
    { h: "Read a CSP directive", lang: "js", code: `// A policy is directives, each with a source list:\n//   default-src 'self'; img-src *.cdn.com; script-src 'none'\n// A missing directive FALLS BACK to default-src.\n//   img-src absent  ->  use default-src's list\n// Sources: 'self' (your origin), 'none' (nothing),\n//   an exact host (cdn.example.com), a wildcard (*.cdn.com\n//   = any SUBDOMAIN, not the bare apex).`, note: "This is the grammar the browser reads on every request. Lesson 1 parses it; the browser enforces it." },
    { h: "Strict AND functional", lang: "js", code: `// Restrictive enough to block injected code,\n// functional enough not to break your own page:\ndefault-src 'none';\nscript-src 'nonce-RPT';        // your OWN scripts carry the nonce\nstyle-src 'unsafe-inline' data:;\nimg-src data:;\n// Injected <script>/<img onerror>/eval have NO nonce -> blocked.`, note: "CSP is defense-in-depth: it catches the XSS your escaping missed. No 'unsafe-inline' for scripts is the whole point." },
    { h: "Headers every app sets", lang: "js", code: `res.headers["X-Content-Type-Options"] = "nosniff";\nres.headers["X-Frame-Options"] = "DENY";\nres.headers["Referrer-Policy"] = "no-referrer";\nres.headers["Strict-Transport-Security"] =\n  "max-age=31536000; includeSubDomains";\nres.headers["Content-Security-Policy"] = "default-src 'self'";`, note: "One middleware, every response. nosniff stops MIME-sniffing; HSTS pins https." },
    { h: "Clickjacking defense", lang: "js", code: `// Can another site put your page in an <iframe>?\n// X-Frame-Options: DENY        -> never\n// X-Frame-Options: SAMEORIGIN  -> only your own origin\n// CSP frame-ancestors https://partner.com  -> just that list\n// (frame-ancestors is the modern replacement for XFO)`, note: "Without one of these, any site can frame yours and trick a click through it." },
    { h: "The hardening pass", lang: "js", code: `// Before you ship, walk the holes:\n// 1) render untrusted text with textContent, not innerHTML\n// 2) allow only http/https on user-supplied href\n// 3) no secret/API key in client source\n// 4) every permission decision lives on the SERVER\n// 5) cap input length; refuse with a visible message`, note: "The capstone project is exactly this checklist against a broken board." }
  ],
  lessons: [

    {
      id: "sec-u7-1",
      title: "CSP: read the policy",
      kind: "js", chip: "SEC", xp: 15, mins: 13,
      brief: "A **Content-Security-Policy** is a contract you hand the browser: which sources may load scripts, images, styles. It reads as directives separated by `;`, each a name and a source list — `default-src 'self'; img-src *.cdn.com; script-src 'none'`.\n\nHere you build the *interpreter*: `parsePolicy(str)` turns that text into an object, and `allows(policy, directive, target)` answers whether a URL is permitted. Four rules matter: `'self'` (your own origin — say your site is `myapp.com`), `'none'` (nothing at all), an exact host, and a wildcard `*.cdn.com` (any **subdomain**, never the bare apex). The one everyone forgets: a directive that isn't listed **falls back to `default-src`**.\n\nHonest framing: this grades the **semantics** — what a policy *means*. It does not enforce anything; the browser does that, and lesson 2 makes it real.",
      steps: [
        { text: "Write `parsePolicy(str)` → an object mapping each directive to its array of sources.",
          test: "T.expect(typeof parsePolicy === 'function', 'Define parsePolicy(str).');\nT.eq(parsePolicy(\"default-src 'self'; img-src *.cdn.com; script-src 'none'\"), { 'default-src': [\"'self'\"], 'img-src': ['*.cdn.com'], 'script-src': [\"'none'\"] }, 'Split on \";\", then on whitespace: first token is the directive, the rest are its sources.');\nT.eq(parsePolicy(\"script-src 'self' 'unsafe-inline' cdn.example.com\"), { 'script-src': [\"'self'\", \"'unsafe-inline'\", 'cdn.example.com'] }, 'A directive can carry several sources — keep them all, in order.');" },
        { text: "Write `allows(policy, directive, target)` — handle `'none'`, `'self'` (myapp.com), an exact host, no-match, and the `\"inline\"` question for `'unsafe-inline'`.",
          test: "T.expect(typeof allows === 'function', 'Define allows(policy, directive, target).');\nvar A = parsePolicy(\"default-src 'self'; img-src *.cdn.com; script-src 'none'\");\nvar B = parsePolicy(\"script-src 'self' 'unsafe-inline' cdn.example.com\");\nT.eq(allows(A, 'script-src', 'https://myapp.com/app.js'), false, \"script-src 'none' blocks everything, even your own origin.\");\nT.eq(allows(B, 'script-src', 'https://myapp.com/app.js'), true, \"'self' should match your own origin (myapp.com).\");\nT.eq(allows(B, 'script-src', 'https://cdn.example.com/lib.js'), true, 'An exact host source should match that host.');\nT.eq(allows(B, 'script-src', 'https://other.com/x.js'), false, 'A host that appears in no source is refused.');\nT.eq(allows(B, 'script-src', 'inline'), true, \"target 'inline' asks: is an inline handler allowed? B has 'unsafe-inline', so true.\");\nT.eq(allows(A, 'script-src', 'inline'), false, \"A's script-src is 'none' — inline is blocked too.\");" },
        { text: "Now the two that trip people: wildcard subdomains, and a missing directive falling back to `default-src`.",
          test: "var A = parsePolicy(\"default-src 'self'; img-src *.cdn.com; script-src 'none'\");\nvar C = parsePolicy(\"default-src 'self'\");\nT.eq(allows(A, 'img-src', 'https://a.cdn.com/x.png'), true, '*.cdn.com matches a subdomain like a.cdn.com.');\nT.eq(allows(A, 'img-src', 'https://cdn.com/x.png'), false, '*.cdn.com does NOT match the bare apex cdn.com — a wildcard needs a subdomain.');\nT.eq(allows(A, 'img-src', 'https://deep.a.cdn.com/x.png'), true, '*.cdn.com matches any depth of subdomain.');\nT.eq(allows(C, 'img-src', 'https://myapp.com/logo.png'), true, 'img-src is UNSPECIFIED in C, so it falls back to default-src \\'self\\' — and myapp.com is self.');\nT.eq(allows(C, 'img-src', 'https://evil.com/logo.png'), false, 'The fallback still applies: default-src \\'self\\' refuses evil.com.');" }
      ],
      files: [
        { name: "script.js", content: `// A CSP is text like:  default-src 'self'; img-src *.cdn.com; script-src 'none'\n// Your site's own origin is:  myapp.com\n//\n// 1) parsePolicy(str) -> object: { "default-src": ["'self'"], ... }\n//      split on ";", trim, split each part on whitespace;\n//      first token = directive name, the rest = its source array.\n//\n// 2) allows(policy, directive, target) -> boolean\n//      - find the directive's list; if it is MISSING, fall back to\n//        policy["default-src"]; if that is missing too, allow (return true).\n//      - if the list contains 'none'      -> false always\n//      - if target === "inline"           -> is 'unsafe-inline' in the list?\n//      - otherwise read target's host (new URL(target).hostname) and match:\n//          'self'          -> host === "myapp.com"\n//          "*.cdn.com"     -> host ends with ".cdn.com" AND is longer\n//          "cdn.example.com" (exact host) -> host === that host\n\nfunction parsePolicy(str) {\n  return {};   // TODO\n}\n\nfunction allows(policy, directive, target) {\n  return true; // TODO\n}\n` }
      ],
      hints: [
        "parsePolicy: `String(str).split(\";\").forEach(part => { const t = part.trim().split(/\\s+/).filter(Boolean); if (t.length) out[t[0]] = t.slice(1); });`",
        "In allows, resolve the list first: `const list = policy[directive] || policy[\"default-src\"]; if (!list) return true;` then check `'none'` and `\"inline\"` before touching the URL.",
        "Wildcard: turn `*.cdn.com` into the suffix `.cdn.com`, then `host.length > suffix.length && host.slice(-suffix.length) === suffix`. An exact host has no `*` and no leading quote — compare `new URL(...).hostname` directly."
      ],
      solution: {
        "script.js": `// A CSP is text; your own origin is myapp.com.\n\nfunction parsePolicy(str) {\n  var out = {};\n  String(str).split(";").forEach(function (part) {\n    var tokens = part.trim().split(/\\s+/).filter(Boolean);\n    if (!tokens.length) return;\n    out[tokens[0]] = tokens.slice(1);\n  });\n  return out;\n}\n\nfunction allows(policy, directive, target) {\n  var list = policy[directive] || policy["default-src"];\n  if (!list) return true;                       // nothing restricts it\n  if (list.indexOf("'none'") !== -1) return false;\n  if (target === "inline") return list.indexOf("'unsafe-inline'") !== -1;\n\n  var host;\n  try { host = new URL(target).hostname; } catch (e) { host = String(target); }\n\n  for (var i = 0; i < list.length; i++) {\n    var src = list[i];\n    if (src === "'self'") {\n      if (host === "myapp.com") return true;\n    } else if (src.indexOf("*.") === 0) {\n      var suffix = src.slice(1);                 // "*.cdn.com" -> ".cdn.com"\n      if (host.length > suffix.length && host.slice(-suffix.length) === suffix) return true;\n    } else if (src.charAt(0) !== "'") {           // an exact host, not a keyword\n      var srcHost;\n      try { srcHost = new URL(/:\\/\\//.test(src) ? src : "https://" + src).hostname; }\n      catch (e2) { srcHost = src; }\n      if (host === srcHost) return true;\n    }\n  }\n  return false;\n}\n`
      }
    },

    {
      id: "sec-u7-2",
      title: "CSP for real: the nested-frame lab",
      kind: "web", chip: "SEC", xp: 15, mins: 14, cspLab: true,
      brief: "Lesson 1 read a policy on paper. Now the **browser** enforces one — for real. This is a lab against your own sandbox: `window.__runCspLab(policy)` mounts a page under *your* policy and runs five payloads inside it — an injected inline `<script>`, an `<img onerror>` handler, an `eval()`, the page's own `<style>`, and the page's own `data:` stylesheet — then reports which ones **ran**.\n\nYour job: set `window.POLICY` to a policy that is **both restrictive and functional**. Restrictive: the three injected attacks (`inlineScript`, `imgOnerror`, `evalCall`) must be blocked. Functional: the page's own styles must still work, and — the trap — the page's own trusted script must still run. That trusted script carries the nonce `'nonce-RPT'`; injected payloads never carry it.\n\nThe starter policy `default-src 'none'` blocks the attacks... and the whole page with them (`reporterBlocked`). Real hardening is tighter than that: allow *your* code by nonce, allow *your* styles, block everything injected.",
      steps: [
        { text: "Under your policy, the three injected attacks are all **blocked**.",
          test: "window.__runCspLab(window.POLICY);\nawait T.sleep(1200);\nvar r = window.__CSP_RESULTS || {};\nT.expect(r.inlineScript === false, 'An injected inline <script> must NOT run — inlineScript should be false. Got ' + r.inlineScript + '. (Do not put \\'unsafe-inline\\' in script-src.)');\nT.expect(r.imgOnerror === false, 'An injected <img onerror> handler must NOT run — imgOnerror should be false. Got ' + r.imgOnerror + '.');\nT.expect(r.evalCall === false, 'eval() must be blocked — evalCall should be false. Got ' + r.evalCall + '. (No \\'unsafe-eval\\'.)');" },
        { text: "...but the page itself still **works**: its own script, styles and stylesheet all survive.",
          test: "window.__runCspLab(window.POLICY);\nawait T.sleep(1200);\nvar r = window.__CSP_RESULTS || {};\nT.expect(r.reporterBlocked !== true, \"Your policy is so strict it blocked the page's OWN trusted script (nonce 'nonce-RPT') — that is what 'default-src \\\\'none\\\\'' alone does. Allow it with  script-src 'nonce-RPT'.\");\nT.expect(r.inlineStyle === true, \"The page's own <style> must still apply — inlineStyle should be true. Allow it with  style-src 'unsafe-inline'.\");\nT.expect(r.ownStylesheet === true, \"The page's own data: stylesheet must still load — ownStylesheet should be true. Add  data:  to style-src.\");" }
      ],
      files: [
        { name: "index.html", content: `<!DOCTYPE html>\n<html>\n<head>\n  <link rel="stylesheet" href="styles.css">\n</head>\n<body>\n  <h1>CSP lab \u{1F9EA}</h1>\n  <p>The checks mount a page under <code>window.POLICY</code> and fire five payloads at it.</p>\n  <p>Goal: block the injected ones, keep the page's own code working.</p>\n  <script src="script.js"></script>\n</body>\n</html>\n` },
        { name: "styles.css", content: `body { font-family: Arial, sans-serif; padding: 20px; color: #1e293b; }\ncode { background: #f1f5f9; padding: 2px 5px; border-radius: 5px; }\n` },
        { name: "script.js", content: `// Set window.POLICY to a Content-Security-Policy string.\n//\n// The lab runs FIVE payloads under your policy and reports which RAN:\n//   inlineScript  - an injected inline <script>        (attack: block it)\n//   imgOnerror    - an injected <img onerror> handler   (attack: block it)\n//   evalCall      - an eval() call                      (attack: block it)\n//   inlineStyle   - the page's own <style> block         (keep it working)\n//   ownStylesheet - the page's own data: stylesheet      (keep it working)\n//\n// The page's OWN trusted script carries the nonce 'nonce-RPT'.\n// A functional policy must let it run (script-src 'nonce-RPT').\n// Injected payloads never carry the nonce.\n//\n// This starter blocks everything... including the page itself. Tighten it\n// into a policy that is BOTH restrictive AND functional.\nwindow.POLICY = "default-src 'none'";\n` }
      ],
      hints: [
        "Start from `default-src 'none'` and open exactly what your OWN page needs, nothing more.",
        "Allow your own scripts by nonce, not by 'unsafe-inline': `script-src 'nonce-RPT'` — injected scripts have no nonce, so they stay blocked.",
        "Your styles need both an inline block and a data: sheet: `style-src 'unsafe-inline' data:`. The working shape is `default-src 'none'; script-src 'nonce-RPT'; style-src 'unsafe-inline' data:; img-src data:`."
      ],
      solution: {
        "script.js": `// Restrictive AND functional: block injected code, keep the page's own\n// script (by nonce) and styles working.\nwindow.POLICY = "default-src 'none'; script-src 'nonce-RPT'; style-src 'unsafe-inline' data:; img-src data:";\n`
      }
    },

    {
      id: "sec-u7-3",
      title: "Security headers & clickjacking",
      kind: "js", chip: "SEC", xp: 15, mins: 13,
      brief: "CSP is one header. A hardened response sets a handful, and it's the same **middleware** move you learned in `srv-u4`: one wrapper stamps every response. `securityHeaders(res)` adds `X-Content-Type-Options: nosniff` (stop MIME-sniffing), `X-Frame-Options: DENY` (no framing), `Referrer-Policy: no-referrer`, `Strict-Transport-Security` (pin https), and a `Content-Security-Policy` — without clobbering headers already there.\n\nThen the flip side: `isFramable(headers, parentOrigin)` decides whether another origin may put your page in an `<iframe>` — the clickjacking question. `DENY` says never; `SAMEORIGIN` says only your own origin (`https://myapp.com`); and a CSP `frame-ancestors` list names exactly who may. Get all three right and an attacker can't frame your page to steal a click.",
      steps: [
        { text: "Write `securityHeaders(res)` — it adds the five headers and returns the response.",
          test: "T.expect(typeof securityHeaders === 'function', 'Define securityHeaders(res).');\nvar res = { status: 200, headers: { 'Content-Type': 'text/html' }, body: '<h1>hi</h1>' };\nvar out = securityHeaders(res);\nT.eq(out.headers, { 'Content-Type': 'text/html', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'DENY', 'Referrer-Policy': 'no-referrer', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Content-Security-Policy': \"default-src 'self'\" }, 'Add all five headers on top of the ones already present.');" },
        { text: "It must not clobber existing headers, nor touch the status or body.",
          test: "var res2 = { status: 201, headers: { 'Content-Type': 'application/json', 'Set-Cookie': 'sid=abc' }, body: { ok: true } };\nvar out2 = securityHeaders(res2);\nT.eq(out2.headers['Set-Cookie'], 'sid=abc', 'An existing Set-Cookie header must survive untouched.');\nT.eq(out2.headers['Content-Type'], 'application/json', 'And Content-Type stays whatever it already was.');\nT.eq(out2.headers['X-Frame-Options'], 'DENY', 'While your headers are still added.');\nT.eq(out2.status, 201, 'The status must not change.');\nT.eq(out2.body, { ok: true }, 'The body must not change.');" },
        { text: "Write `isFramable(headers, parentOrigin)` — decide DENY, SAMEORIGIN and frame-ancestors correctly.",
          test: "T.expect(typeof isFramable === 'function', 'Define isFramable(headers, parentOrigin).');\nT.eq(isFramable({ 'X-Frame-Options': 'DENY' }, 'https://myapp.com'), false, 'DENY forbids ALL framing, even your own origin.');\nT.eq(isFramable({ 'X-Frame-Options': 'SAMEORIGIN' }, 'https://myapp.com'), true, 'SAMEORIGIN allows your own origin (https://myapp.com).');\nT.eq(isFramable({ 'X-Frame-Options': 'SAMEORIGIN' }, 'https://evil.com'), false, 'SAMEORIGIN forbids any OTHER origin.');\nT.eq(isFramable({ 'Content-Security-Policy': 'frame-ancestors https://trusted.com' }, 'https://trusted.com'), true, 'frame-ancestors names exactly who may frame you.');\nT.eq(isFramable({ 'Content-Security-Policy': 'frame-ancestors https://trusted.com' }, 'https://evil.com'), false, 'An origin not in the frame-ancestors list is refused.');" }
      ],
      files: [
        { name: "script.js", content: `// Your own origin is:  https://myapp.com\n// request/response shape:  res = { status, headers: {...}, body }\n\n// 1) securityHeaders(res): add these five headers (keep existing ones!),\n//    then return res.\n//      X-Content-Type-Options:   nosniff\n//      X-Frame-Options:          DENY\n//      Referrer-Policy:          no-referrer\n//      Strict-Transport-Security: max-age=31536000; includeSubDomains\n//      Content-Security-Policy:  default-src 'self'\n\nfunction securityHeaders(res) {\n  return res;   // TODO: add the headers first\n}\n\n// 2) isFramable(headers, parentOrigin) -> boolean: may parentOrigin frame us?\n//      X-Frame-Options DENY        -> false\n//      X-Frame-Options SAMEORIGIN  -> parentOrigin === "https://myapp.com"\n//      CSP frame-ancestors <list>  -> parentOrigin must be in the list\n//                                     ('none' -> false; 'self' -> your origin)\n//      nothing set                 -> true (framing is allowed by default)\n\nfunction isFramable(headers, parentOrigin) {\n  return true;  // TODO\n}\n` }
      ],
      hints: [
        "securityHeaders just assigns onto `res.headers` and returns `res` — never rebuild the object, or you drop headers that were already there.",
        "isFramable: read `headers[\"X-Frame-Options\"]` first and handle DENY / SAMEORIGIN, then fall through to the CSP.",
        "For frame-ancestors: `const m = /frame-ancestors ([^;]*)/.exec(headers[\"Content-Security-Policy\"] || \"\");` then split `m[1]` on whitespace and check whether parentOrigin (or 'self' → your origin) is in it; `'none'` means false."
      ],
      solution: {
        "script.js": `// Your own origin is https://myapp.com.\n\nfunction securityHeaders(res) {\n  res.headers["X-Content-Type-Options"] = "nosniff";\n  res.headers["X-Frame-Options"] = "DENY";\n  res.headers["Referrer-Policy"] = "no-referrer";\n  res.headers["Strict-Transport-Security"] = "max-age=31536000; includeSubDomains";\n  res.headers["Content-Security-Policy"] = "default-src 'self'";\n  return res;\n}\n\nfunction isFramable(headers, parentOrigin) {\n  var xfo = headers["X-Frame-Options"];\n  if (xfo === "DENY") return false;\n  if (xfo === "SAMEORIGIN") return parentOrigin === "https://myapp.com";\n\n  var csp = headers["Content-Security-Policy"] || "";\n  var m = /frame-ancestors ([^;]*)/.exec(csp);\n  if (m) {\n    var sources = m[1].trim().split(/\\s+/);\n    if (sources.indexOf("'none'") !== -1) return false;\n    if (sources.indexOf("'self'") !== -1 && parentOrigin === "https://myapp.com") return true;\n    return sources.indexOf(parentOrigin) !== -1;\n  }\n  return true;   // nothing forbids framing\n}\n`
      }
    },

    {
      id: "sec-u7-p",
      title: "Project: Harden ShoutBoard",
      kind: "web", chip: "SEC", xp: 60, mins: 40, project: true,
      mockFn: `(url, opts) => {\n  opts = opts || {};\n  var method = String(opts.method || "GET").toUpperCase();\n  var headers = opts.headers || {};\n  var auth = headers.Authorization || headers.authorization || "";\n  var path = String(url).split("?")[0];\n  if (method === "DELETE" && path.indexOf("/api/posts/") === 0) {\n    if (String(auth).indexOf("token-admin") !== -1) return { status: 204, body: { ok: true } };\n    return { status: 403, body: { error: "forbidden" } };\n  }\n  if (method === "GET" && path === "/api/posts") {\n    return { status: 200, body: [\n      { id: 1, user: "ada", avatar: "https://cdn.example.com/ada.png", text: "first post!" },\n      { id: 2, user: "bo", avatar: "https://cdn.example.com/bo.png", text: "nice board" },\n      { id: 3, user: "eve", avatar: "javascript:window.__fired=(window.__fired||0)+1", text: "hi all" },\n      { id: 4, user: "mallory", avatar: "https://cdn.example.com/m.png", text: "<img src=x onerror='window.__fired=(window.__fired||0)+1'>" }\n    ] };\n  }\n  return { status: 404, body: { error: "not found" } };\n}`,
      brief: "The capstone: one board, **five holes**, the whole course applied at once. It's a lab against your own sandbox — ShoutBoard works, but every defense you learned is missing. Fix all five and the checks (which drive the board and try to break it) go green:\n\n1. **Stored XSS** — comment text is rendered with `innerHTML`. Render it as literal text instead.\n2. **`javascript:` link** — an avatar's `href` is used raw. Allow only `http`/`https`, drop the rest (keep the safe ones).\n3. **A key in the source** — a `sk_live_` API key rides in the client. Remove it; the server holds keys. `findSecrets` (from Unit 5) must come back empty.\n4. **Client-side authorization** — delete is gated on `window.currentUser.isAdmin`, which the user can flip. Move the decision to the server: send the token and let the mocked API decide.\n5. **No length cap** — a giant comment is accepted. Refuse anything over 280 chars with a visible message in `#error`.\n\nWork through `script.js`. Ship DOMPurify and a real framework in production — this is the checklist, done by hand so you know what the library buys you.",
      steps: [
        { text: "Hole 1 — a stored comment must render as **literal text**, never execute.",
          test: "await T.sleep(250);\nT.expect(window.__fired === undefined, 'A stored comment executed — render comment text with textContent, not innerHTML. window.__fired = ' + window.__fired);\nvar boardText = T.text('#board') || '';\nT.expect(boardText.indexOf('<img') !== -1, 'The payload should be visible as LITERAL text (angle brackets and all). Board text: ' + boardText);\nT.expect(T.count('#board img') === 0, 'No <img> element may be created from a comment — found ' + T.count('#board img') + '.');" },
        { text: "Hole 2 — a `javascript:` avatar link is dropped; a safe `https:` one survives.",
          test: "await T.sleep(60);\nvar avatars = T.$$('#board a.avatar');\nT.expect(avatars.length >= 1, 'Avatar links should render.');\nvar hrefs = avatars.map(function (a) { return a.getAttribute('href'); });\nT.expect(hrefs.every(function (h) { return !h || h.slice(0, 11).toLowerCase() !== 'javascript:'; }), 'No avatar link may keep a javascript: href. Got: ' + JSON.stringify(hrefs));\nT.expect(hrefs.indexOf('https://cdn.example.com/ada.png') !== -1, 'A safe https avatar link must keep its href. Got: ' + JSON.stringify(hrefs));" },
        { text: "Hole 3 — no secret ships in the source, and the board still loads its posts.",
          test: "await T.sleep(60);\nT.expect(typeof findSecrets === 'function', 'Keep the findSecrets helper from Unit 5.');\nvar allScript = T.$$('script').map(function (s) { return s.textContent || ''; }).join('\\n');\nT.eq(findSecrets(allScript), [], 'No API key may remain in the shipped source — findSecrets over all <script> text must return []. Found: ' + JSON.stringify(findSecrets(allScript)));\nT.expect(T.count('#board .post') >= 3, 'The board must still load its posts (the feature works without the key) — found ' + T.count('#board .post') + '.');" },
        { text: "Hole 4 — flipping the client `isAdmin` flag must NOT authorize a delete; a real admin token does.",
          test: "await T.sleep(60);\nwindow.currentUser.isAdmin = true;\nwindow.authToken = 'token-user';\nvar before = T.count('#board .post');\nT.expect(before >= 2, 'Need posts on the board to test delete.');\nawait deletePost(2);\nawait T.sleep(220);\nT.expect(T.count('#board .post') === before, 'A client-side isAdmin flag must not authorize a delete — the SERVER decides, and a normal token is refused. The post should survive. Count went ' + before + ' -> ' + T.count('#board .post'));\nwindow.authToken = 'token-admin';\nawait deletePost(2);\nawait T.sleep(220);\nT.expect(T.count('#board .post') === before - 1, 'With a real admin token the server authorizes the delete and the post is removed. Expected ' + (before - 1) + ', got ' + T.count('#board .post'));" },
        { text: "Hole 5 — a 5000-char comment is refused with a message in `#error`, and nothing is added.",
          test: "var before = T.count('#board .post');\nT.type('#comment', new Array(5001).join('x'));\nT.submit('#form');\nawait T.sleep(80);\nT.expect(T.count('#board .post') === before, 'A 5000-char comment must be refused — nothing added to the board. Count went ' + before + ' -> ' + T.count('#board .post'));\nT.expect((T.text('#error') || '').length > 0, 'Show a visible message in #error explaining the comment was too long.');" }
      ],
      files: [
        { name: "index.html", content: `<!DOCTYPE html>\n<html>\n<head>\n  <link rel="stylesheet" href="styles.css">\n</head>\n<body>\n  <h1>ShoutBoard \u{1F4E3}</h1>\n  <div id="board"></div>\n  <form id="form">\n    <input id="comment" placeholder="Say something\u2026" autocomplete="off">\n    <button type="submit">Post</button>\n  </form>\n  <div id="error"></div>\n  <script src="script.js"></script>\n</body>\n</html>\n` },
        { name: "styles.css", content: `body { font-family: Arial, sans-serif; padding: 20px; color: #1e293b; }\n#board { margin-bottom: 16px; }\n.post { padding: 8px 10px; border: 1px solid #e2e8f0; border-radius: 10px; margin-bottom: 6px; }\n.avatar { font-weight: bold; color: #6366f1; text-decoration: none; margin-right: 6px; }\n.text { }\n.del { margin-left: 8px; font-size: 12px; cursor: pointer; }\ninput { padding: 8px; border: 2px solid #cbd5e1; border-radius: 8px; width: 60%; }\nbutton { font-size: 14px; padding: 8px 12px; border-radius: 8px; border: 2px solid #cbd5e1; background: white; cursor: pointer; }\n#error { color: #dc2626; min-height: 20px; margin-top: 8px; }\n` },
        { name: "script.js", content: `// ShoutBoard: a working comment board with FIVE security holes.\n// Fix each one. The checks drive the board and try to break it.\n\n// --- given helper (from Unit 5): scan text for committed secrets ---\nfunction findSecrets(text) {\n  var hits = [];\n  var rx = /sk_live_[A-Za-z0-9]{16,}/g;   // leaked API key pattern\n  var m;\n  while ((m = rx.exec(String(text))) !== null) hits.push(m[0]);\n  return hits;\n}\n\n// HOLE 3: a secret API key sitting in shipped client source.\nconst API_KEY = "sk_live_FAKEdemoKeyNotReal";\n\nvar board = document.querySelector("#board");\nvar form = document.querySelector("#form");\nvar commentInput = document.querySelector("#comment");\nvar errorEl = document.querySelector("#error");\n\n// The client TRUSTS this flag to decide who can delete — HOLE 4.\nwindow.currentUser = { isAdmin: false };\nwindow.authToken = "token-user";\n\nvar posts = [];\nvar nextId = 100;\n\nfunction render() {\n  // HOLE 1: comment text via innerHTML.  HOLE 2: avatar href used raw.\n  var html = "";\n  for (var i = 0; i < posts.length; i++) {\n    var p = posts[i];\n    html += '<div class="post">'\n      + '<a class="avatar" href="' + p.avatar + '">' + p.user + '</a>'\n      + '<span class="text">' + p.text + '</span>'\n      + '<button class="del" data-id="' + p.id + '">delete</button>'\n      + '</div>';\n  }\n  board.innerHTML = html;\n  var dels = board.querySelectorAll(".del");\n  for (var j = 0; j < dels.length; j++) {\n    dels[j].addEventListener("click", function () {\n      deletePost(Number(this.getAttribute("data-id")));\n    });\n  }\n}\n\nfunction deletePost(id) {\n  // HOLE 4: the CLIENT decides. Flip window.currentUser.isAdmin and it obeys.\n  if (window.currentUser && window.currentUser.isAdmin) {\n    posts = posts.filter(function (p) { return p.id !== id; });\n    render();\n  }\n}\n\nform.addEventListener("submit", function (e) {\n  e.preventDefault();\n  // HOLE 5: no length cap.\n  posts.push({ id: nextId++, user: "you", avatar: "", text: commentInput.value });\n  commentInput.value = "";\n  render();\n});\n\nfunction loadPosts() {\n  // HOLE 3: the key rides along in the request from the browser.\n  return fetch("/api/posts?key=" + API_KEY)\n    .then(function (r) { return r.json(); })\n    .then(function (data) { posts = data; render(); });\n}\n\nloadPosts();\n` }
      ],
      hints: [
        "Holes 1 & 2 both live in render(): build each post with createElement and set the comment via span.textContent (never innerHTML), and only set the avatar href when its scheme is http/https.",
        "Hole 3: delete the API_KEY constant and fetch \"/api/posts\" with no key — the server keeps secrets. findSecrets over the page's scripts should then return [].",
        "Hole 4: deletePost should `return fetch(\"/api/posts/\" + id, { method:\"DELETE\", headers:{ Authorization: \"Bearer \" + window.authToken } })` and only remove the post when `res.ok`. Hole 5: in submit, if `commentInput.value.length > 280`, set errorEl.textContent and return before pushing."
      ],
      solution: {
        "script.js": `// ShoutBoard, hardened: all five holes closed.\n\n// --- given helper (from Unit 5) ---\nfunction findSecrets(text) {\n  var hits = [];\n  var rx = /sk_live_[A-Za-z0-9]{16,}/g;\n  var m;\n  while ((m = rx.exec(String(text))) !== null) hits.push(m[0]);\n  return hits;\n}\n\n// FIX 3: no secret in the client — the server holds any keys it needs.\n\nvar board = document.querySelector("#board");\nvar form = document.querySelector("#form");\nvar commentInput = document.querySelector("#comment");\nvar errorEl = document.querySelector("#error");\n\nwindow.currentUser = { isAdmin: false };\nwindow.authToken = "token-user";\n\nvar posts = [];\nvar nextId = 100;\n\nfunction safeHref(url) {\n  var u = String(url).trim().toLowerCase();\n  if (u.indexOf("http:") === 0 || u.indexOf("https:") === 0) return String(url);\n  return null;   // FIX 2: drop javascript:, data:, everything else\n}\n\nfunction render() {\n  board.innerHTML = "";\n  for (var i = 0; i < posts.length; i++) {\n    var p = posts[i];\n    var div = document.createElement("div");\n    div.className = "post";\n\n    var a = document.createElement("a");\n    a.className = "avatar";\n    var href = safeHref(p.avatar);\n    if (href) a.setAttribute("href", href);\n    a.textContent = p.user;\n\n    var span = document.createElement("span");\n    span.className = "text";\n    span.textContent = p.text;   // FIX 1: literal text, never parsed as HTML\n\n    var btn = document.createElement("button");\n    btn.className = "del";\n    btn.setAttribute("data-id", p.id);\n    btn.textContent = "delete";\n    (function (id) {\n      btn.addEventListener("click", function () { deletePost(id); });\n    })(p.id);\n\n    div.appendChild(a);\n    div.appendChild(span);\n    div.appendChild(btn);\n    board.appendChild(div);\n  }\n}\n\nfunction deletePost(id) {\n  // FIX 4: the SERVER decides. The client flag proves nothing.\n  return fetch("/api/posts/" + id, {\n    method: "DELETE",\n    headers: { Authorization: "Bearer " + window.authToken }\n  }).then(function (res) {\n    if (res.ok) {\n      posts = posts.filter(function (p) { return p.id !== id; });\n      render();\n    }\n  });\n}\n\nform.addEventListener("submit", function (e) {\n  e.preventDefault();\n  var text = commentInput.value;\n  if (text.length > 280) {   // FIX 5: cap length, show a visible message\n    errorEl.textContent = "Comment too long \u2014 keep it under 280 characters.";\n    return;\n  }\n  errorEl.textContent = "";\n  posts.push({ id: nextId++, user: "you", avatar: "https://cdn.example.com/you.png", text: text });\n  commentInput.value = "";\n  render();\n});\n\nfunction loadPosts() {\n  return fetch("/api/posts")   // FIX 3: no key in the URL\n    .then(function (r) { return r.json(); })\n    .then(function (data) { posts = data; render(); });\n}\n\nloadPosts();\n`
      }
    },

    {
      id: "sec-quiz-final",
      title: "Final quiz: Web Security Basics",
      kind: "quiz", xp: 10,
      brief: "The whole course, from trust boundaries to hardening headers. 80% to pass.",
      questions: [
        { q: "Your app reads an `isAdmin` value it previously saved in localStorage and trusts it. Why is that a security bug?",
          choices: [
            "localStorage is encrypted per-origin, so only your own code can ever read the value back",
            "The user can edit localStorage in devtools, so it is untrusted input",
            "localStorage is wiped the moment the browser tab closes",
            "Only pages served over https are allowed to read from localStorage"
          ],
          answer: 1, explain: "localStorage lives in a browser the user fully controls — they can open devtools and set isAdmin to true in seconds. Anything with permission or money attached must be decided server-side from a value the client cannot forge. Its encryption, lifetime, and scheme are irrelevant to whether you can trust it." },
        { q: "You assign `el.innerHTML = '<script>steal()</script>'` and steal() never runs. Are you safe from XSS?",
          code: "el.innerHTML = '<script>steal()</script>';  // steal() never runs",
          lang: "js",
          choices: [
            "Yes — the browser strips every script and event handler from any innerHTML assignment",
            "Yes — assigning to innerHTML can never cause cross-site scripting",
            "No — an `<img src=x onerror=...>` inserted the same way DOES run",
            "No — but the payload only runs on pages served without https"
          ],
          answer: 2, explain: "The HTML parser refuses to execute a `<script>` inserted via innerHTML, which fools beginners into thinking innerHTML is safe. But event-handler payloads like `<img src=x onerror=...>` fire immediately when the element is parsed, so innerHTML with untrusted input is still an XSS sink. The https scheme has nothing to do with it." },
        { q: "You hand-wrote escapeHtml and a small allow-list sanitizer for this course. What is the right call for production?",
          choices: [
            "Hand-rolled escaping is always enough once it passes your unit tests",
            "Disable JavaScript everywhere on the page so no injected code can ever run",
            "Only accept comment input from users who are currently logged in",
            "Ship a maintained library like DOMPurify for sanitizing HTML"
          ],
          answer: 3, explain: "Writing your own escaper teaches the mechanics, but real sanitization has endless edge cases — mutation XSS, nested contexts, weird encodings — that a maintained library like DOMPurify has already fought and fixed. A login check does not make input safe, and disabling JS is not a real option. Learn it by hand, then ship the library." },
        { q: "SQL injection, NoSQL operator injection, and shell-command injection are fundamentally the same bug. What is it?",
          choices: [
            "A string concatenated where a structured value belonged",
            "Using a database engine that has not been patched to a recent version",
            "Forgetting to check that a required field is actually present",
            "Running the application server process as the root user"
          ],
          answer: 0, explain: "Every injection is one shape: untrusted text concatenated into a place that expects structure — a query, a filter object, an argv array — so the data breaks out and becomes code. The fix is always to keep the structure: parameterized queries, real objects, argument arrays. Patch levels, presence checks, and OS accounts are separate concerns." },
        { q: "Which statement about secrets in front-end code is true?",
          choices: [
            "Minifying and obfuscating the bundle reliably hides API keys from end users",
            "An httpOnly cookie is fully readable by the JavaScript running on your page",
            "Environment variables inlined into the client bundle remain secret at runtime",
            "Anything shipped to the browser is public — keep secrets on the server"
          ],
          answer: 3, explain: "Minifying only obscures; anyone can open the network tab or devtools and read every string the browser downloaded, so a key in front-end code is already public. Secrets belong on the server, behind an endpoint. An httpOnly cookie is specifically the one token JavaScript cannot read, which is why it resists theft by XSS." },
        { q: "A logged-in, non-admin user asks to delete another user's post. Which status code fits best?",
          choices: ["200", "401", "403", "404"],
          answer: 2, explain: "401 means \"I don't know who you are\" — you aren't authenticated. 403 means \"I know exactly who you are, and you may not do this\" — the authenticated-but-forbidden case, which is what a failed role check is. (For IDOR on an object you shouldn't even know exists, a 404 that hides its existence can be the better answer.)" },
        { q: "What role does Content-Security-Policy play against XSS?",
          choices: [
            "It completely removes the need to escape output anywhere in your app",
            "A second line of defense the browser enforces if your escaping fails",
            "It encrypts the page source so injected scripts cannot be read",
            "It validates form field formats before the form is submitted"
          ],
          answer: 1, explain: "CSP is defense-in-depth: even when an XSS bug slips past your escaping, a strict policy — no 'unsafe-inline' for scripts, a nonce for your own code — stops the injected script from ever running. It does not replace escaping and it encrypts nothing; the browser is what enforces it, which is why the header has to be correct." },
        { q: "Which `X-Content-Type-Options` value stops the browser from MIME-sniffing a response into a different type?",
          choices: ["nosniff", "no-referrer", "DENY", "SAMEORIGIN"],
          answer: 0, explain: "`X-Content-Type-Options: nosniff` forces the browser to trust the declared Content-Type instead of guessing, which blocks attacks that smuggle an executable script past a text/plain or image label. no-referrer is a Referrer-Policy value, while DENY and SAMEORIGIN belong to X-Frame-Options." }
      ]
    }
  ]
});
